### ISSUE TITLE
Java http.* proxy flags ignored

### ISSUE THREAD

**Issue by rnaval** [googleapis/google-cloud-java#10046]
#### Environment details

1. OS type and version: CentOS Linux 7 (Core)
2. Java version: JDK11
3. Version(s): 
```
        <groupId>com.google.cloud</groupId>
        <artifactId>libraries-bom</artifactId>
        <version>26.25.0</version>
```

#### Steps to reproduce

  1. Run your java application with the following flags for example: `java -Dhttp.proxyHost=webcache.mydomain.com -Dhttp.proxyPort=8080 <APP_NAME>`
  
Note: HTTPS proxies seem to work fine. E.g: `java -Dhttps.proxyHost=webcache.mydomain.com -Dhttps.proxyPort=8080 <APP_NAME>`

Are http.* flags being ignored expected?

**Comment by mpeddada1** [comment]
@rnaval I think this is expected. The Google Cloud client libraries use HTTPS and gRPC under the hood to communicate with services so as described by this [section in the README](https://github.com/googleapis/google-cloud-java?tab=readme-ov-file#configuring-a-proxy) configuring proxies is generally done through `https.proxyHost` or `https.proxyPort`.

**Comment by rnaval** [comment]
Ok thanks - closing this issue
