### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of com.google.auth:google-auth-library-oauth2-http

### ISSUE THREAD

**Issue by Bing-ok** [googleapis/google-cloud-java#10059]
## Issue Description:
Hi, there are multiple versions of **_com.google.auth:google-auth-library-oauth2-http_** in **_google-cloud-java-1.24.0/java-monitoring/google-cloud-monitoring_**. As shown in the following dependency tree, according to Maven  "nearest wins" strategy, only **_com.google.auth:google-auth-library-oauth2-http:1.20.0_** can be loaded, **_com.google.auth:google-auth-library-oauth2-http:1.4.0_** and **_com.google.auth:google-auth-library-oauth2-http:1.20.0_** will be shadowed.

However, several methods defined in shadowed version **_com.google.auth:google-auth-library-oauth2-http:1.4.0_** are referenced by client project via **_com.google.api:gax-grpc:2.37.0_** and **_com.google.api:gax:2.37.0_** but missing in the actually loaded version **_com.google.auth:google-auth-library-oauth2-http:1.20.0_**.

For instance, the following missing method(defined in **_com.google.auth:google-auth-library-oauth2-http:1.4.0_** and **_com.google.auth:google-auth-library-oauth2-http:1.20.0_**) are actually referenced by Google Cloud Monitoring, which will introduce a runtime error(i.e., "NoSuchMethodError") into Google Cloud Monitoring.

1. **_<com.google.auth.oauth2.ServiceAccountCredentials: java.lang.String getQuotaProjectId()>_**  is invoked by Google Cloud Monitoring via the following path:
```
paths--
<com.google.cloud.monitoring.v3.stub.GroupServiceStubSettings$Builder: void init (com.google.api.gax.rpc.ClientContext)> com.google.cloud:google-cloud-monitoring:3.31.0;
<com.google.api.gax.rpc.StubSettings$Builder: void init (com.google.api.gax.rpc.ClientContext)> com.google.api:gax:2.37.0; 
<com.google.api.gax.rpc.StubSettings$Builder: java.lang.String getQuotaProjectIdFromClientContext(com.google.api.gax.rpc.ClientContext)> com.google.api:gax:2.37.0;
<com.google.auth.oauth2.ServiceAccountCredentials: java.lang.String getQuotaProjectId()>
```

Suggested fixing solutions:
1. Upgrade direct dependency **_com.google.auth:google-auth-library-oauth2-http_** from **_1.20.0_** to **_1.20.0_**. Because version **_1.20.0_** includes the above missing methods and is compatible with other versions of **_com.google.auth:google-auth-library-oauth2-http_** in the project.

Please let me know if you agree to this solution? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

## Dependency tree --
<pre><code>
[INFO] |  |  +- (io.grpc:grpc-protobuf:jar:1.59.0:compile - version managed from 1.59.0; omitted for duplicate)
[INFO] |  |  +- (io.grpc:grpc-stub:jar:1.59.0:compile - version managed from 1.59.0; omitted for duplicate)
[INFO] |  |  +- (com.google.protobuf:protobuf-java:jar:3.24.4:compile - version managed from 3.24.0; omitted for duplicate)
[INFO] |  |  +- org.conscrypt:conscrypt-openjdk-uber:jar:2.5.2:compile
[INFO] |  |  +- (com.google.guava:guava:jar:32.1.2-jre:compile - version managed from 32.0.1-jre; omitted for duplicate)
[INFO] |  |  +- <b>(com.google.auth:google-auth-library-oauth2-http:jar:1.20.0:compile - version managed from 1.4.0; omitted for duplicate)</b>
[INFO] |  |  \- (io.grpc:grpc-netty-shaded:jar:1.59.0:compile - version managed from 1.59.0; omitted for duplicate)
[INFO] |  +- io.grpc:grpc-auth:jar:1.59.0:compile (version managed from 1.59.0; scope not updated to compile)
[INFO] |  |  +- (io.grpc:grpc-api:jar:1.59.0:compile - version managed from 1.59.0; omitted for duplicate)
[INFO] |  |  +- (com.google.auth:google-auth-library-credentials:jar:1.20.0:compile - version managed from 1.4.0; omitted for duplicate)
[INFO] |  |  \- (com.google.guava:guava:jar:32.1.2-jre:runtime - version managed from 32.0.1-android; omitted for duplicate)
[INFO] |  +- (io.grpc:grpc-protobuf:jar:1.59.0:compile - version managed from 1.59.0; omitted for duplicate)
[INFO] |  +- (io.grpc:grpc-stub:jar:1.59.0:compile - version managed from 1.59.0; omitted for duplicate)
[INFO] |  +- io.grpc:grpc-netty-shaded:jar:1.59.0:compile (version managed from 1.59.0; scope not updated to compile)
[INFO] |  |  +- (com.google.guava:guava:jar:32.1.2-jre:runtime - version managed from 32.0.1-android; omitted for duplicate)
</code></pre>

**Comment by suztomo** [comment]
> Upgrade direct dependency com.google.auth:google-auth-library-oauth2-http from 1.20.0 to 1.20.0.

It seems there's a typo. Both versions are the same. Would you correct the suggestion?

**Comment by suztomo** [comment]
I'll close this issue. If you really encounter dependency conflicts, let us know.
