### ISSUE TITLE
Compute SDK is throwing InvalidArgumentException for missing permissions

### ISSUE THREAD

**Issue by qooiprww** [googleapis/google-cloud-java#10061]
I received the `InvalidArgumentException` when trying to attach a non boot Disk to VM with the Java Compute SDK:
```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: Operation with name "operation-1700106345250-60a3cdac9feda-912d28eb-2ac327a0" failed with status = HttpJsonStatusCode{statusCode=INVALID_ARGUMENT} and message = BAD REQUEST
```

Here is the error given for this operation on GCP Console:
```
SERVICE_ACCOUNT_ACCESS_DENIED
The user does not have access to service account 'myorgdefaultserviceaccountid@developer.gserviceaccount.com'. User: 'myserviceaccountid@myorgname.iam.gserviceaccount.com'. Ask a project owner to grant you the iam.serviceAccountUser role on the service account
```

I was able to successfully attach the disk after adding these permissions to the custom role of my service account:
```
iam.serviceAccounts.actAs
iam.serviceAccounts.get
iam.serviceAccounts.list
resourcemanager.projects.get
```

**Comment by suztomo** [comment]
I'm glad to hear you were able to successfully attach the disk after adding permissions. Getting the exception when your account does not have permission sounds reasonable to me. Was there anything unexpected to you in the client library?

**Comment by suztomo** [comment]
I'll close this issue. If you feel the exception could have a better message, would you please raise a feature request for it?
