### ISSUE TITLE
Transport section in module README.md files is incorrect for most modules

### ISSUE THREAD

**Issue by meltsufin** [googleapis/google-cloud-java#10118]
In most modules it says "gRPC", even though REST is enabled.

@suztomo

**Comment by suztomo** [comment]
```
java_gapic_library(
    name = "dialogflow_java_gapic",
    srcs = [":dialogflow_proto_with_info"],
...
    transport = "grpc+rest",
```

Interesting. I thought that BUILD.bazel files are generated from the service yaml file. https://github.com/googleapis/googleapis/blob/master/google/cloud/dialogflow/v2/dialogflow_v2.yaml does not have any mention in grpc, rest, or transport.

**Comment by meltsufin** [comment]
cc: @blakeli0

**Comment by alicejli** [comment]
Rectifying this should be considered as part of https://github.com/googleapis/google-cloud-java/issues/10090 whenever that is being worked on

**Comment by suztomo** [comment]
Let's work on this after the README files are created by the hermetic build process.

**Comment by blakeli0** [comment]
This issue is fixed as part of the hermetic build project, as the transport section is now automatically generated with the value fro BUILD.bazel. See example section in [java-dialogflow](https://github.com/googleapis/google-cloud-java/tree/main/java-dialogflow#transport).
