### ISSUE TITLE
GitHub Actions workflow dispatch for new-client.py

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#10168]
Let's set up GitHub Actions workflow dispatch for new-client.py invocation, so that the user of the script (a release manager) does not need to prepare the environment (docker, Python version, etc).

- Rename the existing https://github.com/googleapis/google-cloud-java/blob/main/.github/workflows/newclient.yaml to mention it's for testing new client release scripts in a pull request.
- Workflow dispatch can take parameters ([document](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)). Design the parameters (very likely the same set of the parameters as new-client.py) The image below is a screenshot from the GitHub documentation, where you can choose parameters when running workflow dispatch:
  ![image](https://github.com/googleapis/google-cloud-java/assets/28604/0b4b761f-c622-4ab9-88bf-5f94038f0b3b)
  - What would be required parameters and optional parameters?
- Implement the workflow via a pull request. Your the main branch in your forked repository to test. It's easier to test the pull request in your forked repository (e.g., https://github.com/diegomarquezp/google-cloud-java; [You need to enable actions first in a forked repository](https://github.com/orgs/community/discussions/26865)). 
- Try running it with edgenetwork and compare the result (`git diff`) with https://github.com/googleapis/google-cloud-java/pull/10136
- If there's fixes, then create another pull request.

**Comment by diegomarquezp** [comment]
Solved in https://github.com/googleapis/google-cloud-java/pull/10488
