### ISSUE TITLE
[cloudtasks] Create tasks in bulk

### ISSUE THREAD

**Issue by stickfigure** [googleapis/google-cloud-java#10181]
The old (GAE) tasks API supports bulk adding tasks, which dramatically increases the rate at which tasks can be added.

The new API to Cloud Tasks doesn't appear to support bulk adds. This is the one major issue keeping us on the old APIs.

**Comment by suztomo** [comment]
> The old (GAE) tasks API supports bulk adding tasks

Would you share the documentation about bulk adding tasks?

Memo: As you understood, it's very likely not an SDK issue.

https://cloud.google.com/appengine/migration-center/standard/java/migrating-push-queues#features-not-available

> Adding tasks asynchronously

**Comment by stickfigure** [comment]
Here's the bulk add tasks method from the legacy GAE Java API:

https://cloud.google.com/appengine/docs/legacy/standard/java/javadoc/com/google/appengine/api/taskqueue/Queue.html#add-java.lang.Iterable-

It's synchronous, but it lets you submit up to 100 tasks at a time. The 1-2 order of magnitude increase in submission rate makes many operations possible (in reasonable execution timeframe) that would otherwise require elaborate custom fanout logic.

If not here (because it requires service work), where should I put this feature request?

**Comment by suztomo** [comment]
Thank you for the reference.

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/).
