### ISSUE TITLE
Use a single unique java library to call the vertex AI API

### ISSUE THREAD

**Issue by fedecompa** [googleapis/google-cloud-java#10484]
Currently there are two distinct java library to call vertex AI services APIs: "google-cloud-aiplatform" and "google-cloud-vertexai". 

https://mvnrepository.com/artifact/com.google.cloud/google-cloud-aiplatform

https://mvnrepository.com/artifact/com.google.cloud/google-cloud-vertexai

It could be very useful to unify the two libraries in a single official one.

**Comment by ZhenyiQ** [comment]
Hi @fedecompa , thanks for the feedback! Please think of aiplatform as the dependency of vertexai (it basically is, but we didn't want the users to install both and to need to import from both so we incorporate the code into vertexai). If you are only using GenAI inference, please consider using vertexai alone. If you're using other services on Vertex AI, you should use aiplatform.
