### ISSUE TITLE
Google cloud error reporting - INVALID_ARGUMENT: Reported Error too large

### ISSUE THREAD

**Issue by pramodShehan5** [googleapis/google-cloud-java#10548]
Hello,
I am using "com.google.cloud" % "google-cloud-errorreporting" % "0.122.4-beta"

when I am trying to send the error, sometime I am getting  **Google APIcom.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Reported Error too large.**

Thanks!

**Comment by zhumin8** [comment]
IIUC, sounds like the client library is working as expected and you are getting the above runtime error from the service. 
This repository and maintainers are not familiar with the service itself, if you have further question about this product, please refer to error reporting [product page ](https://cloud.google.com/error-reporting) or try to get support from channel listed [here](https://cloud.google.com/stackdriver/docs/getting-support).

Closing this issue, please reopen if I am misunderstanding the issue in anyway.

**Comment by pramodShehan5** [comment]
Hello @zhumin8 ,

is there anyway to split the error and send it to the GCloud?

https://cloud.google.com/knowledge/kb/error-400-bad-request-request-payload-size-exceeds-the-limit-000004321#:~:text=The%20error%20Request%20payload%20size,limit%20and%20cannot%20be%20increased.

**Comment by mpeddada1** [comment]
Closing the loop on this; Discussion continued at https://github.com/googleapis/google-cloud-java/issues/10780.
