### ISSUE TITLE
Create a guide for RetrySettings

### ISSUE THREAD

**Issue by alicejli** [googleapis/google-cloud-java#10586]
RetrySettings have been a source of customer confusion. We should create an external-facing guide to using and explaining RetrySettings within the GAPIC java client libraries

**Comment by blakeli0** [comment]
Currently we don't have any public guide other than Javadocs in [RetrySettings](https://github.com/googleapis/sdk-platform-java/blob/main/gax-java/gax/src/main/java/com/google/api/gax/retrying/RetrySettings.java), which could take customers a while to figure out. We should add a section for it to our README, similar to [Long Running Operations](https://github.com/googleapis/google-cloud-java?tab=readme-ov-file#long-running-operations) section.

**Comment by lqiu96** [comment]
@alicejli @blakeli0 Added a first draft for the README. Let me know if anything is unclear or if anything else should be added.
