### ISSUE TITLE
Mapping the AnnotateImageRequest to AnnotationImageResponse in Vision API

### ISSUE THREAD

**Issue by Y-AKBAS** [googleapis/google-cloud-java#10731]
Hi dear cloud team,

currently I am working with the google cloud vision api and with the `BatchAnnonateImageRequest` we can send multiple `AnnotateImageRequest`s. The`BatchAnnotateImageResponse` that we get returns multiple `AnnotateImageResponse`s as expected. The problem here is we do not know which response belongs to which request that we sent and therefore we cannot map them to our entities. 

I would be very happy if we can somehow relate the requests with the responses that we get.

A possible way to achieve could be that we introduce a **requestId** in proto files both for `AnnotateImageRequest` and `AnnotationImageResponse` classes and the server maps this from request to the response so that we can know which response belongs to which request.

Here is an example code snippet in Kotlin to show what I want to achieve:

```
                val bytesOfImages = links.map { async { getImage(it) } }.awaitAll().filterNotNull()
                val singleRequests = bytesOfImages.map {
                    AnnotateImageRequest.newBuilder()
                        .setRequestId(UUID.randomUUID().toString()) // doesn't exist now.
                        .setImage(Image.newBuilder().setContent(ByteString.copyFrom(it)).build())
                        .addFeatures(Feature.newBuilder().setType(Feature.Type.WEB_DETECTION).build())
                        .setImageContext(ImageContext.getDefaultInstance())
                        .build()
                }
                val batchRequest = BatchAnnotateImagesRequest.newBuilder().addAllRequests(singleRequests).build()
                val responses = imageAnnotatorClient!!.batchAnnotateImages(batchRequest).responsesList
// with the help of requestIds I want to know which response belongs to which request
                val reqResPair = batchRequest.requestsList.map { request -> request to responses.find { it.requestId == request.requestId } }
```

In the following links you can see that there were some questions in the StackOverFlow but we cannot rely on the order of returned responses: 
* [mapping problem on stackoverflow](https://stackoverflow.com/questions/70664508/does-batchannotateimagesresponse-in-google-cloud-vision-api-preserve-the-order-o)
* [cloud community website](https://www.googlecloudcommunity.com/gc/AI-ML/Order-of-entries-in-BatchAnnotateImagesResponse/td-p/182949/highlight/true/page/2)

If I can support you in a way I would be happy to do that. Thank you very much in advance!

**Comment by zhumin8** [comment]
Thanks for filing your issue. Unfortunately, this repository contains only the java client library for Vision api, and we do not have the expertise in actual services.
What you are describing sounds more a feature request to the Vision API. You might want to try one of the channels listed in the product's support page [here](https://cloud.google.com/vision/docs/getting-support).

**Comment by Y-AKBAS** [comment]
Hi @zhumin8 ! Thank you very much for your response. I will check the mentioned support page then.
