### ISSUE TITLE
[java-maps-places] How to set FieldMask

### ISSUE THREAD

**Issue by Breefield** [googleapis/google-cloud-java#10766]
The Places API (New) [indicates that a FieldMask](https://developers.google.com/maps/documentation/places/web-service/place-details#fieldmask) can be passed as a REST header, or gRPC metadata.

Users have had a [similar question](https://github.com/googleapis/google-cloud-python/issues/12083) in the Python library, but not this java one. In Python there is a `metadata` property which can be passed to indicate the FieldMask. 

This Java library [has no such argument.](https://github.com/googleapis/google-cloud-java/blob/ab3ab4999f54fa20e21206d4876900c9fec2d6e6/java-maps-places/google-maps-places/src/main/java/com/google/maps/places/v1/PlacesClient.java#L602).

As the client is generated from protobuf I'd anticipate the clients would have similar arguments...
How does one set the `FieldMask` for this api?

**Comment by Breefield** [comment]
I figured out I can do it like so (kotlin code):
```
val credentials = ServiceAccountCredentials.fromStream(json.byteInputStream())

val fieldMask = listOf(
    "id",
    "name",
    "addressComponents",
    "formattedAddress",
    "location",
    "types",
).joinToString(",")

val placesSettings = PlacesSettings.newBuilder()
    .setCredentialsProvider(
        FixedCredentialsProvider.create(credentials),
    ).setHeaderProvider {
        mutableMapOf("X-Goog-FieldMask" to fieldMask)
    }.build()

return PlacesClient.create(placesSettings)
```

**Comment by saadfarooq** [comment]
That's kinda ridiculous... we have to create a new client if we want to change fields.

**Comment by hoathaivu** [comment]
I found a way to use the same client in Java. The implementations of _*Client_ like `PlacesClient` always use `UnaryCallable.call(request)` method; however, beneath it is another method `UnaryCallable.call(request, ApiCallContext)`, whose parameter `ApiCallContext` is passed as `null` in the former method. This param allows us to add additional headers to the call, which I show below.

```
    public Place getPlaceById(String placeId) throws IOException {
        try (PlacesClient placesClient = PlacesClient.create(placesSettings)) {
            return callWithHeader(
                    placesClient.getPlaceCallable(),
                    GetPlaceRequest
                            .newBuilder()
                            .setName(PlaceName.of(placeId).toString())
                            .build(),
                    "X-Goog-FieldMask",
                    "id,displayName"
            );
        }
    }

    public static <RequestT, ResponseT> ResponseT callWithHeader(
            UnaryCallable<RequestT, ResponseT> callable,
            RequestT request,
            String headerKey,
            String headerVal) {
        return callable.call(
                request,
                GrpcCallContext.createDefault().withExtraHeaders(Map.of(headerKey, List.of(headerVal))));
    }
```
