### ISSUE TITLE
Splitting error report into multiple requests 

### ISSUE THREAD

**Issue by pramodShehan5** [googleapis/google-cloud-java#10780]
Hello,

Is there any way to split the error into multiple requests and send it to the GCloud error reporting?
I am using **"com.google.cloud" % "google-cloud-errorreporting" % "0.122.4-beta"**

https://cloud.google.com/knowledge/kb/error-400-bad-request-request-payload-size-exceeds-the-limit-000004321#:~:text=The%20error%20Request%20payload%20size,limit%20and%20cannot%20be%20increased.

**Comment by pramodShehan5** [comment]
yes. is there any way to stream the  error report bigger than 10 MB limit?

**Comment by suztomo** [comment]
I see. I only think of the solution listed there https://cloud.google.com/knowledge/kb/error-400-bad-request-request-payload-size-exceeds-the-limit-000004321#solution.

**Comment by pramodShehan5** [comment]
Hello @suztomo ,
when splitting the error message into several request, is there any way to identify the error group on GCloud error reporting side?
