### ISSUE TITLE
Cloud Commerce Partner Procurement API

### ISSUE THREAD

**Issue by sandeep-khanna** [googleapis/google-cloud-java#10861]
Is there a reason why this collection does not include the [Google Cloud Commerce Partner Procurement API](https://cloud.google.com/marketplace/docs/partners/commerce-procurement-api/reference/rest) cloud client library?

Elsewhere on GitHub, I have requested the conversion and addition of the Google Cloud Commerce Partner Procurement OpenAPI spec in YAML. This could be used to generate a Java client library using something like [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator#openapi-generator).

- [Issue#23@google-discovery-to-openapi](https://github.com/stackql/google-discovery-to-openapi/issues/23)
- [Issue#36@google-discovery-to-swagger](https://github.com/APIs-guru/google-discovery-to-swagger/issues/36)

**Comment by sandeep-khanna** [comment]
> Note: We have a library here that you can use: https://github.com/googleapis/google-cloud-java/tree/main/java-cloudcommerceconsumerprocurement

This suggested library is for use by Cloud Marketplace customers. My request is related to 'Partner' version of the API leveraged during the provisioning of a marketplace offer.

**Comment by lqiu96** [comment]
I see. I'm not too familiar with the partner version. Let me reach out to the team to get more information about the library and the status.

**Comment by lqiu96** [comment]
Hi @sandeep-khanna, I have reached out to the service team for more information.

The Partner API is only used for companies selling through GCP Marketplace: https://cloud.google.com/marketplace/docs/partners/get-started. Users are onboarded when they become a reseller. The service team will enable the API on a dedicated "producer project" for that Marketplace Partner and you will be able to use API keys from that project to access the API.

Currently, only certain languages have the Partner API library released (for example: [golang](https://github.com/googleapis/google-api-go-client/tree/main/cloudcommerceprocurement/v1)). There currently is not an ETA for releasing an equivalent library for Java.
