### ISSUE TITLE
Setting fields to return with AsyncGetPlace 

### ISSUE THREAD

**Issue by hybp** [googleapis/google-cloud-java#10945]
Here is a sample usage getting the place details using the [client](https://github.com/googleapis/google-cloud-java/blob/main/java-maps-places/samples/snippets/generated/com/google/maps/places/v1/places/getplace/AsyncGetPlace.java).

```
import com.google.api.core.ApiFuture;
import com.google.maps.places.v1.GetPlaceRequest;
import com.google.maps.places.v1.Place;
import com.google.maps.places.v1.PlaceName;
import com.google.maps.places.v1.PlacesClient;

public class AsyncGetPlace {

  public static void main(String[] args) throws Exception {
    asyncGetPlace();
  }

  public static void asyncGetPlace() throws Exception {
    // This snippet has been automatically generated and should be regarded as a code template only.
    // It will require modifications to work:
    // - It may require correct/in-range values for request initialization.
    // - It may require specifying regional endpoints when creating the service client as shown in
    // https://cloud.google.com/java/docs/setup#configure_endpoints_for_the_client_library
    try (PlacesClient placesClient = PlacesClient.create()) {
      GetPlaceRequest request =
          GetPlaceRequest.newBuilder()
              .setName(PlaceName.of("[PLACE_ID]").toString())
              .setLanguageCode("languageCode-2092349083")
              .setRegionCode("regionCode-1991004415")
              .setSessionToken("sessionToken-696552189")
              .build();
      ApiFuture<Place> future = placesClient.getPlaceCallable().futureCall(request);
      // Do something.
      Place response = future.get();
    }
  }
}
```

I am not sure how to set the fields that I want (e.g., displayName, shortFormattedAddress, location, ...).

Same goes for SearchNearby and SearchText.
 
I found a [github issue](https://github.com/googleapis/google-cloud-python/issues/12083) about this for [google-cloud-python](https://github.com/googleapis/google-cloud-python), but I couldn't find one for Java.

Thanks in advance.

**Comment by nicolasjandre** [comment]
I'm also facing the same issue, do you was able to figure out?

**Comment by vedranstanic82** [comment]
This is not right for 

		<dependency>
		  <groupId>com.google.maps</groupId>
		  <artifactId>google-maps-places</artifactId>
		  <version>0.17.0</version>
		</dependency>

the .setFieldMask does not exist.

**Comment by an-tex** [comment]
@vedranstanic82 try this https://github.com/googleapis/google-cloud-java/issues/11017#issuecomment-2424236040
