### ISSUE TITLE
Option classes do not support JSON serialization/deserialization

### ISSUE THREAD

**Issue by junan-trustarc** [googleapis/google-cloud-java#11013]
#### Environment details

1. Specify the API at the beginning of the title. For example, "[vision]: ...").
   General, Core, and Other are also allowed as types
  google-cloud-vertexai
2. OS type and version: Window 11
3. Java version: 21
4. Version(s): 1.6.0

I am creating wrapper endpoint for vertex AI API on our AI microservice to have add-on features and centralize many other AI providers.
and we have our own SDK to call this wrapper endpoint.
most of classes from this library doesn't support JSON serialization/deserialization.
Since there is too many properties and it keeps managing by library, I can't manually map it.
Is there anyway to do?

#### Code example

```java
   @PostMapping(value = "/generate-content")
    public Flux<GenerateContentResponse> generateContent(@RequestBody GenerateContentRequest request) {
        // request is not working since it doesn't support deserialization 
    }
```

**Comment by blakeli0** [comment]
> most of classes from this library doesn't support JSON serialization/deserialization.

All the request/response classes are generated by Protobuf, and they can be serialized to Json by protobuf utils. See relevant [discussion](https://stackoverflow.com/questions/28545401/java-json-protobuf-back-conversion) on Stackoverflow.
