### ISSUE TITLE
Vertex AI Generative model: Add support for context cache

### ISSUE THREAD

**Issue by patrick-zinner** [googleapis/google-cloud-java#11044]
While the Java library is great to execute prompts, we'd like to execute multiple smaller prompts for the same file, as we've discovered that those work better (for our usecase). For that we'd like to use context caching as described here:

https://cloud.google.com/vertex-ai/generative-ai/docs/context-cache/context-cache-overview

While a workaround is to simply build our own client and make the REST calls ourselves, it would be better to have regular updates by using the library and as well as having the convinience of application credentials.

I hope that the description is good enough!

**Comment by zhumin8** [comment]
Thanks for filing this issue with us. However, this sounds like a feature request and the java client library are only in position exposing methods that the underlying service chooses to. 
For your request, you will have a better chance contacting support console if you have a support contract with Google, or else reach out to support channels listed in the product [getting-help page](https://cloud.google.com/vertex-ai/generative-ai/docs/getting-help).

**Comment by Dobiasd** [comment]
Hi, hopefully, I don't misunderstand the situation, but to me, it looks like this:
- [The REST API for VertexAI does support context caching](https://cloud.google.com/vertex-ai/generative-ai/docs/context-cache/context-cache-create#create-context-cache-sample-drest).
- [It's exposed in the Python wrapper around that REST API](https://cloud.google.com/vertex-ai/generative-ai/docs/context-cache/context-cache-create#create-context-cache-sample-python).
- But it's not exposed in the Java wrapper around that REST API.

So it would be cool if the Java library could also expose (support) context caching, so Java users do not need to call the REST API manually to use context caching.
