### ISSUE TITLE
Compute API: ConfidentialInstanceType missing from ConfidentialInstanceConfig

### ISSUE THREAD

**Issue by deeglaze** [googleapis/google-cloud-java#11072]
The compute engine API supports new confidential compute instance types like SEV_SNP and TDX (Preview), but those changes to the API are not reflected in the Java client.

 It would be great to see the API generator re-run for the compute engine API.

**Additional context**
Request from a large GCP customer. They manage their instances with Java and can't use confidential compute due to this.

**Comment by blakeli0** [comment]
The [proto changes](https://github.com/googleapis/googleapis/pull/903) in googleapis is not merged yet. The Java client library should be auto-generated and released in two weeks after the proto changes are merged.

**Comment by deeglaze** [comment]
Thank Blake. That's.. quite the PR. Which team is managing that, so we can find out an ETA?

**Comment by deeglaze** [comment]
@blakeli0 The PR is merged, so regenerating the proto would be appreciated for the next release.

**Comment by blakeli0** [comment]
I can see changes related to [SEV_SNP](https://github.com/googleapis/google-cloud-java/blame/885e8252a0aad01a47ac2161f7a1183b450d144b/java-compute/proto-google-cloud-compute-v1/src/main/java/com/google/cloud/compute/v1/ConfidentialInstanceConfig.java#L169) are already on main branch, and we just released it today. Can you double check [java-compute](https://github.com/googleapis/google-cloud-java/tree/main/java-compute) already has all the latest changes?
