### ISSUE TITLE
[discoveryengine]: LRO timeouts in RetrySettings are not applied to DocumentServiceClient

### ISSUE THREAD

**Issue by maborghe** [googleapis/google-cloud-java#11096]
I'm trying to import a document into a discovery engine data store. The import takes about 15 minutes, but after 5 minutes I get error logs such as `The task has been cancelled. Please refer to https://github.com/googleapis/google-cloud-java#lro-timeouts for more information` and `java.util.concurrent.CancellationException: Task was cancelled.`.
Following the instructions reported in https://github.com/googleapis/google-cloud-java#lro-timeouts and https://cloud.google.com/java/docs/reference/gax/latest/com.google.api.gax.retrying.RetrySettings, as well as the source code in 
https://github.com/googleapis/google-cloud-java/blob/main/java-discoveryengine/google-cloud-discoveryengine/src/main/java/com/google/cloud/discoveryengine/v1/stub/DocumentServiceStubSettings.java, I came up with the following initialization code for the DocumentServiceClient:

```
        DocumentServiceSettings.Builder documentServiceSettingsBuilder = DocumentServiceSettings.newBuilder();
        documentServiceSettingsBuilder
            .importDocumentsSettings()
            .setRetrySettings(
                RetrySettings.newBuilder()
                    .setInitialRetryDelay(Duration.ofMillis(1000L))
                    .setRetryDelayMultiplier(1.3)
                    .setInitialRpcTimeout(Duration.ZERO) // ignored
                    .setRpcTimeoutMultiplier(1.0) // ignored
                    .setMaxRpcTimeout(Duration.ZERO) // ignored
                    .setMaxRetryDelay(Duration.ofMillis(12*60*100))
                    .setTotalTimeout(Duration.ofHours(1L))
                    .build());
        DocumentServiceSettings documentServiceSettings = documentServiceSettingsBuilder.build();
        this.documentService = DocumentServiceClient.create(documentServiceSettings);
```

I've also tried omitting the rcp timeout setup, as well as different values for the total timeout (e.g. using Duration.ofMillis or Duration.ofMinutes). Nevertheless, the task is still interrupted after 5 minutes.

#### Environment details
- 2nd gen Cloud Function
- Java 21
- pom dependency: ```google-cloud-discoveryengine```, version ```0.41.0```
- Java import: ```com.google.cloud.discoveryengine.v1.DocumentServiceSettings```

#### Stack trace
```
java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1574)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:573)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:67)
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:125)
```

**Comment by suztomo** [comment]
At first glance, it's the default timeout of "Total Timeout (Max Time allowed for polling): 5 minutes". But I see you set `setTotalTimeout(Duration.ofHours(1L))`.

https://github.com/googleapis/google-cloud-java?tab=readme-ov-file#lro-timeouts

We will dig more.

**Comment by maborghe** [comment]
@suztomo Thanks for the feedback. Here's the code that does the RPC call, as you pointed out there is a call to `importDocumentsAsync`. As you can see I'm trying to import multiple documents, but the same problem occurs when the document is just one.
```
List<OperationFuture<ImportDocumentsResponse, ImportDocumentsMetadata>> importDocumentAsyncs = new ArrayList<>();
for (String uri : urisToImport) {
    ImportDocumentsRequest request = ImportDocumentsRequest.newBuilder()
        .setParent(parent)
        .setGcsSource(GcsSource.newBuilder().addInputUris(uri).setDataSchema("content"))
        .build();
    importDocumentAsyncs.add(documentService.importDocumentsAsync(request));
}

for (var async : importDocumentAsyncs) {
    try {
        async.get();
    } catch (InterruptedException | ExecutionException e) {
        throw new IOException(e);
    }
}
```

**Comment by suztomo** [comment]
Would you try `TimedRetryAlgorithm` as per https://github.com/googleapis/google-cloud-java?tab=readme-ov-file#lro-timeouts:

```
        TimedRetryAlgorithm timedRetryAlgorithm = OperationTimedPollAlgorithm.create(
                RetrySettings.newBuilder()
                        .setInitialRetryDelay(Duration.ofMillis(1000L))
                        .setRetryDelayMultiplier(1.3)
                        .setMaxRetryDelay(Duration.ofMillis(5000L))
                        .setInitialRpcTimeout(Duration.ZERO) // ignored
                        .setRpcTimeoutMultiplier(1.0) // ignored
                        .setMaxRpcTimeout(Duration.ZERO) // ignored
                        .setTotalTimeout(Duration.ofMinutes(10L))
                        .build());
        documentServiceSettingsBuilder.importDocumentsOperationSettings().setPollingAlgorithm(timedRetryAlgorithm);
```

**Comment by maborghe** [comment]
All right, it works as expected now. My bad, the documentation was actually pretty clear about that.
Thanks for your support!
