### ISSUE TITLE
https://github.com/googleapis/google-cloud-java/blame/8f37b9a318820e544bcaae25337e828ae9192ecb/.github/CODEOWNERS#L5

### ISSUE THREAD

**Issue by Playgirlkaybraz11** [googleapis/google-cloud-java#11108]
https://github.com/googleapis/google-cloud-java/blame/8f37b9a318820e544bcaae25337e828ae9192ecb/.github/CODEOWNERS#L5

**Comment by suztomo** [comment]
Did you find anything interesting at the line 5?

(I'll close this if this was created accidentally)
