### ISSUE TITLE
Broken Client Library Documentation Link in README.md

### ISSUE THREAD

**Issue by Asbeiru** [googleapis/google-cloud-java#11125]
**Description of the issue**
The link to the Client Library Documentation in the README.md file is broken. Clicking it does not lead to the expected page.

**Broken Link**
The current link points to: https://cloud.google.com/java/docs/reference/google-maps-routing/latest/overview

**Expected Behavior**
The link should direct users to the most up-to-date Google Routes API Client Library Documentation page.

**Additional Information**
Please verify whether there is an updated URL for this link and correct it in the README.md file.

**Comment by suztomo** [comment]
I'm afraid that there are certain links currently broken.

Duplicate of https://github.com/googleapis/google-cloud-java/issues/10057
