### ISSUE TITLE
How does google-cloud-resourcemanager have a grpc-s2a dependency?

### ISSUE THREAD

**Issue by ejona86** [googleapis/google-cloud-java#11324]
In https://github.com/grpc/grpc-java/issues/11703 we noticed [google-cloud-resourcemanager 1.56.0 has a dependency on the new grpc artifact grpc-s2a](https://repo1.maven.org/maven2/com/google/cloud/google-cloud-resourcemanager/1.56.0/google-cloud-resourcemanager-1.56.0.pom).

I was surprised to see such a dependency, so I was looking at the source in this repo, and I don't understand how/why that dependency exists. The [POM in this repository](https://github.com/googleapis/google-cloud-java/blob/v1.48.0/java-resourcemanager/google-cloud-resourcemanager/pom.xml) is substantially different than the POM on Maven Central, and it doesn't have an s2a dependency.

Everything could be fine, but it seems weird things are going on.

**Comment by suztomo** [comment]
About the mystery of pom.xml file, we use flatten-maven-plugin https://www.mojohaus.org/flatten-maven-plugin/flatten-mojo.html. It moves the transitive dependencies to direct dependencies when we release Maven artifacts.

**Comment by ejona86** [comment]
With that in mind, `mvn dependency:tree` shows:
```
...
[INFO] +- com.google.api:gax-grpc:jar:2.58.0:compile
[INFO] |  +- io.grpc:grpc-inprocess:jar:1.68.1:compile
[INFO] |  |  \- io.grpc:grpc-core:jar:1.68.1:compile
[INFO] |  |     +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  |     \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.24:runtime
[INFO] |  +- io.grpc:grpc-alts:jar:1.68.1:compile
[INFO] |  |  +- io.grpc:grpc-grpclb:jar:1.68.1:compile
[INFO] |  |  \- org.conscrypt:conscrypt-openjdk-uber:jar:2.5.2:compile
[INFO] |  +- io.grpc:grpc-auth:jar:1.68.1:compile
[INFO] |  +- io.grpc:grpc-s2a:jar:1.68.1:compile
...
```

And that led me to https://github.com/googleapis/sdk-platform-java/pull/3326. Thank you.
