### ISSUE TITLE
BaseEntity.toPb method is not public

### ISSUE THREAD

**Issue by vikkyrk** [googleapis/google-cloud-java#1431]
There are cases where users want to convert com.google.cloud.datastore.Entity objects to native protobuf Entity objects (com.google.datastore.v1.Entity). For ex: while using Cloud Dataflow DatastoreIO, which only works with protobuf Entities. It would be nice to expose the toPb method by making it public.

**Comment by garrettjonesgoogle** [comment]
Could you give a link to the code for Cloud Dataflow DatastoreIO?

**Comment by vikkyrk** [comment]
@garrettjonesgoogle  relevant files are here https://github.com/GoogleCloudPlatform/DataflowJavaSDK/tree/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/io/datastore

**Comment by hzyi-google** [comment]
The feature request is added to the [backlog](https://github.com/GoogleCloudPlatform/google-cloud-java/wiki/Feature-backlog). The issue will be closed but is linked in the backlog and can continue to be used for comment and discussion.

**Comment by topecongiro** [comment]
@hzyi-google 
What does it mean for the issue to be added to the backlog? Do maintainers of this SDK will accept a PR that fixes this issue? IMHO this will hugely benefit the DX of SDK users, as working with  `com.google.datastore.v1.Entity` is very painful, especially when you try to create it manually for tests.

**Comment by hzyi-google** [comment]
Please always feel free to send over a pull request :)
