### ISSUE TITLE
JVM Hangs on gRPC if you don't close Spanner Object

### ISSUE THREAD

**Issue by ericandrewschmidt** [googleapis/google-cloud-java#2315]
I ran across a path with the Java Spanner client that if you create several Spanner instances and do not explicitly close them the JVM will hang (it will not terminate it's process after code execution).

To reproduce the behavior create an object that wraps Spanner creation. Create the object several times in a loop. Then execute some additional code.  

You can see the hanging wait on KQueueArrayWrapper.

Thanks.

![screen shot 2017-08-07 at 9 05 21 pm](https://user-images.githubusercontent.com/10247749/29055913-43020fd8-7bb4-11e7-8b5d-aa1dcf718525.png)

![screen shot 2017-08-07 at 9 05 36 pm](https://user-images.githubusercontent.com/10247749/29055921-5595b730-7bb4-11e7-80b5-2ca4ad7923c3.png)

**Comment by garrettjonesgoogle** [comment]
We may creating non-daemon threads somewhere.

**Comment by vkedia** [comment]
@ericandrewschmidt Does this only happen if you create multiple instance of Spanner object? 
Also are you creating multiple `SpannerOptions` or are you creating a single `SpannerOptions` and multiple Spanner instances from that?
It will be useful if you can put a short code snippet showing exactly how you are creating the spanner objects.
@garrettjonesgoogle Only explicit thread we create in spanner library is a daemon thread:
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/WatchdogInterceptor.java#L106

**Comment by vkedia** [comment]
@ericandrewschmidt Ping!

**Comment by pongad** [comment]
I'll close this due to inactivity. Please reopen if you are still seeing this problem.

**Comment by TJ-Liu** [comment]
I experience similar thing. 
Our application did: 

    SpannerOptions options = SpannerOptions.newBuilder().setProjectId(projectId).build();
    Spanner spanner = options.getService();
    dbClient = spanner.getDatabaseClient(DatabaseId.of(options.getProjectId(), instance, database));

Spanner is not closed gracefully and the application hangs after dbClient read/write some requests. It has been hanging for days until reboot manually.

**Comment by sduskis** [comment]
@TJ-Liu which version of the client are you using?

**Comment by olavloite** [comment]
I can confirm this behavior in all recent versions of the client library. I tested from 1.14.0 to 1.19.0, and they all show this behavior using this simple application:

```java
  public static void main(String[] args) throws IOException {
    System.out.println("Starting application");
    SpannerOptions options = SpannerOptions.newBuilder().setProjectId("test-project")
        .setCredentials(GoogleCredentials.fromStream(new FileInputStream("key.json")))
        .build();
    Spanner spanner = options.getService();
    DatabaseClient client = spanner.getDatabaseClient(DatabaseId.of("test-project", "test-instance", "test-db"));
    try(ResultSet rs = client.singleUse().executeQuery(Statement.of("SELECT 1" ))) {
      while(rs.next()) {
        // do nothing
      }
    }
    System.out.println("Finished application");
  }
```

It seems it is caused by the default executor that is created here:

https://github.com/googleapis/google-cloud-java/blob/07c3d62165d5d6b8b96b83988729a274495be1c8/google-cloud-clients/google-cloud-core-grpc/src/main/java/com/google/cloud/grpc/GrpcTransportOptions.java#L57

Changing that executor to create daemon threads solves the problem and will allow the above example program to shutdown automatically at the end of the main method.

@sduskis I would think that this is something that should be changed in google-cloud-core-grpc and not something that the Spanner library should try to work around. Or is there a reason why this class is not creating daemon threads?

**Comment by olavloite** [comment]
Note to all above: Even though this problem should be fixed, it is still **always** a good idea to close a Spanner instance at the end of your application. `Spanner#close()` will close all connections and clean up all sessions that have been created on the backend Cloud Spanner servers. Failing to do so, will keep sessions living longer on the backend than is necessary. Spanner has a limit on the number of open sessions per node, and you could run into [this limit](https://cloud.google.com/spanner/quotas#limits_for_creating_reading_updating_and_deleting_data) if you fail to close your Spanner instances.
