### ISSUE TITLE
Storage service should manage resumeable signedURL uploads

### ISSUE THREAD

**Issue by salrashid123** [googleapis/google-cloud-java#2462]
google-cloud-java currently allows users to mint a signedURL but offers not way to separately manage the resumable upload given _just_ the signedURL.

The usecase for this is if i have in possession a signedURL that allows for resumeable uploads, i'd like to use google-cloud-java to manage the transfer for me. 

some background:

 - a resumable transfer session requires a special header to get it going (```x-goog-resumable: start```) as described [here](https://cloud.google.com/storage/docs/xml-api/resumable-upload#step_1wzxhzdk14initiate_the_resumable_upload).   At the moment, our java libraries do not support baking in the canonical headers into the signedURL.  see [issue#2000](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2000)
          
- Even if we do support a signeURL that allows for the transfer initiation, i didn't see anyplace within the library which will manage that transfer for you (i.,e handle retries, partial transfers, etc) given just a signedURL.  It does appear that resumeable uploads are [supported](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/Bucket.java#L834)  but that appears to be about authenticated uploads (not signedURL)

my 2c on how this may look

create a signedURL somewhere else and provide a header to allow the uploads 

```java
         Storage storage_service = StorageOptions.newBuilder()
        .setCredentials(ServiceAccountCredentials.fromStream(new FileInputStream("svc_acct.json")))
        .build()
        .getService();          
        
        BlobId blobId = BlobId.of(bucketName, objectName);
        BlobInfo blobInfo = BlobInfo.newBuilder(blobId).setContentType(content_type).build();
    
        SignUrlOption opts = SignUrlOption.withContentType()  // (+new way to add headers:("x-goog-resumable:start")       
        URL signedUrl = storage_service.signUrl(blobInfo, 60,  TimeUnit.SECONDS, opts);

```

then on the client, google-cloud-java would upload an object without needed authentication...and manage the retry on resume.

```java
        Storage storage_service_no_creds = StorageOptions.newBuilder()
        .setCredentials(NoCredentials.getInstance())
        .build()
        .getService();         
       
        storage_service_no_creds.create(blobInfo, "filecontent".getBytes(UTF_8), signedUrl);      

```

**Comment by frantello** [comment]
Kindly see pull request #2422 for a solution for issue #2000

**Comment by salrashid123** [comment]
also for ref
[google-cloud-dotnet's implementation](https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Storage.V1/api/Google.Cloud.Storage.V1.SignedUrlResumableUpload.html)

**Comment by hzyi-google** [comment]
@frantello  Thanks for the pull request. Close the issue now. @salrashid123 please share your thoughts here if you have more questions.

**Comment by salrashid123** [comment]
The two PR's cited in https://github.com/googleapis/google-cloud-java/issues/2462#issuecomment-332474754  don't cover managing a resumeable upload entirely from the client (which is what this git issue is about).  Those PRs seem to cover creating and sending a one-time transfer.

**Comment by andrey-qlogic** [comment]
@salrashid123 , @sduskis 
I would assume you could add "x-google-resumable" header as an extension header using this approach. Please let me know if the method works for you.
```java
    SignUrlOption optWithContentType = SignUrlOption.withContentType();
    Map<String, String> extHeaders = new HashMap<>();
    extHeaders.put("x-goog-resumable", "start");
    SignUrlOption optWithExtHeaders = SignUrlOption.withExtHeaders(extHeaders);
    SignUrlOption[] opts = {optWithContentType, optWithExtHeaders};
    URL signedUrl = storage_service.signUrl(blobInfo, 60, TimeUnit.SECONDS, opts);
```

**Comment by salrashid123** [comment]
We can add the header in now but that'll address the first part; there still isn't a way to use that URL within context of this library, eg we can do this now

```java
BlobId blobId = BlobId.of(bucketName, objectName);
BlobInfo blobInfo = BlobInfo.newBuilder(blobId).setContentType(content_type).build();

Map<String, String> mmap = new HashMap<String,String>() {{
	put("x-goog-resumable", "start");
}};
SignUrlOption opts = SignUrlOption.withContentType().withExtHeaders(mmap);

URL signedUrl = storage_service.signUrl(blobInfo, 60,  TimeUnit.SECONDS, opts);
System.out.println(signedUrl);
```

and we're left with a URL that has the properties (headers) we need to start the trasfer

but i dind't see a place to put that URL in to do the uploads by just passing in a url (string) alone

eg, to do this

```java
Storage storage_service_no_creds = StorageOptions.newBuilder()
.setCredentials(NoCredentials.getInstance())
.build()
.getService();         
		   
storage_service_no_creds.create("filecontent".getBytes("utf-8"), signedUrl);  
```

Having a client that does this upload management is a nice to have (otherwise, i'd take the signedURL and perform client-side management like [this](https://medium.com/google-cloud/google-cloud-storage-signedurl-resumable-upload-with-curl-74f99e41f0a2).   Its fair to ask/question if _this_ client library should also contain logic to do that (meaning, if i knew java well and was careful, i could write a `com.sal.resumableupload.Uplaoder(content,url)`  and just use that independently of this library

**Comment by andrey-qlogic** [comment]
@salrashid123 
Can you use MediaHttpUploader, which support the [resumable upload](https://github.com/googleapis/google-api-java-client/blob/41fac3bd26919cd60e220a82513bbd6fb720f179/google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploader.java#L330) for your task ?

**Comment by salrashid123** [comment]
i gave it a shot but i think the protocols are a little different.  When the signedURL is generated, we've got specify the headers precisely and the URLs have got to match exactly

eg, here's the signedURL:

```
https://storage.googleapis.com/mineral-minutia-820/signed.txt?GoogleAccessId=svc-2-429@mineral-minutia-820.iam.gserviceaccount.com&Expires=1552598875&Signature=yjpj5O<redacted>
```

and if i pass that through to the meaduploader,  it looks like this (note the headers and the last `&uploadType=resumeable`

```
POST https://storage.googleapis.com/mineral-minutia-820/signed.txt?GoogleAccessId=svc-2-429@mineral-minutia-820.iam.gserviceaccount.com&Expires=1552598875&Signature=yjpj5OY<redacted>&uploadType=resumable
Accept-Encoding: gzip
User-Agent: Google-HTTP-Java-Client/1.28.0 (gzip)
x-upload-content-type: text/plain
Content-Length: 0
```

It _maybe_ possible to use this client after some modifications.   If anyone is interested, i've placed what i've done so far in this gist:

https://gist.github.com/salrashid123/5649782f04449f1226f86c8f6e8e85f0
and reference the [signedurl upload with curl article](https://medium.com/google-cloud/google-cloud-storage-signedurl-resumable-upload-with-curl-74f99e41f0a2)

**Comment by salrashid123** [comment]
ok, looked at it a bit more...i got the sigedurl with the correct headers, then the location header value for resumable uploads.   but  i think the logic at the final step here 
- [MediaHttpUploader.java](https://github.com/vparfonov/google-api-java-client/blob/master/google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploader.java#L289)
 expects a slightly different protocol.


If anyone wants to try it out, here is the latest sample:

- [Test.java](https://gist.github.com/salrashid123/5649782f04449f1226f86c8f6e8e85f0#file-com-test-testapp-java-L179)

* note, i do know the signed resumable URL is constructed properly:  using the locationURL provided in the sample above, i can successfully upload via `curl -v -X PUT --upload-file /tmp/signed.txt <url>`

 i suspect it is possible to adapt the MediaHttpUploader somehow but i don't have the cycles to look at that part
