### ISSUE TITLE
cannot resolve method .getService();

### ISSUE THREAD

**Issue by RakeshSiddu** [googleapis/google-cloud-java#2548]
CODE =  final Translate translate = TranslateOptions.getDefaultInstance().getService();
here getService() is not working.

**Comment by garrettjonesgoogle** [comment]
What environment are you getting this error in?

**Comment by ImranArtwel** [comment]
I am also having the same problem. Running on android studio
`final Translate translate = TranslateOptions.getDefaultInstance().getService();`

**Comment by pongad** [comment]
@ImranArtwel We don't currently support Android. Please see the list of supported platforms [here](https://github.com/GoogleCloudPlatform/google-cloud-java#supported-platforms).

**Comment by Pankajbhalekar93** [comment]
@pongad 
I am getting the same here cannot find symbol for
"TranslateOptions.getDefaultInstance().getService();"

Please help

Thanks

**Comment by thgiang** [comment]
Same error :(
