### ISSUE TITLE
Spanner: Automatically release session to the pool when read/query ends on single use transaction

### ISSUE THREAD

**Issue by vkedia** [googleapis/google-cloud-java#2666]
Currently in a single use transaction, when the `ResultSet` returned by read/executeQuery is closed or it completely iterated on (till `next` returns false), we release the session to the pool. This is error prone as the user might not do either.
Instead of this we should automatically free up the session when the rpc finished.

**Comment by pongad** [comment]
@vkedia Has this been worked on?

**Comment by vkedia** [comment]
Not yet.

**Comment by sduskis** [comment]
I'm closing this for now.  Please reopen this issue if there's anything we need to do.
