### ISSUE TITLE
Firestore Query: unsupported FieldFilter value type: 6

### ISSUE THREAD

**Issue by Klabauterman** [googleapis/google-cloud-java#2816]
Hello,
I was using a filter like this on a firestore collection:
`whereEqualTo("access", emptyMap<String, Any>())`
I want to find all documents, where all users stopped using them and hence delete them afterwards.

After setting up the listener I get the correct result, but directly after that I get the following error:
`com.google.cloud.firestore.FirestoreException: Backend ended Listen stream: Unsupported FieldFilter value type: 6`

So my question:
Will you add support for such Queries? If not, why do I get a correct the result at first?

**Comment by schmidt-sebastian** [comment]
This is a known issue and we are currently prioritizing this work. Thanks for your report! For now, we recommend that you use the non-streaming `Query.get()` API endpoint.

**Comment by Klabauterman** [comment]
Cool, thanks for the information.

**Comment by rockwotj** [comment]
This should be fixed now.

**Comment by ajaaym** [comment]
Closing this as it seems fixed.
