### ISSUE TITLE
Generalize Bigtable's regenerate scripts to applicable to other clients

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-java#2852]
The new Bigtable client has 2 scripts to help test GAPIC config changes. The scripts allow the developer to make a change in a local googleapis checkout and see how the changes will look in `api-client-staging` and `google-cloud-java`. It would be nice to open these scripts to other clients.

Also, the update script is currently pretty careless about overwriting local changes, this will need to narrowed down to autogenerated files to avoid destroying local changes

**Comment by igorbernstein2** [comment]
This came out of discussion in #2841. I was planning on generalizing the scripts once the bigtable client stabilizes. Should I not be planning to do this?

**Comment by hzyi-google** [comment]
Sorry I thought this issue was used to track the merged PR.

**Comment by chingor13** [comment]
There is now the `utilities/batch_generate_apis.py` script and yoshi-team is using [synthtool](https://github.com/googleapis/synthtool) to regenerate clients in #3765.
