### ISSUE TITLE
Remove ssl context customization in Spanner

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/google-cloud-java#2871]
Specifically, ciphers should not be set to null:

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java#L311

Then this line can be removed, which is netty specific:

https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java#L299

**Comment by garrettjonesgoogle** [comment]
cc @vkedia @pongad @ejona86

**Comment by danoscarmike** [comment]
Removing priority label as this is not a bug. Let's triage feature requests separately and prioritize appropriately in development backlog.

**Comment by garrettjonesgoogle** [comment]
This is a potential security concern. Removing the feature request label.

**Comment by ejona86** [comment]
It's also a compatibility concern. Any environment actually using one of the additional ciphers chosen here (like if running on JDK 7 with Jetty ALPN) is unsupported and can break at any time.

**Comment by hzyi-google** [comment]
Migrating to Gapics would remove ssl context customization.

**Comment by chingor13** [comment]
Spanner gapic migration makes this no longer necessary.
