### ISSUE TITLE
Perform snapshot releases after successful builds to master

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/google-cloud-java#2882]
We lost releases of snapshot versions when we turned off the oraclejdk7 build on Travis (since the after_success.sh script only performed releases for that build variant). 

Now that we are using Circle, we should add a step in the CircleCI workflow to perform a snapshot release after all jobs finish (operating systems + integration tests).

**Comment by sduskis** [comment]
We release weekly.  I don't think we plan on doing SNAPSHOT releases.
