### ISSUE TITLE
Bucket logging configuration using library

### ISSUE THREAD

**Issue by ihsanhaikalz** [googleapis/google-cloud-java#2911]
I was wondering whether it is possible to set the bucket logging in the target bucket with the access logs are then stored in the bucket log as it is explained here https://cloud.google.com/storage/docs/access-logs but this is only possible using gsutil. There is the option for XML API here https://cloud.google.com/storage/docs/xml-api/put-bucket-logging but not sure if there is one in this google-cloud-java storage library. If it is possible how do I do it?

**Comment by pongad** [comment]
I don't believe this feature is available here yet. @hzyi-google can you confirm? If it is unavailable, let's turn it into feature request.

**Comment by hzyi-google** [comment]
I don't think there is either.

**Comment by ihsanhaikalz** [comment]
I think it will be good as well if you could check the status of bucket logging and remove bucket logging if needed as doing this from console is quite hectic
