### ISSUE TITLE
Bigquery API should support external Sheets-based tables

### ISSUE THREAD

**Issue by mikekap** [googleapis/google-cloud-java#2952]
Google Sheets based tables don't currently show up via the java API. There's also no way to create new tables with sheets definitions. It would be nice if this was supported.

**Comment by tswast** [comment]
Relevant API docs:

https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/bigquery/ExternalTableDefinition.Builder.html#setFormatOptions-com.google.cloud.bigquery.FormatOptions-

https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/bigquery/GoogleSheetsOptions.html

**Comment by shollyman** [comment]
Closing this one as it's present in the library. There's some supplemental work to expose the range property for sheets, but that's being handled in https://github.com/googleapis/google-cloud-java/issues/6198
