### ISSUE TITLE
bigtable: Rename Mutation -> Mutations

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-java#2957]
As reported by @kevinsi4508:

`Mutation` represents a set of mutations for a row, so it would be less confusing if it was pluralized.

**Comment by sduskis** [comment]
@igorbernstein2, is this still desired?

**Comment by igorbernstein2** [comment]
I think it's low enough priority that I would prefer not to break compatibility

**Comment by sduskis** [comment]
@igorbernstein2, can we close this?
