### ISSUE TITLE
bigtable: update javadocs for settings to describe the defaults

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-java#2992]
This is extracted from: https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2986/files/5ce135c8e7f55fd510382574357b14a775f5619b#r171952810

The javadocs should document the default timeouts

Please assign this to me

**Comment by sduskis** [comment]
@igorbernstein2, our team will be tackling docs issues next week.  Let's discuss how to move this forward.
