### ISSUE TITLE
Convert Spanner to use Watchdog from GAX

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/google-cloud-java#2999]
Deprecate https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/WatchdogInterceptor.java , use https://github.com/googleapis/gax-java/blob/master/gax/src/main/java/com/google/api/gax/rpc/Watchdog.java instead.

If Spanner uses watchdogs for client streaming or bidi streaming cases, then analogs to https://github.com/googleapis/gax-java/blob/master/gax/src/main/java/com/google/api/gax/rpc/WatchdogServerStreamingCallable.java will need to be created in GAX.

**Comment by danoscarmike** [comment]
@garrettjonesgoogle as a priority: p1 we need to assign this work. Is it related to the general body of work including #3001?  If yes, then suggest we downgrade and manage as a cohesive plan rather than individual issues. WDYT?

**Comment by garrettjonesgoogle** [comment]
Yes, this falls under the work of #3001 . It makes sense to remove "p1", although work is actively in progress by @hzyi-google .

**Comment by chingor13** [comment]
Fixed in #3923
