### ISSUE TITLE
Create new efficient batching implementation for Pub/Sub and Logging

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/google-cloud-java#3003]
Try to support BigTable too. 
- [x] Bigtable
- [ ] Pub/Sub
- [ ] Logging

**Comment by sduskis** [comment]
This is in progress for Cloud Bigtable: https://github.com/googleapis/gax-java/pulls?utf8=%E2%9C%93&q=is%3Apr+batcher

This will land eventually.

**Comment by IRus** [comment]
Does this new API will include ability to publish list of messages? Like `fun publish(messages: List<PubsubMessage>): ApiFuture<List<String>>`

**Comment by rahulKQL** [comment]
@IRus Sorry for the late response. As of now, we have yet to implement this feature on `google-cloud-pubsub`.

The surface for that is not yet finalized but it would support something similar to [Batcher](https://github.com/googleapis/gax-java/blob/master/gax/src/main/java/com/google/api/gax/batching/Batcher.java#L45-L79)<PubsubMessage, String>, then one can perform batching with this batcher.

**Comment by jmouvill** [comment]
What would be the difference with the current `BatchSettings` available on the Publisher's builder ? 
i.e: 
```
Publisher
      .newBuilder(topic)
      .setBatchingSettings(
        BatchingSettings.newBuilder.
          setFlowControlSettings(...)
          .setElementCountThreshold(...)
          .setRequestByteThreshold(...)
          .setDelayThreshold(...)
          .build
    )
```
where you can specify an `elementCountThreshold`, `requestByteThreshold` etc ?

**Comment by rahulKQL** [comment]
@jmouvill This feature has been little delayed for Pubsub, but I would say `BatchingSettings` configurations would be similarly respected in new batching impl. We are planning to use the same `BatchingSettings` to set thresholds for `Batcher`instance.

**Comment by chingor13** [comment]
This issue has been split into the 2 linked tracking issues to implement in the logging and pubsub clients respectively.
