### ISSUE TITLE
Interop w/ other Google HTTP clients

### ISSUE THREAD

**Issue by saturnism** [googleapis/google-cloud-java#3013]
GCP and other Google products have also published ready to use HTTP clients: https://mvnrepository.com/artifact/com.google.apis

With a little interop configurations, it can be very easy to consume these client libraries using google-cloud-java's authentication bootstrap.

**Comment by Alos** [comment]
+1

**Comment by chingor13** [comment]
A `HttpCredentialsAdpapter` is already available to use credentials fetched from google-auth-library-java (com.google.auth). Note that this will only work for cloud like APIs that can use service accounts (will not work for 3-legged OAuth2 where you need to authenticate on behalf of an end-user).

Something like:
```java
// import com.google.api.client.http.HttpRequestInitializer;
// import com.google.api.services.bigquery.Bigquery;
// import com.google.auth.http.HttpCredentialsAdapter;
// import com.google.auth.oauth2.GoogleCredentials;

GoogleCredentials credentials = GoogleCredentials.getApplicationDefault();
HttpRequestInitializer requestInitializer = new HttpCredentialsAdapter(credentials);

Bigquery bq = new Bigquery.Builder(HTTP_TRANSPORT, JSON_FACTORY, requestInitializer)
    .setApplicationName(APPLICATION_NAME)
    .build();
```

We should document this, likely on the google-auth-library-java repository and link to the instructions from the primary README.
