### ISSUE TITLE
Logback logstash exception logging 

### ISSUE THREAD

**Issue by skjolber** [googleapis/google-cloud-java#3031]
Logging of exception stacktraces for Logback have been resolved in #2765, however we are aiming to do  JSON logging to console and per default it seems this will not give us stack traces in the 'message' field of jsonPayload as required by [Formatting Errors in Stackdriver Logging](https://cloud.google.com/error-reporting/docs/formatting-error-messages). 

Do you have any advice on this can be done using [logstash-logback-encoder](https://github.com/logstash/logstash-logback-encoder)?

**Comment by jabubake** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2912#issuecomment-369552213

**Comment by sduskis** [comment]
@ajaaym, can this be closed?

**Comment by ajaaym** [comment]
Closing this issue, please try to follow the configuration as per link in above discussion and reopen or create new if required.
