### ISSUE TITLE
Using Pubsub with Proxy that needs a basic authentication

### ISSUE THREAD

**Issue by jjpet123** [googleapis/google-cloud-java#3035]
Hello, 

We are using GCP SDK and pubsub service in our project and we'd need to go through an outbound proxy before reaching out to Google. We understand the transport for pubsub is gRPC. We are wondering if there is a way that we can configure the basic authentication for the outbound proxy via the SDK or any other way? We are aware of setting proxy HOST and PORT via environment variables but nothing related to the basic authentication for proxy though, any information on proxy authentication for pubsub is appreciated, thanks!

**Comment by jjpet123** [comment]
Hello,

Does anyone know how to authenticate with a proxy when using GCP pubsub? Does pubsub support proxy authentication like basic? It is pretty much blocking our process here, any info is much appreciated!

**Comment by jjpet123** [comment]
Hey, is there any clue around this? supported or not, like a workaround, etc? Thanks.

**Comment by ajaaym** [comment]
proxy authentication can be set by using ```java.net.Authenticator.setDefault()``` as per example over [here](https://www.blackbaud.com/files/support/infinitydevguidemobile/Advanced/subsystems/inwebapi-developer-help/Content/Java/coJavaBasicAuthentication.htm) Closing this issue for now. Please reopen this issue if it needs further attention.

**Comment by jochenw** [comment]
Please, reopen. The suggested solution to use Authenticator.setDefault() is obviously unusable in a multi-threaded environment, where the Basic authentication credentials cannot be considered constant.
