### ISSUE TITLE
dialogflow heartbeat/ping using SDK

### ISSUE THREAD

**Issue by prayagupd** [googleapis/google-cloud-java#3038]
**Is there a way to check if my app is able to talk to dialogflow agent using java SDK?** (https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-dialogflow)

The purpose is just to verify the `credentials` are working and connectivity is working when I deploy my application, before actual traffic flows in.

One way I can think of is make a intent-request itself which is not a good solution in my opinion; I wrote something as below (in clojure using java sdk)

```clojure
(defn heartbeat [{nlu-agent :nlu-agent utterance :utterance creds-file :creds-file}]
  (try
    (send-intent-request
     {:nlu-agent  nlu-agent
      :utterance  utterance
      :creds-file creds-file})
    "success"
    (catch Throwable e
      (.getMessage e))))
```

And obviously I'm using `credentials.json` provided my `gcloud` which looks as below (taken from https://cloud.google.com/video-intelligence/docs/common/auth#authenticating_with_application_default_credentials);

```json
{
  "type": "service_account",
  "project_id": "project-id",
  "private_key_id": "some_number",
  "private_key": "-----BEGIN PRIVATE KEY-----\n....
  =\n-----END PRIVATE KEY-----\n",
  "client_email": "<api-name>api@project-id.iam.gserviceaccount.com",
  "client_id": "...",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/...<api-name>api%40project-id.iam.gserviceaccount.com"
}
```

But don't want to send actual intent-requests in PROD every minute just for the sake of heartbeat.

I had same question in another place too but this seems a right place to ask questions - https://github.com/dialogflow/dialogflow-java-client-v2/issues/14

**Comment by chingor13** [comment]
Are you changing your credentials all the time? 

It seems unnecessary to try and verify that your credentials are continuing to work. This would be the case for any resource on any API - you shouldn't need to check to see if your credentials work every time before making the API calls.
