### ISSUE TITLE
NIO channels could optimize buffer-invalidation on seeks

### ISSUE THREAD

**Issue by ryan-williams** [googleapis/google-cloud-java#3041]
[`BlobReadChannel` dumps its buffer on any seek](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.38.0/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannel.java#L104), therefore [so does `CloudStorageReadChannel`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.38.0/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageReadChannel.java#L164).

This causes unexpected/pathological behavior, e.g. in [hadoop-bam](https://github.com/HadoopGenomics/Hadoop-BAM)/[spark-bam](http://www.hammerlab.org/spark-bam/) where the read pattern is roughly "read 100 bytes, rewind 99 bytes, repeat 1000x"; basically the same [2MB](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.38.0/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannel.java#L41) is fetched over the network at every iteration.

spark-bam uses a [`CachingChannel`](https://github.com/hammerlab/io-utils/blob/channel-1.4.0/channel/src/main/scala/org/hammerlab/channel/CachingChannel.scala) abstraction that LRU-caches blocks of the underlying channel, which fixes this.

Just wanted to call out this "gotcha"; might be worth fixing here.

**Comment by lbergelson** [comment]
@jean-philippe-martin This is a slightly different use case than the buffering/prefetching we do in gatk, but maybe it could be addressed as part of the work on porting that.

**Comment by jean-philippe-martin** [comment]
It'd probably be best to at least first port the prefetching as is, but yes: the prefetcher *does* optimize buffer invalidation on seeks so if you are using it then you're good.

**Comment by lbergelson** [comment]
The weird bit here is that this query moves backwards slightly from the original fetch.  Does the current pre-fetcher handle that correctly? I  had thought it only supported forward motion and would probably invalidate the buffer if it moved backwards.  I could just be wrong though.

**Comment by jean-philippe-martin** [comment]
The prefetcher uses blocks. So long as the backward read is within the block, we'll be able to serve data. If you go far back enough that we don't have that data anymore we have to fetch it again of course.

So for example if you use 1 million bytes blocks, and you seek to 1'000'300, read something, and then seek to 1'00'020, you'll be good because you're in the same block. That's just a random number for explanation, of course.

**Comment by lbergelson** [comment]
Ah, sounds good then.

**Comment by jean-philippe-martin** [comment]
Pull request #3054 introduced `SeekableByteChannelPrefetcher` into nio, which does smart buffering (also, prefetching). It retains buffers on seeks so closes this issue (even though it's a tad different, as @lbergelson pointed out).

**Comment by ryan-williams** [comment]
`SeekableByteChannelPrefetcher` is really cool, but last I looked, it was not used in this codebase, so no one is getting it via the `FileSystemProvider` implemented here.

I've always thought that was strange, but didn't think to ask what the story was. Am I missing something?

AFAICT we would need to change e.g. `BlobReadChannel` to use it, to satisfy the initial issue I reported.

**Comment by lbergelson** [comment]
@jean-philippe-martin Would it be possible to add an `OpenOption` that would allow you to configure the prefetcher?  I.e `Files.newByteChannel( Paths.get(input), new PrefetchingBufferSize(1024))` which would be understood by the filesystem?  That might be a nice way to do it but I don't know if that's doable.

**Comment by ryan-williams** [comment]
@jean-philippe-martin cool, I didn't realize it was that easy. Perhaps there are still places where a channel is used, but consumed and not exposed to outside code? Anyway it does seem like this solves a lot of the issue, so gtk.

**Comment by jean-philippe-martin** [comment]
@lbergelson this would violate the minimality principle: this function is already available in the API, adding a second way to do the same thing would bring very little benefit but be confusing to users. It would increase the maintenance, testing, and documentation burden, and every single new user would have to ask themselves "which way is better?" and investigate. I'd rather have a single way to do this.

**Comment by jean-philippe-martin** [comment]
@ryan-williams I don't think the google-cloud-nio library opens its own channel anywhere. Even the copy operation delegates to `storage.copy`.

**Comment by chingor13** [comment]
This issue appears to be resolved. Feel free to re-open if it's still an issue.
