### ISSUE TITLE
BigQuery Create partitioned table with Tables.insert(tableResourceObject). TimePartitioning doesnot support 'field' string

### ISSUE THREAD

**Issue by rsurve-infoworks** [googleapis/google-cloud-java#3058]
TimePartitioning object should ideally have   "timePartitioning": {
    "type": string,
    "expirationMs": long,
    "field": string,
    "requirePartitionFilter": boolean
  },
In the current api, there is no support for specifying 'field' and 'requirePartitionFilter' for creating a load job for partitioned tables.

**Comment by pmakani** [comment]
This seems fixed. Please feel free to reopen this one or create new one if needed.
