### ISSUE TITLE
ConcurrentModificationException in endpoints v2.0 tester, app engine standard, using maven archetype for hello-world

### ISSUE THREAD

**Issue by askrht** [googleapis/google-cloud-java#3068]
The function
```javascript
_.createError = function createError(msg){
  return new $wnd.Error(msg);
}
;
```
inside `com.googe.apis.explorer.Explorer-0.js` reports the following Exception:

`java.util.ConcurrentModificationException`

Steps:
1. Generate a new endpoints v2.0 app for app engine standard, using maven archetype, for hello-world
1. cd hello-world
1. mvn clean compile package
1. mvn appengine:run
1. Disable the security in Google Chrome by using the command line options and navigate to http://localhost:8080/_ah/api/explorer
1. Click on Services > hello world API
1. You will see a JavaScript error `Uncaught Error: com.google.gwt.event.shared.UmbrellaException`.
1. Put a breakpoint in the script:function mentioned above and you will see the error `java.util.ConcurrentModificationException`

I also noticed this error as a peculiar side effect of [Multiclass API](https://cloud.google.com/endpoints/docs/frameworks/java/multiclass) that I was trying earlier. This error only showed up in the  Discovery Services API and in the first custom API. It works fine up when you click the 2nd custom API. Strange.

The error stays whether you use Java 7 or Java 8 or if you user cloud version 191.0.0 or version 194.0.0.

**Comment by ajaaym** [comment]
@askrht I tried the steps you mentioned and cant reproduce. If you are still facing this issue can you please provide full repro?

**Comment by codyoss** [comment]
Closing due lack of response from reported, please re-open if you are still having issues.
