### ISSUE TITLE
Improve Providing Credential Programmatically or String

### ISSUE THREAD

**Issue by saturnism** [googleapis/google-cloud-java#3070]
Documentation for providing credentials seems outdated.
For most services, need to use a `CredentialProvider` to wrap another `Credentials` object.

There is `GoogleCredentails.fromStream` and `ServiceAccountCredentials.fromStream`. There is no documentation on when to use what and why one is not preferred.

Lastly, when setting credentials programmatically, setting the credential via a String as oppose to `InputStream` is common. 

Proposed enhancements
- [ ] Improve documentation on providing credentials programmatically for both HTTP-based client and gRPC-based client
- [ ] De-duplicate GoogleCredentials and ServiceAccountCredentials?
- [ ] Add a method to set JSON key content via a String in addition to the current InputStream.

**Comment by tswast** [comment]
In addition to clearing this up / de-duplicating, I'd the solution to show how to provide arbitrary credentials, such as end-user credentials via a 3-legged OAuth2 flow.

**Comment by chingor13** [comment]
ADC is the much preferred method for authentication. The explicit builder interface is fine for instantiating credentials programmatically.
