### ISSUE TITLE
google-cloud-logging-logback: NoSuchMethodError with 0.42.0

### ISSUE THREAD

**Issue by ggprod** [googleapis/google-cloud-java#3099]
java.lang.NoSuchMethodError: com.google.protobuf.AbstractMessageLite$Builder.addAll(Ljava/lang/Iterable;Ljava/util/List;)V at com.google.logging.v2.WriteLogEntriesRequest$Builder.addAllEntries(WriteLogEntriesRequest.java:1818) at com.google.cloud.logging.LoggingImpl.writeLogEntriesRequest(LoggingImpl.java:511) at com.google.cloud.logging.LoggingImpl.writeAsync(LoggingImpl.java:593) at com.google.cloud.logging.LoggingImpl.writeLogEntries(LoggingImpl.java:559) at com.google.cloud.logging.LoggingImpl.write(LoggingImpl.java:522) at com.google.cloud.logging.logback.LoggingAppender.append(LoggingAppender.java:201) at com.google.cloud.logging.logback.LoggingAppender.append(LoggingAppender.java:63) at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84) at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51) at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270) at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257) at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421) at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383) at ch.qos.logback.classic.Logger.log(Logger.java:765) at org.apache.commons.logging.impl.SLF4JLocationAwareLog.info(SLF4JLocationAwareLog.java:155) at org.springframework.boot.SpringApplication.logStartupProfileInfo(SpringApplication.java:597) at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:342) at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) at

**Comment by ocervell** [comment]
Encountering the same issue.

**Comment by pongad** [comment]
@ggprod Which version of protobuf are you using? I believe the latest library uses protobuf version `3.5.1`.

**Comment by neeleym** [comment]
I, too, am having the same result with this dependency. My dependency tree does show 3.5.1 of protobuf being used. I am using this in conjunction with google-cloud-dlp release 0.46.0-beta.

**Comment by pongad** [comment]
@neeleym This is very surprising. Protobuf 3.5.1 [source file](https://github.com/google/protobuf/blob/v3.5.1/java/core/src/main/java/com/google/protobuf/AbstractMessageLite.java) suggests that this dependency should exist. Could you share your `pom.xml` file? I can try to figure out what's going on.

**Comment by neeleym** [comment]
@pongad I agree that the dependency as suggested does exist, so unsure how this is not succeeding. Below is my pom file. I am using this in conjunction with Flume, so you will see that in the pom file. I am excluding guava from Flume because it is using a very old version and I am letting the DLP guava version take over ( 0.20.0 ). I got passed that collision and now have the error originally posted by the OP. My stack trace is below the pom file later.

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.objectcomputing.dlp</groupId>
    <artifactId>custom-dlp-interceptor</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-dlp</artifactId>
            <version>0.46.0-beta</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.protobuf</groupId>
                    <artifactId>protobuf-java</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flume</groupId>
            <artifactId>flume-ng-core</artifactId>
            <version>1.8.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>
        </plugins>
    </build>



</project>`



Stack trace:

`java.lang.NoSuchMethodError: com.google.protobuf.AbstractMessageLite$Builder.addAll(Ljava/lang/Iterable;Ljava/util/List;)V
	at com.google.privacy.dlp.v2beta1.InspectConfig$Builder.addAllInfoTypes(InspectConfig.java:1877)
	at com.objectcomputing.dlp.flume.interceptor.GcpDlpClient.protect(GcpDlpClient.java:22)
	at com.objectcomputing.dlp.flume.interceptor.CustomDlpInterceptor.intercept(CustomDlpInterceptor.java:22)
	at com.objectcomputing.dlp.flume.interceptor.CustomDlpInterceptor.intercept(CustomDlpInterceptor.java:35)
	at org.apache.flume.interceptor.InterceptorChain.intercept(InterceptorChain.java:62)
	at org.apache.flume.channel.ChannelProcessor.processEventBatch(ChannelProcessor.java:148)
	at org.apache.flume.source.SpoolDirectorySource$SpoolDirectoryRunnable.run(SpoolDirectorySource.java:258)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by dinvlad** [comment]
Similar issue here. We're using an outdated version of `google-cloud-java` (0.20.3-alpha) for compatibility reasons, and yesterday our services started to fail trying to communicate with Logging API. Now we have no choice but to attempt an (expensive) upgrade.

**Comment by ocervell** [comment]
It also seems like the link to the [google-cloud-logging-loback repository](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-contrib/google-cloud-logging-logback) doesn't exist anymore. Actually the whole 'google-cloud-contrib' seems to have vanished. @pongad Any idea what happened here ?

**Comment by AbhideepChakravarty** [comment]
@ggprod @dinvlad Did you guys make it work? I am using this library with firebase-admin and I am getting same exception. Basically if one library of Google is used with another, you end up at this type of exception.

**Comment by ggprod** [comment]
@AbhideepChakravarty no, I ended up giving up on that approach

**Comment by AbhideepChakravarty** [comment]
@ggprod So how are logging now ?

**Comment by ggprod** [comment]
@AbhideepChakravarty just used the ConsoleAppender in logback to put post the logs to stdout and stderr which is collected automatically by Stackdriver. It isn't ideal, but it worked
