### ISSUE TITLE
Severity is always set to INFO when using logging logback plugin

### ISSUE THREAD

**Issue by ocervell** [googleapis/google-cloud-java#3109]
I use the google-cloud-logging-logback plugin and the logs are forwarded properly to the ingestion agent (fluentd). 
However, the log level seems to not be picked up and the 'severity' field always shows as 'INFO' in Stackdriver, and this for any logs no matter their original level.
Any idea how to configure the logback.xml so that the severity is correctly reflected in Stackdriver Logging ?

**Comment by SergeyZadorozhniy** [comment]
Looks like it's already solved.
Have tested with different levels(info, warn, error, ..) all levels transferred correctly into Stackdriver.

Could you please provide some code example? 
To be sure the problem has been fixed.

**Comment by ajaaym** [comment]
Closing this assuming its fixed as per comment from @SergeyZadorozhniy. Please this is still an issue.

**Comment by ysde** [comment]
Still bump into this problem when using 0.76.0-alpha, all errors are logged as serverity: "INFO"
```"com.google.cloud" % "google-cloud-logging-logback" % "0.76.0-alpha"```

**Comment by garfieldnate** [comment]
I don't think this is fixed by default; this configuration is required:

    <encoder class="net.logstash.logback.encoder.LogstashEncoder">
        <fieldNames>
            <level>severity</level>
        </fieldNames>
    </encoder>

We override the field name for `level` to `severity`, as expected by Stackdriver.
