### ISSUE TITLE
Reduce size of gh-pages

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/google-cloud-java#3124]
Probably just retain latest/ instead of every single version every generated.

**Comment by sduskis** [comment]
@chingor13, do you have any context on this issue?

**Comment by chingor13** [comment]
We have a long term plan to move the hosted docs off of GitHub pages. The generated docs are huge and there's not a ton we can do about it (lots of static html pages). Even a single version's generated docs are large.

**Comment by sduskis** [comment]
I changed this to "type: process" since this relates to infrastructure rather than specific docs changes.

**Comment by sduskis** [comment]
@chingor13, can we close this?
