### ISSUE TITLE
[BigQuery] Allow to stream compressed data into BigQuery

### ISSUE THREAD

**Issue by zero-master** [googleapis/google-cloud-java#3169]
How can I turn on compression in BigQuery's Java driver?
I found here that the API supports gzip: https://cloud.google.com/bigquery/docs/api-performance

I need it for my streaming inserts which have very high compression ratio:
https://cloud.google.com/bigquery/streaming-data-into-bigquery#bigquery-stream-data-java

**Comment by ajaaym** [comment]
Gzip compression is enabled by default. Closing this issue for now. Please reopen this issue if you see uncompressed data.
