### ISSUE TITLE
Local Datastore API's

### ISSUE THREAD

**Issue by lesv** [googleapis/google-cloud-java#3186]
App Engine standard has [API's](https://cloud.google.com/appengine/docs/standard/java/tools/localunittesting#high-replication-datastore) to support unit testing in customers app's.

**Comment by jabubake** [comment]
@jba FYI

**Comment by willedwards** [comment]
Thanks for clarifying this. I find it bizarre there is no equivalent way to unit test like LocalDataService in the std version. Not what I'd expect from google.

This is a big enough reason to stick with java8 + std version for me.

**Comment by hzyi-google** [comment]
This looks like a feature request. Feel free to change the labels if not.

**Comment by ajaaym** [comment]
There is this [LocalDatastoreHelper](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/testing/LocalDatastoreHelper.java) available for unit test. [Here](https://gist.github.com/ensonic/a1b64be415f537b59bcc951883b29596) is the example how to create as external resource rule in case you want to use for unit test.

**Comment by ajaaym** [comment]
closing this issue. Please feel free to open if required.
