### ISSUE TITLE
Update all Maven and Gradle based library import instructions to use BOM

### ISSUE THREAD

**Issue by patflynn** [googleapis/google-cloud-java#3190]
all the specific API readme's instruct the user to directly import the versioned dependency using 
`<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-translate</artifactId>
  <version>1.27.0</version>
</dependency>`

This is setting users up for diamond dep conflicts as soon as they choose to import another library in the catalog.  

Instead we should always instruct the user to use the BOM to import google-cloud-java libraries.

**Comment by patflynn** [comment]
@GoogleCloudPlatform/cloud-tools-for-java

Garrett is accepting PRs. :)  Anybody got the bandwidth to work on updating these docs?

**Comment by chingor13** [comment]
This was fixed in #3269
