### ISSUE TITLE
Failed to deploy - FileNotFoundException

### ISSUE THREAD

**Issue by AdamSHurwitz** [googleapis/google-cloud-java#3275]
## Expected
JAR deployment to AppEngine instance for Kotlin app.

## Actual
During deployment to my AppEngine instance I am receiving the following **FileNotFoundException**. This error is not logical because the same built **JAR** runs the app successfully via IntelliJ prior to the deploy attempt.

Here is the Kotlin app file hierarchy which runs as expected both as an IntelliJ Application and JAR configuration. The "missing" directory/file is **firebase/carpecoin-service-firebase-adminsdk-cyl9p-4b18763dbc.json** which is nested under the **main** directory. The hierarchy was not altered after creating and building my JAR.

**App Hiearchy**
![screen shot 2018-05-15 at 11 06 43 pm](https://user-images.githubusercontent.com/3938076/40099483-0b74d550-5895-11e8-8c31-61e6961f4a39.png)

**Build Config**
![screen shot 2018-05-15 at 11 35 24 pm](https://user-images.githubusercontent.com/3938076/40100470-db82ca42-5898-11e8-9a12-dfaea673e0b2.png)

## Error
```Exception in thread "main" java.io.FileNotFoundException: src/main/firebase/carpecoin-service-firebase-adminsdk-cyl9p-4b18763dbc.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at Coordinator.main(Coordinator.kt:12)`
`Failed to deploy '[2018-05-15 23:00:21] carpe.coin_main.jar. Project: carpecoin-service. Version: auto': Deployment failed with exit code: 1```

## IntelliJ Info
IntelliJ IDEA 2018.1.3 (Community Edition)
Build #IC-181.4892.42, built on May 7, 2018
JRE: 1.8.0_152-release-1136-b38 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.10.5

**Comment by AdamSHurwitz** [comment]
I just ran the command **gcloud components update** and upgraded to the following:

```
Google Cloud SDK 201.0.0
app-engine-java 1.9.63
app-engine-python 1.9.69
bq 2.0.33
core 2018.05.11
gsutil 4.31
```
I'll attempt redeploying the same AppEngine build configuration.

**Comment by etanshaul** [comment]
thanks for details @AdamSHurwitz 

in that error, could you possibly paste in all the way up the stack? It looks like you provided only the end. I'm wondering if there is anything there that can help us debug.

**Comment by etanshaul** [comment]
and also, just to avoid further back and forth: could you also provide the contents of your `app.yaml` file (removing any personal info)?

**Comment by etanshaul** [comment]
I just realized, this is on the wrong repo. could you please migrate this to https://github.com/GoogleCloudPlatform/google-cloud-intellij

**Comment by AdamSHurwitz** [comment]
@etanshaul - Unfortunately I cannot provide the full log as I've re-created my Google Cloud and AppEngine Project in order to follow the recommendation for #3 under the potential issues above. I can re-do the original implementation if the following does not work.

**Potential Issues**
1. The service account key is not stored in version control history. I'm adding it locally to the project and ignoring the JSON file so it's not committed to Git.
2. I will test this implementation if 3 does not work.
3. I've attempted to implement this by starting a new Firebase project that is linked to a Google Cloud Project, however I am receiving an error. I've attempted with both GCP Billing enabled and disabled. Is this linking required in order to use the **default app engine credentials**? 

![add a project](https://user-images.githubusercontent.com/3938076/40156629-7fc9d6de-594f-11e8-9f7f-1de44be2c8cf.png)

![confirm firebase billing plan](https://user-images.githubusercontent.com/3938076/40156633-8286cfc6-594f-11e8-8416-3abb58a1079d.png)

**Comment by etanshaul** [comment]
@AdamSHurwitz I'm glad using the default credentials worked for you.

> My question with this implementation is am I supposed to save the code above to version control? How do I ensure anyone with this code cannot access my Firebase database?

Yes. That auth code can live in your vcs. Presumably you needed to authenticate in order to deploy your app in the first place to your GCP account. Only apps running on your account should have access via your application default credentials. Maybe I misunderstood the concern?

Regarding the Firebase billing concern, I'll defer to @garrettjonesgoogle to please help with routing the question as I don't have all the relevant information on this.

**Comment by AdamSHurwitz** [comment]
@etanshaul - My concern is if I shared my GitHub repository publicly someone would be able to run the authentication portion of code in order to interact with my Firebase database.

Thank you for directing my Firebase/GCP project linking bug to @garrettjonesgoogle.

**Comment by garrettjonesgoogle** [comment]
The firebase billing thing is outside of the scope of my knowledge - sorry!

**Comment by chingor13** [comment]
For the firebase billing error, that should be filed with Firebase: https://firebase.google.com/support/contact/

The original issue appears to have been answered. Feel free to reopen if this is not the case.
