### ISSUE TITLE
google-cloud-datastore Java library exposes too little of the information in query results

### ISSUE THREAD

**Issue by dgay42** [googleapis/google-cloud-java#3279]
In particular, this makes it impossible to implement a more efficient implementation of counting query results, as that requires the values from the skipped_results and more_results fields.

See https://groups.google.com/forum/#!topic/gcd-discuss/wH8lVOA-a8Y for an in-depth discussion of what's needed from query results to implement that.

Generally, skipped_results, more_results and snapshot_version should be available in QueryResults
(https://github.com/googleapis/googleapis/blob/master/google/datastore/v1/query.proto#L261)

**Comment by pongad** [comment]
@wsh Could you take a look?

**Comment by wsh** [comment]
Sure, though I'm not sure what you'd like me to look for/at. [QueryResultsImpl](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/a9f3af8413813efc394356918bd6b1c1ecdad999/google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/QueryResultsImpl.java#L78) already uses the `more_results` field. I think this is a question of taking the info from the existing proto and adding an elegant encapsulation for the interface (_or_ potentially exposing `runQueryResponsePb` itself).
