### ISSUE TITLE
BigQuery insertAll always retries operation

### ISSUE THREAD

**Issue by neuromantik33** [googleapis/google-cloud-java#3321]
Hi. First time reporter here.
I wanted to report a small but perhaps inconvenient bug in BigQuery, specifically regarding streaming inserts using an `InsertAllRequest`. It seems for some reason unknown to me that inserts are retried using the client's `RetrySettings` whenever row ids are supplied for deduplication.
When the current implementation always attempts a retry (which I discovered during these odd retry errors) due to the fact that `Lists.transform()` is strictly lazy.
Anyhow the fix is minor and I corrected it on my branch but I'm unsure how to write the necessary tests in order to validate my claim. My commit is here: https://github.com/neuromantik33/google-cloud-java/commit/984b5bb41cfb1ec0ef7cea27a0bc38d8adde5051, and after proper review I can submit a pull request.

Thanks in advance for any feedback.

**Comment by andreamlin** [comment]
Hi @neuromantik33,

Thanks for catching this issue! Would you mind turning your commit into a pull request? For testing, one option could be to add a unit test to `BigQueryImplTest.java`, set a spy on the `BigQueryOptions options` (see line 274), and assert that `getRetrySettings()` is called on that spy object when `BigQueryImpl.insertAll` is run or not run.
