### ISSUE TITLE
Document how to add custom outbound headers

### ISSUE THREAD

**Issue by saturnism** [googleapis/google-cloud-java#3336]
This issue came up a number of times already, where users need to add custom headers when using w/ their own proxy server for outbound calls.  Should document how to do this for both HTTP and gRPC  clients.

**Comment by pmakani** [comment]
@chingor13 please take a look this [doc](https://gist.github.com/pmakani/2fd4190ad58dde936c4e03b1cf96dab4)

**Comment by meltsufin** [comment]
Obsolete.
