### ISSUE TITLE
datastore.run can't be used without ReadOptions

### ISSUE THREAD

**Issue by maria-pacana-ck** [googleapis/google-cloud-java#3371]
I want to be able to call `run` without specifying any ReadOptions: `Option(datastore.run[Entity](query)`. If I don't pass in any ReadOptions, I get this error: 
```
ambiguous reference to overloaded definition, both 
method run in trait Datastore of type (
x$1: com.google.cloud.datastore.Query[com.google.cloud.datastore.Entity], 
x$2: com.google.cloud.datastore.ReadOption*)com.google.cloud.datastore.QueryResults[com.google.cloud.datastore.Entity]
and  
method run in trait DatastoreReader of type (
x$1: com.google.cloud.datastore.Query[com.google.cloud.datastore.Entity])
com.google.cloud.datastore.QueryResults[com.google.cloud.datastore.Entity]
match argument types (com.google.cloud.datastore.EntityQuery)
```

...because `run` is defined both on the `Datastore` interface and the `DatastoreReader` interface, which `Datastore` inherits from.

What's worse, the *only* ReadOption is `EventualConsistency`. So it's currently impossible for me to call `datastore.run` and enforce strong consistency.

In case it matters, I'm calling `datastore.run` from a Scala application.

**Comment by marykogan** [comment]
I don' get the whole point of showing sbt examples in docs and announcing Scala support, when almost nothing  in datastore library is working out of the box and request some time-consuming workaround. Furthermore, filled problem is labeled as feature. Great job!

**Comment by ajaaym** [comment]
This is a scala issue rather than library issue. Please follow
[stackoverflow](https://stackoverflow.com/questions/16829114/ambiguous-reference-to-overloaded-definition-one-vs-two-parameters) [SI-2991](https://issues.scala-lang.org/browse/SI-2991) [SI-4728](https://issues.scala-lang.org/browse/SI-4728)

To resolve this issue to allow strong consistency which is by default, you can call like this 
datastore.run(query, Seq.empty[ReadOption])

**Comment by ajaaym** [comment]
closing this now. Please feel free to reopen.

**Comment by rich-j** [comment]
Encountered the same issue with `datastore.get`.  A helpful [Stackoverflow](https://stackoverflow.com/questions/13358705/force-single-argument-in-scala-varargs) provides:

```scala
datastore.get(key, Nil: _*)
```
