### ISSUE TITLE
User reports it takes 5 seconds to start gRPC connection for Cloud Spanner

### ISSUE THREAD

**Issue by ChengyuanZhao** [googleapis/google-cloud-java#3405]
https://stackoverflow.com/questions/50861577/spring-boot-gcp-data-spanner-latency-issues

The user here is using the cloud spanner client lib and reports that it takes him 5 seconds to start the connection to Cloud Spanner and then he is getting slow performance out of each query and read operation. There is sample code in there as well.

**Comment by olavloite** [comment]
The problem in this case was that the user was not closing the `ResultSet` that was returned by the query (and also did not completely consume the `ResultSet`), causing the library to create a new session for each new query. I could reproduce the exact same behavior in a very simple setup with basically the same timing as reported by the user. Changing the example code to use a try-with-resources block on the `ResultSet` solves it. I posted a full answer to the stackoverflow question.

The corresponding example code:

```java
/**
 * This method will execute the query quickly, as the ResultSet
 * is closed automatically by the try-with-resources block.
 */
private Long executeQueryFast() {
  Statement statement = Statement.of("SELECT * FROM T WHERE ID=1");
  try (ResultSet resultSet = dbClient.singleUse().executeQuery(statement)) {
    while (resultSet.next()) {
      return resultSet.getLong("ID");
    }
  } catch (Exception ex) {
    // log
  }
  return null;
}

/**
 * This method will execute the query slowly, as the ResultSet is
 * not closed and the Spanner library thinks that the session is
 * still in use. Executing this method repeatedly will cause
 * the library to create a new session for each method call.
 * Closing the ResultSet will cause the session that was used
 * to be returned to the session pool, and the sessions will be
 * re-used.
 */
private Long executeQuerySlow() {
  Statement statement = Statement.of("SELECT * FROM T WHERE ID=1");
  try {
    ResultSet resultSet = dbClient.singleUse().executeQuery(statement);
    while (resultSet.next()) {
      return resultSet.getLong("ID");
    }
  } catch (Exception ex) {
    // log
  }
  return null;
}
```
