### ISSUE TITLE
Question: Kotlin Interopability

### ISSUE THREAD

**Issue by bshaffer** [googleapis/google-cloud-java#3412]
It would be great to have this library follow the [Kotlin Interoperability Guide](https://android.github.io/kotlin-guides/interop.html). 

I would love to submit a PR to fix any of these interoperability issues in this library, in the downstream [gapic-generator](https://github.com/googleapis/gapic-generator), and also in the [apiary client](https://github.com/google/google-api-java-client). 

Of course maintaining Backwards Compatibility will be key, and if there's a situation where breaking BC is required, we'll handle those case-by-case.

Thoughts?

**Comment by hzyi-google** [comment]
This would be non-trivial work for current libraries. We always welcome PRs but I'll let @garrettjonesgoogle decide whether we can do this at this moment.
