### ISSUE TITLE
[PubSub][Question] DEADLINE_EXCEEDED after 60s for sending acks/modacks

### ISSUE THREAD

**Issue by guess-burger** [googleapis/google-cloud-java#3414]
We've recently added a new feature which involves a new topic and subscriptions using google-cloud-pubsub version 1.35.0.

However, we noticed warning logs for `DEADLINE_EXCEEDED` over a number of days all stating a 60 second deadline like the following:

```
3549577 [Gax-11] WARN c.g.c.p.v.StreamingSubscriberConnection - failed to send operationsio.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 59999669883ns at
io.grpc.Status.asRuntimeException(Status.java:526) at
io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419) at
io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) at
io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) at
io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) at
io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391) at
io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475) at
io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) at
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557) at
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478) at
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590) at
io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) at
io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at
java.util.concurrent.FutureTask.run(FutureTask.java:266) at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at
java.lang.Thread.run(Thread.java:748)
```

We had set a 300 second Ack Deadline on topic creation but investigating the code reveals instead a default of 60 seconds is used since [pubsub: re-implement periodic deadline adjustment](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2639). However, that deadline should have adjusted and we use the default Max Ack Extension setting so would expect a larger deadline than 60 seconds.

Further investigation led to discovering that the unary calls to send the acks/modacks also has a deadline of 60 seconds and it appears that the stacktrace is produced by the logging StreamObserver used during this step.

Could someone confirm whether these stacktraces actually relate to the the sending of ack/modacks timing-out?

**Comment by goxr3plus** [comment]
@guess-burger  Found any solution bro :) ?

**Comment by guess-burger** [comment]
@goxr3plus, we didn't. We had all sorts of problems with high duplication of messages even though items were handled in a few seconds.

In the end we just stopped using the Async Stream Pull consumer. Even flow control setting of max 1 outstanding still produced issues. We started to synch-pull one item at a time and duplicates stopped and so did these error messages. 
Although now we occasionally see deadline exceeded for a negative length of time!

**Comment by pongad** [comment]
I can confirm these stack traces are related to sending ack/modacks timing out.

Could you let us know how you're setting up the executor? We've seen problem in the past where all threads in executor are busy with messages that they cannot service an RPC. With flow control at 1, this seems unlikely unless you have a single-threaded executor?

**Comment by maros7** [comment]
We are seeing the same behaviour with v1.37.1. We are creating an executor provider with ```FixedExecutorProvider.create(Executors.newScheduledThreadPool(4))``` and using the default ```FlowControlSettings```.

**Comment by pongad** [comment]
@maros7 How long running are your tasks? Eg, does each message take 1 second of executor's time? 10 seconds? etc. I might be onto something but would like to understand this better first.

**Comment by maros7** [comment]
@pongad Our ```MessageReceiver``` creates a Spring Integration Message including the ```AckReplyConsumer``` as a message header and puts the message on a Spring Integration channel. This takes less than 1 second. Processing is done by the consumer of the Spring Integration Channel.

**Comment by guess-burger** [comment]
@pongad, we were using the default executor provided by the Subscription.Builder which looks like [5 * Num available Processors](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.51.0/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java#L420).

**Comment by ajaaym** [comment]
@guess-burger Can you please try with latest version? It has better configuration of channel pool and executor provider and see if it helps?

**Comment by sduskis** [comment]
This issue is out of date.  Please retry with the latest version.  If that doesn't help, please open a new issue.
