### ISSUE TITLE
Includes the .proto files in generated jars

### ISSUE THREAD

**Issue by MMMarcy** [googleapis/google-cloud-java#3417]
Right now the proto-google-cloud-xxx dependencies (eg [dialogflow](https://search.maven.org/#artifactdetails%7Ccom.google.api.grpc%7Cproto-google-cloud-dialogflow-v2%7C0.18.0%7Cjar) ) only include the generated source files. This makes impossible to import the source protos in your protos in an easy way.

For instance, the workaround for using [protobuf-maven-plugin](https://www.xolstice.org/protobuf-maven-plugin/index.html) is to add this repository as a submodule and configure the plugin to lookup the proto files.

Adding the protos would make working with the libraries easier. Also, this is done for [other Google artifacts](http://search.maven.org/#artifactdetails%7Ccom.google.protobuf%7Cprotobuf-java%7C3.1.0%7Cbundle).

**Comment by sduskis** [comment]
The latest `proto-*` jars have the `*.proto` files thanks to @BenWhitehead in #5208.
