### ISSUE TITLE
Netty crashes when LoggingAppender is configured in logback.xml

### ISSUE THREAD

**Issue by stetra** [googleapis/google-cloud-java#3455]
I am trying to use [com.google.cloud.logging.logback.LoggingAppender](https://cloud.google.com/logging/docs/setup/java) to send logs to Stackdriver. However, when I add the appender to `logback.xml`, Netty crashes upon initialization. It's strange that this only occurs when the appender is configured in logback.xml. If I instead manually instantiate the logger within application code, logging works and Netty doesn't crash. Please let me know how I can help resolve this.

I have created an example repo at https://github.com/stetra/minrepro

To reproduce (you might need to set `GOOGLE_APPLICATION_CREDENTIALS`):

    1. git clone https://github.com/stetra/minrepro.git && cd minrepro
    2. mvn clean compile assembly:single
    3. java -jar ./target/minrepro-1.0-SNAPSHOT-jar-with-dependencies.jar 

logback.xml:

    <configuration>
        
        <appender name="CLOUD" class="com.google.cloud.logging.logback.LoggingAppender">
        </appender>
    </configuration>

Crash output:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7ef7c2ce90, pid=11025, tid=0x00007f7f42061700
#
# JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x00007f7ef7c2ce90
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/steven/minrepro2/minrepro/hs_err_pid11025.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted
```

Full crash log: [hs_err_pid11025.log](https://github.com/GoogleCloudPlatform/google-cloud-java/files/2186581/hs_err_pid11025.log)

**Comment by JesseLovelace** [comment]
Cut an [issue](https://github.com/grpc/grpc-java/issues/4878) to grpc

**Comment by JesseLovelace** [comment]
This is blocked on https://github.com/netty/netty/issues/8337

**Comment by codyoss** [comment]
I was able to reproduce this with the repo provided.  But when I upgraded to the latest dependencies this issue went away for me:

```xml
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-monitoring</artifactId>
      <version>1.93.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-logging-logback</artifactId>
      <version>0.111.0-alpha</version>
    </dependency>
```
Then I believe this should just be a matter of setting up proper authentication. The [Grpc project ](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#transport-security-tls) seems to have some pretty good documentation on this. 

 @stetra Are you still running into these issues with newer dependencies?

**Comment by codyoss** [comment]
Closing this as I believe newer version fixes this as I said in the comment above. Feel free to reopen if this is still an issue for you.
