### ISSUE TITLE
NoSuchMethod Error in gax core

### ISSUE THREAD

**Issue by philkrie** [googleapis/google-cloud-java#3470]
Here is my pom file

	<dependencies>
		
		<dependency>
			<groupId>com.google.appengine</groupId>
			<artifactId>appengine-api-1.0-sdk</artifactId>
			<version>1.9.49</version>
		</dependency>
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-pagespeedonline</artifactId>
			<version>v2-rev13-1.22.0</version>
		</dependency>

		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>3.0-alpha-1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jstl</groupId>
			<artifactId>jstl</artifactId>
			<version>1.2</version>
		</dependency>

		<dependency>
			<groupId>com.googlecode.objectify</groupId>
			<artifactId>objectify</artifactId>
			<version>5.1.14</version>
		</dependency>

		
		<dependency>
			<groupId>com.google.apis</groupId>
			<artifactId>google-api-services-sqladmin</artifactId>
			<version>v1beta4-rev50-1.23.0</version>
		</dependency>

		
		<dependency> 
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.42</version>  
		</dependency>
		<dependency>
			<groupId>com.google.cloud.sql</groupId>
			
			<artifactId>mysql-socket-factory</artifactId>
			<version>1.0.5</version>
		</dependency>

		
		<dependency>
			<groupId>org.restlet.jee</groupId>
			<artifactId>org.restlet</artifactId>
			<version>${restlet.target.version}</version>
		</dependency>
		<dependency>
			<groupId>org.restlet.jee</groupId>
			<artifactId>org.restlet.ext.json</artifactId>
			<version>${restlet.target.version}</version>
		</dependency>
		<dependency>
			<groupId>org.restlet.jee</groupId>
			<artifactId>org.restlet.ext.servlet</artifactId>
			<version>${restlet.target.version}</version>
		</dependency>
		<dependency>
			<groupId>org.restlet.jee</groupId>
			<artifactId>org.restlet.ext.fileupload</artifactId>
			<version>${restlet.target.version}</version>
		</dependency>
		<dependency>
			<groupId>org.restlet.jee</groupId>
			<artifactId>org.restlet.ext.xml</artifactId>
			<version>${restlet.target.version}</version>
		</dependency>
		<dependency>
			<groupId>org.restlet.osgi</groupId>
			<artifactId>org.restlet.ext.swagger</artifactId>
			<version>${restlet.target.version}</version>
			<exclusions>
				
				
				<exclusion>
					<groupId>org.raml</groupId>
					<artifactId>raml-parser</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		<dependency>
			<groupId>org.raml</groupId>
			<artifactId>raml-parser</artifactId>
			<version>0.8.11</version>
		</dependency>

		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<version>2.9.7</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>18.0</version>
		</dependency>

		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-all</artifactId>
			<version>2.0.2-beta</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.google.appengine</groupId>
			<artifactId>appengine-testing</artifactId>
			<version>${appengine.target.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.google.appengine</groupId>
			<artifactId>appengine-api-stubs</artifactId>
			<version>${appengine.target.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-storage</artifactId>
			<version>1.4.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.endpoints</groupId>
			<artifactId>endpoints-framework-tools</artifactId>
			<version>2.0.3</version>
		</dependency>
		<dependency>
			<groupId>com.google.endpoints</groupId>
			<artifactId>endpoints-management-control-appengine</artifactId>
			<version>1.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.google.endpoints</groupId>
			<artifactId>endpoints-framework-auth</artifactId>
			<version>1.0.2</version>
		</dependency>
	</dependencies>`

Project was working earlier in the day, suddenly is returning an internal server error:

`Caused by: java.lang.NoSuchMethodError: com.google.api.gax.core.GaxProperties.getLibraryVersion(Ljava/lang/Class;)Ljava/lang/String;
at com.google.cloud.ServiceOptions.getLibraryVersion(ServiceOptions.java:614)
	at com.google.cloud.ServiceOptions.getApplicationName(ServiceOptions.java:577)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.<init>(HttpStorageRpc.java:94)
	at com.google.cloud.storage.StorageOptions$DefaultStorageRpcFactory.create(StorageOptions.java:53)
	at com.google.cloud.storage.StorageOptions$DefaultStorageRpcFactory.create(StorageOptions.java:47)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:506)
	at com.google.cloud.storage.StorageOptions.getStorageRpcV1(StorageOptions.java:121)
	at com.google.cloud.storage.StorageImpl.<init>(StorageImpl.java:98)
	at com.google.cloud.storage.StorageOptions$DefaultStorageFactory.create(StorageOptions.java:43)
	at com.google.cloud.storage.StorageOptions$DefaultStorageFactory.create(StorageOptions.java:37)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:493)`

Was something deprecated? Not really sure what the issue could be.

**Comment by philkrie** [comment]
Looks like the guava dependency was changed, I switched it back to an earlier commit, which uses the following.

```
<dependency>
  <groupId>com.google.guava</groupId>
  <artifactId>guava-jdk5</artifactId>
  <version>17.0</version>
</dependency>
```

After running mvn clean install, error was gone. 

Why do I have to use guava-jdk5? Would prefer to use the latest library, the app is running on java 8

**Comment by elharo** [comment]
You have lots of out of date dependencies there. E.g.

appengine-api-1.0-sdk should be about 1.9.64
Objectify should be around 5.1.25
servlet-api should not be alpha

There are likely others. It's hard to tell exactly which one is at fault here.
For Guava try 20.0.0

**Comment by chingor13** [comment]
You should not need guava-jdk for any recent version of google-cloud-java. Currently, our underlying libraries use guava 20.0 (for compatibility reasons).
