### ISSUE TITLE
Pub/Sub access to message ack id in the subscribe use case

### ISSUE THREAD

**Issue by meltsufin** [googleapis/google-cloud-java#3479]
When pulling messages, we get `ReceivedMessage` that contains the ack id that can then be used to ack multiple messages at once using the `ModifyAckDeadlineRequest`.

However, on the subscribe side all we get is `PubsubMessage` and `AckReplyConsumer`, without access to the ack id of the message. So, this means that we cannot ack messages in batch.

@garrettjonesgoogle

**Comment by kir-titievsky** [comment]
@meltsufin Mike, can you explain why this is needed, given that the client library already batches acks?

**Comment by meltsufin** [comment]
I wasn't aware that there is batching happening for `AckReplyConsumer.ack()`.  In any case, we want to be able to pass ack IDs around and have a common abstraction for a message received via pull and async streaming. That abstraction should include an ack ID.

**Comment by kamalaboulhosn** [comment]
We currently do not intend to expose the ack ID for the subscriber client library. The library intentionally abstracts users away from this item. As @kir-titievsky mentions, the client library does its own batching of acks and performs mod acks in the background. Passing ack IDs around and acking out of band would not work with the client library as these manually-acked messages would still count against flow control limits, which would result in the inability to receive more messages.

**Comment by unoexperto** [comment]
@kamalaboulhosn This is very limiting factor. Could you please suggest how one can postpone acking bunch of messages? I'm using PubSub as durable storage of messages which I batch into 1 hr chunks and send elsewhere. I could of course hold on to instances of `AckReplyConsumer` for each message in the batch that I haven't processed yet but it poses risk of OOM exception. What would you suggest?

**Comment by kamalaboulhosn** [comment]
@unoexperto Relatively speaking, I expect the AckReplyConsumer is going to be much smaller than the messages you are buffering themselves, so I don't think holding on to them is going to be a major contributing factor to OOMs. However, holding on to messages for an hour in a subscriber client and only acking after a batch is flushed is an anti-pattern for Cloud Pub/Sub. You want to try to ack messages very quickly. The longer you wait to ack, the more risk there is of duplicate delivery, which would also waste resources. You'd be better off writing messages to some persistent storage locally when you receive them, acking them, and then flushing the data every hour. You could do this using [Apache Beam/Cloud Dataflow](https://stackoverflow.com/questions/42914198/buffer-and-flush-apache-beam-streaming-data).
