### ISSUE TITLE
Speech is taking a long time to respond

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/google-cloud-java#3502]
The customer is using a sip client called peers to redirect stream from a VoIP call to speech API but the customer is seeing a latency of approximately 8 seconds before they can receive the first response from the server. This is their [code](https://github.com/absin1/peersNew/blob/master/peers-demo/src/main/java/net/sourceforge/peers/demo/StreamSoundManager1.java). The method `writeData(byte[] buffer, int offset, int length)` is a callback function to receiving data from the VoIP call and in this method the customer constructs a `streamingRecognizeRequest` from the bytes received and sends the request to the server. The customer also mentioned that they already checked that bytes from VoIP has no latency. 

More discussions from [3188](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3188#issuecomment-406766162)

cc/ @absin1

**Comment by sduskis** [comment]
These types of issues need support tickets.  Please see https://cloud.google.com/speech-to-text/docs/support on how to get support for this type of issue.
