### ISSUE TITLE
null returned when calling field.getMode()

### ISSUE THREAD

**Issue by ghost** [googleapis/google-cloud-java#3509]
Hello,
when calling ` field.getMode()` in the com.google.cloud.bigquery.Field, I got null returned when I creating field by 
```java
public static Field of(String name, LegacySQLTypeName type, Field... subFields) {
    return newBuilder(name, type, subFields).build();
  }
``` 
which only set the name and type, do you think this should set the default mode of `nullable` when not specified a mode

**Comment by hzyi-google** [comment]
Since the server side would consider a `Field` with unspecified `Mode` as a `Field` with `NULLABLE` mode according to the [api documentation](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables), it doesn't seem necessary to force this behavior again on the client side.
