### ISSUE TITLE
Firestore client stops functioning after 100 snapshot listeners are registered

### ISSUE THREAD

**Issue by nikammerlaan** [googleapis/google-cloud-java#3514]
I've run into an issue with my application where all requests (get/set/update/queries) and listeners stop functioning after the 100th one is added (the first 100 listeners still function, all ones added after just sit idle and never receive any events). If I had to guess what could be causing the issue, I'd guess that there is probably a saturated threadpool somewhere. I tried to look around in the source for that but I couldn't find what I was looking for. 

Edit: After doing some more investigating, it seems that all requests (get, set, update, query, etc)block after that 100th listener is added.

**Comment by schmidt-sebastian** [comment]
@nikammerlaan Thanks for reporting this issue! This is actually a limitation of our network stack. By default, we only support 100 concurrent streams. If you are hitting this limit, you can increase how many connections we initialize in our pool. To change the setting you can do the following:

```
Builder options =  FirestoreOptions.newBuilder().build().toBuilder();
options.setChannelProvider(
   FirestoreOptions.getDefaultTransportChannelProviderBuilder().setPoolSize(2).build());
firestore = options.build().getService();
```

We allow 100 streams per entry in the pool, but you can adjust this setting as needed. Note that introduces some overhead, as each connection requires its own setup.

**Comment by appsgenie** [comment]
Does this mean 100 total snapshots across all clients for the entire database or 100 from one client (either a mobile device or with admin sdk)?

**Comment by lucazin** [comment]
I have this kind of problema.. 

i have 7 listeners but always disconnecting.. im using java.

What i have to do..to stop this behavior..??  because its intermitent..

I have to move to realtime database? Use just one listener?

![image](https://github.com/googleapis/google-cloud-java/assets/28266902/c2340253-23a6-435e-b37c-58ebb2be6fa3)
