### ISSUE TITLE
Publish batch operation for pub sub

### ISSUE THREAD

**Issue by LukeDefeo** [googleapis/google-cloud-java#3518]
We have an api which wraps pub sub, we accept messages one at a time, do some light processing and put them on pub sub. Are clients are slow because they need to wait  one round trip before sending the next. It would be better if they could send us a large batch and in the api we put them all on to pubsub as a batch. 

The java api hides pub subs batch write message behind a queuing / buffering layer. While this is nice for some use-cases it would be good if there was a simple way to publish a batch of messages to pub sub atomically. If we were to accept a batch from our client and pass them to the java api it could get split across two batches, and a partial write could occur

**Comment by CremboC** [comment]
Is this any update on this? 

We generate thousands of messages per second per instance and attaching thousands of ApiFutureCallbacks per second seems a bit insane to me. I much rather attach a single listener for a batch as we don't actually need confirmation for *every single message*.

**Comment by ajaaym** [comment]
@LukeDefeo Here is another way to do this, put all msg thats part of batch in PublishRequest message and call the api directly.

```
    PublisherStubSettings.Builder builder = PublisherStubSettings.newBuilder();
    builder.publishSettings().setBatchingSettings(BatchingSettings.newBuilder().setIsEnabled(false).build());
    try(PublisherStub publisherStub = GrpcPublisherStub.create(builder.build())){
      ApiFuture<PublishResponse> publishResponseApiFuture = publisherStub.publishCallable().futureCall(PublishRequest.newBuilder().build());
    }
```

**Comment by ajaaym** [comment]
Closing this as provided solution. Please reopen if this doesn't help.
