### ISSUE TITLE
Errors received in OCR requests to Cloud Vision through Java library

### ISSUE THREAD

**Issue by ankit-joinwal** [googleapis/google-cloud-java#3525]
Lot of our requests to Google Vision service are being failing with below error response from Google Vision service:
"We can not access the URL currently. Please download the content and pass it in."

The images are accessible publicly.
Some samples:
https://media.cheggcdn.com/media%2Fcb6%2Fcb6cd4d5-9514-44b2-bc13-fbe2a7ba075b%2FphpfPVqJT.png
https://media.cheggcdn.com/media%2Fc0f%2Fc0f3d013-9c10-4a93-b04b-290a9b3e1b15%2FphpZrrY0q.png
https://media.cheggcdn.com/media%2F260%2F260698fa-d72c-40b0-b30c-860607d06d06%2FphpdTycEW.png

If we retry the same images after some time, the OCR works fine. So the issue is very intermittent but is happening for almost 30 requests out of 50.

We are using the following libraries:
```
  'com.google.api-client:google-api-client:1.22.0',
  'com.google.http-client:google-http-client:1.22.0',
  'com.google.apis:google-api-services-vision:v1-rev369-1.22.0',
  'com.google.apis:google-api-services-oauth2:v2-rev133-1.23.0',
  'com.google.http-client:google-http-client-jackson2:1.23.0',
  'com.google.oauth-client:google-oauth-client:1.23.0'
```

We pass the image URL in the Vision request.
```
new AnnotateImageRequest()
            .setImage(new Image().setSource(new ImageSource().set("imageUri", document.getImage())))
            .setFeatures(ImmutableList.of(new Feature().setType(GoogleVision.FEATURE_TEXT_DETECTION)))
```
Can someone please help us in resolving it. 

I also found https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-vision which shows below artifact to be used:
compile 'com.google.cloud:google-cloud-vision:1.38.0'

Not sure why are there two kinds of artifacts for Cloud Vision library.

**Comment by tarun4279** [comment]
Our team is also facing this issue.

**Comment by hzyi-google** [comment]
Hi,

The google-cloud-vision library in this repo is the library we encourage our customers to use if possible. It's newer than google-api-services-vision and is what we are focusing on developing, and generally handles retry, streaming, batching, asynchronous call etc. more nicely.

If you have to use the older google-api-services-vision, could you please give us a complete snippet showing how you make the requests, the full stack trace and the error code you received (if you have them)?

**Comment by meredithslota** [comment]
I'm assuming the previous answer solved the problem given lack of follow-up; closing this out. Please reopen if needed.
