### ISSUE TITLE
META-INF/services/ files are incorrect in shaded google-cloud-nio jar

### ISSUE THREAD

**Issue by lbergelson** [googleapis/google-cloud-java#3540]
The `google-cloud-nio-0.56.0-alpha-shaded.jar` doesn't correctly update the services files for shaded dependencies.  
Specifically the two files 
`META-INF/services/org.threeten.bp.zone.TzdbZoneRulesProvider`
and 
`META-INF/services/com.fasterxml.jackson.core.JsonFactory` should probably be updated to point to the shaded version of those classes instead.

**Comment by hzyi-google** [comment]
Yes it is. The two files are still pointing at the non-shaded version of those classes in the latest google-cloud-nio on maven (0.74).
