### ISSUE TITLE
Wrong Android detection

### ISSUE THREAD

**Issue by Recognized** [googleapis/google-cloud-java#3543]
When library is used in Intellij Plugin, it detects Android plugin for Intellij IDEA as Android.
![image](https://user-images.githubusercontent.com/6931331/43894198-08d82076-9bda-11e8-8239-6b59101d4aaa.png)

**Comment by ajaaym** [comment]
@Recognized if you have android SDK enabled for project it will detect that this is android. Can you please provide more detail what should be expected outcome?
