### ISSUE TITLE
Java code for PartnerDTSClient, ManagedTransferRun and TableContext

### ISSUE THREAD

**Issue by deepakstriim** [googleapis/google-cloud-java#3545]
I'm looking for the equivalent java code for the 3 classes:  PartnerDTSClient, ManagedTransferRun and TableContext which are being used in the python library here: https://github.com/mtai/bq-dts-partner-sdk/blob/master/bq_dts/base_connector.py
for moving data from GCS to BQ using the DTS api. I have the following 2 dependencies and it doesn't seem to have code to fulfill the functionality of those classes:
            com.google.cloud /  google-cloud-bigquerydatatransfer  /  0.55.1-beta</version>
         com.google.cloud   /  google-cloud-pubsub  /  1.37.1
Please let me know what am I missing

**Comment by hzyi-google** [comment]
The python library you mentioned does not seem to be developed by google and it's hard to tell which classes are equivalent between two libraries in two languages. [Here's](https://cloud.google.com/bigquery/docs/reference/datatransfer/rest/) the REST API reference for BigQuery Data Transfer. Also, feel free to describe what you want to achieve here and we can help you with it.

**Comment by sduskis** [comment]
I'm closing this issue, since we don't have anything actionable to work on in this repository.  Please open a new issue if this is still a problem.
