### ISSUE TITLE
 WriteChannel of google storage client increases memory usage and gives memory leak

### ISSUE THREAD

**Issue by sonalijha1711** [googleapis/google-cloud-java#3587]
Hi Everyone,

I am using google cloud storage client library to store files in google cloud storage.
I am using the below code for that:

```
WriteChannel writer = null;
ReadableByteChannel input=null;
try {
    int bufferSize = Integer.getInteger("buffer.size", 1024 * 1024);	
    writer = storageClient.writer(blobInfo);
    //the fileInputStream from the file
    input = Channels.newChannel(fileInputStream);
			
    ByteBuffer buffer = ByteBuffer.allocateDirect(bufferSize);
			
    writer.setChunkSize(5*bufferSize);		
    while (input.read(buffer) != -1) {
	buffer.flip();
	writer.write(buffer);
	buffer.compact();
    }
}

IOUtils.closeQuietly(fileInputStream);	
IOUtils.closeQuietly(writer);
IOUtils.closeQuietly(input);

```

As the document suggested for big file should use the WriteChannel writer from the storage client.
But after using this code when i do the memory analysis , Its increasing up after each request .
All ways i tried mentioned in the google cloud storage documents.I am not understanding why the code is not channeling and its allocating memory  with each request and memory is not getting released , which soon  gives memory leak error.

Kindly help and guide me if i am doing something wrong.

Thanks in advance.

**Comment by ajaaym** [comment]
Can you please provide exact error message? Also why are you using allocateDirect? Allocating new direct buffer with every request would not cause GC which will prevent process to reclaim native heap memory.

**Comment by ajaaym** [comment]
closing this issue bcoz of staleness. Please reopen if needs help with this.

**Comment by vinayhudli** [comment]
Hi,
I'm facing similar issue. Though I don't get out of memory but the pod rss keeps increasing and even when all the requests are processed the memory doesn't drop . I'm attaching the screenshot that contains memory request, usage and limit . The used memory didn't drop to lower level even though the application is not doing any work.
<img width="470" alt="Screen Shot 2021-09-17 at 11 24 16 PM" src="https://user-images.githubusercontent.com/1204958/133878676-b110b744-c1ac-4b8f-97f4-e9f41af84ffd.png">
Thanks
