### ISSUE TITLE
utilities/generate_api errors

### ISSUE THREAD

**Issue by pongad** [googleapis/google-cloud-java#3595]
`TypeError: sequence item 0: expected str instance, bytes found`

Commenting out `dump_version` can temporarily fix the problem.

**Comment by sduskis** [comment]
@pongad, is this still active?

**Comment by pongad** [comment]
I honestly don't know. I have moved team and haven't used this in a while :/ It's OK to close this out for now if you'd like.

**Comment by chingor13** [comment]
We standardized using synthtool across all our languages over any preexisting scripts.
