### ISSUE TITLE
Guava 19/20 convergence error in google-cloud-core

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-java#3613]
GAX's guava is upgraded at head but not in latest 1.30.0 release. We need a new release of GAX.

We also need to upgrade protobuf-java-util to Guava 20 and push a new release. 

and GAX's com.google.auth:google-auth-library-oauth2-http should go to 0.11.0

```
Dependency convergence error for com.google.guava:guava:20.0 paths to dependency are:
+-com.google.cloud:zero-pom-test:0.0.1-SNAPSHOT
  +-com.google.cloud:google-cloud-core:1.41.0
    +-com.google.guava:guava:20.0
and
+-com.google.cloud:zero-pom-test:0.0.1-SNAPSHOT
  +-com.google.cloud:google-cloud-core:1.41.0
    +-com.google.api:api-common:1.7.0
      +-com.google.guava:guava:19.0
and
+-com.google.cloud:zero-pom-test:0.0.1-SNAPSHOT
  +-com.google.cloud:google-cloud-core:1.41.0
    +-com.google.api:gax:1.30.0
      +-com.google.guava:guava:20.0
and
+-com.google.cloud:zero-pom-test:0.0.1-SNAPSHOT
  +-com.google.cloud:google-cloud-core:1.41.0
    +-com.google.api:gax:1.30.0
      +-com.google.auth:google-auth-library-oauth2-http:0.10.0
        +-com.google.guava:guava:19.0
and
+-com.google.cloud:zero-pom-test:0.0.1-SNAPSHOT
  +-com.google.cloud:google-cloud-core:1.41.0
    +-com.google.protobuf:protobuf-java-util:3.6.1
      +-com.google.guava:guava:19.0

```

**Comment by garrettjonesgoogle** [comment]
You're fighting an uphill battle.

**Comment by elharo** [comment]
I think the battle is worth fighting. If nothing else, this shows us where we missed upgrades. Right now, the problem seems more to be dependencies that aren't updated frequently enough rather than dependencies that are moving too fast.

**Comment by JustinBeckwith** [comment]
@garrettjonesgoogle is this a thing we plan on doing?

**Comment by garrettjonesgoogle** [comment]
We should generally keep up to date. My comment to @elharo was about the "how" - filing ad hoc tickets for each case where a repo is not up to date; this feels like a losing battle.
