### ISSUE TITLE
How to specify Spanner connect timeout?

### ISSUE THREAD

**Issue by meltsufin** [googleapis/google-cloud-java#3616]
If the client has some kind of network issue connecting to Spanner, it seems to hang indefinitely. Is there a way to specify the timeout? I don't see anything in `SpannerOptions`.

**Comment by andreamlin** [comment]
Hello, [SpannerSettings.java](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/675ace7601e2c09474ce986d5d2223af5cb15f28/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerSettings.java) has timeout settings, and there is a sample code snippet in the class javadoc as an example.

**Comment by meltsufin** [comment]
I think the issue is happening on creation of the session. What is the current timeout? Whatever it is, currently there is no way to change it, right?

**Comment by snehashah16** [comment]
@nithinsujir  - could u please help here.
For our createSession(db) call, it does a retry using:
  static <T> T runWithRetries(Callable<T> callable) { .. }  [code](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/675ace7601e2c09474ce986d5d2223af5cb15f28/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java#L216) 

Could u please verify behavior (infinite retry attempts w/ exponential sleep ?) when it is a retry-able SpannerException ?

**Comment by nithinsujir** [comment]
Will take a look.

**Comment by nithinsujir** [comment]
@snehashah16
Modified the callable in createSession to throw a retryable exception. Verified that this will indeed cause an infinite retry attempt with exponential sleep.

Is this the intended design? I can imagine for transactions where this might be intentional. Do we want to set a retry limit for createSession()?

**Comment by snehashah16** [comment]
@hzyi-google - does the SpannerSettings work in this case (when the client is using the new library) ? Since this is a corner case (of netw issues ), I would be inclined to wait and adopt the new library v/s fixing code that we are in the process of deprecating.

**Comment by hzyi-google** [comment]
@snehashah16 Yes SpannerSettings should work.

**Comment by nithinsujir** [comment]
@hzyi-google Can you elaborate for my knowledge what is different in the new library? Is there anything from my side to be done?

**Comment by hzyi-google** [comment]
@nithinsujir The migrated library will be using the runtime library [gax-java](https://github.com/googleapis/gax-java) to make gRPC calls. Gax also provides a lot of helper utilities to give callers control over the settings of the gRPC calls. For example, [`StubSettings`](https://github.com/googleapis/gax-java/blob/master/gax/src/main/java/com/google/api/gax/rpc/StubSettings.java) is the super class of `SpannerSettings` mentioned above and has a lot of configurable fields for callers to tune the client. 

As for what needs to be done, please refer to the previous comment I just updated. The tl;dr is to deprecate `SpannerOptions` and use `SpannerSettings` to create Spanner clients (But of course this isn't the only approach). Also tagging @snehashah16  since I updated the comment. Sorry for the inconvenience.

**Comment by olavloite** [comment]
If this problem occurs consistently on one specific VM or server, then there's a good chance that it is the same problem as in #3889 where an SSLHandshakeException is thrown. The first call to Spanner that needs a session will try to create one. That call would end up in an infinite retry loop in the createSession(...) method.

This code hangs indefinitely before the fix of #3889 when the client computer does not accept the SSL certificate of the server, and throws an SSLHandshakeException after the fix.
```java
    SpannerOptions options = SpannerOptions.newBuilder()
        .setProjectId("test-project").build();
    Spanner spanner = options.getService();
    DatabaseClient client = spanner.getDatabaseClient(
        DatabaseId.of("test-project", "static-test-instance", "test-db"));
    client.singleUse().executeQuery(Statement.of("SELECT 1"));
```

I'll also look into whether it is possible to add a timeout setting for the clients that are using `SpannerOptions`.

**Comment by olavloite** [comment]
Returning to the original question: It is now possible to specify timeout settings for grpc calls for a `Spanner` service by setting these on one of the `StubSettings.Builder`s exposed by the `SpannerOptions.Builder`. Setting a specific timeout value for all unary methods for the Spanner interface can be done like this:

```java
    final RetrySettings retrySettings =
        RetrySettings.newBuilder()
            .setInitialRpcTimeout(Duration.ofSeconds(10L))
            .setMaxRpcTimeout(Duration.ofSeconds(20L))
            .setMaxAttempts(5)
            .setTotalTimeout(Duration.ofSeconds(30L))
            .build();
    SpannerOptions.Builder builder =
        SpannerOptions.newBuilder()
            .setProjectId("[PROJECT]"));
    builder
        .getSpannerStubSettingsBuilder()
        .applyToAllUnaryMethods(
            new ApiFunction<UnaryCallSettings.Builder<?, ?>, Void>() {
              @Override
              public Void apply(Builder<?, ?> input) {
                input.setRetrySettings(retrySettings);
                return null;
              }
            });
    Spanner spanner = builder.build().getService();
```

**Comment by FengnaLiu** [comment]
@olavloite  I experienced the same situation. I tried to delete 1 billion rows with Partitioned DML, but it failed with [deadline exceeded] error. It seemed like timeout problem.
So I tried to specify the timeout with the method you provided.
I got a new error [Error:(44,54) java: type com.google.cloud.spanner.SpannerOptions.Builder does not take parameters]. Why it's not working?

The code is like following
`final RetrySettings retrySettings =
                RetrySettings.newBuilder()
                        .setInitialRpcTimeout(Duration.ofMinutes(60L))
                        .setMaxRpcTimeout(Duration.ofMinutes(60L))
                        .setMaxAttempts(5)
                        .setTotalTimeout(Duration.ofMinutes(60L))
                        .build();
        SpannerOptions.Builder builder =
                SpannerOptions.newBuilder()
                        .setProjectId("my project");

        builder
                .getSpannerStubSettingsBuilder()
                .applyToAllUnaryMethods(
                        new ApiFunction<UnaryCallSettings.Builder<?, ?>, Void>() {
                            **public Void apply(Builder<?, ?> input) {**
                                input.setRetrySettings(retrySettings);
                                return null;
                            }
                        });


        builder
                .getSpannerStubSettingsBuilder()
                .executeStreamingSqlSettings()
                .setRetrySettings(retrySettings);
        builder
                .getSpannerStubSettingsBuilder()
                .streamingReadSettings()
                .setRetrySettings(retrySettings);

        Spanner spanner = builder.build().getService();
        SpannerOptions options=builder.build();
`

**Comment by olavloite** [comment]
Hi @FengnaLiu 
What version of the client library are you using?
We introduced a specific timeout setting for Partitioned DML a while ago, because it often requires a different timeout than other RPCs. It can be set like this:

```java
SpannerOptions.newBuilder().setPartitionedDmlTimeout(Duration.ofMinutes(60L)).build();
```

I'm not sure why your code example is giving an error. The following example does not return any errors for me (although it's not the way you should set the timeout for Partitioned DML, use the example above):

```java
    final RetrySettings retrySettings =
        RetrySettings.newBuilder()
            .setInitialRpcTimeout(Duration.ofMinutes(60L))
            .setMaxRpcTimeout(Duration.ofMinutes(60L))
            .setMaxAttempts(5)
            .setTotalTimeout(Duration.ofMinutes(60L))
            .build();
    SpannerOptions.Builder builder = SpannerOptions.newBuilder().setProjectId("my project");
    builder
        .getSpannerStubSettingsBuilder()
        .applyToAllUnaryMethods(
            new ApiFunction<UnaryCallSettings.Builder<?, ?>, Void>() {
              @Override
              public Void apply(Builder<?, ?> input) {
                input.setRetrySettings(retrySettings);
                return null;
              }
            });
    Spanner spanner = builder.build().getService();
    SpannerOptions options = builder.build();
```

**Comment by FengnaLiu** [comment]
@olavloite 
I really appreciate your reply. The client library should be the latest version.
I also tried 
` SpannerOptions options = SpannerOptions.newBuilder().setPartitionedDmlTimeout(Duration.ofHours(30L)).build();`
It gave the same error 「504 Deadline Exceeded」 after about 5 hours. The data I tried to delete is very large about 1 billion rows.
Is it not possible to delete so large number data with PartitionedDML at once?

And the code example you provided is running right and it does seem like not the right way to set timeout for PartitionedDML. Thanks a lot for your useful information.

**Comment by olavloite** [comment]
@FengnaLiu 

> It gave the same error 「504 Deadline Exceeded」 after about 5 hours.

That is strange. Would you mind opening a new issue in https://github.com/googleapis/java-spanner/issues for this problem? That makes it easier for others to also chime in if they have any ideas, and to track the progress of this specific problem.

**Comment by FengnaLiu** [comment]
> That is strange. Would you mind opening a new issue in https://github.com/googleapis/java-spanner/issues for this problem? That makes it easier for others to also chime in if they have any ideas, and to track the progress of this specific problem.

@olavloite  I will open a new issue about this problem. Thanks a lot.
