### ISSUE TITLE
BigtableTableAdminSettings is missing credential provider options 

### ISSUE THREAD

**Issue by ajaaym** [googleapis/google-cloud-java#3634]
BigtableTableAdminSettings dont have option to set CredentialProvider. As of now to set credentialProvider we need to get stubSettings and set in that. Its Better to have this as setter in BigtableTableAdminSettings.

**Comment by igorbernstein2** [comment]
Can you clarify why its better?

**Comment by ajaaym** [comment]
so that it can be chained with other method call.  Right now we need to create builder, set it in stub setting and then build the settings builder.

**Comment by igorbernstein2** [comment]
We should generalize this to make a list of settings that need to be promoted to the top level settings. (I'm planning on updating the data client to hide most settings in stubSettings() as well)

**Comment by rahulKQL** [comment]
Can we close this issue?

As both [`BigtableDataSettings`](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataSettings.java#L332-L335) & [`BigtableTableAdminSettings`](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/admin/v2/BigtableTableAdminSettings.java#L157-L161) have consistent options to set `CredentialProvider` on `Builder` as well as their Stub.
