### ISSUE TITLE
BigtableDataClient is missing sync methods

### ISSUE THREAD

**Issue by ajaaym** [googleapis/google-cloud-java#3635]
Add below sync method in BigtableDataClient.

- [ ] readRow
- [ ] readRows
- [ ] sampleRowKeys
- [ ] mutateRow
- [ ] bulkMutateRows
- [ ] checkAndMutateRow
- [ ] readModifyWriteRow

**Comment by igorbernstein2** [comment]
Currently each rpc has 2 entrypoints: callable and async.  I don't think it makes sense to add sync variant for only `readRow`. So I think this should be expanded to include a sync variant for all RPCs

**Comment by ajaaym** [comment]
Agree. Should include sync variant of all RPCs.

**Comment by sduskis** [comment]
@elisheva-qlogic, can you please look at this one?

**Comment by igorbernstein2** [comment]
It should be pretty straight forward to add sync variants for all of the methods:
for readRow:

```java
public Row readRow(String tableId, ByteString rowKey) {
  return ApiExceptions.callAndTranslateApiException(readRowAsync(tableId, rowKey));
}
```
