### ISSUE TITLE
Possibly cycle in the dependency tree

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-java#3683]
Still investigating so this may be a false report, and if it's not it's probably not google-cloud-java's fault but I'm investigating a possible cycle in the dependency tree that starts like this:

```
com.google.cloud:google-cloud-logging-logback:0.59.0-alpha / ch.qos.logback:logback-classic:1.2.3 / org.codehaus.groovy:groovy-all:2.4.0 / com.thoughtworks.xstream:xstream:1.4.7 / dom4j:dom4j:1.6.1 / jaxen:jaxen:1.1-beta-6 / dom4j:dom4j:1.5.2 / jaxen:jaxen:1.1-beta-4 / dom4j:dom4j:1.5.2 / jaxen:jaxen:1.1-beta-4 / dom4j:dom4j:1.5.2 / jaxen:jaxen:1.1-beta-4 / dom4j:dom4j:1.5.2 / jaxen:jaxen:1.1-beta-4 / dom4j:dom4j:1.5.2 / jaxen:jaxen:1.1-beta-4 / dom4j:dom4j:1.5.2 / jaxen:jaxen:1.1-beta-4 / dom4j:dom4j:1.5.2 / jaxen:jaxen:1.1-beta-4 / dom4j:dom4j:1.5.2 / jaxen:jaxen:1.1-beta-4 / dom4j:dom4j:1.5.2 / jaxen:jaxen:1.1-beta-4 / dom4j:dom4j:1.5.2 / jaxen:jaxen:1.1-beta-4 /
```

**Comment by elharo** [comment]
Might be able to break this by upgrading ch.qos.logback:logback-classic:1.2.3  to org.codehaus.groovy:groovy-all:2.5.0

Worth a try

**Comment by elharo** [comment]
https://github.com/x-stream/xstream/pull/131 sent

This may be a runtime scope, not compile scope, issue.

**Comment by elharo** [comment]
The real issue seems to be the dom4j <--> jaxen cycle. This has been a problem for years. I have commit rights on jaxen, and I should fix it there, though that will still require everyone to upgrade their jaxen and dom4j anyway.

**Comment by sduskis** [comment]
This doesn't seem to be an issue for this repo, so I'm closing this issue.
