### ISSUE TITLE
DialogFlow performance

### ISSUE THREAD

**Issue by andreamaroni** [googleapis/google-cloud-java#3701]
Hi, I am trying to build a service that detects intents from multiple Dialogflow projects, so I have to create a SessionClient object every time my service is invoked [like in this example:]( https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/dialogflow/cloud-client/src/main/java/com/example/dialogflow/DetectIntentTexts.java). This operation is very time consuming (elaboration time is close to 2 seconds), but I noticed that if I re-use the same SessionClient for detecting 2 different intents, the second request is way much faster than the first (less than 500ms). My question is: is there a way to store the authentication data (e.g using Redis), so that I can speed up the detectIntent call at every invocation?

**Comment by pongad** [comment]
I suppose it is possible, but I haven't actually tried. That said, why do you need multiple `SessionClient`s? You can call `sessionsClient.detectIntent(session, queryInput)`, multiple times (even concurrently), the `session`s don't need to be the same.

**Comment by andreamaroni** [comment]
I cannot keep the same session client for handling all my requests because my application runs on a server and the detectIntent is called within a static method. I guess the only way to have an effective solution would be to use the same instance of a SessionClient once it's created and let it handle all the requests for that project.
