### ISSUE TITLE
Document purpose of test-jar and testlib dependencies

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-java#3715]
These aren't standard in Maven and aren't obvious from the code, at least to me.

**Comment by chingor13** [comment]
The `test-jar` dependencies pull in the jar that contains the tests for the specified dependency. It's used because there may be reused tests or base test classes that are inherited for package tests.

I'll look for a place to document this.

**Comment by chingor13** [comment]
The google-cloud-core test-jar is unnecessary for many clients, so I'm removing it from the dependencies.
