### ISSUE TITLE
Follow these instructions link has no instructions

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-java#3747]
On most, perhaps all, of the client READMEs we find:

You will need a Google Developers Console project with the Cloud Asset API enabled. Follow these instructions to get your project set up. 

The link on Follow these instructions goes to: https://cloud.google.com/docs/authentication#preparation

The linked page has no instructions. It does not tell the user what to to. It especially does not tell them how to enable the relevant API and doesn't even mention the API console.

**Comment by sduskis** [comment]
Thanks @elisheva-qlogic!
