### ISSUE TITLE
Parquet Redshift Copy Schema mismatch

### ISSUE THREAD

**Issue by abMatillion** [googleapis/google-cloud-java#3753]
Parquet Redshift Copy does not seem to error on a mismatch of schema, it performs the copy but all column values are null. Orc Redshift copy in comparison gives an error of and does not populate the given bigquery table:

```Error while reading data, error message: Mismatch between schema...```

**Comment by sduskis** [comment]
@JesseLovelace, is this something we need to as the BigQuery experts about?

**Comment by shollyman** [comment]
More information is needed.  I suspect this may be a question about using Matillion to import from redshift into BigQuery, but there's not enough information to make it actionable.

**Comment by shollyman** [comment]
Closing this for now due to lack of actionable information.
