### ISSUE TITLE
Dataproc Client API: Job in state SETUP_DONE not cancellable

### ISSUE THREAD

**Issue by geraldtoepper** [googleapis/google-cloud-java#3754]
Hi,
the dataproc API does not allow cancelling a job which is in state SETUP_DONE. Is there any specific reason why or is this a bug? Cancellation in states PENDING or RUNNING is working fine for me. From my understanding a job usually gets transferred from PENDING to SETUP_DONE and SETUP_DONE to RUNNING.

Specifically I am using this method for cancellation:
https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/com/google/cloud/dataproc/v1/JobControllerClient.html#cancelJob-java.lang.String-java.lang.String-java.lang.String-

This is the exception I am getting:
```
com.google.api.gax.rpc.FailedPreconditionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Cannot cancel jobId '4e41f6fb-xxx' in projectId 'xxx' in state: 'SETUP_DONE'; cancellable states: '[PENDING, RUNNING]'
```

Currently I am using the dataproc API version _0.58.0-alpha_.

Thank you!

**Comment by codyoss** [comment]
Hey @geraldtoepper I think this would be a feature request for the product itself. If you are still interested in this I suggest opening up a feature request from the [GCP Public Issue Tracker](https://cloud.google.com/support/docs/issue-trackers)
