### ISSUE TITLE
walkFileTree should return consistently absolute or relative paths.

### ISSUE THREAD

**Issue by jean-philippe-martin** [googleapis/google-cloud-java#3772]
The expected behavior from `Files.walkFileTree` is that if the starting path is absolute, then all the visited paths are absolute. If the starting path is relative, then all the visited paths are relative.

However, the output of `Files.walkFileTree("/dir/")` is something like this:

```
dir/file.txt
dir/dir2/another.txt
dir/dir2/
/dir/
```

As you can see, only the last entry is absolute. They should be consistent (in this case, they should be absolute).

**Comment by chingor13** [comment]
Fixed in #3773
