### ISSUE TITLE
Can not add Enable billing for Project (Cloud API)

### ISSUE THREAD

**Issue by Thien658jjh** [googleapis/google-cloud-java#3776]
I got this Error when I wanted to add payment method : 
### Unable to complete transaction: prepaid cards can't be used

Why is that ?

**Comment by chingor13** [comment]
This policy is dictated by Google Cloud Platform as a whole. See https://cloud.google.com/billing/docs/how-to/payment-methods. If you have further questions about this, please [contact GCP support](https://support.google.com/cloud).

Closing this out as it is not caused by the java libraries.
