### ISSUE TITLE
PubSub : repeatedly extend the acknowledgement deadline for backlogged pull messages

### ISSUE THREAD

**Issue by dhoard** [googleapis/google-cloud-java#3779]
For the asynchronous subscriber, backlogged messages have automatic acknowledgement deadline processing.

"<snip> Because the client library repeatedly extends the acknowledgement deadline for backlogged messages <snip>"

This feature would be useful for messages that are being processed via synchronous (pull.)

**Comment by yuri-sergiichuk** [comment]
We've implemented our own wrapper around PubSub sync functionality that starts `ScheduledExecutorService` and performs automatic ack prolong action if the task is not yet acknowledged.

**Comment by ajaaym** [comment]
closing this and will track in #3500
