### ISSUE TITLE
com.google.cloud:google-cloud-storage:jar:1.48.0 is invalid, transitive dependencies (if any) will not be available

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-java#3801]
Encountered this warning today while testing the dashboard. Noting here until I can dig into it. Perhaps someone else can explain this?

```
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.google.cloud:google-cloud-storage:jar:1.48.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce) @ upper-bounds-check ---
[WARNING] Invalid POM for com.google.cloud:google-cloud-storage:jar:1.48.0, transitive dependencies (if any) will not be available, enable debug logging for more details
```

**Comment by elharo** [comment]
Looks like a corrupt local repo. I don't see the error in the file in maven central.

**Comment by elharo** [comment]
[WARNING] The POM for com.google.cloud:google-cloud-core:jar:1.49.0 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for com.google.cloud:google-cloud-core:1.49.0
[FATAL] Non-parseable POM /Users/elharo/.m2/repository/com/google/cloud/google-cloud-clients/0.67.0-alpha/google-cloud-clients-0.67.0-alpha.pom: in epilog non whitespace content is not allowed but got o (position: END_TAG seen ...</profiles>\n</project>\no... @973:2)  @ /Users/elharo/.m2/repository/com/google/cloud/google-cloud-clients/0.67.0-alpha/google-cloud-clients-0.67.0-alpha.pom, line 973, column 2

[WARNING] The POM for com.google.cloud:google-cloud-storage:jar:1.49.0 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for com.google.cloud:google-cloud-storage:1.49.0
[FATAL] Non-parseable POM /Users/elharo/.m2/repository/com/google/cloud/google-cloud-clients/0.67.0-alpha/google-cloud-clients-0.67.0-alpha.pom: in epilog non whitespace content is not allowed but got o (position: END_TAG seen ...</profiles>\n</project>\no... @973:2)  @ /Users/elharo/.m2/repository/com/google/cloud/google-cloud-clients/0.67.0-alpha/google-cloud-clients-0.67.0-alpha.pom, line 973, column 2

**Comment by elharo** [comment]
Files are definitely malformed on my local system. Might be a maven bug that corrupts artifacts during download.

**Comment by elharo** [comment]
POM does not look corrupt on server so why does it keep getting corrupted locally? Maybe an eclipse interaction? (just guessing).

**Comment by sduskis** [comment]
I'm going to close this, since this seems not to be actionable here.
