### ISSUE TITLE
Need mechanism to keep dependencies up to date

### ISSUE THREAD

**Issue by chingor13** [googleapis/google-cloud-java#3802]
We should be notified automatically when dependencies are out of date so we can update them without the need for external contributors discovering them and filing ad hoc issues.

**Comment by elharo** [comment]
We're working on this. It's tricky because it's not always true that dependencies should be upgraded. We're trying to define a consistent set of dependency versions across google-cloud-java.

**Comment by sduskis** [comment]
This is done now that we have renovate.
