### ISSUE TITLE
Update BigQuery Table's schema

### ISSUE THREAD

**Issue by the-dagger** [googleapis/google-cloud-java#3805]
Hi, I was curious as to how I can update my BigQuery Table's schema based on my input data from a Streaming Dataflow Pipeline?

The input events that I get can have varied incremental schema and I want my BigQuery to adopt to the changes.

I [looked up an article on Google Cloud Blog](https://cloud.google.com/blog/products/gcp/how-to-handle-mutating-json-schemas-in-a-streaming-pipeline-with-square-enix) on a very similar topic, but there's no explanation on how the mutation was done (see the attached image)

<img width="1096" alt="screenshot 2018-10-09 at 7 48 13 pm" src="https://user-images.githubusercontent.com/6565270/46770883-c994ab80-cd0e-11e8-8e62-025d2d8da4dd.png">

Any ideas/leads on how I can do this?

**Comment by JesseLovelace** [comment]
Hi, just to clarify, is this question about updating a table schema in general, or specifically about integrating with Dataflow? If it's the latter, could you specify which points you need help with?

if you're asking in general how to update a table's schema, this could be done with the BigQuery client's `update` function. For example,

```java
bigquery.update(
            yourTable
            .toBuilder()
            .setDefinition(yourTable.getDefinition().toBuilder().setSchema(yourNewSchema).build())
            .build()
    );
```

`yourNewSchema` here would be a new `Schema` object constructed using `Schema.of` which specifies the new Schema to update your table to.

**Comment by the-dagger** [comment]
Hi @JesseLovelace thank you for the reply!
The query was to integrate it with Cloud Dataflow.
In my usecase, the clients can send me data points which can have different schema that is additive in nature.

What I am trying to do is update the schema of my BigQuery table automatically once I get a data point that has a different schema than my current table's schema.
I hope that makes sense? 

P.S. Do note that the schema can only be additive in nature; i.e. if the initial schema has 3 rows, the change schema can only have 4 rows or more, not less.

**Comment by sduskis** [comment]
I asked the author of the blog (Reza) for some help with this issue.

**Comment by the-dagger** [comment]
Thank you @sduskis

**Comment by ajaaym** [comment]
here is the example [dataflow-dynamic-schema](https://github.com/ryanmcdowell/dataflow-dynamic-schema)

**Comment by harshithdwivedi** [comment]
Hi @ajaaym, the example doesn't work.
If you look at the issue section of the example, you'll find that I've created an issue for the same.

Could you reopen this?

**Comment by sduskis** [comment]
This seems like a problem that should be raised in https://github.com/ryanmcdowell/dataflow-dynamic-schema/, and not something we should fix here.  @harshithdwivedi, can you please raise an issue in that repository?
