### ISSUE TITLE
Change in TableId behaviour for non default BigQueryClient project 1.44 -> 1.45

### ISSUE THREAD

**Issue by NickApostolidesMatillion** [googleapis/google-cloud-java#3808]
When using the getTable method of the BigQuery client the project of the TableId is overwritten. TableId would previously ignore this if a project had been set. Table Id has been changed such that the project is always overwritten. There is now no way to get a table for a project other than the one the client was created for.

```
TableId tableId = TableId.of(project, schema, tableName);
Table table = client.getTable(tableId);
// table returns null if project != client.getOptions().getProjectId()
```

_this is due to the change in TableId_

In BigQueryImpl:
```
public Table getTable(TableId tableId, TableOption... options) {
    final TableId completeTableId = tableId.setProjectId(getOptions().getProjectId());
    ...
```

TableId old code:
```
TableId setProjectId(String projectId) {
  return getProject() != null ? this : TableId.of(projectId, getDataset(), getTable());
}
```

TableId new code:
```
TableId setProjectId(String projectId) {
  Preconditions
    .checkArgument(!Strings.isNullOrEmpty(projectId), "Provided projectId is null or empty");
  return TableId.of(projectId, getDataset(), getTable());
}
```

**Comment by NickApostolidesMatillion** [comment]
@MMMarcy that would work for us. It is more suitable to have this logic in BigQueryImpl.

Thanks

**Comment by MMMarcy** [comment]
Perfect. Waiting for the owners thoughts now. If positive, I can open a PR

**Comment by MMMarcy** [comment]
Actually, thinking more about this using the proposed solution I mentioned hides too much of the behavior to the caller. Maybe overloading the `getTable` method with

```java
public Table getTable(TableId tableId, ProjectId projectId, TableOption... options) {
...
}
```
seems a better alternative.

**Comment by NickApostolidesMatillion** [comment]
TableId already has a factory method including the project:

`public static TableId of(String project, String dataset, String table)`

I would suggest that if the project is set in TableId, the developer knows the project he wants.

**Comment by polleyg** [comment]
Unless I've missed something obvious folks, this issue should be reopened. The [PR](https://github.com/googleapis/google-cloud-java/pull/3873) only fixed the `getTable()` method, but the same bug exists for other methods like `delete(TableId tableId)` and `update(TableInfo tableInfo)`. Other methods like `create()` and `update()` also appear to have the same issue.

**Comment by NickApostolidesMatillion** [comment]
The TableId changes also effect all code where TableInfo.setProjectId is referenced too.

**Comment by NickApostolidesMatillion** [comment]
@MMMarcy Can this issue be reopened and all occurrences be fixed or the original change reverted?

**Comment by chingor13** [comment]
@JesseLovelace PTAL

**Comment by mikekap** [comment]
I think there's way more callsites of `setProjectId` that aren't fixed - including `insertAll` that are still broken. IntelliJ shows 15 usages of which 3 are fixed now.

**Comment by sduskis** [comment]
@pmakani, it looks like there are more places that need to change.

**Comment by chingor13** [comment]
@pmakani Did #4196 actually fix all the cases?

**Comment by polleyg** [comment]
@chingor13 I was about to ask the same. He's all the references I see to `setProject()` in my IDEA..
<img width="1055" alt="screen shot 2018-12-13 at 11 00 13 am" src="https://user-images.githubusercontent.com/5554342/49906595-a335ec80-fec6-11e8-8350-c2281cf759cd.png">

**Comment by lepistone** [comment]
Hi, we believe this is still broken as of today (1.65.0). As in the description of this ticket, still `There is now no way to get a table for a project other than the one the client was created for`.

Specifically, in https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/BigQueryImpl.java#L635-L639 , the project in my `tableId` will *always* be overridden with the project of the service, if the service has a project.

Maybe the intention of that code was to override the project only if it is not set *in tableId*? Then the code would look like 

```java
          tableId.setProjectId(
              Strings.isNullOrEmpty(tableId.getProjectId())
                  ? serviceOptions.getProjectId());
                  : tableId.getProject()
 ```

Or maybe, the confusion arose between `TableId` and `TableInfo`. The code above calls `TableId::setProject`, which will **always** perform the change. See: https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigquery/src/main/java/com/google/cloud/bigquery/TableId.java#L100

Thanks!
