### ISSUE TITLE
BigQuery table labels not retrieved from getTable

### ISSUE THREAD

**Issue by oquere** [googleapis/google-cloud-java#3817]
"Labels" field has been added in the issue #2865 but no Field selector "Labels" is defined in the TableField enum.

So, there is no way to retrieve the labels of a table. 

#### Environment details

- cloud java version : 0.49.0

**Comment by JesseLovelace** [comment]
Thanks for bringing this to our attention! #3879 should have resolved this, please reopen if you still have any issues
