### ISSUE TITLE
Once g-c-j supports Java 11, add note that g-c-j can be used on Alpine and ARM (e.g. Raspberry Pi)

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/google-cloud-java#3827]
Reason: ALPN is available by default in Java 11, so netty-tcnative is not necessary.

**Comment by chingor13** [comment]
We are only declaring a dependencyManagement version on netty-tcnative, but it's not actually in the dependency tree. We're using `io.grpc:grpc-netty-shaded` which includes netty-tcnative.

**Comment by garrettjonesgoogle** [comment]
Both grpc-netty and grpc-netty-shaded don't work on Alpine or ARM. I'm kind of treating grpc-netty/grpc-netty-shaded as equivalent for this issue; the point is that I think neither one of them is strictly necessary in the dependency tree with Java 11, because ALPN is available by default in Java 11, meaning that grpc & google-cloud-java should work on Alpine and ARM in Java 11.

**Comment by sduskis** [comment]
Would it make sense to mark this as a "feature request" rather than "docs"?  It seems like we have work to do before we document anything.

**Comment by jbg** [comment]
Works well on Alpine Linux here with Java 11.
