### ISSUE TITLE
Include source proto files in jar for extensibility

### ISSUE THREAD

**Issue by daltonj** [googleapis/google-cloud-java#3834]
#### Environment details

- OS: Ubuntu 18.04
- Java version: 1.8
- google-cloud-java version(s): 1.49.0

#### Steps to reproduce

Create a project that has a proto import dependency on one of the .proto files. 

For example, 
google/cloud/dialogflow/v2/webhook.proto

#### Code snippet

import "google/cloud/dialogflow/v2/webhook.proto";
import "google/api/annotations.proto";

service WikiDialogue {
    // Send the response from agent using when a webhookrequest is received.
    rpc GetResponseFromAgent (google.cloud.dialogflow.v2.WebhookRequest) returns (google.cloud.dialogflow.v2.WebhookResponse) {
        option (google.api.http) = { post: "/v1/wikitalk/talk" };
    }
}

This results in a build error because the proto will not be found; it is not included in the jar file. 

The fix for this is to modify the pom file to include the proto file in the jar file when it is constructed, e.g.:

To include all the proto files:
 <resources>
      <resource>
        <directory>src/main/proto</directory>
        <includes>
          <include>google/cloud/dialogflow/v2/webhook.proto</include>
          <include>google/cloud/dialogflow/v2/intent.proto</include>
          <include>google/cloud/dialogflow/v2/session.proto</include>
          <include>google/cloud/dialogflow/v2/session_entity_type.proto</include>
          <include>google/cloud/dialogflow/v2/entity_type.proto</include>
          <include>google/cloud/dialogflow/v2/agent.proto</include>
          <include>google/cloud/dialogflow/v2/context.proto</include>
        </includes>
      </resource>
    </resources>

This would allow us to import and use the proto files in developing service APIs that build on top of Google APIs.

Thanks!

**Comment by sduskis** [comment]
@pongad, where do the proto jars get generated?

**Comment by sduskis** [comment]
FWIW, the proto files are at: https://github.com/googleapis/googleapis

**Comment by pongad** [comment]
Sorry I'm late to this. By "proto jars" do you mean the source protos? I don't think we're creating these right now.

To be fair, I don't think it's right to import proto files from JARs, many APIs depend on the same protos and you'll end up in a bit of a mess. If you'd like to import proto files, consider seeing https://github.com/googleapis/googleapis like @sduskis suggested and https://github.com/googleapis/api-common-protos .

**Comment by daltonj** [comment]
This is not resolved. Can we re-open this? Or can you refer me to an appropriate issue location?

I'm looking for an equivalent of a cloud proto library for user in service definitions, like the ones that exist for a subset of services, e.g. proto-google-common-protos. This commons library DOES export protos inside of jar.  This is needed for the maven dependency artifacts.

In thise case, it could be something like:
proto-google-googleapis-protos

Or perhaps more fine-grained to mirror the generated java code:
e.g. google-cloud-dialogflow (java) vs. google-cloud-dialogflow-proto (proto def)

Otherwise, what would you suggest for creating services that interact with the google apis?
