### ISSUE TITLE
can't parse WebHookRequest

### ISSUE THREAD

**Issue by joaquinjsb** [googleapis/google-cloud-java#3850]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

#### Environment details

- OS: Windows 10 Pro X64
- Java version: 1.8.131
- google-cloud-java version(s): 0.67.0-alpha

#### Steps to reproduce

1. ? send request from Dialogflow
2. ? parse WebHookRequest from Controller on Spring

#### Stacktrace
`
com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:551)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:514)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:633)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:295)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readGroup(CodedInputStream.java:2369)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:541)
	at com.google.protobuf.GeneratedMessageV3.parseUnknownFieldProto3(GeneratedMessageV3.java:305)
	at com.google.cloud.dialogflow.v2beta1.WebhookRequest.<init>(WebhookRequest.java:100)
	at com.google.cloud.dialogflow.v2beta1.WebhookRequest.<init>(WebhookRequest.java:13)
	at com.google.cloud.dialogflow.v2beta1.WebhookRequest$1.parsePartialFrom(WebhookRequest.java:1656)
	at com.google.cloud.dialogflow.v2beta1.WebhookRequest$1.parsePartialFrom(WebhookRequest.java:1650)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:239)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:244)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:311)
	at com.google.cloud.dialogflow.v2beta1.WebhookRequest.parseFrom(WebhookRequest.java:507)
	at it.joaquin.test.web.rest.ProductResource.searchByName(ProductResource.java:42)
`

```

com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:115)

```

#### Code snippet
```java
@PostMapping("/search-by-name")
    public ResponseEntity<String> searchByName(@RequestBody String body) throws IOException {
        InputStream stream = new ByteArrayInputStream(body.getBytes(StandardCharsets.UTF_8));
        WebhookRequest webhookRequest = WebhookRequest.parseFrom(stream);
```
 

#### External references such as API reference guides used
- ?

#### Any additional information below

Message from Dialogflow
`[{
  "responseId": "ff6d0d81-e09d-46e8-a3f2-41b6058729bd",
  "queryResult": {
    "queryText": "2 confezioni di pane",
    "action": "input.buy",
    "parameters": {
      "product": "pane",
      "quantity": 2.0,
      "measureUnit": "confezioni"
    },
    "allRequiredParamsPresent": true,
    "fulfillmentText": "vedo cosa trovo per 2 confezioni di pane",
    "fulfillmentMessages": [{
      "text": {
        "text": ["ho capito che vuoi comprare 2 confezioni di pane"]
      }
    }],
    "intent": {
      "name": "projects/test-181222/agent/intents/d060e25c-2e4e-4c7e-903b-5cb55c13a6f0",
      "displayName": "start shopping"
    },
    "intentDetectionConfidence": 0.9,
    "languageCode": "it"
  },
  "originalDetectIntentRequest": {
    "payload": {
    }
  },
  "session": "projects/test-181222/agent/sessions/fa784619-43bd-f263-858f-8dd51ff7a69d"
}]`

Thanks

**Comment by ajaaym** [comment]
probably you need something like this?
```Java
JsonFormat.parser().merge(body, WebhookRequest.newBuilder());
```

**Comment by joaquinjsb** [comment]
Working like a charm, thank you!

**Comment by ajaaym** [comment]
@joaquinjsb can you please try below?

```
    Struct.Builder payloadBuilder = Struct.newBuilder();
    Struct.Builder googleBuilder = Struct.newBuilder();
    ListValue.Builder messageList = ListValue.newBuilder();
    products.forEach(product -> {
      Intent.Message.Builder message = Intent.Message.newBuilder();
      Intent.Message.BasicCard.Builder basicCard = Intent.Message.BasicCard.newBuilder();
      basicCard.setFormattedText(product.getShortDescr());
      basicCard.setTitle(product.getName());
      Intent.Message.Image.Builder image = Intent.Message.Image.newBuilder();
      image.setImageUri(product.getMediaURLMedium());
      basicCard.setImage(image);
      message.setBasicCard(basicCard);
      messageList.addValuesBuilder().setField(Intent.getDescriptor().findFieldByNumber(Intent.MESSAGES_FIELD_NUMBER),message.build());
    });
    googleBuilder.putFields("richResponse", Value.newBuilder().setListValue(messageList).build());
    payloadBuilder.putFields("google", Value.newBuilder().setStructValue(googleBuilder).build());
    responseBuilder.setPayload(payloadBuilder);
```

**Comment by joaquinjsb** [comment]
I'll update you as soon as I test it, thank you very much!

**Comment by ajaaym** [comment]
Closing this for now. Please reopen if this doesnt work.

**Comment by Kamatam** [comment]
Hi,

I also tried the above solution to build the payload and still facing same issue "java.lang.IllegalArgumentException: FieldDescriptor does not match message type". Please check the following code and let me know your suggestions

import com.google.cloud.dialogflow.v2.Intent;
import com.google.cloud.dialogflow.v2.Intent.Message;
import com.google.cloud.dialogflow.v2.Intent.Message.BasicCard;
import com.google.cloud.dialogflow.v2.Intent.Message.Image;
import com.google.cloud.dialogflow.v2.QueryResult;
import com.google.cloud.dialogflow.v2.WebhookResponse;
import com.google.protobuf.Descriptors.FieldDescriptor;
import com.google.protobuf.ListValue;
import com.google.protobuf.Struct;
import com.google.protobuf.Value;
..
public static void buildWebhookPayload(String apiResponse)
			throws ConversationException {
		Struct.Builder payload = Struct.newBuilder();
		Struct.Builder google = Struct.newBuilder();
		ListValue.Builder messageList = ListValue.newBuilder();
		Message.Builder message = Message.newBuilder();
		BasicCard.Builder basicCard = BasicCard.newBuilder();
		basicCard.setFormattedText(apiResponse); // api response, 
		basicCard.setTitle("Card title");
		Image.Builder image = Image.newBuilder();
		image.setImageUri("http://test.jpg");
		basicCard.setImage(image);
		message.setBasicCard(basicCard);

		FieldDescriptor fieldDesc = Intent.getDescriptor().findFieldByNumber(Intent.MESSAGES_FIELD_NUMBER);	
		messageList.addValuesBuilder().setField(fieldDesc, message.build()); // java.lang.IllegalArgumentException: FieldDescriptor does not match message type.
		google.putFields("richResponse", Value.newBuilder().setListValue(messageList).build());
		payload.putFields("google", Value.newBuilder().setStructValue(google).build());
		WebhookResponse webhookResp = WebhookResponse.newBuilder().setPayload(payload).build();	
	}
