### ISSUE TITLE
Threads leak with Logback Appender for Google Cloud Logging

### ISSUE THREAD

**Issue by volodymyrd** [googleapis/google-cloud-java#3880]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

#### Environment details

- OS: Ubuntu 16
- Java version: 1.8
- google-cloud-java version(s): gcp_logback_logging: '0.68.0-alpha'

#### Steps to reproduce
After turned on gcp logging in a few days my app stop to response. Generally my app consumes twice less threads than without  gcp logging. 
I really want using stackdriver for my app but such behave of it stop me.

Thanks 
Volodymyr

**Comment by volodymyrd** [comment]
Hello,
Is it  possible to use a thread pool for GCP logging, because it could help solving the problem?

**Comment by volodymyrd** [comment]
Hello,
I received something like this "SQL Error: 0, SQLState: null", so my app lost connection to db. I fixed it  rebooting a server. Currently I the gcp logging switched off and everything works fine.

**Comment by SergeyZadorozhniy** [comment]
Can you, please, provide you usage example. Long running tests did not discover the problem.

**Comment by volodymyrd** [comment]
I updated to   '0.70.0-alpha' version and it looked good for a few days, but yesterday the issue reproduced again, I attach the thread dump
You can see a lot of http-nio- threads created by google logging system.
[threaddump-1542231673167.tdump.zip](https://github.com/googleapis/google-cloud-java/files/2584189/threaddump-1542231673167.tdump.zip)

**Comment by volodymyrd** [comment]
Hello,
Are there any updates?
Thanks

**Comment by volodymyrd** [comment]
It looks like the same [issue](https://github.com/googleapis/google-cloud-java/issues/2796#issuecomment-431323121)
