### ISSUE TITLE
Question about setting maxOutstandingByteCount to null on FlowControlSettings

### ISSUE THREAD

**Issue by j256** [googleapis/google-cloud-java#3884]
Sorry for the question but I didn't get any answers to my [SO question](https://stackoverflow.com/q/52932362/179850).

What are the ramifications of setting the max-outstanding value on `FlowControlSettings` to be null or some large integer? Does this only impact client side memory storage of outstanding GUIDs or other telemetry? Anything else we need to worry about?

We have our own flow-control that will limit the outstanding messages but we need to vary the record-count based on our own triggers.

Thanks.

**Comment by sduskis** [comment]
@igorbernstein2, do you have a good answer for this?

**Comment by igorbernstein2** [comment]
I'm not familiar with the pubsub client in specific, but I can try to help with FlowController in general.

Removing it will impact client side memory as well as the service itself. If you have a large number of outstanding RPCs, then it implies that your application is sending RPCs faster than the service can send replies. If you don't throttle your qps, then your service will never catch up.  The general idea of the FlowController is to temporarily block your calling thread from sending more requests while the service is processing the already sent ones.

Does that help at all?

**Comment by dhoard** [comment]
The Pub / Sub **service** has a maximum number of outstanding messages.  Once you hit the limit, you will not receive any new messages.  We encountered this limit around 1 million outstanding messages.

There _may_ be a Pub / Sub **service** maximum on outstanding bytes as well.

**Comment by j256** [comment]
Thanks for the response @igorbernstein2 .  Sorry to not respond sooner.

I suspected as much.  We need more fine grained control over the outstanding messages so we block the client threads which seems to be working.  Thanks again.
