### ISSUE TITLE
Why cacerts update is needed in GCE/GKE

### ISSUE THREAD

**Issue by Rossco8** [googleapis/google-cloud-java#3901]
When reading files from a Google Storage Bucket from within a container running in GKE or GCE. The following code fails:

    public String readSmallTextFileFromBucket(String bucketName, String textFile) {

        Blob blob = storage.get(bucketName, textFile);
        String fileContent = new String(blob.getContent());
        return fileContent;
        }

With the error:

`com.google.cloud.storage.StorageException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

If I replace the default `java/jdk-10.0.2/lib/security/cacerts` file you get when you download OpenJDK with the one from my desktop, the code above works.

Why is that? and what is the correct way to enable the Java API to read from a storage bucket from within a container?

#### Environment details
- OpenJDK 10
- Google Kubernetes

**Comment by TimWSpence** [comment]
👍 I have the same issue

**Comment by Rossco8** [comment]
A suggestion was published as to how to fix this on my question on StackOverflow, but it did not work as the CA Certs on the Docker image are already the latest

**Comment by Rossco8** [comment]
This issue is resolved for me, answer documented on Stackoverflow 
https://stackoverflow.com/questions/53094694/why-cacerts-update-is-needed-in-kubernetes/53357568#53357568

**Comment by ajaaym** [comment]
Looks like this is answered correctly, I am closing this for now. Please reopen if required.
