### ISSUE TITLE
GCS NIO readAttributes returns CloudStorageObjectAttributes for directory like objects

### ISSUE THREAD

**Issue by tomcham** [googleapis/google-cloud-java#3918]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

#### Environment details

- google-cloud-java version(s): google-cloud-nio:0.69.0-alpha

#### Steps to reproduce

1. In the GCS UI within a bucket, press create folder button and create a folder called `dir`
2. Upload a file within `dir` call this `fileA`

#### Code snippet

```java
    FileSystem fs = ....
    Files.walkFileTree(fs.getPath("dir") new SimpleFileVisitor<Path>() {
      @Override
      public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
        System.out.println(file);
        return FileVisitResult.CONTINUE;
      }
```

#### Any additional information below

The GCS UI creates a 0 byte object called `dir/` This causes `readAttributes` to return https://github.com/googleapis/google-cloud-java/blob/v0.69.0/google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java#L765, which prevents further traversal of objects within that directory. 

Does it make sense to do a check like https://github.com/googleapis/google-cloud-java/blob/v0.69.0/google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java#L756 `usePseudoDirectories` is enabled and it is a 0 byte object?

I saw this related merged PR https://github.com/googleapis/google-cloud-java/pull/3775/files by  @jean-philippe-martin

**Comment by andrey-qlogic** [comment]
@chingor13 
Perhaps, you would like to add a check blobInfo for null at this line https://github.com/googleapis/google-cloud-java/blob/78f67a29e8b9c46ba01de566a2eae0fd1c03edea/google-cloud-clients/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java#L745, that makes no sense that is always null there.

**Comment by jean-philippe-martin** [comment]
Yes, what the UI does is rather surprising. As discussed in [this GitHub issue](https://github.com/broadinstitute/gatk/pull/5546) we end up with both a file and a directory that have the same name.

I didn't see your fix before writing mine, sorry. I think it makes sense for NIO to report the underlying truth, namely that both the file and the directory exist.

**Comment by jean-philippe-martin** [comment]
Reopen: there is some tool out there that now creates 11-byte files with a trailing slash to pretend directories exist, and this breaks the merged fix.

See [this bug report](https://github.com/broadinstitute/gatk/issues/5935) for an example.

**Comment by jean-philippe-martin** [comment]
OK no need to reopen, let's use #5203 instead.
