### ISSUE TITLE
Cloud Client Documentation: missing lib versions

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/google-cloud-java#3919]
For instance, when Pub/Sub users land on [https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html?com/google/cloud/pubsub/v1/package-summary.html
?](https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html?com/google/cloud/pubsub/v1/package-summary.html), it's not clear which version the documentation is for. 

In fact, the screen quickly flashes version 0.69.XX, which is behind 1.51.0 (current).

**Comment by sduskis** [comment]
@anguillanneuf, I think that this issue can be closed. Can you please see the link you listed, and take a look at the bottom right?

**Comment by anguillanneuf** [comment]
Awesome. Yes, you may close this issue now.
