### ISSUE TITLE
Upgrade Guava to the latest version

### ISSUE THREAD

**Issue by elefeint** [googleapis/google-cloud-java#3931]
[Spring Cloud GCP](https://github.com/spring-cloud/spring-cloud-gcp) uses `google-cloud-bom` for the common dependencies. We have recently turned on Snyk vulnerability detection, and it found a [deserialization issue](https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236) with Guava 20.0. 
The recommended remediation step is to upgrade to 24.1.1 or higher.

Would it be possible to upgrade Guava version in [google-cloud-clients POM](https://github.com/googleapis/google-cloud-java/blob/a7bd8a5717e70d7df2ee8e57ed1a37dac0bde94e/google-cloud-clients/pom.xml#L163)?

Spring Cloud GCP tracking issue: spring-cloud/spring-cloud-gcp#1207

**Comment by sduskis** [comment]
@elharo, can you please chime in?

**Comment by garrettjonesgoogle** [comment]
A more recent version of grpc-java is using guava 26.0-android now, so we should bump to that.

**Comment by elharo** [comment]
I feel like we should upgrade everything or nothing. 26.0-android is likely strictly better but there's more than grpc to fix here.
