### ISSUE TITLE
Translate does not preserve new line or enter

### ISSUE THREAD

**Issue by trueman1** [googleapis/google-cloud-java#3938]
- OS: Debian 9
- Java version: java-1.8.0-openjdk
- google-cloud-java version(s): 1.40.0

#### Steps to reproduce

1. Hello how are you? \n I am fine.
2. Translated text does not preserve new line.

#### Code snippet

            String text = "how are you\n I am fine";

            Translation translation =
                    CGlobals.g_Translate.translate(
                            text,
                            Translate.TranslateOption.model("nmt"),
                            com.google.cloud.translate.Translate.TranslateOption.sourceLanguage("en"),
                            com.google.cloud.translate.Translate.TranslateOption.targetLanguage("mr"));

            //System.out.printf("Text: %s%n", text);
            String translatedText = translation.getTranslatedText();

            System.out.printf("Translation: %s%n", translatedText);

Thanks!

**Comment by sduskis** [comment]
As per [this Stackoverflow question](https://stackoverflow.com/questions/44444910/unable-to-preserve-line-breaks-in-google-translate-response), please add `com.google.cloud.translate.Translate.TranslateOption.format("text")` to your `CGlobals.g_Translate.translate(` options to format the output with a new line.

**Comment by dungla2011** [comment]
I also want translate Html (not text) keep end line response (\n)
