### ISSUE TITLE
OperationCallable ran out of place??

### ISSUE THREAD

**Issue by winfield007** [googleapis/google-cloud-java#4015]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

#### Environment details

- OS:
- Java version:
- google-cloud-java version(s):

#### Steps to reproduce

1. ?
2. ?

#### Stacktrace

```
Any relevant stacktrace here.
```

#### Code snippet

```java
Any relevant code snippet to help reproduce the issue.
```

#### External references such as API reference guides used

- ?

#### Any additional information below

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sduskis** [comment]
@winfield007, it's not clear what you mean.  Can you please add more information so that we can understand the problem?

**Comment by ajaaym** [comment]
closing this due to staleness. Please feel free to reopen with more information.
