### ISSUE TITLE
Bigtable: investigate GCRule.fromProto being incorrect

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-java#4057]
From a user:

> GCRule and GcRule classes are confusing and .fromProto() conversion does not work properly in some cases. Not 100% sure which scenario it was, but I think we were setting maxversions and maxage, and only one of them was in the final result after calling .fromProto().

**Comment by sduskis** [comment]
@igorbernstein2, and additional info would be helpful.

**Comment by igorbernstein2** [comment]
I updated the description

**Comment by sduskis** [comment]
@rahulKQL, can you please look at this?
