### ISSUE TITLE
0.71.0 has an upper bounds failure

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-java#4089]
I'm sending PRs to fix this upstream but we might want to work around this her in the meantime.

```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for com.google.auth:google-auth-library-oauth2-http:0.11.0 paths to dependency are:
+-com.google.cloud:upper-bounds-check:0.0.1-SNAPSHOT
  +-com.google.cloud:google-cloud-core:1.53.0
    +-com.google.api:gax:1.35.0
      +-com.google.auth:google-auth-library-oauth2-http:0.11.0
and
+-com.google.cloud:upper-bounds-check:0.0.1-SNAPSHOT
  +-com.google.cloud:google-cloud-storage:1.53.0
    +-com.google.cloud:google-cloud-core-http:1.53.0
      +-com.google.auth:google-auth-library-oauth2-http:0.12.0
and
+-com.google.cloud:upper-bounds-check:0.0.1-SNAPSHOT
  +-com.google.cloud:google-cloud-storage:1.53.0
    +-com.google.cloud:google-cloud-core-http:1.53.0
      +-com.google.api:gax-httpjson:0.52.0
        +-com.google.auth:google-auth-library-oauth2-http:0.11.0
]
```

**Comment by chingor13** [comment]
What command were you running to find this? We should be able to catch this with CI.

**Comment by elharo** [comment]
This happened with the upper bounds checker for the cloud-oss-bom when I attempted to upgrade that to 0.71.0. 0.70.0 worked. I need to dig into this more deeply. It may depend on the order in which dependencies are declared.

**Comment by sduskis** [comment]
I think that this repo is doing the right thing.  `gax` should update its `com.google.auth:google-auth-library-oauth2-http`.  renovate-bot will take care of that.  This specific issue is outdated now that auth was upgraded in gax: https://github.com/googleapis/gax-java/pull/701
