### ISSUE TITLE
Bigtable: Remove typesafe names from the api

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-java#4091]
Currently they create more issues than they solve:
- Some names are duplicated between the admin and data namespace
- Some names are only available in the admin namespace, which means they are duplicated in the models namespace instead.

To avoid all of these issues, we should just use strings for now.

**Comment by rahulKQL** [comment]
This issue can be closed as @igorbernstein2 has already removed typesafe names from Bigtable API.
Related PRs:

#4671, #4505, #4258, #4257
