### ISSUE TITLE
Bad link on Storage docs page

### ISSUE THREAD

**Issue by alexamies** [googleapis/google-cloud-java#4169]
There is a bad at
https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-storage

The link in the text
"application on the StorageExample docs page"
points to a 404
https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/?com/google/cloud/examples/storage/StorageExample.html

**Comment by sduskis** [comment]
@alexamies, can you please review the current state now that we've updated the README?
