### ISSUE TITLE
Dependency issue in cloud storage API

### ISSUE THREAD

**Issue by ZeJ0hn** [googleapis/google-cloud-java#4175]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

#### Environment details

- OS: Linux
- Java version: 8
- google-cloud-java version(s): 1.54 (and previous)

#### Steps to reproduce

1. untar the archive
[Issue_Example.tar.gz](https://github.com/googleapis/google-cloud-java/files/2645801/Issue_Example.tar.gz)

2. mvn install

3. see the output :
The compilation failed cause of many "Dependency convergence error"

#### Stacktrace

[Issue_mvn_output.txt](https://github.com/googleapis/google-cloud-java/files/2645808/Issue_mvn_output.txt)

#### Code snippet

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.total</groupId>
	<artifactId>Example</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>3.0.0-M2</version>
				<executions>
					<execution>
						<id>enforce</id>
						<phase>compile</phase>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<dependencyConvergence />
							</rules>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-storage</artifactId>
			<version>1.54.0</version>
		</dependency>
	</dependencies>
</project>

#### External references such as API reference guides used

- ?

#### Any additional information below

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sduskis** [comment]
@elharo, FYI

**Comment by ZeJ0hn** [comment]
Hello,

Thank you for your answer.
First, why do I need to use the google-cloud-bom ? because I just need the
storage library.

I'm working, in my company, on a huge java software with many library.
To avoid any issues, we have activated the plugin maven to check
convergence.

So today, I'm no able to passed the integration test because the library is
not ok regarding dependency convergence.

What is the solution is that case ?

Thank you for your help

Jonathan

**Comment by sduskis** [comment]
I'm going to see if I can exclude some of the troublesome dependencies.

**Comment by sduskis** [comment]
@ZeJ0hn, There's internal debate about this issue.  The synopsis is that we generally recommend the use of `</requireUpperBoundDeps>`.  I'm happy to chat about this offline (see my GitHub profile for more details).

**Comment by sduskis** [comment]
We decided that we can't have complete dependency convergence in this repo.  We suggest using `</requireUpperBoundDeps>` or that users manually exclude dependencies.

**Comment by elonazoulay** [comment]
The following added to <dependencyManagement> eliminated dependency convergence issues for version 1.101.0:

`
      <dependency>
        <groupId>com.google.api.grpc</groupId>
        <artifactId>proto-google-common-protos</artifactId>
        <version>1.17.0</version>
        <exclusions>
          <exclusion>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>com.google.api.grpc</groupId>
        <artifactId>proto-google-iam-v1</artifactId>
        <version>0.13.0</version>
        <exclusions>
          <exclusion>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
          </exclusion>
          <exclusion>
            <groupId>com.google.api.grpc</groupId>
            <artifactId>proto-google-common-protos</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>com.google.apis</groupId>
        <artifactId>google-api-services-storage</artifactId>
        <version>v1-rev20190910-1.30.3</version>
        <exclusions>
          <exclusion>
            <groupId>com.google.api-client</groupId>
            <artifactId>google-api-client</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>com.google.api</groupId>
        <artifactId>gax-httpjson</artifactId>
        <version>0.66.1</version>
        <exclusions>
          <exclusion>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
`
