### ISSUE TITLE
Logback Appender for Google Cloud Logging does not comply with Error Reporting

### ISSUE THREAD

**Issue by drelum** [googleapis/google-cloud-java#4179]
Logback Appender for Google Cloud Logging does not comply with STACKDRIVER ERROR REPORTING.

 See https://cloud.google.com/error-reporting/docs/formatting-error-messages

Field"serviceContext" is mandatory and is not being generated by com.google.cloud.logging.logback.LoggingAppender

The following method should be changed:

```java
  private LogEntry logEntryFor(ILoggingEvent e) {
    StringBuilder payload = new StringBuilder(e.getFormattedMessage()).append('\n');
    writeStack(e.getThrowableProxy(), "", payload);

    Level level = e.getLevel();
    LogEntry.Builder builder =
        LogEntry.newBuilder(Payload.StringPayload.of(payload.toString().trim()))
            .setTimestamp(e.getTimeStamp())
            .setSeverity(severityFor(level));

    builder
        .addLabel(LEVEL_NAME_KEY, level.toString())
        .addLabel(LEVEL_VALUE_KEY, String.valueOf(level.toInt()));

    if (loggingEnhancers != null) {
      for (LoggingEnhancer enhancer : loggingEnhancers) {
        enhancer.enhanceLogEntry(builder);
      }
    }

    if (loggingEventEnhancers != null) {
      for (LoggingEventEnhancer enhancer : loggingEventEnhancers) {
        enhancer.enhanceLogEntry(builder, e);
      }
    }

    return builder.build();
  }
```

**Comment by ajaaym** [comment]
google-cloud-errorreporting is separate service than google-cloud-logging and logback appender for google-cloud-logging is not integrated with cloud error reporting yet.

**Comment by ajaaym** [comment]
more information over [#2912](https://github.com/googleapis/google-cloud-java/issues/2912) [#2669](https://github.com/googleapis/google-cloud-java/issues/2669) [#3031](https://github.com/googleapis/google-cloud-java/issues/3031) Closing this and we will track this in [#3031](https://github.com/googleapis/google-cloud-java/issues/3031)
