### ISSUE TITLE
Bigtable: The new emulator is not available from maven central

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-java#4187]
I see it on the website:
https://search.maven.org/artifact/com.google.cloud/google-cloud-bigtable-emulator/0.72.0-alpha/jar

But maven can't get it:
`mvn dependency:get -Dartifact=com.google.cloud:google-cloud-bigtable-emulator:0.72.0-alpha`

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project standalone-pom: Couldn't download artifact: Unable to get dependency information for com.google.cloud:google-cloud-bigtable-emulator:jar:0.72.0-alpha: Failed to process POM for com.google.cloud:google-cloud-bigtable-emulator:jar:0.72.0-alpha: Non-resolvable parent POM for com.google.cloud:google-cloud-bigtable-emulator:0.72.0-alpha: Could not find artifact com.google.cloud:google-cloud-testing:pom:0.72.0-alpha in central (https://repo.maven.apache.org/maven2)
[ERROR]   com.google.cloud:google-cloud-bigtable-emulator:jar:0.72.0-alpha
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] Path to dependency: 
[ERROR] 	1) org.apache.maven.plugins:maven-downloader-plugin:jar:1.0
```

Looks like we have to publish the google-cloud-testing pom as well. 
However, that pom is explicitly marked not to be published to avoid publishing the child modules. I'm not sure what's the best way to proceed here.

@chingor13  Any ideas?

**Comment by chingor13** [comment]
We should be able to remove the `<parent>` section of the `pom.xml`. We will need to make sure that the emulator artifact is not inheriting any properties or build configuration from the parent.

**Comment by sheetalj2205** [comment]
Hello, community
I am trying to test Google Cloud bigtable emulator with java. For which I am following the code of this blog - [https://www.inovex.de/de/blog/cloud-bigtable-unit-testing-java/](Blog). I am using SST tool and created a spring starter project but it is showing me the error message - "**The import com.google.cloud.bigtable.emulator cannot be resolved**" . I have checked the Maven Dependencies folder also and it has both the jar files of google-cloud-bigtable-emulator and grpc-google-cloud-bigtable-v2.

Can someone help me with this? It would be appreciated.

Thank you
Sheetal Jain
https://www.linkedin.com/in/sheetaljain225/
