### ISSUE TITLE
Document dependency convergence issues / approach

### ISSUE THREAD

**Issue by sduskis** [googleapis/google-cloud-java#4198]
Our team has a sprawling set of dependencies that we own or influence and will never be able to have dependency convergence.  We will also have issues in projects that use our libraries like Apache Beam.  

Document the problems, our approach and how to use the tools we created in order to solve common problems.

**Comment by chingor13** [comment]
This needs be encoded in one of the [JLBP](https://github.com/GoogleCloudPlatform/cloud-opensource-java/tree/master/library-best-practices) (Java Library Best Practices) and then we can link there.
