### ISSUE TITLE
Stopping the receivers in Google pubsub?

### ISSUE THREAD

**Issue by j256** [googleapis/google-cloud-java#4211]
Is there a way for me to stop the PubSub Subscriber message receivers _without_ calling the `stopAsync()`?

The use case is that I want to shutdown the Subscriber but I also want to nack any messages that have been received and queued locally or are in the process of being received as I shutdown my application.  Right now my only recourse is to call `stopAsync()`, nack the messages by the calling thread, and then once my queues are empty, join with the Subscriber being stopped.  I assume that this means that a certain number of the nacks will not get delivered to the Pubsub servers because the Subscriber is coming down.  This means that I have to rely on the ack timeouts for the messages to be retransmitted which is not optimal.

Sorry if I'm not understanding how the nack/ack/retransmit system works.

**Comment by chrisribble** [comment]
I handle this in my apps by having the message handler that the subscriber delegates to use an ExecutorService to dispatch actual work. When we are shutting down, I shut down that ExecutorService first (causing subsequent calls to enqueue work to throw RejectedExecutionException, which I have generate a nack), then awaitTermination on the ExecutorService for a predetermined timeout to allow tasks to finish and ack/nack as appropriate, then call ExecutorService.shutdownNow() to ensure tasks get interrupted and nack if they did not complete within the timeout, and then one more (shorter) predetermined timeout for tasks to handle the interrupt, and then finally I call Subscriber.stopAsync.

This works pretty well as long as you pick good timeouts based on your operation completion times.

**Comment by pmakani** [comment]
@j256 @chrisribble

I have tested with various scenario and it seems to working fine. can you please retest it ?

```
 public static String projectId = ServiceOptions.getDefaultProjectId();
  public static String topicName = "Publisher-Test-Topic";
  public static final BlockingQueue<PubsubMessage> messages = new LinkedBlockingDeque<>();
  public static Subscriber subscriber = null;

  static class MessageReceiverExample implements MessageReceiver {
    @Override
    public void receiveMessage(PubsubMessage message, AckReplyConsumer consumer) {
      messages.offer(message);
    }
  }

  public static void main(String... args) throws Exception {
    // set subscriber id, eg. my-sub
    String subScriptionId = "Subscriber-Test-Topic1";
    // subscribeTopic(projectId, topicName, subScriptionId);
    subscribeMessage(projectId, subScriptionId);
  }

  public static void subscribeMessage(String projectId, String subscriptionId) {
    // String subscriptionId = "javaTest";
    ProjectSubscriptionName subscriptionName =
        ProjectSubscriptionName.of(projectId, subscriptionId);
    try {
      subscriber = Subscriber.newBuilder(subscriptionName, new MessageReceiverExample()).build();
      subscriber.startAsync().awaitRunning();
      // subscriber.stopAsync();
      int count = 0;
      while (count <= 10) {
        PubsubMessage message = messages.take();
        System.out.println("Start1----------------" + count + "--------------------");
        System.out.println("Message Id1: " + message.getMessageId());
        System.out.println("Data1: " + message.getData().toStringUtf8());
        System.out.println("End1----------------" + count + "--------------------");
        count++;
      }
      subscriber.stopAsync();
      subscriber = Subscriber.newBuilder(subscriptionName, new MessageReceiverExample()).build();
      subscriber.startAsync().awaitRunning();
      int count2 = 0;
      while (count2 <= 10) {
        PubsubMessage message = messages.take();
        System.out.println("Start2----------------" + count2 + "--------------------");
        System.out.println("Message Id2: " + message.getMessageId());
        System.out.println("Data2: " + message.getData().toStringUtf8());
        System.out.println("End2----------------" + count2 + "--------------------");
        count2++;
      }
      subscriber.stopAsync();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
```
