### ISSUE TITLE
Spanner: Better document the difference between singleUse() and singleUseReadOnlyTransaction().

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-java#4212]
Hi,
I think the documentation of the difference between `DatabaseClient.singleUse()` and `DatabaseClient.singleUseReadOnlyTransaction()` needs to be more verbose.

This is the documentation for both of these:
> Returns a context in which a single read can be performed using TimestampBound.strong() concurrency.

> Returns a read-only transaction context in which a single read or query can be performed using TimestampBound.strong() concurrency.

By looking at the code, the only difference I can really find is that `ReadOnlyTransaction` (returned by `singleUseReadOnlyTransaction()`) holds the `read_timestamp` selected internally by Spanner once the `Read` or query finishes. If I'm reading it correctly, that means that `singleUse()` is not less transactional than `singleUseReadOnlyTransaction()` is. Is there any reason (beyond compatibility) not to remove `singleUse()` from the `DatabaseClient`?

**Comment by olavloite** [comment]
>  Is there any reason (beyond compatibility) not to remove singleUse() from the DatabaseClient?

The only difference between singleUse() and singleUseReadOnlyTransaction() is that the latter will include the read timestamp in the return value. This field is an optional field that is not returned by default by Cloud Spanner, and you have to specifically request that it should be returned by Cloud Spanner. There is however nothing in the (public) grpc documentation of Cloud Spanner that indicates that this is something that impacts performance in any detectable way, but maybe someone from the Cloud Spanner backend team could confirm that.
