### ISSUE TITLE
API doc links are broken

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-java#4228]
For example:
- bigtable's readme has: https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html?com/google/cloud/bigtable/package-summary.html
- spanner's readme has: https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html?com/google/cloud/spanner/package-summary.html

Both lead to a 404

**Comment by chingor13** [comment]
We had a bad docs build. This should now be fixed.
