### ISSUE TITLE
What should we use instead since ApiFutures. addCallback(  future,callback) is deprecated

### ISSUE THREAD

**Issue by ayushj158** [googleapis/google-cloud-java#4233]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

#### Environment details

- OS: Linux/Windows
- Java version: 1.8
- google-cloud-java version(s):1.50

#### Steps to reproduce

1.ApiFuture.addCallback(future,callback) method is deprecated and new method with ApiFuture.addCallback (future,callback,exectuor) is added in API . I am not exactly sure what is the significance/correct way to use this executor and if should we use it at  all . 
2. We are seeing Run time Exceptions in logs because of deprecated method usage possibly.

#### Stacktrace
```
c.g.c.util.concurrent.AbstractFuture - RuntimeException while executing runnable com.google.common.util.concurrent.Futures$4@1ce5789e with executor MoreExecutors.directExecutor()
```

#### Code snippet
```
final ApiFuture<String> result = publisher.publish(pubsubMessage);
ApiFutures.addCallback(result, new ApiFutureCallback<String>() {
                public void onSuccess(String result) {
                }
                public void onFailure(Throwable ex) {
                }
            })
```

**Comment by chingor13** [comment]
@ayushj158 You should use the [version that provides the executor as the 3rd argument](https://googleapis.github.io/api-common-java/1.7.0/apidocs/com/google/api/core/ApiFutures.html#addCallback-com.google.api.core.ApiFuture-com.google.api.core.ApiFutureCallback-java.util.concurrent.Executor-) so you can more finely control how your futures are executed.

If you want to maintain the same behavior, use guava's [MoreExecutors#directExecutor](https://google.github.io/guava/releases/26.0-android/api/docs/com/google/common/util/concurrent/MoreExecutors.html#directExecutor--)

**Comment by ayushj158** [comment]
@chingor13 I understand that a new method is available with Executor argument. 
Lets say i create a new Executor with thread pool size 1 and pass it to future , does it mean my other callbacks will wait for this to complete and get queued , wont that cause performance impact  ? 

How did it use to work previously ?  I am trying to understand implement this with new Executor
