### ISSUE TITLE
Getting GCP available regions without doing a request

### ISSUE THREAD

**Issue by adriaferre** [googleapis/google-cloud-java#4234]
Hello,
I would like to know if there is a way to get all GCP available regions without doing a request to GCP.
I've been looking at the source code, and the only way that I found to retrieve all the regions is doing a request: https://github.com/googleapis/google-cloud-java/blob/969bbeef18f004fd51fd46c5def1ae5c644cae3c/google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/RegionClient.java#L272

So, maybe it's not possible 😓 

Do you thing this could be a cool feature? I've been working with others [cloud competitors SDK](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/regions/Regions.java) and they have this feature, and I think it's useful.

**Comment by andreamlin** [comment]
@adriaferre Thanks for submitting this feature request!

It does seem that we have a static set of Regions: https://cloud.google.com/compute/docs/regions-zones/.

Could we envision this as a static class with just a static list of Region objects?

**Comment by adriaferre** [comment]
Hello @andreamlin 
I've been digging more on GCP SDK and I figured out that there is a method to retrieve regions: https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/RegionClient.java#L272 but it requires and extra request...

Yes, definitely having a static list of Region objects will work perfectly for us :) This is what we are doing meanwhile we don't have this feature in the official GCP SDK.

**Comment by andreamlin** [comment]
Ok!
