### ISSUE TITLE
Convert BQ Table schema to Avro Schema

### ISSUE THREAD

**Issue by darrenhaken** [googleapis/google-cloud-java#4237]
I'm trying to convert a BigQuery schema into an Avro Schema, is this possible?

I want to do this so that in a DataFlow job I can write BQ data as Parquet on GCS. For some reason the Parquet writer expects an Avro schema:
 
#### Environment details

- OS: Mac
- Java version: 1.8
- google-cloud-java version(s): 1.5.6 

#### Code snippet

```java
Schema schema = bigQuery.getTable("", "")..getDefinition().getSchema();
```

```java
//Beam writer
FileIO.write().via(ParquetIO.sink(schema))
```

**Comment by ajaaym** [comment]
@darrenhaken There is no utility available to convert bigquery schema to avro schema, but you can do something like this.
```
List<Field> avroFields = new ArrayList();
for(Field bigqueryField : bigquerySchema.getFields()) {
Field avroField = new Schema.Field(
       bigqueryField.getName(),
       Schema.Create(ConvertToAvroType(bigquery.getType())),
      "doc",
      null);
avroFields.add(avroField);
}
Schema(Avro) avroSchema = Schema.createRecord(avroFields);
```

```
public Schema.Type convertToAvroType(LegacySQLTypeName bigqueryType) {
  for(Schema.Type avroType : Schema.Type.values()) {
    if(bigqueryType.name().startsWith(avroType.name()) {
       return avroType;
   }
 }
   return null;
}
```

**Comment by ajaaym** [comment]
closing this issue. Please feel free to reopen if needed.
