### ISSUE TITLE
 "Maven Central" badge shows old version

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/google-cloud-java#4241]
The "Maven Central" badge in the main README shows version `v0.47.0-alpha` as the latest version of google-cloud-java because it is based on the `google-cloud` artifact which was deprecated and no longer exists. The badge should be changed to look up a different version (since the latest is now v0.74.0).

**Comment by chingor13** [comment]
Perhaps a single maven badge no longer makes sense and we should instead put a badge next to each API listed below (corresponding to the google-cloud-X version).

**Comment by garrettjonesgoogle** [comment]
If this is going to be retained, I would suggest using the version of `google-cloud-bom`.

**Comment by sduskis** [comment]
This was fixed by #4322
