### ISSUE TITLE
In 'google-cloud-storage', Allow passing data size to Storage.create

### ISSUE THREAD

**Issue by PadrePadrone** [googleapis/google-cloud-java#4273]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

#### Environment details

- OS:
- Java version:
- google-cloud-java version(s):

#### Steps to reproduce

1. ?
2. ?

#### Stacktrace

```
Any relevant stacktrace here.
```

#### Code snippet

```java
Any relevant code snippet to help reproduce the issue.
```

#### External references such as API reference guides used

- ?

#### Any additional information below

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by PadrePadrone** [comment]
Environment details
OS: Any
Java version: Any
google-cloud-java version(s): Current (1.56.0)

The 'create' method in the Storage interface, receives the data as a byte[] argument, and implicitly uses the array length as the data size.

We are using a pool of such arrays, all of the same size, however on every call to 'create' the actual data size is <= than the array length.
Current 'create' forces us to create a clone of the data array with the exact size. With thousands of object written, this memory used is significant significant.

Would be great if you could add a version of create with array length and offset:
    Blob create(BlobInfo var1, byte[] var2, **int offset, int len,** Storage.BlobTargetOption... var3);

**Comment by frankyn** [comment]
@andrey-qlogic I'm looking over what @PadrePadrone stated in their request.

> Current 'create' forces us to create a clone of the data array with the exact size. With thousands of object written, this memory used is significant.

Isn't this technically what #4273 is adding to the library, but instead hiding it from the developer? 

@PadrePadrone could you comment if change #4273 will solve your issue?
