### ISSUE TITLE
Support Java11 without warnings

### ISSUE THREAD

**Issue by ludoch** [googleapis/google-cloud-java#4275]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

When using the GA Open JDK 11 (Soon to be used widely, including in Google internal and external products, I see some warnings.

For example, a Cloud Datastore sample app emits this warning:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/ludo/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

So it seems that at least the protobuf internal dependency is a bit obsolete.

**Comment by sduskis** [comment]
#2545 discusses this. protobuf-java-3.6.1.jar is a dependency of grpc, so there isn't much we can do about it in this repository.

**Comment by sduskis** [comment]
The pressure doesn't seem actionable.

**Comment by sduskis** [comment]
The right people are looking at the issue at protocolbuffers/protobuf#3781.  There's nothing we can do in this repository, and the right people are looking at it.  Please feel free to follow up on protocolbuffers/protobuf#3781.

**Comment by mikessoldier** [comment]
As stated in [#3781](https://github.com/protocolbuffers/protobuf/issues/3781) there the error should be fixed in the 3.7.1 version, but you're still using the 3.6.1 version : `com.google.protobuf:protobuf-java-util:3.6.1`.
Any ETA for this?
