### ISSUE TITLE
Firestore / io.grpc generates memory leaks stopping/undeploying a webapp on Glassfish/Payara

### ISSUE THREAD

**Issue by skonx** [googleapis/google-cloud-java#4296]
**I've already opened an issue** on [firebase-admin-java](https://github.com/firebase/firebase-admin-java/issues/237) describing the problem and searching the issue on github I've found it could be linked with [io.grpc](https://github.com/netty/netty/issues/6891).

Undeploying a webapp on Glassfish or Payara, we've noticed many memory leaks in the logs.
We are observing the same behavior running on Spring 5.

> Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@7365d5a6]) and a value of type [io.grpc.Context] (value [io.grpc.Context@696d6a0e]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@18ba65d6]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@17a3c33f]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

There are many couple of errors as requests to Firestore...

It seems Firebase/Firestore is not well closed (and cleaned up) during undeployment. 
Many threads are brutally interrupted and the ThreadPool is not well managed...

**Could you please provide a patch or best practices closing Firestore running on a Java ee container?**

#### Environment details

- OS: Ubuntu 16.04 / MacOS | Payara 5.184 / Glassfish 5
- Java version: Oracle 1.8.0_191
- google-cloud-java version(s): firebase-admin-6.6.0

**Comment by skonx** [comment]
I've finally found a strack trace just after deploying the webapp : 

> Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@10f2363d]) and a value of type [io.grpc.Context] (value [io.grpc.Context@4058997c]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@faafa9c]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@3bf943c8]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@10f2363d]) and a value of type [io.grpc.Context] (value [io.grpc.Context@4058997c]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@faafa9c]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@3a3bd954]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@10f2363d]) and a value of type [io.grpc.Context] (value [io.grpc.Context@4058997c]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   The web application [] created a ThreadLocal with key of type [com.google.api.client.util.escape.Platform$1] (value [com.google.api.client.util.escape.Platform$1@3eac2416]) and a value of type [char[]] (value [[C@668a5745]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@faafa9c]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@179caf5f]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@10f2363d]) and a value of type [io.grpc.Context] (value [io.grpc.Context@4058997c]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   The web application [] created a ThreadLocal with key of type [io.grpc.protobuf.lite.ProtoLiteUtils$1] (value [io.grpc.protobuf.lite.ProtoLiteUtils$1@73092581]) and a value of type [java.lang.ref.WeakReference] (value [java.lang.ref.WeakReference@2c5a3362]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@faafa9c]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@18de69d3]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   Exception in thread "grpc-default-worker-ELG-1-3" 
Severe:   java.lang.IllegalStateException: This web container has not yet been started
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1548)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1505)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.freeChunk(PoolArena.java:293)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:443)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:413)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:405)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:262)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:253)
	at io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:226)
	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:450)
	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.onRemoval(PooledByteBufAllocator.java:426)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocal.remove(FastThreadLocal.java:269)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocal.removeAll(FastThreadLocal.java:68)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:32)
	at java.lang.Thread.run(Thread.java:748)

**Comment by skonx** [comment]
anybody?

**Comment by ajaaym** [comment]
@skonx 

As described [here](https://github.com/netty/netty/issues/6891#issuecomment-453823354) below code properly shutdown the client.

```
firestore.close();
LockSupport.parkNanos(2_000_000_000); // ideally there await termination in client.
InternalThreadLocalMap.destroy();
```

**Comment by skonx** [comment]
firestore.close(); ✅ 
InternalThreadLocalMap.destroy(); ✅ 
Will test LockSupport.parkNanos(2_000_000_000); soon. I'm running on a java ee container... impossible to wait, it will be bypassed.

**Comment by skonx** [comment]
Same error using `LockSupport.parkNanos(2_000_000_000);` : 

> Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@7549471b]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@6d33ce53]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by skonx** [comment]
@ajaaym I'm also following and contributing to the specified thread.

**Comment by ajaaym** [comment]
@skonx Closing this over here, since this is something related to netty and we can track there. Please feel free to reopen if you think otherwise.
