### ISSUE TITLE
Suggestion : Improvement of String.equals("xxx")

### ISSUE THREAD

**Issue by o0lwj0o** [googleapis/google-cloud-java#4320]
Hi,
I have found some usage of “String.equals("xxx")” in this project.

When using string.equals("a") ，it will get nullpointexception if string ==null.
The problem can be fixed by repalced with "a".equals(string) or Objects.equals(string,"a").

Detail websites and lines are listed below

77 80 83   86 89 92 95 98 101 104 | https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-compute/src/main/java/com/google/cloud/compute/v1/InsertTargetTcpProxyHttpRequest.java

There are too many cases of "fieldName.equals("xxxxx")" .

Best regards

**Comment by javabrown** [comment]
This is similar issue as #4292, gapic java generation for discovery-based api's doesn't seems to be stable.

**Comment by andreamlin** [comment]
Hi @o0lwj0o (what a username!), thanks a lot for filing this bug. Indeed this is a problem, and it should be easily fixed.

**Comment by andreamlin** [comment]
This fix will be available in the next release of google-cloud-compute.

**Comment by andreamlin** [comment]
Update: this is now in master: https://github.com/googleapis/google-cloud-java/commit/f62e169b0fdb60a2cb1f427e6090f0496bfe8a50 and in the [0.78-alpha release](http://repo1.maven.org/maven2/com/google/cloud/google-cloud-clients/).

Thanks again for pointing this out @o0lwj0o !
