### ISSUE TITLE
Include a markdown CHANGELOG.md in the repo

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-java#4331]
Today we have a `CHANGES.md`, but it looks like that isn't being kept up to date.  The changes recorded in /releases look great - it would be nice to have these in `CHANGLOG.md` like the other languages as well though.

**Comment by grant** [comment]
I think this should be removed as this file is outdated. We can re-add the file when it is ready.

**Comment by chingor13** [comment]
The split repos have this with our newest release tooling
