### ISSUE TITLE
[Documentation] Pubsub emulator example code seems to use deprecated code

### ISSUE THREAD

**Issue by Qi77Qi** [googleapis/google-cloud-java#4347]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

* https://github.com/googleapis/google-cloud-java/blob/master/TESTING.md#testing-code-that-uses-pubsub pubsub emulator code example provided here looks outdated. Is there more recent code example?

#### Any additional information below

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by kolea2** [comment]
Hi @Qi77Qi, I believe the Pub/Sub emulator examples are up to date here: https://cloud.google.com/pubsub/docs/emulator. We can update that file to reflect this for future reference.
