### ISSUE TITLE
BQ - ListTableData ignores schema and/or `row.get(field)` returns wrong field

### ISSUE THREAD

**Issue by gbougeard** [googleapis/google-cloud-java#4349]
#### Environment details

- OS: MacOs + Linux
- Java version: >+ 1.8
- google-cloud-java version(s): 1.48 to 1.52 at least

#### Steps to reproduce

Since a few days we have a comportment change without having upgrade the google-cloud-bigquery lib (1.48 but I also reproduced with 1.52) : 
The snippets is quite simple because it comes from the examples https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/BigQuerySnippets.java#L523

When fetching a specific field, it returns another one.
I tracked the input schema and the schema related to the ` TableResult tableData` object returned by the `listTableData` function and they are exactly the same.
But when I print the `tableData.getValues`, fields are not ordered like in the schema.
I mean here is my schema : 
```
Field{name=batch_ts, type=INTEGER, mode=null, description=null}
Field{name=topic_and_region, type=STRING, mode=null, description=null}
Field{name=vid, type=STRING, mode=null, description=null}
Field{name=segments, type=RECORD, mode=REPEATED, description=null}
Field{name=country, type=STRING, mode=null, description=null}
Field{name=ts, type=TIMESTAMP, mode=null, description=null}
Field{name=batch_inc, type=INTEGER, mode=null, description=null}
```
and a `tableData.getValues` row : 
```
[FieldValue{attribute=PRIMITIVE, value=1547655841}, FieldValue{attribute=PRIMITIVE, value=1538344800.0}, FieldValue{attribute=REPEATED, value=[FieldValue{attribute=RECORD, value=[FieldValue{attribute=PRIMITIVE, value=1538344800}, FieldValue{attribute=PRIMITIVE, value=2}]}, FieldValue{attribute=RECORD, value=[FieldValue{attribute=PRIMITIVE, value=1538344800}, FieldValue{attribute=PRIMITIVE, value=3}]}, FieldValue{attribute=RECORD, value=[FieldValue{attribute=PRIMITIVE, value=1538344800}, FieldValue{attribute=PRIMITIVE, value=4}]}]}, FieldValue{attribute=PRIMITIVE, value=US}, FieldValue{attribute=PRIMITIVE, value=a-vid-C}, FieldValue{attribute=PRIMITIVE, value=euw1}, FieldValue{attribute=PRIMITIVE, value=null}]
```

So when I want to retrieve the `segments` field doing `row.get("segments").getRepeatedValue` I expect a List. But I have now a `java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List` because  `row.get("segments")` does not return the `segments` field but another one.

My guess is  `row.get("segments")` find in the schema for the `segment` field index 4 , then fetch the 4th field from the row but because the fields are not ordered the same way, it does not return the correct field.

Like I earlier said, we did not upgrade any lib nor code since at least 2 weeks. The table is programmatically recreated at each run (actually this code is part of UTs). 
We have this behaviour since less than a week. 
I think it's maybe more related to BQ engine rather than to the client lib.

**Comment by pmakani** [comment]
@gbougeard I am not able to reproduce this.

**Comment by gbougeard** [comment]
Hi @pmakani I opened a support ticket to the BQ team and they were able to reproduce it.
In the mean time it seems solved (at least yesterday we were not able to reproduce the issue)
