### ISSUE TITLE
[Compute] Inconsistency while using ResourceName.of() helpers

### ISSUE THREAD

**Issue by dtretyakov** [googleapis/google-cloud-java#4416]
- google-cloud-java version: 0.79-alpha

#### Steps to reproduce

The recent changes linked to #3604 have caused that Compute SDK usage has become more complicated. Let take a look on the following examples.

#### Code snippet

Before:

```kotlin
val machineType = ProjectZoneMachineTypeName.of(machineType, myProjectId, zone).toString()
val instance = Instance.newBuilder().setMachineType(machineType).build()
instanceClient.insertInstance(instance)
```

After #3604 `ResourceName.toString()` methods does not append `projects/` prefix anymore and as result the previous code fragment fails with exceptions like that because [they're required by REST APIs](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert):
```java
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid value for field 'resource.machineType': 'project-123/zones/europe-west3-b/machineTypes/n1-standard-1'. The URL is malformed."
   },
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'project-123/global/images/image-name'. The URL is malformed."
   }
  ],
  "code": 400,
  "message": "Invalid value for field 'resource.machineType': 'project-123/zones/europe-west3-b/machineTypes/n1-standard-1'. The URL is malformed."
 }
}
```

To resolve it for each `ResourceName` should be added `ResourceName.SERVICE_ADDRESS` prefix like that:
```kotlin
val machineType = ProjectZoneMachineTypeName.SERVICE_ADDRESS + 
    ProjectZoneMachineTypeName.of(machineType, myProjectId, zone).toString()
val instance = Instance.newBuilder().setMachineType(machineType).build()
instanceClient.insertInstance(instance)
```

**Comment by dtretyakov** [comment]
//cc andreamlin, ajaaym

**Comment by andreamlin** [comment]
Thanks for filing this issue @dtretyakov .
Looking at it.

**Comment by andreamlin** [comment]
Repro'd.
@dtretyakov also thanks for the proposed fix! I'll put that into the code generator.

**Comment by andreamlin** [comment]
Fix should be available in the next release.
