### ISSUE TITLE
Reintroduce *-format methods to clients that now have ResourceNames

### ISSUE THREAD

**Issue by andreamlin** [googleapis/google-cloud-java#4475]
APIs that introduce resource name message configurations to their GAPIC yaml will lose the `format-*` methods that format resource names. So as to not break clients, we have to reintroduce these methods.
APIs affected:
- [vision](https://github.com/googleapis/google-cloud-java/pull/4161)
- [iamcredentials](https://github.com/googleapis/google-cloud-java/pull/4430)
- [firestore](https://github.com/googleapis/google-cloud-java/pull/4469#issuecomment-461805423)

Steps to fix:
- [x] check-in gapic-generator [fix to reenable](https://github.com/googleapis/gapicgenerator/pull/2522) the formatting methods (DONE)~ edit: this turned out to be partially wrong
- [x] releasing artman v0.16.11 to pick up that fix ([DONE](https://hub.docker.com/r/googleapis/artman/tags/))
- [x] fix bug introduced by above PR, https://github.com/googleapis/gapic-generator/pull/2561
- [x] releasing artman v0.16.11 to pick up that fix
- [x] updating the GAPIC config for the affected APIs; this would be done internally and then bubble up to the github googleapis repo

Ideally we would deprecate these formatting functions, so in the next major version we wouldn't have them at all, since ResourceName classes are superior in static-type-checking and usability.

**Comment by andreamlin** [comment]
cc @sduskis @chingor13

**Comment by sduskis** [comment]
@andreamlin, can we close this issue?

**Comment by andreamlin** [comment]
Yay!

I'll open another issue that follows up to this to add documentation or code changes that would prevent this from happening in the future hopefully.
