### ISSUE TITLE
Google Cloud Java doesn't provide proper batch endpoints

### ISSUE THREAD

**Issue by JesseLovelace** [googleapis/google-cloud-java#4522]
[BatchRequest](https://github.com/googleapis/google-api-java-client/blob/2079c4c371c05c9a4c12ca1e4dda91ccbf3bb4c9/google-api-client/src/main/java/com/google/api/client/googleapis/batch/BatchRequest.java) points by default to the global batch endpoint, http://www.googleapis.com/batch. However, this endpoint is considered legacy and will stop working on March 25th. Instead users are supposed to use service specific endpoints, such as http://www.googleapis.com/batch/compute/v1.

The user can specify whatever endpoint they want, but currently Google Cloud Java does not provide a way for users to easily infer or generate the proper endpoint. We need to add this, and/or infer the endpoint from BatchRequest itself to stop the global endpoint from being used.

**Comment by sduskis** [comment]
First, I think we need information about the `batchPath` (see here as an example: https://www.googleapis.com/discovery/v1/apis/compute/v1/rest), somewhere meaningful.  After that we can do some inference in `BatchRequest`.

@ajaaym, FYI

**Comment by ajaaym** [comment]
@JesseLovelace @sduskis This is already being inferred based on discovery document in generated old service based client. 
For new gax based compute client this batch functionality doesn't exists yet.
