### ISSUE TITLE
Google Cloud Storage removeBucketIamMember() not executing

### ISSUE THREAD

**Issue by k8r3l** [googleapis/google-cloud-java#4530]
I implemented a `revoke access` function with the help of the snippet below. Everything runs fine, no exceptions are thrown and the function prints out that the identity has been removed. However, when I look at the Permissions page in my bucket, the user is still defined.

#### Environment details

- OS: macOS 10.14.3
- Java version: 8
- google-cloud-java version(s): google-cloud-storage; version-id 1.62.0

#### Steps to reproduce
From [snippets](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/BucketIamSnippets.java), execute

```java
removeBucketIamMember(String bucketName, Role role, Identity identity)
```

#### Any additional information below
- No errors in output
- Service account is integrated in application and has Storage Admin permission  @(verified)
- The users (identities) I try to remove do not have inherited roles
- Granting access works fine
- Currently circumvented with an embedded gsutil bash process, but client api side support is highly desired for security reasons...

**Comment by andrey-qlogic** [comment]
@k8r3l Can you probide a code shipped that you using. Did you check your role with getBindings().get(role) call ?

**Comment by k8r3l** [comment]
@andrey-qlogic
I checked with the `getBindings().get(role)` call and discovered it was `null`.

After some looking around, I discovered that I pass the value `Role.of("objectViewer")` as Role which is not the same as the `Role: roles/storage.objectViewer`.

It now works like a charm. Much appreciated for the help!!!
