### ISSUE TITLE
GCS URL signing takes longer for GCE instances not based in US

### ISSUE THREAD

**Issue by zulkifal** [googleapis/google-cloud-java#4557]
#### Environment details

- google-cloud-java/google-cloud-clients/google-cloud-storage/ version(s): 1.62.0

#### Steps to reproduce

1. Create a signed URL from a GCE instance, using default service account,  in us-central1
2. Create a signed URL from a GCE instance, using default service account, in asia-east2 - Takes 4-5X longer
3. Create a signed URL from a GCE instance, using default service account, in europe-west1 - Takes 4-5X longer

#### Any additional information below
- I suspect signblob[1] API that this gcs java library is using is deprecated and is not deployed globally
- When running on GCE and using default service account, the old API[2] is being invoked 

[1]: https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/signBlob
[2]: https://github.com/googleapis/google-auth-library-java/blob/44a5d33f8a9554192af1302d58f1dcab47cd2568/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java#L76

Thanks!

**Comment by sduskis** [comment]
@frankyn, any ideas would be greatly appreciated.

**Comment by zulkifal** [comment]
Could we use IAMCredentials[1] from googleapis/google-api-java-client-services[2] or is it better to patch ComputeEngineCredentials[3] in googleapis/google-auth-library-java[4]?

[1] - https://github.com/googleapis/google-api-java-client-services/blob/master/clients/1.28.0/google-api-services-iamcredentials/v1/com/google/api/services/iamcredentials/v1/IAMCredentials.java#L40
[2] - https://github.com/googleapis/google-api-java-client-services
[3] - https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java#L69
[4] - https://github.com/googleapis/google-auth-library-java

**Comment by frankyn** [comment]
@sduskis I'm not sure what may be happening here. I'll sent an email internally to the Cloud IAM team and will report back with any findings.

**Comment by frankyn** [comment]
@zulkifal and @sduskis I synced with the IAM team over email. The IAM SignBlob API has the limitation raised by this bug, being that the service is only available in the "US". On the otherhand IAMCredentials SignBlob API doesn't have this limitation and should serve "asia-east2" and "europe-west1". 

The recommendation is to use IAMCredentials. I think in this case it'd be better to update ComputeEngineCredentials in googleapis/google-auth-library-java. 

The one concern is the IAMCredentials API is still in Beta. I'd like to get checkoff from the @googleapis/yoshi-java team before moving forward with that change or if it should wait until the API is GA.

**Comment by zulkifal** [comment]
Generally public docs mention if an API is in Beta. There seems to be no such warning in this instance: https://cloud.google.com/iam/credentials/reference/rest/v1/projects.serviceAccounts/signBlob

**Comment by frankyn** [comment]
Hi @zulkifal,

I spoke with the @googleapis/yoshi-java team and they agreed to move forward with the change. I sent a PR for review which updates the endpoint. 

We appreciate your patience!

**Comment by zulkifal** [comment]
Thanks for the update @frankyn. Appreciate the effort put into this.
Do we have any ETA around maven releases of google-cloud-java and google-auth-library-java?

**Comment by frankyn** [comment]
Should now be fixed in the latest release, thank you @kolea2 and @JesseLovelace!
