### ISSUE TITLE
Upgrade google-api-client version from 1.27.0 to 1.28.0

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#4579]
Thanks for stopping by to let us know something could be better!

Please include as much information as possible:

#### Environment details

- OS: Linux
- Java version: Java 8
- google-cloud-java version(s): 1.63.0

#### Steps to reproduce

1. ?
2. ?

#### Stacktrace

```
$ mvn compile

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /usr/local/google/home/suztomo/cloud-opensource-java/example-problems/class-removed-from-google-http-client/src/main/java/com/google/cloud/tools/examples/HelloTransport.java:[31,50] cannot access com.google.api.client.http.apache.ApacheHttpTransport
  class file for com.google.api.client.http.apache.ApacheHttpTransport not found
```

#### Code snippet

```java
  public static void main(String[] arguments) throws GeneralSecurityException, IOException {
    GoogleApacheHttpTransport.newTrustedTransport();
    System.out.println("Hello Transport");
  }
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.google.cloud.tools.opensource</groupId>
  <artifactId>class-removed-from-google-http-client</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>class-removed-from-google-http-client</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-bigtable</artifactId>
      <version>0.81.0-alpha</version>
    </dependency>
    <dependency>
      <groupId>com.google.api-client</groupId>
      <artifactId>google-api-client</artifactId>
      <version>1.27.0</version>
    </dependency>

  </dependencies>
</project>
```

#### External references such as API reference guides used

- ?

#### Any additional information below

`Com.google.cloud:google-cloud-core-http:1.63.0` and the following Maven artifacts depend on `com.google.api-client:google-api-client:1.27.0`, which contains `com.google.api.client.googleapis.apache.GoogleApacheHttpTransport`. This class (version 1.27.0) does not work with `com.google.http-client:google-http-client:1.28.0` used by com.google.cloud:google-cloud-bigtable:0.81.0-alpha and other artifacts.

- com.google.cloud:google-cloud-core-http:1.63.0
- com.google.apis:google-api-services-bigquery:v2-rev20181104-1.27.0
- com.google.apis:google-api-services-compute:v1-rev20181022-1.27.0
- com.google.apis:google-api-services-dns:v1-rev20180813-1.27.0

By upgrading the google-api-client version to 1.28.0, the libraries will become more compatible in users' environments. I see `api-client.version` is [set 1.27.0 in pom.xml](https://github.com/googleapis/google-cloud-java/blob/c011130c0114ccdcde9bda60202f334722df331d/google-cloud-clients/pom.xml#L156)

![image](https://user-images.githubusercontent.com/28604/53429879-766c7e00-39bb-11e9-9a9a-8eeff2ea25f0.png)

**Comment by elharo** [comment]
Not sure, but I think google-cloud-java now depends on 1.28.0 and that's the cause of the issue. We either need to upgrade everything else or downgrade google-cloud-java to 1.2.7.0.

**Comment by sduskis** [comment]
I would suggest an explicit import on `com.google.http-client:google-http-client-parent` if you're using a class from that artifact.  We reduced the dependencies on `google-cloud-java` to only depend on artifacts that we use explicitly.

Also, I would suggest that you upgrade your dependency on `com.google.api-client:google-api-client`

**Comment by sduskis** [comment]
@elharo and I are meeting on this.  It looks like

**Comment by suztomo** [comment]
I see the version has been updated to `1.29.2`. Thank you. Closing this issue.

```
<api-client.version>1.29.2</api-client.version>
```
https://github.com/googleapis/google-cloud-java/blob/7ac29d0/google-cloud-clients/pom.xml#L157
