### ISSUE TITLE
Spanner performance questions/concerns

### ISSUE THREAD

**Issue by vineela-gampa** [googleapis/google-cloud-java#4585]
Thanks for stopping by to let us know something could be better!

1) Using array(Structs) 
we want to hear your inputs on is using array efficient for high perofrmance vs regular query ?
Recently i heard that array(struct) shouldnt be used and its memory intensive. Can you confirm ?In our scenario there is parent with <10 child objects. We are touching only 2 tables at any point of time. 

2)Tuning of spanner session: 
**we observed an issue where spanner is taking >10s to return data on a query when spanner cpu is above 75%. Is there recommendation to finetune to achieve better performance when we are under high load ?**

**Comment by sduskis** [comment]
@crwilcox, @snehashah16, any help would be welcome on this question.

**Comment by crwilcox** [comment]
Hi @vineela-gampa. Thanks for reaching out. If you could file a support ticket at https://cloud.google.com/support/ I think that would provide a better venue to work through issues you are having with your specific deployment/implementation issues.

Also, you reference that you have heard advice on how to best use spanner. Would you mind sharing any links, videos, etc that lead you to this?

Thanks!

**Comment by vineela-gampa** [comment]
Hi @crwilcox its an advice from another team. There is no online source that validate that behaviour hence i reached out to you.
