### ISSUE TITLE
PubSub: Add undelivered messages metric

### ISSUE THREAD

**Issue by agolomoodysaada** [googleapis/google-cloud-java#4627]
**Is your feature request related to a problem? Please describe.**
I would like to access the number of undelivered messages metric directly from the client library. Currently it's only available via Stackdriver monitoring.

 **Describe the solution you'd like**
It seems like there are already some client metrics available below. Perhaps that's a good place to add the undelivered messages metric.
https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriberStats.java

 **Describe alternatives you've considered**
Perhaps there's a stackdriver client that could be used? However, it makes more sense to access it from the pubsub client directly.

**Comment by sduskis** [comment]
Are you looking for the information for just a single client?

**Comment by sduskis** [comment]
@agolomoodysaada, what's your use case for needing these statistics?  That will help us tailor a solution.

**Comment by agolomoodysaada** [comment]
Hey @sduskis , 

Our use case is for a client that exposes their pubsub topic to us with a service account. However they do not want to provide us access to their GCP  project for security reasons.

This puts us in an awkward situation where we can't really get alerted when we're behind on the pubsub topic. Or autoscale consumers for example. Having access to those metrics would allow us to do those operations without accessing the third-party's GCP project, Stackdriver, and so on.

**Comment by sduskis** [comment]
First, we'd definitely need to expose the stats in a single VM, as per PR #4688.  

We could theoretically integrate with [OpenCensus](https://opencensus.io/) which would allow you to quickly aggregate those statistics into your own Stackdriver project.  Would this type of integration be of interest?

**Comment by agolomoodysaada** [comment]
I want to make sure we're talking about the same thing. The PR #4688 is exposing `getTotalNackedMessages`. Is that the same `number_of_undelivered_messages` metric?
If yes, then that's exactly what we're after. 

We use Prometheus for monitoring, which I believe integrates with OpenCensus. Having access to this metric would allow us to expose this metric and autoscale our consumers accordingly.

**Comment by olavloite** [comment]
@agolomoodysaada The `getTotalNackedMessages()` method will return the number of messages that the subscriber has processed and for which it has returned a nack.

Am I correct in assuming that you are looking for the number of messages that the subscriber has received, but not yet processed and responded to? In the PR #4688 that would be the calculation `getTotalReceivedMessages() - getTotalAckedMessages() - getTotalNackedMessages`.

**Comment by agolomoodysaada** [comment]
Hey @olavloite , that's not what I'm interested in. I'm looking for the number of messages that were published but not yet consumed. This is the equivalent of the Kafka consumer lag metric.

**Comment by olavloite** [comment]
I'm afraid that that metric is not included in the statistics for the client, and I also don't see a way to get those into a Subscriber client. I've looked through the gRPC API of pubsub, and there is nothing there that could be used to fetch that metric.

**Comment by agolomoodysaada** [comment]
I understand @olavloite . Thanks for taking a look; that's the reasoning behind filing this issue.
Is there a way we can expose that metric via the gRPC API? Should this issue be filed in another repo?

**Comment by sduskis** [comment]
@agolomoodysaada, I don't think that there's a way around getting access to Stackdriver metrics on the project that owns the topic.

**Comment by agolomoodysaada** [comment]
In the kafka world, subscribers can get information about their offset on a specific topic on their own. Subscribers should own their offset, not topic owners. I understand if this is not available. And I was hoping that filing an issue here would allow the team to explore solutions for this. But it seems like the design is tied to stackdriver.

**Comment by sduskis** [comment]
@agolomoodysaada, that's correct.  Stackdriver is the only way to access the metrics.

This repository's issue tracker is for Java client related issues.  You can ask for a Pub/Sub feature from https://cloud.google.com/pubsub/docs/getting-support.  [Here's a link](https://issuetracker.google.com/issues?q=componentid:187173%20status:open) to the issue tracker that would be better suited for your request.

**Comment by agolomoodysaada** [comment]
Thanks. For those interested, here's my submitted issue: https://issuetracker.google.com/issues/129396362
