### ISSUE TITLE
BigQuery: schema will be null in QueryStatistics after job has executed

### ISSUE THREAD

**Issue by reik-wargaming** [googleapis/google-cloud-java#4655]
Using the Java SDK for BigQuery (google-cloud-bigquery), I can get a `Schema` instance from the `QueryStatistics`. For the same job id, this only works if the job has not executed (dry run). After I fetch the results from the query (no dry run), there won't be a `Schema` in the `QueryStatistics` anymore.

#### Environment details

1. google-cloud-bigquery
2. MacOS HighSierra
3. Java 8, Kotlin 1.3
4. google-cloud-java version(s): 1.55.0 

#### Steps to reproduce

  1. see code below

#### Code example

```kotlin
import com.google.auth.Credentials
import com.google.auth.oauth2.GoogleCredentials
import com.google.cloud.bigquery.*
import org.junit.jupiter.api.Test
import org.assertj.core.api.Assertions.assertThat
import java.io.FileInputStream

class BigQueryIssue() {

    @Test
    fun testIssue() {
        val credentials = credentials()
        val bq = BigQueryOptions.newBuilder()
            .setCredentials(credentials)
            .build()
            .service

        val query = "SELECT word, corpus FROM `bigquery-public-data.samples.shakespeare` LIMIT 1"

        // create job and extract schema from QueryStatistics
        val (_, createAndDrySchema) = schema(bigQuery = bq, query = query, dryRun = true)
        assertThat(createAndDrySchema).isNotNull // works before execution

        // get job and execute
        val (job, _) = schema(bigQuery = bq, query = query, dryRun = false)
        val tableResult = job.getQueryResults()
        assertThat(tableResult.totalRows).isEqualTo(1L)
        assertThat(tableResult.schema).isNotNull // schema is now in the TableResult

        // get job and extract schema from QueryStatistics
        val (_, getAndDrySchema) = schema(bigQuery = bq, query = query, dryRun = true)
        assertThat(getAndDrySchema).isNotNull // fails
    }

    private fun schema(bigQuery: BigQuery, query: String, dryRun: Boolean): Pair<Job, Schema?> {
        val queryJobConfiguration = QueryJobConfiguration.newBuilder(query)
            .setUseLegacySql(false)
            .setDryRun(dryRun)
            .build()

        val jobId = JobId.of("shakespeare-job-${query.hashCode()}")
        val jobInfo= JobInfo.newBuilder(queryJobConfiguration)
            .setJobId(jobId)
            .build()

        val job= bigQuery.getJob(jobInfo.jobId) ?: bigQuery.create(jobInfo)
        val queryJob = if (!dryRun) {
            job.waitFor()
        } else job

        val queryStatistics = queryJob.getStatistics<JobStatistics.QueryStatistics>()
        return Pair(queryJob, queryStatistics.schema)
    }

    private fun credentials(): Credentials {
        return // your credentials
    }
}
```

#### Any additional information below	

What are we doing: we have an application that allows users to run their queries in BigQuery using the JavaSDK. We need to extract the column names from the user query. The job id is based on the actual query (hash code). The problem arises if a user want to run a query that another user has already executed. 

One workaround, that I don't like, is to use a new unique job id every time. I'd rather tie the job id to the actual query.

**Comment by shollyman** [comment]
As you've noted, the schema field you're accessing via job querystatistics is only populated for dryrun queries using standard SQL, which is for validating output schema.  For executed queries, you want the schema from the destination table, which holds the result of the executed query.

Fortunately, the schema is present via `getQueryResults()` in your example.  You should access it via query statistics for dryrun, and via the getQueryResults for the real execution case.

Background:  The underlying `bigquery.jobs.getQueryResults` REST method merges both the job representation and the query result (table) representation into a single combined response.  If you instead needed to get schema using only a job's representation, you would need to use the destination table reference in the query statistics to fetch that table representation, which would then provide the schema.

Does this help?  This is a case where where a better name in the response would have likely helped, such as calling the validation schema dryRunSchema or similar.

**Comment by reik-wargaming** [comment]
@shollyman thanks for the clarification but the issue is, that even for dryRuns it fails to get the schema from the querystatistics after the query has been executed once. I am doing

- dry run
- execution
- dry run

In that order, the expectation is that I can get the schema via

- querystatistics
- queryresults
- querystatistics (not working)

**Comment by shollyman** [comment]
Let me know if I'm misunderstanding, but from the sample it looks like you're gettting the job info if it exists via getJob, otherwise executing.  Because you're using a consistent jobID you're fetching the job metadata from the executed query rather than running the dryrun again.

Dryrun query responses are not persisted in the job history, so you could simply not set the jobID for the dryrun case and I believe it would give you the behavior you want.

**Comment by shollyman** [comment]
Additionally, is it intentional that you only use query hash for the job ID determination?  It implies all queries are on static data where none of the data in the referenced tables ever change, absent some other refresh mechanism.

**Comment by reik-wargaming** [comment]
> but from the sample it looks like you're gettting the job info if it exists via getJob, otherwise executing

correct. we get the job if `getJob` returns it, otherwise we create a new one. in our application, the caller can either do a dry-run or execute a query. so yes, potentially `getJob` could return a job that has already executed and perform a dry-run. Is your suggestion to use a unique job id whenever we do dry-runs *but* use a deterministic job id when we execute?

> It implies all queries are on static data where non of the data in the referenced tables ever change

I haven't used big query that long. Can you elaborate? Yes we derive the job id from the query string using hashing. But the tables we are reading from are likely to change. From the docs, I understood that for the same job id, the result would be fetched from a result table (that is created automatically in our case). If the referenced tables (source data) change, that result table wouldn't be used but a new one would be created before execution.

**Comment by shollyman** [comment]
> Is your suggestion to use a unique job id whenever we do dry-runs but use a deterministic job id when we execute?

dryrun queries are for transient validation.  they ensure a query parses, and can resolve things like output schema and estimate query costs.

> Can you elaborate?

Typically, control of the jobID is leveraged for execution idempotency.  If there's anything like a transient network failure during the job insertion and you fail to get a structured job response from BigQuery, you can simply poll/re-insert using the same jobID to avoid duplicate work.  Its valuable for queries in general, but even more valuable for jobs that mutate data (DML queries, load jobs, etc).

The important concept:  jobIDs are persistent, unique within a project, and immutable once created.  You can't re-run an existing job using the same job ID.

If the intent is caching results for a single user, leveraging the default behavior is sufficient:  bigquery will detect cache hits and simply serve the previous results.  More background on cache mechanics here:
https://cloud.google.com/bigquery/docs/cached-results

If you're instead trying to build some form of multi-use cache mechanism in BQ, then you likely want to control the outputs IDs, not the execution IDs.  Use a hash of the query input to set the destination table ID.  With that, you can verify if the table exists for a given input and is sufficiently up-to-date, and serve the results directly.  If not, run the query to create/refresh the contents.  You can leverage things like TTLs to automatically expire data as it ages in this scenario as well.

**Comment by shollyman** [comment]
Hope this was helpful.  I'll go ahead and close this issue for now, but feel free to revisit if there's anything else.
