### ISSUE TITLE
Does it works with the Java native GraalVM? 

### ISSUE THREAD

**Issue by ludoch** [googleapis/google-cloud-java#4664]
Playing with the new native target for https://quarkus.io/
Samples work well on Google App Engine (Java11 alpha).
Did not try yet, but we need to validate if the Cloud Java APIs work well with the GraalVM target https://www.graalvm.org/

It is possible that GraalVM has some limitations related to code introspection and more (see https://github.com/oracle/graal/blob/master/substratevm/LIMITATIONS.md)
It would be nice to declare the Google Cloud Java APIs GraalVM ready, so that quarkusIO customers can use them in a supported manner.

**Comment by sduskis** [comment]
Step one is to make sure that grpc works well.

**Comment by ludoch** [comment]
https://twitter.com/haraldpehl/status/1103995414251032581

**Comment by sduskis** [comment]
@ludoch, thanks for the reference.  Is GraalVM also expected to work with gRPC?

**Comment by ludoch** [comment]
https://github.com/hpehl
That is the point of this bug/feature request... If issues we need to find a way to address them.

**Comment by sduskis** [comment]
@ludoch, has the gRPC team been involved with this yet?  If not, I'll ping someone on this thread.

**Comment by ludoch** [comment]
Pretty sure none, unless via hidden channels I am not aware of...

**Comment by sduskis** [comment]
@ludoch, perhaps it's better if you start a thread on https://github.com/grpc/grpc-java to maximize the chances that you'd find the right audience.

**Comment by ludoch** [comment]
Maybe Cloud Java is using 5% of gRPC, so maybe I would start first to run the Cloud Java tests with a graalVM target, and then start digging in the inner (hidden?) deps as we go, if we find issues.

**Comment by ludoch** [comment]
I see https://github.com/hpehl/quarkus-grpc-extension/blob/master/runtime/src/main/java/io/quarkus/grpc/runtime/graal/GrpcNettySubstitutions.java for example...

**Comment by ludoch** [comment]
https://github.com/quarkusio/quarkus/issues/820

**Comment by sduskis** [comment]
@ludoch, is there anything actionable for `google-cloud-java` at this moment?

**Comment by lesv** [comment]
This should be addressed.

**Comment by meredithslota** [comment]
Hi folks — just closing the loop here. This work is underway here: https://github.com/GoogleCloudPlatform/native-image-support-java and is now in "experimental" support. I think that this issue is therefore ok to close out. Let me know if I'm reading this wrong and we can reopen.
