### ISSUE TITLE
Add a client to google cloud document indexing and search

### ISSUE THREAD

**Issue by chayki** [googleapis/google-cloud-java#4678]
Request to add client for indexing documents and search.

**Comment by sduskis** [comment]
Does this help? https://github.com/googleapis/google-api-java-client-services/tree/master/clients/1.28.0/google-api-services-cloudsearch/v1

**Comment by sduskis** [comment]
@chayki, I'm going to close this.  Please reopen this issue or another issue if the information provided doesn't not answer your question.
