### ISSUE TITLE
Question: How can you use a custom SSL Socket Factory with a Cloud Pub/Sub Subscriber?

### ISSUE THREAD

**Issue by Dak0ta** [googleapis/google-cloud-java#4679]
We have a requirement to utilize a custom SSL Socket factory with Cloud Pub/Sub (that doesn't affect the entire JVM) - looking at the sample Subscriber build() examples how would you set a custom provider?

And will it be a org.apache.commons.httpclient.protocol.SecureProtocolSocketFactory or something different?

**Comment by sduskis** [comment]
Can you please give a bit more information about why you want to set an SSL Socket Factory?  

For context, there are two different places where SSL is configured:

1. for getting a credentials token
2. for the runtime behavior of the subscriber that's controlled by grpc.

For the second, here's a reference of what you would have to work with: https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L201

**Comment by sduskis** [comment]
@Dak0ta, can you please provide more information about what you're looking for?  (Please see my previous comment for more details)

**Comment by Dak0ta** [comment]
Hi @sduskis - there are many reasons why an end user might not want to use the default socket factory set on the current JVM. Often people want to get around security and make things less strict but in this instance we have a more configurable and flexible socket factory than the currently set default available and want to utilize it but not change the setting JVM wide.

Thanks for the info on where to start (NettyChannelBuilder and Credentials) - we can close this out for now and I'll re-open later if needed!

**Comment by s-bir** [comment]
> Hi @sduskis - there are many reasons why an end user might not want to use the default socket factory set on the current JVM. Often people want to get around security and make things less strict but in this instance we have a more configurable and flexible socket factory than the currently set default available and want to utilize it but not change the setting JVM wide.
> 
> Thanks for the info on where to start (NettyChannelBuilder and Credentials) - we can close this out for now and I'll re-open later if needed!

I also had this problem and an easier way to add a secure socket factory would be very welcome. I worked around this as well but an easier solution would be very useful. The MQTT api supports this with a single call.
