### ISSUE TITLE
cloud KMS violates semver

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-java#4681]
Note: This client is a work-in-progress, and may occasionally make backwards-incompatible changes.

and yet it is 1.1.0

**Comment by sduskis** [comment]
The client is completely generated.  It would be backwards incompatible if either the generator or the proto files change in a non-backwards compatible way.  Do you have specific instances where it was not backwards compatible?  That will help us figure out the root cause.

**Comment by sduskis** [comment]
@elharo, can you please give us more information about the problem?

**Comment by elharo** [comment]
I don't know that it is incompatible. My concern is that the docs say "Note: This client is a work-in-progress, and may occasionally make backwards-incompatible changes." and yet the version number is 1.1.0 which is a violation of semantic versioning. If it is stable, then a 1.1.0 version is appropriate. However we should remove the notes from  google-cloud-java/google-cloud-clients/google-cloud-kms/README.md that say

"Note: This client is a work-in-progress, and may occasionally make backwards-incompatible changes."

and 

"It is currently in major version zero (0.y.z), which means that anything may change at any time and the public API should not be considered stable."
