### ISSUE TITLE
Any examples demonstrating posting Java objects to PubSub and reading them in DataFlow

### ISSUE THREAD

**Issue by KishoreNamala** [googleapis/google-cloud-java#4711]
I'm looking for some code examples on writing Java objects to PubSub and retrieving them in DataFlow.

**Comment by sduskis** [comment]
Unofrtunately, this repository deals with Pub/Sub, but not Dataflow / Apache Beam related.  A general web search might get you what you need.

**Comment by KishoreNamala** [comment]
I think I found what I needed. Thank you

**Comment by KishoreNamala** [comment]
@JustinBeckwith - do I need to do anything here ?

**Comment by JustinBeckwith** [comment]
No action needed - apologies for the noise!
