### ISSUE TITLE
Make FakeStorageRpc class public for more flexible StorageOption settings

### ISSUE THREAD

**Issue by bricejlin** [googleapis/google-cloud-java#4739]
Hi!

I was wondering if we could expose the `FakeStorageRpc` class for customizable StorageOption builds. `LocalStorageHelper` as it stands doesn't allow for me to pass in custom credentials. Since my app uses signed urls, I need to pass in a `ServiceAccountCredentials` type credential when instantiating my test `Storage` impl.

Ex:
```java
Storage storage = StorageOptions.newBuilder().setProjectId("dummy-project-for-testing")
          .setCredentials(ServiceAccountCredentials.newBuilder().build())
          .setServiceRpcFactory(options -> new FakeStorageRpc(false)).build();
```

Thanks,

Brice

**Comment by ajaaym** [comment]
@bricejlin you can set ```GOOGLE_APPLICATION_CREDENTIALS``` env variable to service account credential file that you want to use.

**Comment by bricejlin** [comment]
@ajaaym I don’t want to provide a valid service account json for testing. I want to be able to mock it.

**Comment by ajaaym** [comment]
@bricejlin In that case you can just directly mock ```StorageRpc```. Also can you please provide more detail exactly what you want to test?

**Comment by bricejlin** [comment]
@ajaaym FakeStorageRpc gives me an in-memory impl that I want but i just want the ability to pass in mock creds so it can sign urls as well.

I have a service that provides signed gcs urls via storage.signurl. For integration testing I’d like to provide an in-memory storage impl that can also sign urls, but I want to pass in a stub service account credential

**Comment by ajaaym** [comment]
@bricejlin You dont need StorageRpc for that, you just need storage. You can do that as below.

Options 1 use stubbed ServiceCredential while building service
```
    Storage storage =
        StorageOptions.getDefaultInstance().newBuilder().setCredentials(<Stubbed Service Credential>).build().getService();
    storage.signUrl(<BlobInfo>, 2000, TimeUnit.SECONDS);
```

Option 2 pass stubbed ServiceCredential while calling sign url

```
Storage storage = StorageOptions.getDefaultInstance().getService();
storage.signUrl(<BlobInfo>, 2000, TimeUnit.SECONDS, SignUrlOption.signWith(<Stubbed Service Credential>));
```

**Comment by bricejlin** [comment]
Thanks @ajaaym. With the first option, will that not call the real storage / gcs?

I’m doing option 2 right now actually, but I’d like to pass the creds into storage first to avoid mocking two things (storage/creds) into multiple places.

**Comment by ajaaym** [comment]
@bricejlin signUrl doesnt call any real storage rpcs.

**Comment by bricejlin** [comment]
@ajaaym right, but id also like to use the storage impl during testing for read/writes, which is why I'm relying on LocalStorageHelper

**Comment by ajaaym** [comment]
@bricejlin normally you wouldnt need to use LocalStorageHelper unless you want to test the library code as part of your application. Your application should stub Storage for unit test or for integration test it should use either emulator or actual gcp.

**Comment by bricejlin** [comment]
@ajaaym i see. So LSH was not meant to be used publicly for non lib code? I’m using it as an emulator for my integration tests, which for the supported methods work. Could we consider extending LSH to allow users to add custom StorageOptions? 

And also do you mean there is another emulator I can use?

**Comment by ajaaym** [comment]
@bricejlin yes LocalStorageHelper is not meant to be used publicly. However you can copy that code in your application and use it. There is no storage emulator as of now for google cloud storage.

**Comment by mfaghloumi** [comment]
@ajaaym It does not say so in the documentation : https://github.com/googleapis/google-cloud-java/blob/master/TESTING.md#testing-code-that-uses-storage
