### ISSUE TITLE
Outdated PMD config

### ISSUE THREAD

**Issue by derekm** [googleapis/google-cloud-java#4751]
The packaged PMD configuration file produces tons of Warnings on the latest versions of PMD and will cause outright failures in the upcoming PMD 7.0 release.

I have produced an updated version of the PMD config file.

See also: https://github.com/google/styleguide/issues/321#issuecomment-476400843

**Comment by JoeAlamo** [comment]
Do you have an example of your PMD ruleset anywhere? I couldn't find an associated MR - I'm not part of this repo but it'd be great to have an example of an up to date ruleset.

**Comment by chingor13** [comment]
We are using [`google-java-format`](https://github.com/google/google-java-format) via [coveo/fmt-maven-plugin](https://github.com/coveo/fmt-maven-plugin) for validating code style. We will remove this outdated file.
