### ISSUE TITLE
Logback Appender for Google Cloud Logging creates a lot of threads

### ISSUE THREAD

**Issue by SebastianStehle** [googleapis/google-cloud-java#4752]
#### Environment details

1. google-cloud-logging-logback
2. OS type and version: Docker
3. Java version: 1.8
4. google-cloud-java version(s): 0.79.0-alpha

Hi,
we use the logback Appender for Google Cloud Logging to connect the logging of our externally hosted Java application with stackdriver.

Today we had a network problem, the connection to stackdriver timed out several times. After this happened everything slowed down until it finally stopped working. I think that there might be a deadlock somewhere. We created the thread-dump and have seen a lot of which looks suspicous but without a deadlock.

I have uploaded the file: https://www.dropbox.com/s/178tvikwvrwox2s/threadDump.tdump?dl=0 

or 

[threadDump.zip](https://github.com/googleapis/google-cloud-java/files/3014259/threadDump.zip)

I am not sure if is a deadlock but I think under no circumstance should the log affect the main application that much.

**Comment by ajaaym** [comment]
@SebastianStehle Looks like at time of threaddump also there was some network error and rpcs were retrying. Can you please share full repro?

**Comment by SebastianStehle** [comment]
Yes, as I said "Today we had a network problem, the connection to stackdriver timed out several times."

Unfortunately I have no repro yet, i am thinking that I will move the whole logging system to a separate process.

**Comment by codyoss** [comment]
@SebastianStehle  would you say this is the same or similar to #4556? To me it sounds the same and if so I would like to close this, and move all the conversation there.

**Comment by SebastianStehle** [comment]
Yes, very likely.
