### ISSUE TITLE
google-cloud-speech should be promoted to GA

### ISSUE THREAD

**Issue by garrettjonesgoogle** [googleapis/google-cloud-java#4915]
google-cloud-speech is Beta, and has been for a while, so it should be promoted to GA. It was Beta because the surfaces for LRO and Bidi streaming weresn't stable yet, but those are now stable.

**Comment by garrettjonesgoogle** [comment]
Well, technically LRO & Bidi streaming still have `@BetaApi`, but I have filed an issue to remove that: https://github.com/googleapis/gax-java/issues/702

**Comment by kolea2** [comment]
👍 I'm currently working on this.
