### ISSUE TITLE
TextToSpeech API not responding or Unavailable

### ISSUE THREAD

**Issue by Shadat-tonmoy** [googleapis/google-cloud-java#4922]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-java/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version: Ubunt 18.04
3. Java version: 1.8
4. google-cloud-java version(s): 0.87.0 - Beta

#### Steps to reproduce

  1. I tried to integrate cloud text to speech api in an android application. But when I called the textToSpeechClient.synthesizeSpeech(input, voice,audioConfig) it does not sendback any response. After a while it  returns com.google.api.gax.rpc.UnavailableException which is according to documentation Exception thrown when the service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff. Is the service currently unavailable?
  2.I tried to test the service from this  (https://cloud.google.com/text-to-speech/) link also. Here I did not got any response though!!!

#### Code example

public void testAPI() {
        try {
            
            Log.e("Input","Will Build");
            TextToSpeechSettings textToSpeechSettings = TextToSpeechSettings.newBuilder()
                    .setCredentialsProvider(FixedCredentialsProvider.create(GoogleCredentials.fromStream((activity.getAssets().open(Constants.CREDENTIAL_FILE)))))
                    .build();
            TextToSpeechClient textToSpeechClient = TextToSpeechClient.create(textToSpeechSettings);
            Log.e("Client","Built");
            // Set the text input to be synthesized
            SynthesisInput input = SynthesisInput.newBuilder()
                    .setText("Hello, World!")
                    .build();

            Log.e("Input","Built");

            // Build the voice request, select the language code ("en-US") and the ssml voice gender
            // ("neutral")
            VoiceSelectionParams voice = VoiceSelectionParams.newBuilder()
                    .setLanguageCode("en-US")
                    .setSsmlGender(SsmlVoiceGender.NEUTRAL)
                    .build();

            Log.e("Voice","Built");

            // Select the type of audio file you want returned
            AudioConfig audioConfig = AudioConfig.newBuilder()
                    .setAudioEncoding(AudioEncoding.MP3)
                    .build();

            Log.e("AudioConfig","Built");

            // Perform the text-to-speech request on the text input with the selected voice parameters and
            // audio file type

            SynthesizeSpeechResponse response = textToSpeechClient.synthesizeSpeech(input, voice,
                    audioConfig);

            Log.e("Response","Built");

            // Get the audio contents from the response
            ByteString audioContents = response.getAudioContent();

            Log.e("Audio",audioContents.toString());

            // Write the response to the output file.
            OutputStream out = new FileOutputStream("output.mp3");
            out.write(audioContents.toByteArray());

        } catch (Exception e) {
            Log.e("APIException", "Error Message "+e+"");
        }
    }

#### Stack trace

04-07 16:13:04.305 23905-24355/com.domain.appname E/Client: WIll  Built
04-07 16:13:04.305 23905-24355/com.domain.appname E/Client: Built
04-07 16:13:04.316 23905-24355/com.domain.appname E/Input: Built
04-07 16:13:04.322 23905-24355/com.domain.appname E/Voice: Built
04-07 16:13:04.331 23905-24355/com.domain.appname E/AudioConfig: Built
04-07 16:22:11.095 23905-24355/com.domain.appname E/APIException: Error Message com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata

#### External references such as API reference guides used	

- ?	

#### Any additional information below	

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by vernazza** [comment]
I have the same problem (on android). 
The problem appeared when I upgraded from 0.83.0-alpha to 0.87.0-Beta

**Comment by igordmv** [comment]
@Shadat-tonmoy have you fixed it?

**Comment by ajaaym** [comment]
@Shadat-tonmoy @vernazza Can you please provide full stack trace and also dependency tree?

**Comment by pmakani** [comment]
@Shadat-tonmoy @vernazza BTW I tested in desktop and android and its working fine. Can you please provide full repro with complete stack trace?

**Comment by Shadat-tonmoy** [comment]
> @Shadat-tonmoy @vernazza BTW I tested in desktop and android and its working fine. Can you please provide full repro with complete stack trace?

Yes!!! Its working now....but I have a question...as per the documentation it is still in the beta stage...that means it may be down at any time (for development purposes) can anyone tell me when it will be available in production release (from beta)...thanks

**Comment by ajaaym** [comment]
@Shadat-tonmoy 

>can anyone tell me when it will be available in production release (from beta)...thanks
Can you contact google support for this? 

Closing this issue for now. Please feel free to reopen.

**Comment by jhonatanstarley** [comment]
I recently had the same problem. But in the case that we had several service servers, we were pointing to the wrong endPoint, and that was generating this error. I tested manuals until I found the right server host where the Google TTS service was installed.
