### ISSUE TITLE
Firestore/Pubsub Dependency Issues

### ISSUE THREAD

**Issue by twang-cs** [googleapis/google-cloud-java#4925]
#### Description

I found an issue dealing with the dependency manager for the Google Cloud API. I started working with Firestore recently, and I was using this documentation to get started: https://firebase.google.com/docs/firestore/quickstart. From there, I went to the API reference in the left navigation bar, and found this link for the javadocs (https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html?com/google/cloud/firestore/package-summary.html). In the CollectionReference documentation in that link, I saw a `listDocuments` method which doesn't actually exist within my codebase when I imported the Admin SDK. 

However, I did some more digging and found this github link: https://github.com/googleapis/google-cloud-java, which gave me a dependency manager to use if there were versioning conflicts. This fixed my issue where my version of CollectionReference didn't have the `listDocuments` function. But as I moved along in my project, I tried pulling in Pubsub's maven dependency and got this issue: `Could not resolve dependencies for project: Failed to collect dependencies for <project_name>` (stack trace is below). 

After removing the dependency manager, the versioning issues resolved itself, but I once again had the version of the Firestore Admin SDK without the `listDocuments` function. This isn't an issue for me anymore, since I no longer require that function, but this build conflict confused me and took me awhile to fix. 

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version: OSX Mojave (10.14.2)
3. Java version: 1.8.0_151
4. google-cloud-java version(s): 1.66.0

#### Steps to reproduce

  1. Include the following tags in a pom.xml maven project: 
```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-bom</artifactId>
        <version>0.87.0-alpha</version>
        <type>pom</type>
        <scope>import</scope>
       </dependency>
     </dependencies>
  </dependencyManagement>

<dependencies>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-pubsub</artifactId>
            <version>1.66.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>6.8.0</version>
        </dependency>
....
```
  2. Run `mvn clean package`

#### Stack trace
```
[ERROR] Failed to execute goal on project <project_name>: Could not resolve dependencies for project <project_name>>: Failed to collect dependencies for <project>: Could not resolve version conflict among [com.google.cloud:google-cloud-pubsub:jar:1.66.0 -> com.google.cloud:google-cloud-core-grpc:jar:1.68.0 -> io.grpc:grpc-protobuf:jar:1.19.0 -> io.grpc:grpc-core:jar:1.19.0, com.google.cloud:google-cloud-pubsub:jar:1.66.0 -> com.google.cloud:google-cloud-core-grpc:jar:1.68.0 -> io.grpc:grpc-protobuf:jar:1.19.0 -> io.grpc:grpc-protobuf-lite:jar:1.19.0 -> io.grpc:grpc-core:jar:1.19.0, com.google.cloud:google-cloud-pubsub:jar:1.66.0 -> com.google.cloud:google-cloud-core-grpc:jar:1.68.0 -> io.grpc:grpc-netty-shaded:jar:1.19.0 -> io.grpc:grpc-core:jar:[1.19.0,1.19.0], com.google.cloud:google-cloud-pubsub:jar:1.66.0 -> com.google.cloud:google-cloud-core-grpc:jar:1.68.0 -> com.google.api:gax-grpc:jar:1.43.0 -> io.grpc:grpc-alts:jar:1.19.0 -> io.grpc:grpc-grpclb:jar:1.19.0 -> io.grpc:grpc-core:jar:[1.19.0,1.19.0], com.google.cloud:google-cloud-pubsub:jar:1.66.0 -> com.google.cloud:google-cloud-core-grpc:jar:1.68.0 -> com.google.api:gax-grpc:jar:1.43.0 -> io.grpc:grpc-alts:jar:1.19.0 -> io.grpc:grpc-core:jar:[1.19.0,1.19.0], com.google.cloud:google-cloud-pubsub:jar:1.66.0 -> io.grpc:grpc-stub:jar:1.18.0 -> io.grpc:grpc-core:jar:1.18.0, com.google.cloud:google-cloud-pubsub:jar:1.66.0 -> io.grpc:grpc-auth:jar:1.18.0 -> io.grpc:grpc-core:jar:[1.18.0,1.18.0], com.google.firebase:firebase-admin:jar:6.8.0 -> com.google.cloud:google-cloud-firestore:jar:0.86.0-beta -> io.opencensus:opencensus-contrib-grpc-util:jar:0.19.2 -> io.grpc:grpc-core:jar:1.18.0] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

#### External references such as API reference guides used	

- https://firebase.google.com/docs/firestore/quickstart
- https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html?com/google/cloud/firestore/package-summary.html
- https://github.com/googleapis/google-cloud-java
- https://cloud.google.com/pubsub/docs/quickstart-client-libraries

#### Additional Information

I don't think this issue is high priority, since I found a workaround (by simply not using the `listDocuments` function that I once needed), but it's something that did cause me a lot of confusion and I think could come up as an issue for someone else.

**Comment by sduskis** [comment]
I think that adding this will solve the problem:

```
      <dependency>
        <groupId>io.grpc/groupId>
        <artifactId>grpc-bom</artifactId>
        <version>1.19.0</version>
        <type>pom</type>
        <scope>import</scope>
       </dependency>
```
