### ISSUE TITLE
Please add example for real time recording and parsing from computer microphone

### ISSUE THREAD

**Issue by goxr3plus** [googleapis/google-cloud-java#4932]
I am talking about [google-cloud-speech](https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-speech)

Even being an experienced Java Developer i am struggling a lot with this repository ... there are not many examples on how to use it ... if not any at all .

Add examples for recording and providing speed to text from microphone embedded to the computer .

Like i have done this but it's not working properly and it's very slow : 

https://github.com/goxr3plus/java-google-speech-api/issues/4

Add more examples on how to use the library please.

**Comment by igordmv** [comment]
upvoted! I`ts very struggling.

**Comment by sduskis** [comment]
This repository is for client issues.  Samples are in another repository.  I duplicated this issue here: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/1457

**Comment by nnegrey** [comment]
Howdy! As noted by sduskis, we host all our samples in java-docs-samples!
Best resource for info however, is still on the Google Cloud Platform docs pages: https://cloud.google.com/speech-to-text/docs/
