### ISSUE TITLE
Spanner takes long on few calls

### ISSUE THREAD

**Issue by vineela-gampa** [googleapis/google-cloud-java#4974]
Hi Spanner team 

On few calls we observed spanner takes long to respond. 

I observed spanner takes quite long sometimes to respond. It doesnt happen always but on some requests reads on a table (which has 200 records ONLY) took >2s .Below attached tracing has that details

i dont see any CPU Spike on spanner ?Unable to figure out why only few calls have that issues. If you have any insights to share where to start looking would greatly help.

Calls which generally respond <100 ms sometimes takes >2000-3000ms sometimes, i have seen them >5000ms . we are unable to find the root cause. 

Min sessions : 30 , max sessions : 300 in our spanner configuratio. 

![image](https://user-images.githubusercontent.com/2513330/56328860-85171c00-6146-11e9-92f1-627041fda55f.png)

**Comment by sduskis** [comment]
This repository is maintained by a set of developers that know about the client-side more than the server side.  If you need Cloud Spanner support, I would suggest opening up a support ticket which will put you in contact with engineers that have access to monitoring information about your service.  You can see more about opening up a support ticket here: https://cloud.google.com/spanner/docs/getting-support
