### ISSUE TITLE
Listing bucket objects name within a bucket path

### ISSUE THREAD

**Issue by AndresUrregoAngel** [googleapis/google-cloud-java#5010]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
Hello I need to list the objects name within a specific bucket path, I have deployed my code in Java 1.8 and maven 3 , this one look like:

```
 public static void getGcsBucketObjects (String bucketpath){

        Storage storage = StorageOptions.getDefaultInstance().getService();
        Page<com.google.cloud.storage.Blob> blobs =
                storage.list("bucket",BlobListOption.currentDirectory(),
                BlobListOption.prefix("batchfiles/")
                );


        for (com.google.cloud.storage.Blob blob : blobs.getValues()) {

            System.out.print(blob.getName());
        }
    }

```

Which is bad is that the return of this method gives me in one shot the name of all my entire objects without any separate character , example:

`batchfiles/batchfiles/cadcurrency_no_headerbatchfiles/cadcurrency_no_header1batchfiles/cadcurrency_no_header2batchfiles/cadcurrency_no_header3batchfiles/cadcurrency_no_header4batchfiles/cadcurrency_no_header5`

This is so much terrible because I need something like:

* batchfiles/batchfiles/cadcurrency_no_header
* batchfiles/batchfiles/cadcurrency_no_header1
*batchfiles/batchfiles/cadcurrency_no_header2
.....

Picture you want to apply this to any bucket path then how to really easy iterate on the names to only catch the names????

thanks so much

**Comment by ajaaym** [comment]
@AndresUrregoAngel  did you try with println instead of print? like ```System.out.println(blob.getName());```?  You are already iterating on elements in a page so its returning each blob element separately.

**Comment by AndresUrregoAngel** [comment]
y bad this `println` versus `print` and event `printf` in Java kills me lol.
