### ISSUE TITLE
Vision API. Image annotation timeout to be ready to use out of the box.

### ISSUE THREAD

**Issue by evfimivs** [googleapis/google-cloud-java#5012]
**Issue description**
Presently users have to either build their own timeout by directly creating a GrpcImageAnnotatorStub with a customized ApiCallContext plugged into the ClientContext, or to modify an [existing example](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/video/cloud-client/src/main/java/com/example/video/Detect.java#L363-L368) to fit their needs for the image annotation, since the [built in timeout](https://github.com/googleapis/google-cloud-java/blob/c66160837bfc72dae3cb423049feb92a142c91db/google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ImageAnnotatorSettings.java#L51) setting doesn't stop the annotation

 **Describe the solution you'd like**
This feature request is to have a working timeout for image annotation that the users will be able to easily use with a minimal to none learning curve.

 **Additional context**
On this image, for example, the request completes in under 14 seconds, although the timeout 
set up using [this page](https://github.com/googleapis/google-cloud-java/blob/c66160837bfc72dae3cb423049feb92a142c91db/google-cloud-clients/google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ImageAnnotatorSettings.java#L51) was set to 1 second.

![image](https://user-images.githubusercontent.com/39626617/56699644-59ef7800-66c4-11e9-9162-5d9cb46f95f4.png)

**Comment by sduskis** [comment]
There was an internal thread about this.  We need to figure out how GAX works.  There's an interplay between `setInitialRpcTimeout` and `maxRpcTimeout`.  There needs to be a simple way to do timeouts.

**Comment by ajaaym** [comment]
@evfimivs The example link you provided is related to video intelligence, but output is related to vision. Are you using async api? Do you want to cancel the detection process if it doesnt complete after certain time?

**Comment by otourzan** [comment]
I think "setSimpleTimeoutNoRetries()" supposed to address this issue as it's just a simple timeout. I couldn't find a sample in official java-docs-samples repo, so referencing the sample I created for another issue [1].

Also it's likely [2] fixed the builtin timeout mentioned in the first comment.

[1] https://github.com/otourzan/java-docs-samples/blob/master/vision/cloud-client/src/main/java/com/example/vision/QuickstartSample.java#L51
[2] https://github.com/googleapis/gax-java/issues/711

**Comment by sduskis** [comment]
There was a fix to the timeout logic, as @otourzan mentioned.  Please use the latest version of the library, and retry your code with timeouts configured; it should work as expected.  If it doesn't, please reopen this issue, or open a new one.
