### ISSUE TITLE
Authentication in PubSub grpc java client library

### ISSUE THREAD

**Issue by ktandon-informatica-com** [googleapis/google-cloud-java#5014]
The sample I am trying out is to receive subscribed messages(see https://cloud.google.com/pubsub/docs/quickstart-client-libraries#receive_messages ).For authentication, I am seeing the library internally uses an instance of DefaultCredentialsProvider which works only if the "GOOGLE_APPLICATION_CREDENTIALS" is set as environment variable. Is there any other CredentialProvider that we can use in the sample as I dont want to pass the JSON File path but instead pass the private key as a string which is not possible with DefaultCredentialsProvider. The DefaultCredentialsProvider uses GoogleCredential class but this class doesnt have any methods to pass credentials as a string instead of a file. I have referred to this doc https://github.com/googleapis/google-cloud-java#authentication but here as well I didnt find anything useful.

In the image attached, I want inputs to any CredentialsProvider implementation which can be used here and not go with the default? 

![image](https://user-images.githubusercontent.com/37170038/56734838-87e6c200-6781-11e9-9545-dbfe344f9865.png)

**Comment by sduskis** [comment]
You should be able to create a credentials this way:

```java
ByteArrayInputStream inputStream = 
  new ByteArrayInputStream(jsonString.getBytes(StandardCharsets.UTF_8));
GoogleCredentials credentials = GoogleCredentials.fromStream(inputStream);
CredentialsProvider provider = FixedCredentialsProvider.create(credentials);
```

**Comment by kolea2** [comment]
Hi! Going to close this as a solution was provided, please feel free to reopen if there are any issues with this approach. Thanks!
