### ISSUE TITLE
Changing user-agent for Google IAM

### ISSUE THREAD

**Issue by ihsanhaikalz** [googleapis/google-cloud-java#5016]
Is it possible to change user-agent information for API calls to Google IAM when we instantiate it? My code is like this:

```
	public static Iam initIam() throws IOException, GeneralSecurityException {
		InputStream resourceAsStream = GoogleIAM.class.getClassLoader().getResourceAsStream("creds.txt");
		GoogleCredential credential = GoogleCredential.fromStream(resourceAsStream);

		httpTransport = GoogleNetHttpTransport.newTrustedTransport();

		if (credential.createScopedRequired()) {
			List<String> scopes = new ArrayList<>();
			// Enable full Cloud Platform scope.
			scopes.add(IamScopes.CLOUD_PLATFORM);
			credential = credential.createScoped(scopes);
		}

		// Create IAM API object associated with the authenticated transport.
		return new Iam.Builder(httpTransport, JSON_FACTORY, credential).setApplicationName("test").build();
	}

```

I saw that for Google Storage is possible using HeaderProvider like this:

```
		Map<String, String> m = ImmutableMap.<String, String>builder().put("user-agent", "my custom useragent").build();
		HeaderProvider headerProvider = FixedHeaderProvider.create(m);
```
but I couldn't find out how to use HeaderProvider in Google IAM. 

Any ideas?

**Comment by chingor13** [comment]
The `Iam.Builder` class is provided by the [`google-api-services-iam`](https://search.maven.org/search?q=a:google-api-services-iam) artifact and is not part of the repository.

To do this, you will want to use [`setHttpRequestInitializer`](https://googleapis.github.io/google-api-java-client/releases/1.25.0/javadoc/com/google/api/client/googleapis/services/json/AbstractGoogleJsonClient.Builder.html#setHttpRequestInitializer-com.google.api.client.http.HttpRequestInitializer-) on your builder and have your `HttpRequestInitializer` fetch and update the headers for the `HttpRequest`
