### ISSUE TITLE
Add support for Dataproc client for lifecycle management and autoscaling

### ISSUE THREAD

**Issue by lukeFalsina** [googleapis/google-cloud-java#5024]
Hello,

I am currently looking at the Dataproc autoscaling implementation and lifecycle management features described here:
https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/autoscaling
https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/scheduled-deletion

While the v1beta2 REST APIs already offers methods and resources for these functionalities, the current beta Java client does not support any of those configurations (e.g., there is no LifecycleConfig, and AutoscalingConfig), nor there is an AutoscalingController available to manage the autoscaling policies.

Would it be possible for you to regenerate/update the beta APIs of the Dataproc client so to support those features?

Thanks,
Luca

**Comment by chingor13** [comment]
Thanks for letting us know about this. We're working to find out why these beta endpoints are not being created in the client library.

**Comment by chingor13** [comment]
`LifecycleConfig` and `AutscalingConfig` are available under `com.google.cloud.dataproc.v1beta2` be sure that you are using the `com.google.cloud.dataproc.v1beta2` version of the Dataproc clients (like `AutoscalingPolicyServiceClient`)
