### ISSUE TITLE
Dependency conflicts in vision client

### ISSUE THREAD

**Issue by mcantrell** [googleapis/google-cloud-java#5121]
The vision client has quite a few dependency conflicts. Please see the attached pom and maven enforcer report.

[report.zip](https://github.com/googleapis/google-cloud-java/files/3157597/report.zip)

**Comment by sduskis** [comment]
You use `<rules><dependencyConvergence/></rules>`.  We can't guarantee complete convergence.
  We use `<requireUpperBoundDeps/>` (see [here](https://github.com/googleapis/google-cloud-java/blob/20d36e4dfa13dd43b5b041a196be78be2a8d79f9/google-cloud-clients/pom.xml#L530)).

Can you use upper bound deps instead of full convergence?

**Comment by mcantrell** [comment]
Ahh, I was not aware that was an option. There are much less errors:

```
Require upper bound dependencies error for com.google.errorprone:error_prone_annotations:2.2.0 paths to dependency are:
+-com.acme:vision-api-timeout:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-vision:1.72.0
    +-com.google.cloud:google-cloud-core:1.72.0
      +-com.google.guava:guava:27.1-android
        +-com.google.errorprone:error_prone_annotations:2.2.0
and
+-com.acme:vision-api-timeout:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-vision:1.72.0
    +-com.google.cloud:google-cloud-core:1.72.0
      +-com.google.protobuf:protobuf-java-util:3.7.1
        +-com.google.errorprone:error_prone_annotations:2.3.2
and
+-com.acme:vision-api-timeout:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-vision:1.72.0
    +-io.grpc:grpc-stub:1.19.0
      +-io.grpc:grpc-core:1.19.0
        +-com.google.errorprone:error_prone_annotations:2.2.0
```

I was troubleshooting some conflicts with the version of protobuf-java  in com.google.apis:google-api-services-compute and the com.google.cloud:google-cloud-vision when I noticed these. 

It turned out to be the google-http-client causing the conflict which I was able to override in my dependencyManagement. I thought these conflicts might be of interest. I'll go ahead and close this out. Thanks for the time to look at it.
