### ISSUE TITLE
Catching Listener Exceptions in long running Cloud PubSub Subscriber service

### ISSUE THREAD

**Issue by nsmanju01** [googleapis/google-cloud-java#5129]
I am trying to write a long running Subscriber service in Java. I have set up the Listeners to listen to any failures inside the Subscriber service. I am trying to make this fault tolerant and I do not quite understand few things, Below are my doubts/questions.

1. I have followed the basic setup shown here https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/SubscriberSnippets.java. Specifically, I have setup addListener as shown below.

As shown in the following code, initializeSubscriber acts a state variable which will determine if the Subscriber service should restart. Inside the while loop, this variable is continuously monitored to determine if the restart is required.

My question here is, 
1. How do I raise an exception inside Subscriber.Listener's failed method and capture it in the main while loop. I tried throwing a new Exception() in failed method and catching it in catch block inside while, However, I am unable to compile the code as it is a checked exception. 
2. As shown here, I use Java Executor thread to run the Listener. How do I handle the Listener failures ? Will I able to catch Listener failures under general Exception catch block as shown here ?
```  
try {
 boolean initializeSubscriber = true;
    while (true) {
        try {
           if (initializeSubscriber) { 
             createSingleThreadedSubscriber();
             addErrorListenerToSubscriber();
             subscriber.startAsync().awaitRunning();
             initializeSubscriber = false;
           }

          // Checks the status of subscriber service every minute
          Thread.sleep(60000);
 
        } catch (Exception ex) {
          LOGGER.error("Could not start the Subscriber service", ex);
          cleanupSubscriber();
          initializeSubscriber = true;
        }
    }
} catch (RuntimeException e) {
    
} finally {
    shutdown();
}
private void addErrorListenerToSubscriber() {
    subscriber.addListener(
      new Subscriber.Listener() {
          @Override
          public void failed(Subscriber.State from, Throwable failure) throws RuntimeException { 
            LOGGER.info("Subscriber reached a failed state due to " + failure.getMessage()
                + ",Restarting Subscriber service");
            initializeSubscriber = true; 
          }
      },
      Executors.newSingleThreadExecutor());
  }

  private void cleanupSubscriber() {

    try {
      if (subscriber != null) {
        subscriber.stopAsync().awaitTerminated();
      }
      if (!subscriptionListener.isShutdown()) {
        subscriptionListener.shutdown();
      }
    } catch (Exception ex) {
      LOGGER.error("Error in cleaning up Subscriber thread " + ex);
    }
  }


```

**Comment by sduskis** [comment]
It's difficult to figure out what your code is doing.  Is `initializeSubscriber` a class variable?

**Comment by ajaaym** [comment]
@nsmanju01 

you can create a subscriber like this for fault tolerant and when you want to stop shutdown executor provider.

```
  void createSubscriber(final String subscriptionName, final MessageReceiver receiver, ExecutorProvider executorProvider) {

    Subscriber subscriber =
        Subscriber.newBuilder(subscriptionName, receiver)
            .setExecutorProvider(executorProvider)
            .build();
    subscriber.addListener(
        new Subscriber.Listener() {
          @Override
          public void failed(Subscriber.State from, Throwable failure) throws RuntimeException {
            LOGGER.info(
                "Subscriber reached a failed state due to "
                    + failure.getMessage()
                    + ",Restarting Subscriber service");
            if(!executorProvider.getExecutor().isShutdown()) {
              createSubscriber(subscriptionName, receiver, executorProvider);  
            }
          }
        },
        Executors.newSingleThreadExecutor());
    subscriber.startAsync();
  }
```

**Comment by ajaaym** [comment]
closing this for now. Please feel free to reopen if this doesnt help.
