### ISSUE TITLE
CAA record support

### ISSUE THREAD

**Issue by msaifulhaq** [googleapis/google-cloud-java#5130]
Hi,

Latest library still doesn't support CAA record CRUD operations. Is there any plan to add CAA support in near future ?

Thanks!

**Comment by sduskis** [comment]
@msaifulhaq, which library are you referring to?

**Comment by msaifulhaq** [comment]
@sduskis I am referring https://mvnrepository.com/artifact/com.google.cloud/google-cloud-dns/0.90.0-alpha
