### ISSUE TITLE
Bigtable: root package docs are missing

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-java#5177]
Extracted from https://github.com/googleapis/google-cloud-java/pull/5071#issuecomment-490117286.

Cloud Bigtable has a package-info.java:
https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/package-info.java

But it's javadoc doesn't seem to be generated and returns a 404:
https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/index.html?com/google/cloud/bigtable/package-summary.html

**Comment by kolea2** [comment]
Was looking earlier - the problem is that there are no .java files in com.google.cloud.bigtable (just packages). Adding a "Test.java" to the directory created a package-summary.html file. I'm not sure if this is a javadoc bug, but in the meantime we can add two links to the README - one to point to the admin API javadoc, and one to point to the data API javadoc.

**Comment by igorbernstein2** [comment]
Looks like we can workaround it using an empty package protected file:
https://stackoverflow.com/questions/1138390/javadoc-for-package-info-java-only

**Comment by kolea2** [comment]
I'm not sure if I want to add an empty file to get the javadoc to generate the page. @chingor13 WDYT?

**Comment by chingor13** [comment]
I think the correct long-term solution is the reorganization of the javadocs by artifact (service). This link would link to the package index page for the google-cloud-bigquery artifact.

**Comment by igorbernstein** [comment]
But I would still like to have the documentation in https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/package-info.java to be published regardless of where the readme link points to
