### ISSUE TITLE
googleapis.dev may be blocking programmatic access

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-java#5179]
Still investigating but some integration tests have started failing because https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/bigquery/package-summary.html and similar seem unreachable (404) from my JUnit tests. I can load the same URLs in the browser without trouble.

**Comment by chingor13** [comment]
Is your configuration is pointing to the older googleapis.github.io page? To handle every redirect, we had to hijack our own 404 page on github-pages to do a javascript redirect to the new url. Thus, in the browser, it would look fine, but programatically it might fail.

**Comment by elharo** [comment]
That might well have something to do with it. Could you send a 301 instead?

**Comment by chingor13** [comment]
Unfortunately, we don't have control over the response codes returned from github-pages.
