### ISSUE TITLE
Spanner - How does the client library handle aborted commits?

### ISSUE THREAD

**Issue by dzou** [googleapis/google-cloud-java#5186]
In the Spanner [documentation for Commit()](
https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#google.spanner.v1.Spanner.Commit), it says:

>Commit might return an ABORTED error. This can occur at any time; commonly, the cause is conflicts with concurrent transactions. However, it can also happen for a variety of other reasons. If Commit returns ABORTED, the caller should re-attempt the transaction from the beginning, re-using the same session.

How does the Spanner client library handle this case? I found the [resetForRetry()](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionManagerImpl.java#L89) method; so it seems like the user must reattempt the statements that were run in the transaction from the beginning if the exception is thrown?

I was also curious - is it possible to build a feature in which the statements of a transaction are recorded and then reattempted if a commit is aborted? Or does this idea have pitfalls?

**Comment by olavloite** [comment]
Any read/write Cloud Spanner transaction may be aborted by the backend, and the client application / client library should take this into account **for all database calls on a read/write transaction** (that is: not only the commit may abort, but also any query or update statement). This means that every Cloud Spanner read/write transaction should be executed in a retry-loop that checks for an ABORTED exception.

The client library handles this internally if you use the `DatabaseClient#readWriteTransaction()` method. This method will return a `TransactionRunner`. The `TransactionRunner#run(Callable c)` method will run the transaction logic for you and retry the transaction automatically as many times as necessary.

The other option is to use the `DatabaseClient#transactionManager()` method. This method leaves the retry handling to the user. The transaction logic still needs to be placed in a retry loop, and you must call `TransactionManager#resetForRetry()` in case of an aborted transaction like this:

```java
long singerId = my_singer_id;
try (TransactionManager manager = dbClient.transactionManager()) {
  TransactionContext txn = manager.begin();
  while (true) {
    String column = "FirstName";
    Struct row = txn.readRow("Singers", Key.of(singerId), Collections.singleton(column));
    String name = row.getString(column);
    txn.buffer(
        Mutation.newUpdateBuilder("Singers").set(column).to(name.toUpperCase()).build());
     try {
      txn.executeUpdate(Statement.of("UPDATE Albums SET Title='foo' WHERE AlbumId=1"));
      manager.commit();
      break;
    } catch (AbortedException e) {
      Thread.sleep(e.getRetryDelayInMillis() / 1000);
      txn = manager.resetForRetry();
    }
  }
}
```

Recording all statements of a transaction and retrying all these statements could be possible, but still does not solve all problems. You would also have to keep track of the results that are returned by the database statements, as your transaction might have made decisions that are based on the data that were returned. These data may be different during the retry, and the decisions that the original transaction took could be invalid based on the new data. Consider the following pseudo transaction:

```
long currentBalance = execute("SELECT Balance FROM BankAccount WHERE Owner='some_owner'");
if(currentBalance > 1000) {
  execute("UPDATE BankAccount SET Balance=Balance - 1000 WHERE Owner='some_owner'");
  execute("UPDATE BankAccount SET Balance=Balance + 1000 WHERE Owner='some_other_owner'");
} else {
  throw Exception("not enough money in account");
}
commit();
```

If you would only record the statements that were executed during the transaction, and automatically retried these in case of an ABORTED exception without checking whether the result of the statements during the retry were equal to the original transaction, you could end up executing an invalid transaction.

**Comment by dzou** [comment]
Thank you for the clarification, this was very helpful.
