### ISSUE TITLE
maven dependency issues

### ISSUE THREAD

**Issue by rubensayshi** [googleapis/google-cloud-java#5224]
I can't imagine I'm the first to run into this, I do see some old issues that look related but not exactly.  
Maybe I'm just doing some maven stuff wrong, but it looks like a bug to me...

I'm trying to add `google-cloud-firestore` to my maven project, but I seem to end up in some dependency hell, specially in combination with `maven-enforcer-plugin`.

```
Require upper bound dependencies error for io.grpc:grpc-context:1.19.0 paths to dependency are:
+-dev.rubensayshi.com:gimme-firestore:0.0.0-BOOOOOOM
  +-com.google.cloud:google-cloud-firestore:1.5.0
    +-com.google.cloud:google-cloud-core-grpc:1.75.0
      +-io.grpc:grpc-context:1.19.0
and
+-dev.rubensayshi.com:gimme-firestore:0.0.0-BOOOOOOM
  +-com.google.cloud:google-cloud-firestore:1.5.0
    +-io.opencensus:opencensus-api:0.19.2
      +-io.grpc:grpc-context:1.18.0
and
+-dev.rubensayshi.com:gimme-firestore:0.0.0-BOOOOOOM
  +-io.grpc:grpc-protobuf:1.20.0
    +-io.grpc:grpc-core:1.20.0
      +-io.grpc:grpc-context:1.20.0
,
Require upper bound dependencies error for io.grpc:grpc-core:1.19.0 paths to dependency are:
+-dev.rubensayshi.com:gimme-firestore:0.0.0-BOOOOOOM
  +-io.grpc:grpc-netty-shaded:1.19.0
    +-io.grpc:grpc-core:1.19.0
and
+-dev.rubensayshi.com:gimme-firestore:0.0.0-BOOOOOOM
  +-io.grpc:grpc-protobuf:1.20.0
    +-io.grpc:grpc-core:1.20.0
and
+-dev.rubensayshi.com:gimme-firestore:0.0.0-BOOOOOOM
  +-io.grpc:grpc-stub:1.20.0
    +-io.grpc:grpc-core:1.20.0
and
+-dev.rubensayshi.com:gimme-firestore:0.0.0-BOOOOOOM
  +-com.google.cloud:google-cloud-firestore:1.5.0
    +-io.grpc:grpc-auth:1.19.0
      +-io.grpc:grpc-core:1.19.0
and
+-dev.rubensayshi.com:gimme-firestore:0.0.0-BOOOOOOM
  +-com.google.cloud:google-cloud-firestore:1.5.0
    +-io.opencensus:opencensus-contrib-grpc-util:0.19.2
      +-io.grpc:grpc-core:1.19.0
and
+-dev.rubensayshi.com:gimme-firestore:0.0.0-BOOOOOOM
  +-io.grpc:grpc-protobuf:1.20.0
    +-io.grpc:grpc-protobuf-lite:1.20.0
      +-io.grpc:grpc-core:1.20.0
and
+-dev.rubensayshi.com:gimme-firestore:0.0.0-BOOOOOOM
  +-com.google.cloud:google-cloud-firestore:1.5.0
    +-com.google.api:gax-grpc:1.44.0
      +-io.grpc:grpc-alts:1.19.0
        +-io.grpc:grpc-core:1.19.0
and
+-dev.rubensayshi.com:gimme-firestore:0.0.0-BOOOOOOM
  +-com.google.cloud:google-cloud-firestore:1.5.0
    +-com.google.api:gax-grpc:1.44.0
      +-io.grpc:grpc-alts:1.19.0
        +-io.grpc:grpc-grpclb:1.19.0
          +-io.grpc:grpc-core:1.19.0
```

If I look at the dependencies listed on mvnrepository.com as well I see that `com.google.cloud:google-cloud-firestore:1.5.0` requires:
 - `com.google.cloud:google-cloud-core-grpc:1.75.0`
 - `io.opencensus:opencensus-contrib-grpc-util:jar:0.19.2`
 - `com.google.api:gax-grpc:jar:1.44.0`

`com.google.cloud:google-cloud-core-grpc:1.75.0` requires:
 - a bunch of grpc packages, alll `1.19.0`, such as;
 - `io.grpc.grpc-auth:1.19.0`
 - `io.grpc.grpc-protobuf:1.19.0`

`io.opencensus:opencensus-contrib-grpc-util:jar:0.19.2` requires:
 - `io.grpc:grpc-core:jar:1.18.0`
as per https://mvnrepository.com/artifact/io.opencensus/opencensus-contrib-grpc-util/0.19.2

`com.google.api:gax-grpc:jar:1.44.0` and `com.google.cloud:google-cloud-core-grpc:1.75.0` requires:
 - `io.grpc:grpc-core:jar:1.19.0`
as per https://mvnrepository.com/artifact/com.google.api/gax-grpc/1.44.0

in https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/pom.xml#L168 it says in a comment "make sure to keep opencensus version in sync with grpc", but they don't appear to be, or am I completely missing something here?

in my attempts to reproduce it in isolation I created this pom.xml: https://gist.github.com/rubensayshi/6a49cbe442b0f053fb5b22d55c9d1d55

it fails, except if explicitly specify `io.grpc:grpc-core` (uncomment the commented dep), it actually works, which makes me extra confused >_>

**Comment by ajaaym** [comment]
@rubensayshi  why are you explicitly adding dependency for grpc? It would automatically include compatible version along with firestore, I tried your pom with firestore and it works fine without explicit dependency of grpc.

**Comment by rubensayshi** [comment]
well, mainly because I like being explicit ..

I actually "solved" it that as well locally so I could play around with firestore a bit,  

but the real question is, why does it allow installing with mixed dependencies when I don't specify it?  
that must mean either one of the packages is not getting the version it expects,  
it seems to work fine, but that's just "lucky".

**Comment by ajaaym** [comment]
@rubensayshi closing this for now. Please feel free to reopen or open new issue if you need further help.
