### ISSUE TITLE
TimeoutException Google Cloud Logging

### ISSUE THREAD

**Issue by Flakesz** [googleapis/google-cloud-java#5225]
Trying to use the Stackdriver Logging Client with the provided [example from](https://cloud.google.com/logging/docs/reference/libraries).
The severe log is initiating a flush which leads to:
```
Caused by: java.util.concurrent.TimeoutException: Waited 6 seconds for com.google.common.util.concurrent.CollectionFuture$ListFuture@77102b91[status=PENDING, info=[futures=[[com.google.api.core.ApiFutureToListenableFuture@45312be2]]]]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:470)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:92)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:68)
	at com.google.cloud.logging.LoggingImpl.flush(LoggingImpl.java:577)
```

Checked with the debugger that the projectId and credentials are correctly loaded (env vars + creds file) in the options passed to `com.google.cloud.logging.LoggingImpl `, which are exactly as expected. No firewall blocking the request. API is enabled in the Google Cloud Console. Made sure to create the service account with the Cloud Tools Intellij Plugin to ensure correct permissions.

Any ideas how to tackle this?

Info:
- com.google.cloud:google-cloud-logging:1.74.0
- OpenJDK 8
- Ubuntu 18.04

Thanks in advance

**Comment by ajaaym** [comment]
@Flakesz can you set logging level to FINEST and send the log?

**Comment by Flakesz** [comment]
Sure (stripped away the token parts) 
[finest.log](https://github.com/googleapis/google-cloud-java/files/3234098/finest.log)

**Comment by ajaaym** [comment]
@Flakesz Thanks for sending over log file. Can you also please share your pom.xml or gradle settings file?

**Comment by Flakesz** [comment]
There you go. Had to compress it as Github didn't like `.kts` files.
[build.gradle.kts.tar.gz](https://github.com/googleapis/google-cloud-java/files/3234262/build.gradle.kts.tar.gz)

**Comment by ajaaym** [comment]
@Flakesz thanks for sending over .kts file. I see that you also have grpc/google-api as explicit dependancy. Can you remove all grpc/google-api related dependancy and just keep ```compile("com.google.cloud:google-cloud-logging:1.74.0")``` . Also is there any log after " (logging.googleapis.com:443)] Entering READY statecom.google.api.client.http.HttpTransport: -------------- REQUEST  --------------"?

**Comment by Flakesz** [comment]
Well the grpc dependency is needed in the project for grpc services and the other google api dependencies like gmail are also required. But I found the issue:  `com.google.protobuf:protobuf-java` was raised from 3.5.1 -> 3.7.1 due to other dependencies. forced now 3.5.1 across the board, which fixed the TimeoutException.

Thank you for your help :)

**Comment by sanjaypujare** [comment]
> But I found the issue: com.google.protobuf:protobuf-java was raised from 3.5.1 -> 3.7.1 due to other dependencies. forced now 3.5.1 across the board, which fixed the TimeoutException.

Not really a solution but a workaround. What that means is the cloud library won't work with protobuf-java version 3.7.1 (or later). Can we have a proper fix?
