### ISSUE TITLE
google cloud firestore not working in 32bit JVM because of grpc-netty-shaded-1.19.0.jar

### ISSUE THREAD

**Issue by siva461** [googleapis/google-cloud-java#5243]
google cloud firestore not working in 32bit JVM because of grpc-netty-shaded-1.19.0.jar

there's an issue with the grpc-netty-shaded jar which is used in firebase samples to make a quick start.

this netty jar is built for 64bit only and there's no support for 32bit.

is there any options to connect to firestore using 32bit JVM

tried with all versions of netty-tcnative and someother jar files of netty and grpc

InputStream serviceAccount = new FileInputStream("resource/java-firebase.json"); GoogleCredentials credentials = GoogleCredentials.fromStream(serviceAccount); FirebaseOptions options = new FirebaseOptions.Builder().setCredentials(credentials).build(); FirebaseApp.initializeApp(options);

this is should work in 32bit also

**Comment by ajaaym** [comment]
This is same as #5232. closing this
