### ISSUE TITLE
GCR support feature request

### ISSUE THREAD

**Issue by Dmitry1987** [googleapis/google-cloud-java#5420]
Hi, are there plans to add GCR support so it'll be possible to manage image tags, repositories, etc' related to container registry?

**Comment by chingor13** [comment]
I don't believe we have a custom REST or RPC API that provides what you're asking for with GCR. Most of those things can be done via the normal docker API.

If you'd like to file a feature request on the team to add an API, please go to the [main product issue tracker](https://cloud.google.com/support/docs/issue-trackers), find Container Registry, and file and issue there.
