### ISSUE TITLE
Split Snippets – 1 per File

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloud-java#5462]
Split snippets such that there is one snippet per file.
This will mitigate developers having issues around region tags not including imports.

Example Code:
https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/StorageSnippets.java

Bug:
b/117263623

**Comment by sduskis** [comment]
@grant, will changing the snippets now cause any problems to the docs?

**Comment by grant** [comment]
No. The docs should be including snippets at a git commit SHA.

**Comment by meredithslota** [comment]
Samples now live here as part of work by @JesseLovelace: https://github.com/googleapis/java-storage/pull/1258
