### ISSUE TITLE
PubSub Topics Retrieval Blocks Indefinitely When Not Authenticated

### ISSUE THREAD

**Issue by gtomassi** [googleapis/google-cloud-java#5465]
com.google.cloud.pubsub.v1.TopicAdminClient.listTopics blocks forever when gcloud credentials are invalid.

Occurred on local machine and when running on GKE, using com.google.cloud:google-cloud-pubsub:1.77.0

Recommended fix:
Exception should be thrown, at a minimum internal operations underneath listTopics should timeout after some reasonable time. Additionally, faulty credentials should be invalidated and exception should be thrown stating authentication issues.

To reproduce:
```java
    public static void main(String[] args) throws Exception {

        TopicAdminSettings topicAdminSettings = TopicAdminSettings.newBuilder().setCredentialsProvider(ComputeEngineCredentials::create).build();
        TopicAdminClient topicAdminClient = TopicAdminClient.create(topicAdminSettings);
        String projectName = ProjectName.of(ServiceOptions.getDefaultProjectId()).toString();
        System.out.println("BEFORE LIST TOPICS");
        topicAdminClient.listTopics(projectName); // Hangs forever
        System.out.println("AFTER LIST TOPICS -- never reaches");

    }

**Comment by ajaaym** [comment]
This is same as #3573 closing this and lets track over there.

**Comment by gtomassi** [comment]
@ajaaym 
Agreed, thank you.
