### ISSUE TITLE
UNAVAILABLE: HTTP/2 error code: NO_ERROR Received Goawaysession_timed_out

### ISSUE THREAD

**Issue by Amosss** [googleapis/google-cloud-java#5498]
Operating System version: Ubuntu
    Firebase SDK version: 6.8.1
    Firebase Product: Firestore

This is the callstack:
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERRORReceived Goawaysession_timed_out at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500) at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:479) at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76) at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62)

This is my lines of code that triggered this
ApiFuture future = db.collection(collection).document(doc).set(fsData, SetOptions.merge());
future.get();

This is working most of the time, it happened only twice so far so maybe it's something temporary but I have no idea what it is and how to overcome this.

Please advice
Thanks

**Comment by ajaaym** [comment]
@Amosss can you please add log level to FINEST and send it over?

**Comment by Amosss** [comment]
Not sure what do you mean by log level. I added the trace to my post. The line that threw the exception is com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500) 

The trace go back up to my part of the code which is a simple:
ApiFuture future = db.collection(collection).document(doc).set(fsData, SetOptions.merge());
future.get();

It works most of the time and the once or twice it didn't work, it was due to that error.

Looks like a temporary issue that was in a perfect timing with my request. Not something that can be reproducible to the exact details. I wonder maybe if you can add some more checks or retries in such cases.

**Comment by ajaaym** [comment]
@Amosss this rpc is not safely retriable, thats why automatic retry is not enable. Please see conversation in #4235. However you can add retries in application code if its safe to retry.

**Comment by Amosss** [comment]
Thanks but what do you consider "if its safe to retry"?

**Comment by ajaaym** [comment]
means from applications perspective, its ok for the operation to happen more than once without any side effects.

**Comment by Amosss** [comment]
Assuming the first one failed, there was never a "once" to have "more than" :-) Thanks for the tip. I guess I will need to add such fail safe to all my futures. I wish Marty Mcfly was here :)

**Comment by ajaaym** [comment]
@Amosss there can be case where operation is applied on server, but proxy might have sent UNAVAILABLE due to various reason, retrying in this case would cause more than once situation.
