### ISSUE TITLE
Cloud Storage: 400 Bad Request when uploading file - StorageException: Could not decompress request body

### ISSUE THREAD

**Issue by inewland53** [googleapis/google-cloud-java#5529]
#### Maven
<groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-storage</artifactId>
<version>1.74.0</version>

#### Code example

```java
storage.create(BlobInfo.newBuilder(bucketName, objPath).setContentType("application/octet-stream").build(), objStream);
```

#### Stack trace
```
Caused by: com.google.cloud.storage.StorageException: 400 Bad Request
Could not decompress request body.
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:227)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:308)
        at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:178)
```

#### Any additional information below	
This seems to only happen every so often on some objects. I'm using a multi-threaded system to upload as quickly as possible.
This doesn't seem to happen all the time, it seems intermittent. 

Is this a known issue?

**Comment by inewland53** [comment]
Bumping this...

Upgraded to the latest package version 1.79.0 and having the same issue.

It seems like the file store can't handle the workload being sent.

I doubled checked to make sure I was using a service account.

**Comment by JesseLovelace** [comment]
To clarify, do these failures succeed on retries with the same files?

**Comment by inewland53** [comment]
That is correct, the same files success after 1 (sometimes 2) retries.

**Comment by inewland53** [comment]
Bumping...

Any progress on duplicating/fixing this issue?

**Comment by inewland53** [comment]
I believe this issue was due to using the **storage.create** which takes in an InputStream. This method was deprecated since it was not resumable. The error was happening most likely due to the multi-threaded environment threads closing before the stream had completed.

I decided to use the byte[] version of the **storage.create** method instead and that seemed to have fixed it.
