### ISSUE TITLE
Spanner: Adjust timeouts for CreateDatabase and retries for other methods

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-java#5544]
As part of a recent change to GAPIC Configuration, timeouts and retries need to be updated. 

Ensure that the timeouts and retires specified in https://github.com/googleapis/googleapis/commit/cc233544aa39b8947c9b929819aeb08e2cb71feb#diff-4501db3e3507bcce8496c9aea2017d96 are reflected in this client library.

**Comment by olavloite** [comment]
These values are part of the generated gapic client and cannot (or should not) be changed manually. Instead, the gapic client should be re-generated (and I do not have the power to do so).

@kolea2 Is this something you could initiate?

**Comment by kolea2** [comment]
I'll assign to myself and take a look!

**Comment by kolea2** [comment]
@olavloite, #5523 will resolve the retry values (the PR was failing due to testing the default values which I've just fixed). Once merged, we still need to investigate the `timeout_millis` field, as it looks like that wasn't picked up automatically.

**Comment by olavloite** [comment]
> @olavloite, #5523 will resolve the retry values (the PR was failing due to testing the default values which I've just fixed). Once merged, we still need to investigate the `timeout_millis` field, as it looks like that wasn't picked up automatically.

What is the intention of the `timeout_millis` field? To set the total timeout for the call? Because as far as I can tell, that should be the field `total_timeout_millis`.

**Comment by crwilcox** [comment]
Java has constants controlling some of this at this time. It needs to use the configurations that are generated.

**Comment by kolea2** [comment]
@olavloite looks like .net has the same issue we do: https://github.com/googleapis/google-cloud-dotnet/issues/3165

**Comment by olavloite** [comment]
@crwilcox @kolea2 The constants are used in two places in the Java library:
* https://github.com/googleapis/google-cloud-java/blob/e3dd67e6fe84b705357e12c0799d3cc4170feb2a/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java#L920
* https://github.com/googleapis/google-cloud-java/blob/e3dd67e6fe84b705357e12c0799d3cc4170feb2a/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerRetryHelper.java#L39

(The latter is not literally using the constant, but I'll change that)

All other retries use the gapic configuration. I'll change the MIN_BACKOFF_MS value now from 1000 to 250 to conform with the gapic config.

The question is whether we want to change this from using a constant value to actually using a value from the gapic configuration as discussed here: https://github.com/googleapis/google-cloud-java/issues/5543#issuecomment-505444950
That way, this value could also dynamically change with the gapic config, but we would need to choose a config item to link it to.

**Comment by olavloite** [comment]
@crwilcox 

Regarding the high timeout value for CreateDatabase that is not picked up by the regen. I'm not very familiar with the gapic generator and corresponding config, but I noticed the following: 
* There is a retry configuration named `default` that is assigned to the `CreateDatabase` call.
* There are values defined for `initial_rpc_timeout_millis` and `total_timeout_millis` in the default retry config, but there is no value defined for `timeout_millis` in the default config.
* There is a specific retry configuration for the field `timeout_millis` for the `CreateDatabase` call. This field is seemingly not picked up by the generator.

Are you sure that it isn't one of the fields `initial_rpc_timeout_millis` or `total_timeout_millis` that should have been overridden in the configuration for the `CreateDatabase` call?

**Comment by hzyi-google** [comment]
It seems gapic-generator is ignoring the per-method retry definitions. I'll see if I can fix it.

**Comment by skuruppu** [comment]
I believe we have already adjusted the timeouts in [googleapis/spanner_gapic.yaml](https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/spanner_gapic.yaml) to what we want these to be. I'll close this issue and re-open if we need to make further adjustments to the timeouts and retries.
