### ISSUE TITLE
Spanner: Ensure client backoff is implemented to respect client configuration.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-java#5545]
There was an issue in the client library for python where requests to retry could occur without a proper retry object. In this case, rather than defaulting to an exponential backoff, we defaulted to immediate retry. Ensure that for this client library we respect the min, max, and multiplier as specified in the gapic configuration. 

Original Bug: https://github.com/googleapis/google-cloud-python/issues/7303

**Comment by olavloite** [comment]
The Java client library uses the gapic generated client for rpc's and the default Gax retry logic. This retry logic respects the gapic configuration. The user can however choose to change this configuration.

See `SpannerGaxRetryTest` for examples how a user can change the configuration, and also how the client library respects both the default settings and any custom settings the user may specify.

Any retry information in the returned error is however ignored by Gax and will not be used. Instead, it will always use the exponential retry logic.
