### ISSUE TITLE
FirestoreClient.getFirestore(firebaseApp) does not work with Firebase-Admin:6.8.1

### ISSUE THREAD

**Issue by AbhideepChakravarty** [googleapis/google-cloud-java#5548]
#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   Firestore
2. OS type and version: Windows 10 64bit
3. Java version: 1.8.0_211 JDK
4. google-cloud-java version(s): Attached in dependency tree file dep.txt
[dep.txt](https://github.com/googleapis/google-cloud-java/files/3317325/dep.txt)

#### Code example

 FirebaseApp firebaseApp = FirebaseApp.initializeApp(options);
 db = FirestoreClient.getFirestore(firebaseApp);   

If I comment the above line, everything works. Hence the problem is in Firestore, not in Firebase Admin API.

#### Stack trace
[logs.txt](https://github.com/googleapis/google-cloud-java/files/3317328/logs.txt)

#### What is needed
Can you guys please explain why "db = FirestoreClient.getFirestore(firebaseApp);" this line is not working? Which version of Guava you need? Why latest version of Guava is not working??

What should be done to get it fixed? I excluded firestore from firebase dependency and added 1.9.0 explicitly. If I dont do this, even then it does not work. Not sure whats wrong with Firestore API. Because of this issue I am not able to upgrade by firebase admin version and not able to implement few requirements. 

Last what worked was firebase-admin:6.0.0 with Guava 28.0-jre.  That time this exception was not coming, but I need to upgrade to 6.8.1. The moment I do, I am stuck because of firestore problem.

**Comment by chingor13** [comment]
Can you list out the dependencies that your application is pulling in? Without more information, it's hard to figure out what's causing the dependency issue.

**Comment by athakor** [comment]
@AbhideepChakravarty I have tried it with dependency that you have mention in dep.txt file. FirestoreClient.getFirestore(firebaseApp) working fine with latest version of guava and Firebase-Admin:6.8.1 below are the dependencies and code snippets.

**Dependency :**

     <dependencies>
        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>6.8.1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-firestore</artifactId>
            <version>1.9.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>28.0-jre</version>
            <scope>compile</scope>
        </dependency>
     </dependencies>

**code:**
 ```
      GoogleCredentials credentials = GoogleCredentials.getApplicationDefault();
      FirebaseOptions options=FirebaseOptions.builder().setCredentials(credentials).build();
      FirebaseApp firebaseApp = FirebaseApp.initializeApp(options);
      Firestore db = FirestoreClient.getFirestore(firebaseApp);
```

**Comment by AbhideepChakravarty** [comment]
I had to make changes in the webserver configuration. It was by default
giving preference to the guava it already had, than to the guava I was
putting. After doing that, it worked.
