### ISSUE TITLE
NullPointerException reading file from GCS bucket

### ISSUE THREAD

**Issue by turboT4** [googleapis/google-cloud-java#5560]
Following the official documentation I've been trying to read a sample file I stored within GCS, but so far the only thing I've got is a NullPointerException

```
InputStream sampleStream() {
    String bucketName = "sample";
    String fileName = "sample";

    log.info("Loading file from GCS [bucket: {}, key: {}]", bucketName, fileName);
    try {
        GcsInputChannel readChannel = gcsService().openReadChannel(new GcsFilename(bucketName, fileName), 0);
        return Channels.newInputStream(readChannel);
    } catch(Exception ex) {
        log.error("Error loading file...", ex);
    }
}

private GcsService gcsService() {
    return GcsServiceFactory
        .createGcsService(new RetryParams.Builder()
            .initialRetryDelayMillis(10).retryMaxAttempts(10)
            .totalRetryPeriodMillis(15000)
            .build()
        );
}
```

But still retrying all the time...

`RetryHelper(14.16 ms, 1 attempts, com.google.appengine.tools.cloudstorage.SimpleGcsInputChannelImpl$1@278ef74): Attempt #1 failed [java.io.IOException: java.lang.NullPointerException], sleeping for 9 ms`

The NullPointerException is thrown whenever .read() is invoked within the resulting InputStream.

Am I missing credentials (or the path to my local .json auth file) somewhere or should I take into account more things?

**Comment by abhinav-qlogic** [comment]
@turboT4  can you please let us know why you want to use appengine-gcs-client  to read file from bucket any specific reason?
 in-stand of that you can use
[cloud storage client](https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-storage)

**Comment by codyoss** [comment]
Closing due to lack of response. `openReadChannel ()` does throw `java.io.IOException` when the file does not exist. My guess is this is the case. Please reopen if you are still having this issue.
