### ISSUE TITLE
Question: is all user to cloud storage data transportation secured?

### ISSUE THREAD

**Issue by LuQQiu** [googleapis/google-cloud-java#5563]
Do we use HTTPS by default to transport the data?
or do we have any security protection to transport the data from user to cloud storage via this google cloud java API?

Thanks a lot!

**Comment by LuQQiu** [comment]
I noticed that we can set the transport option, but the available transport options are `HttpTransport` and `GrpcTransport`. Is `HttpTransport` directy use `HTTPS` to secure the transport layer?

**Comment by chingor13** [comment]
Yes, all of Google's API endpoints are using https. Storage uses the HttpTransport but it's endpoint is `https://storage.googleapis.com/...`
