### ISSUE TITLE
Deletion of users (identities) from Google bucket IAM Policy does not work

### ISSUE THREAD

**Issue by SyCode7** [googleapis/google-cloud-java#5581]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-java/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types

Google bucket IAM Policy 
2. OS type and version: Windows 10
3. Java version: 1.8
4. google-cloud-java version(s):  1.23.0

#### Steps to reproduce

  1.  Create bucket
  2.  Create users
  3.  Attack users to the bucket via roles and identities

#### Code example

```java
// Read bucket policy and extract unwanted identities
`Set<Identity> wrongIdentities = new HashSet<Identity>();
Role roler = null;    
Policy p = Cache.GCSStorage.getIamPolicy("bucketxyz");
Map<Role, Set<Identity>> policyBindings = p.getBindings();
    for (Map.Entry<Role, Set<Identity>> entry : policyBindings.entrySet()) {
Set<Identity> setidentities = entry.getValue();
    roler = entry.getKey();

        if (roler.getValue().equals("roles/storage.objectAdmin")) {
           setidentities = entry.getValue();
            if ((set.equals("serviceAccount:attacker@csbauditor.iam.gserviceaccount.com"))) {
                    continue;
                } else {
                    wrongIdentities.add(set);
                    }
                }
        }
    }
  removeBucketIamMember("bucektxyz", roler, identity));
    }
 }`

// Remove unwanted identities

`
public static Policy removeBucketIamMember(String bucketName, Role role, 
Identity identity) {
Storage storage = GoogleStorage.initStorage();
Policy policy = storage.getIamPolicy(bucketName);
Policy updatedPolicy = storage.setIamPolicy(bucketName,
policy.toBuilder().removeIdentity(role,Identity.serviceAccount(identity.getValue( 
 ))).build());
if (updatedPolicy.getBindings().get(role) == null|| 
!updatedPolicy.getBindings().get(role).contains(identity)) { 
System.out.printf("Removed %s with role %s from %s\n", identity, role, 
bucketName);
} 
return updatedPolicy;
}
```
#### Stack trace

No error

#### External references such as API reference guides used	

- https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/BucketIamSnippets.java

#### Any additional information below	

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sduskis** [comment]
@SyCode7 can you please elaborate on the problem?

**Comment by SyCode7** [comment]
@sduskis In order to remove identities from a bucket IAM policy, I use the example java code snippets provided at the GCP [bucket examples repo](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/BucketIamSnippets.java).  However, the defaulting users' identities are not removed, the policy does not change at all.  I am wondering if there is something I am missing, I have the correct root credentials to the cloud account, as well as the project ownership credentials. Here is an example of the policy:
` Policy{  
    bindings=   {  
      roles/storage.legacyBucketOwner=      [  
         projectOwner:csbauditor
      ],
      roles/storage.objectAdmin=      [  
         serviceAccount:company-kiehn-log@csbauditor.iam.gserviceaccount.com,
         serviceAccount:company-kiehn-file@csbauditor.iam.gserviceaccount.com,
         serviceAccount:company-howe-file@csbauditor.iam.gserviceaccount.com,
         serviceAccount:company-satterfield-log@csbauditor.iam.gserviceaccount.com,
         serviceAccount:customer-0c1e8536-8bf5-46f4-8e@csbauditor.iam.gserviceaccount.com,
         serviceAccount:company-fahey-log@csbauditor.iam.gserviceaccount.com,
         serviceAccount:company-hammes-file@csbauditor.iam.gserviceaccount.com,
         serviceAccount:company-howe-log@csbauditor.iam.gserviceaccount.com,
         serviceAccount:company-sipes-file@csbauditor.iam.gserviceaccount.com,
         serviceAccount:company-doyle-log@csbauditor.iam.gserviceaccount.com,
         serviceAccount:customer-6a53ee71-95eb-49b2-8a@csbauditor.iam.gserviceaccount.com,
         serviceAccount:company-bergnaum-file@csbauditor.iam.gserviceaccount.com
      ],
      roles/storage.legacyBucketReader=      [  
         projectViewer:csbauditor
      ],
      roles/storage.objectViewer=      [  
       serviceAccount:company-block-log@csbauditor.iam.gserviceaccount.com
      ]
     },
       etag=CLgE,
          version=0
     }
`

**Comment by SyCode7** [comment]
I specifically want to remove all the identities with the role `roles/storage.objectAdmin`. The code executes without error, but the policy remains unchanged , asides the `etag`.

**Comment by SyCode7** [comment]
I have asked the question also at StackOverflow [here](https://stackoverflow.com/questions/56784577/caused-by-com-google-api-client-googleapis-json-googlejsonresponseexception-41/56796880#56796880) and [here](https://stackoverflow.com/questions/56798852/deletion-of-users-identities-from-google-bucket-iam-policy-does-not-work).

**Comment by SyCode7** [comment]
I have found the answer to the issue, thanks to the answer at [stackoverflow](https://stackoverflow.com/questions/56798852/deletion-of-users-identities-from-google-bucket-iam-policy-does-not-work/56850795?noredirect=1#comment100279320_56850795).
