### ISSUE TITLE
Using google-cloud-datastore dependency in modular Java 11 project gives error

### ISSUE THREAD

**Issue by Leejjon** [googleapis/google-cloud-java#5609]
#### Environment details

1. google-cloud-datastore maven dependency
2. OS type and version: Windows 7 (latest)
3. Java version: 
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
4. google-cloud-java version(s): 
```
<dependency>
       <groupId>com.google.cloud</groupId>
       <artifactId>google-cloud-datastore</artifactId>
       <version>1.80.0</version>
</dependency>
```

#### Steps to reproduce
See the stackoverflow post.
  1. git clone https://github.com/Leejjon/SimpleJerseyService
  2. git checkout tags/3.1
  3. cd SimpleJerseyService
  4. mvn clean install exec:exec to see if the server runs at https://localhost:8080/
  5. Add the google-cloud-datastore maven dependency to the pom.xml, and run mvn clean install exec:exec again (may need to kill the previous java process to prevent binding errors on port 8080).
  6. The maven exec:exec plugin fails with the message:
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules grpc.context and grpc.api export package io.grpc to module org.apache.httpcomponents.httpclient

It did work with my old Java 8 project and with a Java 11 non modular project on Google App Engine.

#### Stack trace
https://pastebin.com/c6L7H2jL

#### Any additional information below	
https://stackoverflow.com/questions/56828520/java-lang-module-resolutionexception-when-adding-google-cloud-datastore-dependen

Let me know if more information is needed.

**Comment by Leejjon** [comment]
Found some information here:
https://github.com/grpc/grpc-java/issues/3522 

Somebody managed to hack it here:
https://github.com/grpc/grpc-java/issues/2727#issuecomment-348209549

When I try to use firestore instead of datastore, it has the same problem. So the problem might be closer to google-cloud-core.

**Comment by pmakani** [comment]
@Leejjon  i followed your steps and reproduced that error, which you are getting, error occurred because of dependency conflicts. so exclude that dependency and after it's work fine for me. can you please try this ?
 ```
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-datastore</artifactId>
    <version>1.80.0</version>
    <exclusions>
        <exclusion>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
        </exclusion>
        <exclusion>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by Leejjon** [comment]
The workaround works. I can use it with the gcloud datastore emulator now locally and my simple increment sample counts fine. It does give errors in the logs like:
java.lang.reflect.InaccessibleObjectException: Unable to make field protected volatile java.io.InputStream java.io.FilterInputStream.in accessible: module java.base does not "opens java.io" to module data
store.v1.proto.client
https://pastebin.com/e431R7pW


I'm trying to do a similar workaround with the firestore dependency:
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-firestore</artifactId>
            <version>1.11.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.grpc</groupId>
                    <artifactId>grpc-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

But I seem to be going down a rabbit hole that goes deeper and deeper:
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules grpc.context and grpc.api export package io.grpc to module org.apache.httpcomponents.httpclient

I tried excluding:
<exclusion>
                    <groupId>org.apache.httpcomponents</groupId>
                    <artifactId>httpclient</artifactId>
                </exclusion>
Then I get:
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules proto.google.common.protos and gax.grpc export package com.google.longrunning to module java.annotation

And it goes on.

I'll stick with datastore for now.
