### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [googleapis/google-cloud-java#5650]
Hi
The following lines have cryptographic API misuses. <br> File name => google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/testing/BaseEmulatorHelper.java: Line number => 461: API name => MessageDigest:<BR> File name => google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/testing/BaseEmulatorHelper.java: Line number => 453: API name => MessageDigest:Unexpected call to method <java.security.MessageDigest: byte[] digest()> on object of type java.security.MessageDigest. Expect a call to one of the following methods <java.security.MessageDigest: void update(byte[])>,<java.security.MessageDigest: void update(byte[],int,int)>,<java.security.MessageDigest: byte[] digest(byte[])>,<java.security.MessageDigest: void update(java.nio.ByteBuffer)>,<java.security.MessageDigest: void update(byte)><BR>

**Comment by chingor13** [comment]
Can you elaborate how this usage is misused? 

https://github.com/googleapis/google-cloud-java/blob/71124ba3bc6750abd777df86c813b2fb6945a42b/google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/testing/BaseEmulatorHelper.java#L453-L461

We are iterating over a large file and using `void update(byte[], int, int)`. The final call to `digest()` finishes the computation and returns the fully calculated md5.

**Comment by chingor13** [comment]
Closing as no update was provided
