### ISSUE TITLE
IllegalAccessError in background function when using the google-cloud-storage library

### ISSUE THREAD

**Issue by dvmorris** [googleapis/google-cloud-java#5651]
I encountered an error when trying to invoke a background function written in Java to handle a google.storage.object.finalize event, when the pom file included the following dependency:

```
    <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-storage</artifactId>
        <version>1.80.0</version>
    </dependency>
```

IllegalAccessError: tried to access method com.google.gson.JsonObject.deepCopy()Lcom/google/gson/JsonObject; from class com.google.cloud.functions.invoker.Event$EventDeserializer

After doing some research on google, I was able to resolve the error by explicitly including version 2.8.5 of the gson library in the pom like this:

```
    <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>2.8.5</version>
    </dependency>
```

**Comment by chingor13** [comment]
This should be fixed in google-cloud-storage 1.81.0. We bumped our gson dependency to 2.8.5. Please let us know if this doesn't fix it.
