### ISSUE TITLE
google-cloud-task: Question on using CloudTasksClient

### ISSUE THREAD

**Issue by dannychane** [googleapis/google-cloud-java#5706]
We are trying to use the cloud task api in a spring boot app and wanted to find out if CloudTaskClient is thread safe.  There will be a high frequency use of this service (singleton bean) using this api and wondering if the right path is to upfront create the client once (CloudTasksClient.create()) and reuse the client to add tasks.

Thanks!

**Comment by athakor** [comment]
@dannychane 

The Cloud Tasks service is designed for asynchronous work. It does not provide strong guarantees around the timing of task delivery and is therefore unsuitable for interactive applications where a user is waiting for the result so you could say it's not thread safe.

CloudTaskClient bean can be singleton and should be reused for furthur task creation and bean itself not a threadsafe. As client creation on each request could be costly which in terms of increase response time.

**Comment by dannychane** [comment]
Thx.

**Comment by moadi** [comment]
@athakor sorry for bringing this up again, but I am having a bit of trouble parsing your response above.

> CloudTaskClient bean can be singleton and should be reused for furthur task creation but bean itself not a threadsafe.

if the bean is singleton and should be reused for task creation in the entire application, doesn't that imply it is thread safe?

**Comment by gvastakis** [comment]
@moadi I have the same question as you. I understand that we can and should reuse a single cloud task client in our app, but the note that it isn’t thread-safe is a bit confusing to me.
