### ISSUE TITLE
Issues - Cant use Translation client api on the same project that uses speech cloud api dependencies & also API 'variant.getJavaCompile()' issue.

### ISSUE THREAD

**Issue by BigBangKing** [googleapis/google-cloud-java#5708]
Have two issues. 
1. I have added the client library of translation api but lots of duplicate class errors showed up.

Heres the modified dependencies list of .gradle:
`
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Support libraries
    implementation "com.android.support:design:$supportLibraryVersion"
    implementation "com.android.support:cardview-v7:$supportLibraryVersion"
    implementation "com.android.support:recyclerview-v7:$supportLibraryVersion"

    // gRPC
    implementation "io.grpc:grpc-okhttp:$grpcVersion"
    implementation "io.grpc:grpc-protobuf-lite:$grpcVersion"
    implementation "io.grpc:grpc-stub:$grpcVersion"
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    protobuf 'com.google.protobuf:protobuf-java:3.8.0'

    // OAuth2 for Google API
    implementation('com.google.auth:google-auth-library-oauth2-http:0.7.0') {
        exclude module: 'httpclient'
    }

    //Translation
    implementation 'com.google.cloud:google-cloud-translate:1.79.0'

    // Tests
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}`

errors are: `Duplicate class com.google.protobuf.AbstractMessageLite found in modules protobuf-java-3.7.1.jar (com.google.protobuf:protobuf-java:3.7.1) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
Duplicate class com.google.protobuf.AbstractMessageLite$Builder found in modules protobuf-java-3.7.1.jar (com.google.protobuf:protobuf-java:3.7.1) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
Duplicate class com.google.protobuf.AbstractMessageLite$Builder$LimitedInputStream found in modules protobuf-java-3.7.1.jar (com.google.protobuf:protobuf-java:3.7.1) and protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)` ___and more.

removing this line has no effect: `protobuf 'com.google.protobuf:protobuf-java:3.8.0'`

2. Then we have this issue:
`WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app`
to solve this I tried to update java-protobuf-lite version but that gave more duplicate class issues.

How can I solve these two issues?

**Comment by athakor** [comment]
@BigBangKing 

**1.** You are getting duplicate class errors because of protobuf-java and protobuf-lite.The core of the issue is that protobuf-java and protobuf-lite provide the same classes with different implementations As `protobuf-lite` is more focused for android applications due to small build size, So you should exclude `protobuf-java` from your dependencies.
**i.e**
android {
		...
		configurations.all {
		exclude group: 'com.google.protobuf', module: 'protobuf-java'
		}
	}

**2.** Please refer https://github.com/objectbox/objectbox-java/issues/643 for more details on the same issue.Update your Gradle version to 3.2.0 and warning will be disappeared.I would recommend you to use compatible gradle versions.
**i.e**
buildscript {
    // ... repositories, etc. ...
    dependencies {
		classpath 'com.android.tools.build:gradle:3.2.0'    
    }
}

**Comment by BigBangKing** [comment]
After adding this:
```
configurations.all {
exclude group: 'com.google.protobuf', module: 'protobuf-java'
}
```
it showed this error:
`More than one file was found with OS independent path 'project.properties'`

Using gradle :` classpath 'com.android.tools.build:gradle:3.4.2'`
So assuming that second error is from added libraries.

**Comment by athakor** [comment]
@BigBangKing can you please add

**Comment by Denesh11** [comment]
API 'variant.getJavaCompiler()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
 I have this issue can anyone help me
