### ISSUE TITLE
Javadocs site's version selector is incorrect

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/google-cloud-java#5721]
For example the current spanner docs:
https://googleapis.dev/java/google-cloud-clients/latest/index.html?com/google/cloud/spanner/package-summary.html

The version selector shows 0.98-alpha 
![Screenshot from 2019-07-10 16-26-27](https://user-images.githubusercontent.com/23526194/61002481-9e87c880-a32f-11e9-9f66-af15eb96958f.png)

It shows the same for bigtable

**Comment by kolea2** [comment]
This is the BOM version number, which is intended behavior.
