### ISSUE TITLE
enum Regions.java class not kept up to date

### ISSUE THREAD

**Issue by SeventhOfNine** [googleapis/google-cloud-java#5744]
Hi,

The enum Regions.java (created by https://github.com/googleapis/google-cloud-java/pull/4309) hasn't been updated with the last regions that were made available in Google Cloud. Namely:
- asia-northeast2
- europe-west6

Thanks.

**Comment by SeventhOfNine** [comment]
PR: https://github.com/googleapis/google-cloud-java/pull/4309

**Comment by chingor13** [comment]
Fixed in #5745
