### ISSUE TITLE
CollectionReference listDocuments return ApiFuture of DocRefs 

### ISSUE THREAD

**Issue by ChengyuanZhao** [googleapis/google-cloud-java#5764]
Hi, I'm from the java frameworks team (I'm cccz@google.com) and we're working on a Java Spring Data Reactive implementation for Firestore. (an ORM sort of thing)

We came across CollectionReference.listDocuments which is exactly what we needed but we see that the method blocks and waits for the list of docrefs to return. We also see that the package-private Firestore.sendRequest method within actually returns an ApiFuture so it seems like a small amount of work to make an alternate function, perhaps `futureListDocuments`, that doesn't block and returns an ApiFuture.

The ApiFuture return values are very important to us since we're building a reactive implementation.

We would be happy to contribute a PR for this feature if you guys would accept that. 

my teammates: @elefeint @dmitry-s @meltsufin @dzou

**Comment by BenWhitehead** [comment]
@ChengyuanZhao I believe you decided to go in a different direction from this issue, is that correct? Can we close this?

**Comment by ChengyuanZhao** [comment]
Yes @BenWhitehead , thanks much this issue is now very out of date and obsolete. Closing.
