### ISSUE TITLE
PubSub: support `setEndpoint` on Publisher/Subscriber builders

### ISSUE THREAD

**Issue by chingor13** [googleapis/google-cloud-java#5792]
Currently, the underlying clients can customize the gRPC endpoint but that option is not surfaced to the higher-level handwritten layer.

**Comment by chingor13** [comment]
We can call `setEndpoint` on the SubscriberStubSettings.Builder instantiated here: https://github.com/googleapis/google-cloud-java/blob/76062ba738b3bc35e7646d26cea13dcfffb784be/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java#L158

We would need to add an endpoint option to Subscriber.Builder and conditionally set it on the StubSettings builder if configured.

**Comment by kamalaboulhosn** [comment]
I believe @broady was adding this.
