### ISSUE TITLE
Make CustomClassMapper's serialization and deserialization methods public

### ISSUE THREAD

**Issue by dmitry-s** [googleapis/google-cloud-java#5809]
Hi,

we are working on Spring Data for Firestore. 

It would be useful for us if we could reuse existing object conversion logic so we don't have to re-implement it for our project.
It looks like `com.google.cloud.firestore.CustomClassMapper` have all the necessary logic, but it is package-private.

teammates: @meltsufin @elefeint @ChengyuanZhao @dzou

**Comment by BenWhitehead** [comment]
@dimitry-s Do you still need this implemented, or does https://github.com/googleapis/google-cloud-java/pull/6085 better take care of what you need?

**Comment by dmitry-s** [comment]
@BenWhitehead 
this one can be closed, #6085 is a better approach
