### ISSUE TITLE
https://googleapis.dev/java/google-cloud-clients/latest/ is inaccessible on browser because of certificate issues

### ISSUE THREAD

**Issue by vellab** [googleapis/google-cloud-java#5849]
Hi,

For the last few days, googleapis.dev is inaccessible on any browser because of site's certificate related issue. Chrome is complaining that the website sent incorrect credentials. Please fix this or if I need to change any setting please let me know. Otherwise I am unable to access any javadoc pages for google cloud tools.

**Comment by chingor13** [comment]
That's strange - the certificate looks fine for me: 
<img width="893" alt="Screen Shot 2019-07-24 at 7 22 48 AM" src="https://user-images.githubusercontent.com/32483/61802324-1ac8e400-ade5-11e9-971b-4b2cde7625c9.png">

**Comment by vellab** [comment]
Hi, this might be due to my organization. Please check the snapshot of my screen. 
![image](https://user-images.githubusercontent.com/16768819/61803156-aea7a980-adff-11e9-8c21-ef22facbfb8f.png)

**Comment by vellab** [comment]
Any suggestions as to how to overcome this.

**Comment by vellab** [comment]
Hi, I have found out that our organization is blocking the page. Thanks for helping out though.
