### ISSUE TITLE
Google Speech + Android

### ISSUE THREAD

**Issue by RobertoAlvarezCeballos** [googleapis/google-cloud-java#5914]
Hi,

I'm trying to use this library on Android but after all my attempts I'm getting the following error:

No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact

Has anyone managed to use it on Android, all the help I find is relative to Java on a PC

thanks in advance

**Comment by athakor** [comment]
@RobertoAlvarezCeballos

I have try to use Google Speech api on android app and facing same issue which you are facing so to resolve that issue i have added **io.grpc:grpc-okhttp:1.22.1** and **io.grpc:grpc-netty-shaded:1.22.1** dependency on app level **build.gradle** file and it's working fine for me.

**i.e**

dependencies {
....
    //Speech
    implementation 'com.google.cloud:google-cloud-speech:1.12.0'
    implementation 'io.grpc:grpc-okhttp:1.22.1'
    implementation 'io.grpc:grpc-netty-shaded:1.22.1'
....
}

**Comment by athakor** [comment]
closing this issue for now feel free to reopen it if above help didn't work.

**Comment by trakevital** [comment]
Hi I'm using android studio and trying to get google cloud speech api to work on it but until now it has only been a pain in the neck,
I tried what you have said about adding the dependencies but now it returns the following error:
`java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;)V in class Lio/grpc/internal/AbstractManagedChannelImplBuilder; or its super classes (declaration of 'io.grpc.internal.AbstractManagedChannelImplBuilder' appears in /data/app/com.example.sk.exp-_KkuijTz0OBaY1D3eACAPw==/base.apk!classes3.dex)`

**Comment by trakevital** [comment]
IT WORKS! I found the solution: 
Need to add the follwing to app level gradle.build

```
implementation 'io.grpc:grpc-okhttp:1.38.0'
implementation 'io.grpc:grpc-stub:1.38.0'
compileOnly 'org.apache.tomcat:annotations-api:6.0.53' // necessary for Java 9+
```

source: https://github.com/grpc/grpc-java
