### ISSUE TITLE
hello split packages

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-java#5936]
Related to #5760 

Create a minimal Maven project that demonstrates the split package problem to make sure I understand it. 

My current hypothesis is that a hello world app in a module that imports two modules with split packages without even calling them will have a compile time error. Verify this is true.

**Comment by elharo** [comment]
So the minimal thing that does it is this module-info.java:

```
module example.module {
	requires proto.google.cloud.vision.v1;
	requires grpc.google.cloud.vision.v1;
}
```

These artifacts should also be Maven dependencies, but that alone is not enough. The split package error occurs when the module system imports both modules.

It is not required that any classes from these two modules actually be imported by the Java code.

**Comment by codyoss** [comment]
@elharo do we have any actionable things to do here? If so, what are they?
