### ISSUE TITLE
How to provide backpressure when using ApiStreamObserver?

### ISSUE THREAD

**Issue by meltsufin** [googleapis/google-cloud-java#6018]
You can use the async GRPC client stub and pass in a `ClientResponseObserver` in place of the `StreamObserver`, which has an additional method called `beforeStart` that provides a `ClientCallStreamObserver` that has the `request(count)` method.
However, I cannot find a similar `request(count)` method in `ApiStreamObserver` to provide backpressure.

**Comment by kolea2** [comment]
Hey @meltsufin, is this a better question for googleapis/gax-java?

**Comment by meltsufin** [comment]
@kolea2 You're right!
https://github.com/googleapis/gax-java/issues/773

**Comment by kolea2** [comment]
Thanks! :)
