### ISSUE TITLE
Build: fails because of incompatible mojo scanner API

### ISSUE THREAD

**Issue by jean-philippe-martin** [googleapis/google-cloud-java#6024]
### Environment

1. OS type and version: Linux (Google's flavor)
2. Java version: 1.8.0_181-google-v7
3. google-cloud-java version(s): HEAD, I think it's 0.103.1-alpha-SNAPSHOT.

I'm seeing this problem with both
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00) and
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T12:00:29-07:00)

#### Steps to reproduce

  1. `git pull`
  2. `mvn package -DskipTests -Dmaven.javadoc.skip=true -Dmaven.source.skip=true --projects ./google-cloud-testing/google-cloud-gcloud-maven-plugin --also-make`

Expected: the package compiles.

#### Error message

Actual: the build fails with the following error message.

```
[INFO] Reactor Summary:
[INFO] 
[INFO] Google Cloud Testing ............................... SUCCESS [  0.003 s]
[INFO] google-cloud-gcloud-maven-plugin ................... FAILURE [  2.942 s]
```

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.6.0:descriptor
(default-descriptor) on project google-cloud-gcloud-maven-plugin: The API of the mojo scanner
 is not compatible with this plugin version. Please check the plugin dependencies configured in 
the POM and ensure the versions match. /usr/local/buildtools/java/jdk8-google-v7-
64/jre/lib/amd64/libawt_xawt.so: /usr/grte/v4/lib64/libc.so.6: version `GLIBC_2.25' not found 
(required by /lib/x86_64-linux-gnu/libbsd.so.0) -> [Help 1]

### Notes

This sounds a bit like something is misconfigured on my end but I'm at a loss and perhaps others will run into the same difficulty. It would be nice to add a word about this in the README, or if there's some change to the build rules that'll ensure it builds everywhere.

**Comment by houglum** [comment]
Also seeing this error with the same OS and Java version, at HEAD (commit 16435cbf275), version 0.104.1-alpha-SNAPSHOT.

**Comment by pmakani** [comment]
I followed steps with jdk1.8.0_221 and it's working fine.

**Comment by jean-philippe-martin** [comment]
As a workaround, it's possible to just remove the `google-cloud-gcloud-maven-plugin` module without apparent ill effects. [This branch](https://github.com/jean-philippe-martin/gcloud-java/tree/hide_gcloud-maven-plugin) has the code (feel free to use it). The code change (see [commit](https://github.com/jean-philippe-martin/gcloud-java/commit/7d8bd3afbe4d603c21d7c07f43f0c34f04677f1f)) is just removing one line.

**Comment by pmakani** [comment]
closing issue, feel free to reopen if it's happen again.
