### ISSUE TITLE
Bigtable java client document link not working

### ISSUE THREAD

**Issue by liu-aoao** [googleapis/google-cloud-java#6056]
The links in bigtable client wiki page are not working. E.g https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/bigtable/data/v2/BigtableDataClient.html

**Comment by rahulKQL** [comment]
Hi @liu-aoao,

Can you please retry the link you provided, It's working for me. 
You can try this URL: https://googleapis.dev/java/google-cloud-clients/latest/
