### ISSUE TITLE
Spanner: BatchCreateSessions

### ISSUE THREAD

**Issue by kolea2** [googleapis/google-cloud-java#6169]

**Comment by olavloite** [comment]
The Spanner client library should use the new BatchCreateSessions API to create and maintain the session pool. In addition to using the new API, the following changes will be applied to the session pool to improve performance:
* Change the order of the session pool from FIFO to LIFO. LIFO has been determined to show better and more stable query performance.
* Use BatchCreateSessions to create and maintain the session pool.
* Change the default session pool options to MinSessions > 0.
