### ISSUE TITLE
KMS: java11 google-cloud-kms v1.15.0+ NoClassDefFoundError

### ISSUE THREAD

**Issue by johannesgiani** [googleapis/google-cloud-java#6229]
There is a `NoClassDefFoundError` error when trying to obtain the client via `KeyManagementServiceClient.create()`.

#### Environment details

* google-cloud-kms v1.15.0+ 
* macOS and GAE standard Java 11
* Java 11

#### Steps to reproduce

  1. Use google-cloud-kms:1.15.0 or above as dependency
  2. Call `KeyManagementServiceClient.create()` somewhere

#### Code example

```java
try (KeyManagementServiceClient client = KeyManagementServiceClient.create()) {
 ...
}
```

#### Stack trace
```
Caused by: java.lang.NoClassDefFoundError: com/google/cloud/kms/v1/ListImportJobsRequest
	at com.google.cloud.kms.v1.stub.GrpcKeyManagementServiceStub.<clinit>(GrpcKeyManagementServiceStub.java:105) ~[google-cloud-kms-1.25.0.jar:1.25.0]
	at com.google.cloud.kms.v1.stub.KeyManagementServiceStubSettings.createStub(KeyManagementServiceStubSettings.java:333) ~[google-cloud-kms-1.25.0.jar:1.25.0]
	at com.google.cloud.kms.v1.KeyManagementServiceClient.<init>(KeyManagementServiceClient.java:155) ~[google-cloud-kms-1.25.0.jar:1.25.0]
	at com.google.cloud.kms.v1.KeyManagementServiceClient.create(KeyManagementServiceClient.java:136) ~[google-cloud-kms-1.25.0.jar:1.25.0]
	at com.google.cloud.kms.v1.KeyManagementServiceClient.create(KeyManagementServiceClient.java:127) ~[google-cloud-kms-1.25.0.jar:1.25.0]
```

### Workaround 
This doesn't happen with version 1.14.0 so switching back to that version does the trick for now.

**Comment by athakor** [comment]
@johannesgiani  

I have followed your steps with Java 11 and tried to reproduced it by creating simple kms client creation example but I am unable to reproduced it. I have tried it with above google-cloud-kms v1.15.0 upto kmsv1.26.0 and all are working fine below are the code snippets which is successfully create the kms client and produce its settings.

```
try (KeyManagementServiceClient client = KeyManagementServiceClient.create()) {
      System.out.println("Client Setting : " + client.getSettings());
    }
```

**Output of Client Setting :** 

`KeyManagementServiceSettings{executorProvider=InstantiatingExecutorProvider{executorThreadCount=4, threadFactory=com.google.api.gax.core.InstantiatingExecutorProvider$1@d8305c2}, transportChannelProvider=com.google.api.gax.grpc.InstantiatingGrpcChannelProvider@56bca85b, credentialsProvider=GoogleCredentialsProvider{scopesToApply=[https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloudkms], jwtEnabledScopes=[], OAuth2Credentials=null}, headerProvider=com.google.api.gax.rpc.NoHeaderProvider@75d0911a, internalHeaderProvider=com.google.api.gax.rpc.ApiClientHeaderProvider@75e91545, clock=com.google.api.core.NanoClock@60d1a32f, endpoint=cloudkms.googleapis.com:443, watchdogProvider=com.google.api.gax.rpc.InstantiatingWatchdogProvider@531c311e, watchdogCheckInterval=PT10S}`

**Comment by johannesgiani** [comment]
Are you using maven or gradle?
Just recognized that gradle downloads `com.google.api.grpc:proto-google-cloud-kms-v1` version `0.61.0` instead of `0.74.0`. `0.74.0` is required for ` com.google.cloud:google-cloud-kms:1.26.0`.

**Comment by athakor** [comment]
> @athakor Are you using maven or gradle?
> Just recognized that gradle downloads `com.google.api.grpc:proto-google-cloud-kms-v1` version `0.61.0` instead of `0.74.0`. `0.74.0` is required for ` com.google.cloud:google-cloud-kms:1.26.0`.

 I have tried with maven. okay let me try it with gradle

**Comment by jadsafe** [comment]
I have the same problem running KMS with Google App Engine using Maven. Following steps per KMS installations, I have in pom.xml:
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-kms</artifactId>
			<version>1.26.0</version>
		</dependency>

GAE (standard) gives the same error described by OP during warmup.

**Comment by johannesgiani** [comment]
My current workaround is to add `com.google.api.grpc:proto-google-cloud-kms-v1:0.74.0` as compile dependency.

**Comment by athakor** [comment]
This seems resolved
