### ISSUE TITLE
Support for JobConfiguration.labels

### ISSUE THREAD

**Issue by nbali** [googleapis/google-cloud-java#6240]
**Is your feature request related to a problem? Please describe.**
We would like to provide labels for query jobs, which we can't with this library meanwhile it's there in the "legacy" library.
 **Describe the solution you'd like**
The ability to call `com.google.cloud.bigquery.QueryJobConfiguration.Builder.setLabels(java.util.Map<String, java.lang.String> labels)`.
 **Describe alternatives you've considered**
We can fallback to the legacy library, and implement pretty much everything that is related to this again that is in this library, but it seems like a waste of time.
 **Additional context**
None.

**Comment by pmakani** [comment]
Closing via #6367, #6376, #6387 and #6407
