### ISSUE TITLE
Pub/Sub retry settings examples causing customer & support pain

### ISSUE THREAD

**Issue by kir-titievsky** [googleapis/google-cloud-java#6254]
Current sample retry settings here [1] set initialRpcTimeout = totalRpcTimeout, which effectively turns off retries. This has been causing almost daily escalations from major customers.  Please fix to say something more reasonable like
<pre>
Duration totalTimeout = Duration.ofSeconds(600); // default: 10 seconds
Duration initialRpcTimeout = Duration.ofSeconds(1); // def
</pre>

Also the mention of the defaults in the comments here is likely distracting.  That should be documented in the RetrySettings class documentation instead. 

[1] https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/PublisherSnippets.java#L120

**Comment by athakor** [comment]
@kir-titievsky  PRs [6257](https://github.com/googleapis/google-cloud-java/pull/6257) and [6258](https://github.com/googleapis/google-cloud-java/pull/6258)

**Comment by athakor** [comment]
closing via #6257 & #6258
