### ISSUE TITLE
log.error() is not logging Severity error Instead logging Info

### ISSUE THREAD

**Issue by nitinsridar** [googleapis/google-cloud-java#6385]
I have requirement that If I'm logging with log.error(e); I have to get Severity: Error instead i'm receiving Info. Please help how to acheive this.

@Slf4j
   @ControllerAdvice
   public class CustomExceptionHandler extends ResponseEntityExceptionHandler {
     @ExceptionHandler(SpannerException.class)
public final ResponseEntity<Object> handleUserNotFoundException(SpannerException ex, WebRequest request) {
    List<String> details = new ArrayList<>();
    details.add(ex.getErrorCode().toString());
    ErrorResponse error = new ErrorResponse("Exception occured", details);
    log.error("Exception:" + ex.getMessage());
    return new ResponseEntity(error, HttpStatus.INTERNAL_SERVER_ERROR);
}

My logback.xml
`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/cloud/gcp/logging/logback-json-appender.xml" />
    <include resource="org/springframework/boot/logging/logback/defaults.xml" />
    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />
    <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="CONSOLE" />
    </appender>
    <root level="INFO">
        <appender-ref ref="ASYNC" />
    </root>
</configuration>`

In StackDriver I'm seeing severity is INFO.

**Comment by codyoss** [comment]
In order to map the proper severity you must add the `com.google.cloud.logging.logback.LoggingAppender` as your appender. This takes care of all the mappings. 

An example of how this would look in your logback.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="CLOUD" class="com.google.cloud.logging.logback.LoggingAppender">
        ...
    </appender>
    <root level="INFO">
        <appender-ref ref="CLOUD"/>
    </root>
</configuration>
```

Also ensure you have imported the library into your `pom.xml`.

```xml
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-logging-logback</artifactId>
			<version>0.111.0-alpha</version>
		</dependency>
```

Does this solve your issue @nitinsridar

**Comment by codyoss** [comment]
Closing as the above comment should answer the question. If it does not, feel free to reopen
