### ISSUE TITLE
Storage.create returns error code 400

### ISSUE THREAD

**Issue by liuyuhen670482** [googleapis/google-cloud-java#6404]
Hi,

I followed the example on Google Cloud's API page on creating a blob on GCS, simple code I used to create an empty blob 

`val blobId = BlobId.of("bucket-name", "directory1/_SUCCESS")
val blobInfo = BlobInfo.newBuilder(blobId).setContentType("text/plain").build
val blob = storage.create(blobInfo)`

Returns error code 400 with following json response:

``{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Upload requests must include an uploadType URL parameter and a URL path beginning with /upload/",
    "reason" : "wrongUrlForUpload",
    "extendedHelp" : "https://cloud.google.com/storage/docs/json_api/v1/how-tos/upload"
  } ],
  "message" : "Upload requests must include an uploadType URL parameter and a URL path beginning with /upload/"
}``

Tracing through their source code seems like calling `storage.create()` will trigger the construction and serving the Http request internally. However, Google's endpoint is complaining that the format of their request URL is incorrect (see error response above) and returned the error response. Am I missing something? Please help.

**Comment by liuyuhen670482** [comment]
Just wanted to check if there's any updates on this. Thanks!

**Comment by athakor** [comment]
@liuyuhen670482 I have tried it but unable to reproduced below are the code snippets and outputs. 

**Code Sample:**
```
val storage = StorageOptions.getDefaultInstance().service
val blobId = BlobId.of("xxx-xxx-bucket", "directory1/_SUCCESS")
val blobInfo = BlobInfo.newBuilder(blobId).setContentType("text/plain").build()
val blob = storage.create(blobInfo)
println("Empty blob created successfully.")
println("response:" + blob)
```
**Output :** 
```
Empty blob created successfully.
response:Blob{bucket=xxx-xxx-bucket, name=directory1/_SUCCESS, generation=1571316847752130, size=0, content-type=text/plain, metadata=null}
```

**Comment by JesseLovelace** [comment]
This bug was discussed internally and resolved
