### ISSUE TITLE
What makes java client library incompatible with Android?

### ISSUE THREAD

**Issue by matejdro** [googleapis/google-cloud-java#6423]
[Documentation page](https://cloud.google.com/dialogflow/docs/reference/libraries/java) states `Caution:The Java client library does not support Android.`

However, that message is very vague. What exactly causes it to not be supported on Android? It appears to work fine.

**Comment by codyoss** [comment]
Some of this has due with lack of testing done /w Android. There have also been a number of issues you can find if you search for closed issues tagged with android that explain this. Another thing is type of auth for android client. If you are interested in using similar features from android I suggest you take a look at https://github.com/firebase/firebase-android-sdk. I hope that helps shed some light.

**Comment by matejdro** [comment]
What features from firebse android sdk are similar to DialogFlow?

**Comment by abhi007tyagi** [comment]
@codyoss @matejdro @chingor13 Guys I have created this Android library to integrate Dialogflow based chatbot into an Android app. Do give it a try and share any feedback you have.

https://medium.com/@abhi007tyagi/android-dialogflow-chatbot-library-6b7b3822e7bc
