### ISSUE TITLE
grpc-netty-shaded is adding a lot of weight to apps using google-cloud-java

### ISSUE THREAD

**Issue by clementdenis** [googleapis/google-cloud-java#6425]
The current version of some google-cloud-* libraries have grpc-netty-shaded as a dependency. This jar alone is almost 7 MB in size.

For environments with limited resources (App Engine, Cloud Functions), this can add precious seconds to startup time.

Could you consider changing the default transport?

There a way to reduce the size of the app by excluded the grpc-netty-shaded transport and replacing it with the much lighter grpc-okhttp. Could it be documented?

    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-logging</artifactId>
      <exclusions>
        <exclusion>
          <groupId>io.grpc</groupId>
          <artifactId>grpc-netty-shaded</artifactId>
        </exclusion>
    </exclusions>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-okhttp</artifactId>
      <version>1.23.0</version>
    </dependency>

**Comment by ejona86** [comment]
gRPC team would still suggest using grpc-netty on those platforms. Most of the size of grpc-netty-shaded is for netty-tcnative which has multiple binaries for boringssl, one for each platform. App Engine Java 8 contains Conscrypt, which is an alternative, and with Java 11 neither is strictly necessary. Are you using App Engine Java 8 or 11?

Empirically, how much faster is your app startup by swapping to okhttp? Also mention how long startup is overall.

Using Conscrypt with Netty takes a little bit of runtime configuration at the moment. That could be fixed for App Engine Java 8.

> Could you consider changing the default transport?

No. That doesn't help. We'd need to include Conscrypt for all the other platforms and that would increase the size back to where it is now. Also, Conscrypt is broken for OkHttp on Windows at present (https://github.com/google/conscrypt/issues/444) (Netty works fine with it on Windows).

**Comment by ejona86** [comment]
Actually... looking at OkHttp more it doesn't implicitly use Conscrypt. I _thought_ Conscrypt wasn't in the default providers list in App Engine, but maybe that changed. The other option is @clementdenis is on App Engine Java 11.

**Comment by clementdenis** [comment]
Hi,

I'm running on Java 11 indeed, which requires google-cloud-logging to get the custom log appender that can send the logs to Stackdriver in a way that allows consolidation under the request log entry (BTW, this is a LOT of dependencies for getting a feature that was built-in on App Engine Java 8 ...).

I did not time the improvement of using okhttp over the default provider, but we noticed that startup time on App Engine 11 increases significantly with the number / size of dependencies. So If we can avoid a 7MB jar, that's always a win.

**Comment by ejona86** [comment]
Okay, so for Java 11 you can just use `grpc-netty` instead of `grpc-netty-shaded`. No need to use okhttp.

That has been the expectation for a while: we use grpc-netty-shaded for most users since it "just works" and users that are more concerned about dependency size use grpc-netty directly. I would _love_ a world where we are all on Java 11, but here we are still supporting Java 7.

**Comment by codyoss** [comment]
@clementdenis is this still an issue for you? Or did the suggestion above solve this for you?
