### ISSUE TITLE
Datastore emulator consistency is not representative of real behaviour

### ISSUE THREAD

**Issue by insano10** [googleapis/google-cloud-java#6483]
When using the default consistency setting of 0.9 I see behaviour where an entity can be queried successfully and then a subsequent query returns null. 

I understood the weakly consistent behaviour of production datastore to be that an upserted entity may not be globally queryable for an indeterminate amount of time as it is propagated across the nodes. However once it was there, it would not disappear again. 

In the emulator it seems like the consistency probability is local to the query so sometimes it may be returned and other times not, making it look like entities disappear.

Is this expected behaviour?

**Comment by chingor13** [comment]
The emulators are useful for testing general behavior of the backend services and have no guarantee that the behavior will be identical to the real service.

That said, the issue as you describe it sounds like a bug in the emulator. The emulator is not part of this repo, so please file an issue on the [Datastore public issue tracker](https://issuetracker.google.com/savedsearches/559768)
