### ISSUE TITLE
BigQuery: implement scripting support

### ISSUE THREAD

**Issue by shollyman** [googleapis/google-cloud-java#6489]
Need to implement some incremental changes to enable scripting support in the BigQuery library.

* Jobs (e.g. scripts) can create child jobs.  There's new stats on the Job Statistics like numChildJobs (for the parent), and parentJobId (for the children).  There's also a new enum for the statementType (SCRIPT).

* bigquery.jobs.list now supports passing an option to filter by parentJobId.

* JobStatistics now may include ScriptStatistics message, which itself may also contain ScriptStackFrame information.

This has already been implemented in other languages, so feel free to use them as a reference:
In python, https://github.com/googleapis/google-cloud-python/issues/9190 tracks the work to implement.  In go, see https://code-review.googlesource.com/c/gocloud/+/44311

**Comment by yiga2** [comment]
+1 for a new `list_children()` method as mentioned in https://github.com/googleapis/google-cloud-python/issues/9190

It would only call `list_jobs()` - and as such make an API call - if `numChildJobs` > 0

**Comment by shollyman** [comment]
Adding a helper to construct the job iterator is a reasonable thing to hang off the job abstraction, but I would return it directly rather than gating it on the state of num_child_jobs since that can be out of sync locally with the state of a scripting job (you can start to observe children while the parent is still running, etc).
