### ISSUE TITLE
http-client + datastore

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-java#6680]
Putting this here because we need to do these next steps in a very specific order to avoid behavior (not API) incompatibilities between datastore-v1-proto-client and http-java-client

1. (Optional) Update google-cloud-java to com.google.cloud.datastore:datastore-v1-proto-client:1.6.2
2. Release com.google.cloud.datastore:datastore-v1-proto-client:1.6.3
3. Update google-cloud-java to com.google.cloud.datastore:datastore-v1-proto-client:1.6.3 and google-http-java-client 1.33.0 in the same PR.

**Do not upgrade google-http-java-client before releasing com.google.cloud.datastore:datastore-v1-proto-client:1.6.3**

The GZip hack in com.google.cloud.datastore:datastore-v1-proto-client:1.6.2 and earlier is incompatible with the actual fix introduced in google-http-java-client 1.33.0 . API level checks will not reveal this, though the unit tests might.

```
      <dependency>
        <groupId>com.google.cloud.datastore</groupId>
        <artifactId>datastore-v1-proto-client</artifactId>
        <version>1.6.0</version>
      </dependency>
```

**Comment by chingor13** [comment]
PR to update datastore-v1-proto-client: #6675
