### ISSUE TITLE
Spanner: support stored procedures in the form of Java bytecode

### ISSUE THREAD

**Issue by archiecobbs** [googleapis/google-cloud-java#6713]
Yes I know this is a long shot, just throwing it out there...

 **Is your feature request related to a problem? Please describe.**

The problem is this: like many folks we use Java and persist state using ORM solutions like Hibernate. Because Java is object oriented and inter-object references are everywhere, it's easy for a single transaction to end up requiring lots of query-response round trips to the database, due to the Java code traversing a bunch of collections and object references.

This happens because with SQL it's just not always feasible to JOIN together everything you need to look at in one query (e.g., you can't just set `FetchMode.EAGER` on all your collections or else you get a combinatorial explosion). The only alternative is for collections and referenced objects to be loaded at least somewhat lazily, i.e., on demand. And the more complex your Java transaction, the more complex your data access pattern.

This round-tripping is OK except in scenarios where there is an appreciable round trip time to your database. But this is exactly the situation if someone is using Spanner from the "outside world", i.e., their application is not hosted within Google's cloud infrastructure. We would like to use Spanner from the "outside world".

Of course, the long RTT will not only make transactions slower, but also make them more likely to have a retry failure due to a conflict: typically a transaction will do more reading at the beginning of the transaction, and then do its writing at the end; the more time separation between the reads & writes, the wider the race window.

The obvious way to fix this problem is to move the code to the data instead of what we end up doing today, which is moving a lot of the data to the code.

Some database support SQL stored procedures but trying to write elegant code in that language, and implement and debug it inside a Java application, is a nightmare.

 **Describe the solution you'd like**

I'd like Spanner to have first-class support for moving the code to the data, and I'd like Java classfiles to be one supported code type.

Presumably, Spanner would define some `SpannerQuery` interface that my code could implement. I'd send my code to Spanner and tell it to invoke my code and return the result. The entire execution would be performed within the context of the containing transaction, on the Spanner node where it can access whatever data it decides it needs to access with minimal latency. One round trip and the whole transaction is done!

There are lots of ways this could be configured. For Java, you could designate a table having a `className` and `bytecode` columns to contain your code. Or, call it Java stored procedures and mimic the SQL stored procedure syntax (of course, adding the bytecode part).

Note that [VoltDB](https://www.voltdb.com/) supports Java stored procedures, so the idea is not crazy.

 **Describe alternatives you've considered**

Not using Spanner?

**Comment by olavloite** [comment]
Hi @archiecobbs 
Thank you for your extensive feature request. This is however not a feature that we could logically add to the client libraries. Instead, this would be something that would have to be added to the backend. This GitHub repository is only used for the client libraries. The issue tracker for the backend can be found here: https://issuetracker.google.com/issues?q=componentid:190851%2B%20status:open
Would you mind open a feature request there instead?

I'll leave it to the backend team to discuss whether this has any chance of this being added in the foreseeable future.

### Alternative Solution
If I understand you correctly, your main problem is the high round-trip time to the database as you are executing your application outside the Google infrastructure. At the same time, it would be possible for you to extract the database transaction logic into separable blocks of code that you would like to add to the database, and let the database server execute for you. Could it also be a possibility to place these transaction blocks in a separate container and execute these on [Google Compute](https://cloud.google.com/compute/docs/) or [Google App Engine](https://cloud.google.com/appengine/)?

That would enable you to keep most of your application logic where it currently is, while moving the database transaction logic into the Google infrastructure.

**Comment by archiecobbs** [comment]
@olavloite , sorry for the misdirected issue report and thank you for the redirect and the suggestion. Closing this issue.

**Comment by archiecobbs** [comment]
New issue created: https://issuetracker.google.com/issues/144183725
