### ISSUE TITLE
CloudStorage: The FakeRpcStorage read() method doesn't write the contents to the given OutputStream

### ISSUE THREAD

**Issue by clarkperkins** [googleapis/google-cloud-java#6739]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-java/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

1. Specify the API at the beginning of the title (for example, "BigQuery: ...")
   General, Core, and Other are also allowed as types
2. OS type and version: macOS 10.14
3. Java version: 11.0.5
4. google-cloud-java version(s): google-cloud-nio-0.118.0-alpha

#### Steps to reproduce

  1. call Blob::downloadTo(Path path) when using the FakeStorageRpc
  2. it doesn't write anything to the given file

#### Code example

```groovy
// example
def storage = LocalStorageHelper.options.service
def blob = storage.get(bucket, key)
blob.downloadTo(outputPath)
```

#### Stack trace

n/a

#### External references such as API reference guides used	

n/a

#### Any additional information below	

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by JesseLovelace** [comment]
Thanks for bringing this to our attention and for your PR! I've just merged it in and am following up by adding a test
