### ISSUE TITLE
README.md.tmpl  should reference the BOM 

### ISSUE THREAD

**Issue by elharo** [googleapis/google-cloud-java#6795]
google-cloud-java/utilities/templates/README.md.tmpl 

This section needs to be expanded

Quickstart
----------

[//]: # ({x-version-update-start:google-cloud-{{service}}:released})
If you are using Maven, add this to your pom.xml file
```xml
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-{{service}}</artifactId>
  <version>{{version}}</version>
</dependency>
```

**Comment by chingor13** [comment]
We don't use this template anymore and it has been deleted from the repository.
