### ISSUE TITLE
Appengine API SDK 1.0 and Google Cloud Datastore Emulator

### ISSUE THREAD

**Issue by BrentOliverBC** [googleapis/google-cloud-java#6980]
#### Environment details
Mac OSX Sierra
Java 8
appengine-api-1.0-sdk:1.9.73
google-cloud-datastore:1.74.0
Objectify V5 & V6

#### Steps to reproduce
We have an application that has both GAE standard and GAE flex services. When running the application locally, I use the appengine-api-1.0-sdk for the GAE standard services. The standard services also use Objectify V5 to communicate with the datastore. The datastore's data is persisted in a .bin file

The GAE flex services are using the emulator along with Objectify V6 to communicate to the emulator. The emulator is started up pointing to the same .bin file as the appengine-api-1.0-sdk datastore. 

With all services up and running, the application runs fine and there are no errors with saving or retrieving data, however the GAE standard services, using the datastore from appengine-api-1.0-sdk, is unable to retrieve data that was saved by the GAE flex services. 

I used another datastore viewer, DSUI, to confirm that all the entities are saved correctly to the .bin used by both datastores.

Why can't the datastore bundled with appengine-api-1.0-sdk view all the entities in the .bin? This issue is only observed in the local environment. We have the same setup running in production with no issues. 

Happy to provide additional information! 

Thanks!

**Comment by elharo** [comment]
I'll mark this as a question for now, but none of this is really in scope for this repo. Java runtime issues and emulator issues are elsewhere, though I'm not sure where off the top of my head.

**Comment by BrentOliverBC** [comment]
This appears to be more of an issue with the Appengine API SDK and the emulator than the Java runtime. If there is better place to post, happy to move it. Thanks!

**Comment by meredithslota** [comment]
Hi @BrentOliverBC  — are you still having this problem? If so, can you provide an updated error report?
