### ISSUE TITLE
Spanner/Pubsub: too many threads (Gax)

### ISSUE THREAD

**Issue by nareshgnT** [googleapis/google-cloud-java#6997]
Our apps connect to spanner and 1 publisher and 4 subscribers to pubsub. Even in moderate load apps  spins about 160 to 200 Gax threads. It seems most of the time library not attempt to use existing once instead creates new threads. Is there way to control the no of threads in the app both spanner and pubsub lib?

**Comment by ajaaym** [comment]
@nareshgnT please see [this](https://github.com/googleapis/java-pubsub/issues/27#issuecomment-538508100) if it helps.

**Comment by nareshgnT** [comment]
@ajaaym will same applicable for subscriber and spanner as well? the example given in the mentioned thread is about publisher only?

**Comment by meltsufin** [comment]
Obsolete. This repo no longer contains Spanner and Pub/Sub client libs.
