### ISSUE TITLE
Unlinked references in documentation

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-cloud-java#7106]
Originally filed in https://github.com/googleapis/docuploader/issues/18 by @broady.

**What I did:**

Navigate to:
(Java) https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/pubsub/v1/Subscriber.Builder.html

**What I saw**

(Java) Unlinked references to `com.google.api.gax.core.CredentialsProvider` etc
![image](https://user-images.githubusercontent.com/24982/61830627-78c6ed00-ae20-11e9-90dd-83766059bd5c.png)

**What I expect**

Able to click through to the docs for Java's gax and any other docs for a dependency or transitive dependency.

**Comment by chingor13** [comment]
These are fixed in the split client library javadocs.
