### ISSUE TITLE
com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

### ISSUE THREAD

**Issue by upendaryerabolu** [googleapis/google-cloud-java#7155]
Hi I am getting weird error when pushing message to pubsub.

```
com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
```

what is root cause of this error.

**Comment by waytoalpit** [comment]
Hi, I am getting exactly same error.
Can you please update with the fix?

**Comment by viewdeveloper** [comment]
I am getting this too.
I wasn't experiencing the issue til I moved my build to AWS.

**Comment by nandakumarrk** [comment]
I have the same error.  Anyone find a resolution for this?

**Comment by upen4a3** [comment]
Please find the answer here. https://stackoverflow.com/questions/60495124/gcp-pubsub-sun-security-provider-certpath-suncertpathbuilderexception-unable-t

**Comment by sivasankar244k** [comment]
I do have the same issue , it appears after 2 hours of pull , and my subscriber stops listening to until I do a restart.

**Comment by meltsufin** [comment]
@sivasankar244k Please file an issue on the Pub/Sub repo: https://github.com/googleapis/java-pubsub/issues.
