### ISSUE TITLE
Storage: Setting GOOGLE_APPLICATION_CREDENTIALS to a non-existent file silently falls back to the anonymous user

### ISSUE THREAD

**Issue by sethvargo** [googleapis/google-cloud-java#7184]
#### Environment details

1. OS type and version: Ubuntu, 18.04 (but reproduced elsewhere too)
1. Java version: 1.8
1. google-cloud-java version(s): 1.106.0

#### Steps to reproduce

  1. Set the environment variable `GOOGLE_APPLICATION_CREDENTIALS` to a non-existent filepath
  2. Run the code, note that it falls back to the anonymous user instead of erroring that the filepath given by `GOOGLE_APPLICATION_CREDENTIALS` is invalid or unreadable

#### Code example

```java
import com.google.cloud.storage.Bucket;
import com.google.cloud.storage.Storage;
import com.google.cloud.storage.StorageOptions;
import java.io.ByteArrayInputStream;
import org.junit.jupiter.api.Test;

public class MyTest {

  @Test
  public void testGcp() {
    // Set GOOGLE_APPLICATION_CREDENTIALS=/foo/bar/baz first
    Storage storage = StorageOptions.getDefaultInstance().getService();

    Bucket bucket = storage.get("my-bucket");
    ByteArrayInputStream blobContent =
        new ByteArrayInputStream(bucket.get("schema.json").getContent());
  }
}
```

**Comment by elharo** [comment]
Probably belongs to one of the auth repos?

**Comment by sethvargo** [comment]
The code I traced is in this repo.

**Comment by elharo** [comment]
Do you have more details? Your sample code does not reference classes in this repo.

**Comment by frankyn** [comment]
Hi @sethvargo,

The java repository for Storage library is: https://github.com/googleapis/java-storage
Note that credentials are handled by the Java auth library (https://github.com/googleapis/google-auth-library-java).

Could you forward this issue there? Apologies for the delay.
