### ISSUE TITLE
Google Sheets API: Getting java.lang.NoSuchMethodError when try running the quickstart example

### ISSUE THREAD

**Issue by LouisKwong** [googleapis/google-cloud-java#7332]
#### Environment details

1. OS type and version: OSX 10.15.6
2. Java version: 11.0.8 2020-07-14 LTS
3. google-cloud-java version(s):
build.gradle

plugins {
  id 'java'
  id "com.katalon.gradle-plugin" version "0.0.7"
}

repositories {
  mavenCentral()
}

dependencies {
  compile 'com.google.api-client:google-api-client:1.30.4'
  compile 'com.google.oauth-client:google-oauth-client-jetty:1.30.6'
  compile 'com.google.apis:google-api-services-sheets:v4-rev581-1.25.0'
}

#### Steps to reproduce

  1. When I tried to run the SheetQuickstart.java, I get the following error message 
java.lang.NoSuchMethodError: com.google.api.client.http.HttpRequest.setResponseReturnRawInputStream(Z)Lcom/google/api/client/http/HttpRequest;
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:434)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$execute.call(Unknown Source)

#### Any additional information below	
The error is reproduced from the following:
ValueRange response = service.spreadsheets().values().get(spreadsheetId, range).execute();

Would you please help on this? Thanks.

**Comment by chingor13** [comment]
You appear to be using old and incompatible versions of the libraries. setResponseReturnRawInputStream was added in google-http-client 1.29.0, but you are getting an older version of this google-http-client transitively via your old dependency declarations.

The sheets client you are using depends on a very old dependencies. [v4-rev2020-0908](https://search.maven.org/artifact/com.google.apis/google-api-services-sheets/v4-rev20200908-1.30.10/jar) is the latest version.

google-api-client 1.30.10 is the latest version of that client.

**Comment by LouisKwong** [comment]
Hi @chingor13 ,

Thanks for the dependencies clarification. However, I am still getting the same error.

build.gradle
plugins {
  id 'java'
  id "com.katalon.gradle-plugin" version "0.0.7"
}

repositories {
  mavenCentral()
}

dependencies {
  compile 'com.google.api-client:google-api-client:1.30.10'
  compile 'com.google.oauth-client:google-oauth-client-jetty:1.31.0'
  compile 'com.google.apis:google-api-services-sheets:v4-rev20200908-1.30.10'
}

**Comment by meltsufin** [comment]
google-api-services are in a different repository now.
