### ISSUE TITLE
Improve Sonatype error messages and make it more readable

### ISSUE THREAD

**Issue by stephaniewang526** [googleapis/google-cloud-java#7410]
We sometimes encounter Sonatype errors during the release process. For instance, we could see something like the below which really means "we received a badly formatted response from Sonatype as the plugin is checking their API for release status":
![image](https://user-images.githubusercontent.com/7338432/101387840-07f56900-388d-11eb-931b-0afc761f3ff1.png)

It would be good if we could try to capture various types of Sonatype errors and translate them into something more easily understandable!

Example: https://g3c.corp.google.com/results/invocations/9358b574-e609-4469-ba1f-139f153a4f97/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fjava-bigqueryconnection%2Frelease%2Fstage/log

cc @chingor13

**Comment by Neenu1995** [comment]
With the change to google specific endpoint, this is issue is no longer pertinent.
