### ISSUE TITLE
BigQuery API Services and CloudStorage incompatibility

### ISSUE THREAD

**Issue by jcamerin** [googleapis/google-cloud-java#7415]
#### Environment details
In our project, we depend on both BigQuery and CloudStorage, with the following maven dependency declarations
com.google.cloud:google-cloud-storage:jar:1.113.4:compile
com.google.cloud:google-cloud-bigquery:jar:1.126.0:compile

The google-cloud-bigquery jar declares a dependency on google-api-services-bigquery:jar:v2-rev20201030-1.31.0, which declares a dependency on com.google.api-client:google-api-client:1.31.1

The google-cloud-storage jar declares a dependency on com.google.api-client:google-api-client:jar:1.30.11

Due to maven dependency resolution rules, the resolved api-client version is 1.30.11, however, google-api-services-bigquery fails to initialize using version 1.30.11 and throws the following error:
Caused by: java.lang.IllegalStateException: You are currently running with version 1.30.11 of google-api-client. You need at least version 1.31.1 of google-api-client to run version 1.31.0 of the BigQuery API library.
at com.google.common.base.Preconditions.checkState(Preconditions.java:481)
at com.google.api.client.util.Preconditions.checkState(Preconditions.java:113)
at com.google.api.services.bigquery.Bigquery.<clinit>(Bigquery.java:44)
at com.google.common.base.Preconditions.checkState(Preconditions.java:481)

Google libraries should declare their minimum versions such that combinations of dependencies resolve the required versions correctly.

Our code does not directly consume anything from the api-client jar. The quality control rules do not allow us to workaround this problem by adding an explicit declaration on the required api-client version since we do not use it directly.  We require that our dependencies declare their dependencies correctly.

mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T14:33:14-04:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 1.8.0_144, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

**Comment by suraj-qlogic** [comment]
@jcamerin, Thanks for filling issue.I follow your step and able to reproduce this issue. The cause of issue is ```google-cloud-storage:1.113.4``` use ```google-api-client:1.30.11``` while ```google-cloud-bigquery:1.126.0``` use ```google-api client
:1.31.1```.Here lower level  ```google-api-client:1.30.11``` is require to exclude from ```google-cloud-storage:1.113.4``` 
to fix current scenario. 

Would you try below step and Please let us know if this helps you?

**pom.xml**
```
<dependencies>
    <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-storage</artifactId>
        <version>1.113.4</version>
        <exclusions>
            <exclusion>
                <groupId>com.google.api-client</groupId>
                <artifactId>google-api-client</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-bigquery</artifactId>
        <version>1.126.0</version>
    </dependency>
</dependencies>
```

**Code:**
**BigQueryStorageTest.java**


```java
package com.gcp.main;

import com.google.api.client.http.HttpRequestInitializer;
import com.google.api.client.http.HttpTransport;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.JsonFactory;
import com.google.api.client.json.jackson2.JacksonFactory;
import com.google.api.services.bigquery.Bigquery;
import com.google.api.services.storage.Storage;
import com.google.auth.http.HttpCredentialsAdapter;
import com.google.auth.oauth2.ServiceAccountCredentials;

import java.io.FileInputStream;
import java.io.IOException;

public class BigQueryStorageTest {

    // TODO(developer): Replace these variables before running the sample.
    private static final String jsonFilePath="path to credential file";

    public static void main(String[] args) throws IOException {
        Bigquery bigquery =  createBigQueryAuthorizedClient();
        System.out.println("Bigquery Client::"+bigquery);
        Storage storage = createStorageAuthorizedClient();
        System.out.println("Storage Client::"+storage);
    }

    public static Bigquery createBigQueryAuthorizedClient() throws IOException, IOException {
        // Create the credential
        HttpTransport transport = new NetHttpTransport();
        JsonFactory jsonFactory = new JacksonFactory();
        ServiceAccountCredentials sourceCredentials = ServiceAccountCredentials
                .fromStream(new FileInputStream(jsonFilePath));
        HttpRequestInitializer requestInitializer = new HttpCredentialsAdapter(sourceCredentials);
        //return instance of bigquery client
        return new Bigquery.Builder(transport, jsonFactory, requestInitializer).setApplicationName("BigqueryApplication").build();
    }

    public static Storage createStorageAuthorizedClient() throws IOException {
        // Create the credential
        HttpTransport transport = new NetHttpTransport();
        JsonFactory jsonFactory = new JacksonFactory();
        ServiceAccountCredentials sourceCredentials = ServiceAccountCredentials
                .fromStream(new FileInputStream(jsonFilePath));
        HttpRequestInitializer requestInitializer = new HttpCredentialsAdapter(sourceCredentials);
        //return instance of storage client
        return new Storage.Builder(transport, jsonFactory, requestInitializer).setApplicationName("StorageApplication").build();
    }
}
```
**Output:**
Bigquery Client::com.google.api.services.bigquery.Bigquery@567d299b
Storage Client::com.google.api.services.storage.Storage@6842775d

**Comment by jcamerin** [comment]
I agree with the analysis of the issue, but I disagree with the proposal for us to change our dependency declaration to exclude a required transitive dependency. One of the reasons is that if we remove bigquery from our dependencies, then cloudstorage will break.  Along similar lines, if a future version of CloudStorage requires a newer version of google-api-client, then we will be right back in this situation again where the older version is resolved due to our explicit exclusion. That will be even more difficult for us to track down.

**Comment by chingor13** [comment]
If you are using more than one Google Cloud client library, we recommend you use one of our Bill of Material (BOM) artifacts to help manage dependency versions.

It will look something like:
```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>libraries-bom</artifactId>
      <version>16.1.0</version>
      <type>pom</type>
      <scope>import</scope>
     </dependency>
   </dependencies>
</dependencyManagement>

<dependencies>
  <dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-storage</artifactId>
  </dependency>
  <dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-bigquery</artifactId>
  </dependency>
</dependencies>
```

The BOM declares the versions that we know are compatible dependency-wise (including transitive dependencies). We have many tools in place to make sure that these dependencies are compatible. For more information, you can check out https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM

**Comment by jcamerin** [comment]
Thank you @chingor13 
I should have looked for a BOM, but did not. After applying, a few jars were downgraded, but everything is working.

**Comment by chingor13** [comment]
Yeah, the BOMs may be slightly behind for any single particular library especially when we have to roll out compatible versions to 80+ libraries.

**Comment by jcamerin** [comment]
Very understandable...  minor downgrades thankfully!
