### ISSUE TITLE
Any guide help migrate from appengine-api-1.0-sdk

### ISSUE THREAD

**Issue by peterweb2005** [googleapis/google-cloud-java#7446]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

as:
https://cloud.google.com/appengine/docs/standard/java11/java-differences
Java 11 runtime, the App Engine standard environment no longer includes bundled App Engine services such as Memcache and Task Queues. Instead, Google Cloud provides standalone products that are equivalent to most of the services that were previously bundled with the Java 8 runtime

i am using
datastore
memcache
cloud task (queue)

for example:
## cannot resolve
com.google.appengine.api.datastore.Text
com.google.appengine.api.memcache.MemcacheService
com.google.appengine.api.urlfetch.HTTPHeader

thanks

**Comment by chingor13** [comment]
For datastore, please look at [google-cloud-datastore](https://github.com/googleapis/java-datastore).
For memcache, please look at [google-cloud-memcache](https://github.com/googleapis/java-memcache). This client is used for managing memcache instances.
For cloud tasks, pleaase look at [google-cloud-tasks](https://github.com/googleapis/java-tasks).

**Comment by peterweb2005** [comment]
thanks, but why 
the docs comparing has big difference between appengine and gcloud?

for example, datastore doc:
https://cloud.google.com/appengine/docs/standard/java/datastore
has 1x pages
https://github.com/googleapis/java-datastore
only 1 page

**Comment by meredithslota** [comment]
The Github repo https://github.com/googleapis/java-datastore contains info on the specific client library rather than AppEngine as a whole. https://cloud.google.com/appengine/docs/standard/java/datastore shows a bunch of examples along with sample code and is cross-referenced with other things. Hope this helps!
