### ISSUE TITLE
Add API to set/validate End-to-End Checksum

### ISSUE THREAD

**Issue by vnorigoog** [googleapis/google-cloud-java#7449]
To Support Silent Data Corruption Detection, Google services support end-to-end Checksum.
Add API + library to allow client libs to set/validate end-to-end checksum.

**Comment by elharo** [comment]
references? design doc?

**Comment by vnorigoog** [comment]
Closing this issue because this issue is *probably) more relevant for the repo: https://github.com/googleapis/google-api-java-client

added issue there: https://github.com/googleapis/google-api-java-client/issues/1724
