### ISSUE TITLE
enum Regions.java class not kept up to date

### ISSUE THREAD

**Issue by tmeesala-apptio** [googleapis/google-cloud-java#7574]
similar to https://github.com/googleapis/google-cloud-java/issues/5744

**Comment by danoscarmike** [comment]
@tmeesala-apptio thanks for reaching out. Can you provide a little more detail about the package you are using?

If it is google-cloud-compute then we have a new, improved version release which we should ensure capture this properly.

**Comment by tmeesala-apptio** [comment]
We currently use 0.119.0-alpha version https://mvnrepository.com/artifact/com.google.cloud/google-cloud-compute/0.119.0-alpha

**Comment by Neenu1995** [comment]
https://search.maven.org/artifact/com.google.cloud/google-cloud-compute/1.2.0-alpha/jar
This is the recommended version of google-cloud-compute.

**Comment by tmeesala-apptio** [comment]
I can't find the Regions.java enum in 1.2.0-alpha.
I see only the Regions client but we are looking for an enum instead of making client calls over the network which would need additional permissions as well.
