### ISSUE TITLE
How To Set GoogleCredential in 

### ISSUE THREAD

**Issue by ashhade** [googleapis/google-cloud-java#7578]
Hey there,

currently i'm using AnalyticsAdminServiceClient from this dependency 
```
        <dependency>
            <groupId>com.google.analytics</groupId>
            <artifactId>google-analytics-admin</artifactId>
            <version>0.3.2</version>
        </dependency>
```
but i didn't found any documentation that said how to inject the GoogleCredential into the client library.
 it's my pleasure to hear from you 
Thanks in advance

**Comment by meltsufin** [comment]
There is an example in the javadocs: https://googleapis.dev/java/google-analytics-admin/latest/com/google/analytics/admin/v1alpha/AnalyticsAdminServiceClient.html.
