### ISSUE TITLE
Enable logging in pub/sub emulator

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [googleapis/google-cloud-java#7714]
We are actively using the pub/sub emulator for our development environment and would request for the logging enhancement for the emulator so that it helps to track issues faster.

**Comment by lesv** [comment]
Hi @beena-yatin-kanyal - This is not the best place to ask for this feature request.  You might wish to try posting in either:
* https://github.com/googleapis/java-pubsub
* https://github.com/GoogleCloudPlatform/kafka-pubsub-emulator
* https://github.com/googleapis/python-pubsub

It's best to give what's happening now, what you'd like to happen.

**Comment by beena-yatin-kanyal** [comment]
thanks, @lesv. I will open an enhancement request on one of the repos mentioned above. btw I hope your vacation was great.
