### ISSUE TITLE
How to use API key with this library? 

### ISSUE THREAD

**Issue by peterfigure** [googleapis/google-cloud-java#7728]
Cannot find any references anywhere?

**Comment by Neenu1995** [comment]
Hi @peterfigure 
`google-cloud-java` is not a library. All available libraries have individual repos and should be added individually or as a BOM to the project to be used. README of individual libraries have instructions about how to add the particular dependency.
Then follow the [instructions](https://cloud.google.com/docs/authentication/api-keys) to use API keys.

**Comment by Neenu1995** [comment]
Hope this  answers your question. Closing for now. Feel free to reopen if you have more questions.
