### ISSUE TITLE
GRPC_PROXY_EXP is not for general use

### ISSUE THREAD

**Issue by ejona86** [googleapis/google-cloud-java#7731]
A recent [StackOverflow answer](https://stackoverflow.com/a/66544436/4690866) informed me that [google-cloud-java's README](https://github.com/googleapis/google-cloud-java#grpc-clients) is encouraging the use of GRPC_PROXY_EXP. It should not do so. I'm concerned how many other places this information may be shared.

"EXP" of GRPC_PROXY_EXP means "experimental." It was/is a temporary environment variable for initial testing. gRPC observes `https.proxyHost` and related properties (via [the default ProxySelector](https://docs.oracle.com/javase/8/docs/api/java/net/ProxySelector.html)). And if you need authentication, specify a default [Authenticator](https://docs.oracle.com/javase/8/docs/api/java/net/Authenticator.html) just like http in normal Java.

**Comment by suztomo** [comment]
(This week is my rotation) Working on this.

BTW, I found your answer GRPC_PROXY_EXP https://stackoverflow.com/a/46289362 5 years ago.

**Comment by ejona86** [comment]
Thank you!
