### ISSUE TITLE
How can i mock or create a stub TableResult for unit test? 

### ISSUE THREAD

**Issue by erdemontas** [googleapis/google-cloud-java#8270]
I am trying to create an TableResult object for unit test but I couldn't do it. Do you have any example that I can refer to ?

**Comment by lqiu96** [comment]
Hi @erdemontas, apologies for the delayed response. We were not actively monitoring this repo's issues. 

Can you share some error messages or code snippets that show TableResult not being created/ instantiated/ used properly in your unit tests?

We do have docs on our GCP reference website (i.e. https://cloud.google.com/bigquery/docs/writing-results#writing_large_results_using_legacy_sql)
