### ISSUE TITLE
Add a check for copyright header

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#8406]
Follow up of https://github.com/googleapis/google-cloud-java/pull/8402

**Comment by meltsufin** [comment]
More info: https://github.com/googleapis/repo-automation-bots/tree/main/packages/header-checker-lint

**Comment by meltsufin** [comment]
I enabled it for this repo, but still need to see if starts showing up in PRs.

**Comment by suztomo** [comment]
It's there. For example https://github.com/googleapis/google-cloud-java/pull/9985 has

![image](https://github.com/googleapis/google-cloud-java/assets/28604/5981a62b-ca9f-410c-bdd4-8ae870c5a18b)
