### ISSUE TITLE
Stop showing irrelevant artifacts in Dependency Dashboard

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#8503]
We need google-cloud-shared-dependencies in #7649 . But it's not showing it due to a number of artifacts listed there. Most of them are unnecessary. (Why unnecessary? See https://github.com/googleapis/google-cloud-java/issues/8239)

<img width="883" alt="Screen Shot 2022-10-03 at 10 35 27 AM" src="https://user-images.githubusercontent.com/28604/193604571-ff3ec292-8281-45cc-a9fc-5197ef1a001c.png">

**Comment by suztomo** [comment]
@ddixit14  Can you check this when you have time. (Not high priority for now)

**Comment by meltsufin** [comment]
I'll take this one.

**Comment by suztomo** [comment]
@meltsufin All we want here may be the 1st attempt by Deepankar:

https://github.com/googleapis/google-cloud-java/pull/8414/commits/1c20a75100754331c46648348c154a405af54b6a

**Comment by meltsufin** [comment]
https://github.com/googleapis/google-cloud-java/commit/1c20a75100754331c46648348c154a405af54b6a is fine as a temporary fix. I'm working on a more permanent fix in #8521.

**Comment by suztomo** [comment]
Working on the short term fix.

**Comment by suztomo** [comment]
Now I can see google-cloud-shared-dependencies in Dependency Dashboard:

<img width="955" alt="Screen Shot 2022-10-05 at 12 45 12 PM" src="https://user-images.githubusercontent.com/28604/194116005-d5652eb9-2de7-443c-a64d-d93a30df16fe.png">
