### ISSUE TITLE
[datastore] Serialization of `Entity` no longer stable

### ISSUE THREAD

**Issue by stickfigure** [googleapis/google-cloud-java#8508]
`Entity` has had stable serialization for a very long time. Sometime in recent history it broke:

```
java.io.InvalidClassException: com.google.protobuf.ByteString; local class incompatible: stream classdesc serialVersionUID = -5687838473930111344, local class serialVersionUID = 2497003577682127865
```

I notice that `ByteString` doesn't specify a serialversionuid.

Objectify serializes `Entity` into memcache, so breaking serialization causes headaches.

**Comment by stickfigure** [comment]
Relevant: https://github.com/protocolbuffers/protobuf/issues/10716

**Comment by diegomarquezp** [comment]
Closing as ByteString serialization was [fixed](https://github.com/protocolbuffers/protobuf/pull/10718)
