### ISSUE TITLE
Every module duplicates `<reporting>` configuration

### ISSUE THREAD

**Issue by meltsufin** [googleapis/google-cloud-java#8522]
@lqiu96 Can we move it up to the parent pom? Would javadoc generation break?

**Comment by suztomo** [comment]
Is this preventing something? Or nice-to-have?

**Comment by lqiu96** [comment]
I believe this is a nice-to-have feature. It shouldn't break anything since every module is using the same javadoc configuration for Cloud RAD. If we do swap this, I'd like to test this to confirm.

**Comment by lqiu96** [comment]
I can run the release job (to dev bucket) via fusion. Let me know when the changes go in and I can trigger it.
