### ISSUE TITLE
OwlBot is modifying versions that should be managed by Release Please

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#8532]
OwlBot is modifying versions of the artifacts in BOMs. These values should be managed by Release Please.

<img width="1230" alt="Screen Shot 2022-10-05 at 3 28 24 PM" src="https://user-images.githubusercontent.com/28604/194146065-08599a16-0786-4e44-9309-b9c15e939b57.png">

Maybe it's no harm so far, as long as Release Please sets the versions in release pull requests.

**Comment by meltsufin** [comment]
Where's this set up for OwlBot?
