### ISSUE TITLE
OwlBot is trying to remove content of java-speech's README and BOM

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#8537]
In #8493 , OwlBot is trying to modify unexpected POM files and removing content from README.

<img width="1090" alt="Screen Shot 2022-10-05 at 5 38 19 PM" src="https://user-images.githubusercontent.com/28604/194168989-067172cd-5d87-4f54-88b4-ef364e57ff9f.png">

```
Error: ] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.google.api.grpc:grpc-google-cloud-speech-v2:2.5.10-SNAPSHOT: Could not find artifact com.google.cloud:google-cloud-speech-parent:pom:2.5.10-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 10, column 11
[FATAL] Non-resolvable parent POM for com.google.api.grpc:proto-google-cloud-speech-v2:2.5.10-SNAPSHOT: Could not find artifact com.google.cloud:google-cloud-speech-parent:pom:2.5.10-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 10, column 11
```

Investigate why it happens. Read log files in owlbot-java postprocessor. Understand the logic of README update.

Why the split repo pull request https://github.com/googleapis/java-speech/pull/956/files did not touch README.md but this similar pull request in monorepo is trying to touch this README (mostly removing content).

Nothing special about README in https://github.com/googleapis/java-speech/blob/main/.github/.OwlBot.yaml or https://github.com/googleapis/java-speech/blob/main/owlbot.py.

The last time OwlBot updated the split repo's README, it was just few line changes (not removing many sample list) https://github.com/googleapis/java-speech/commit/580861f3a36157f144525213644809dfbe8d45e4

**Comment by meltsufin** [comment]
It's regenerating the readme as it's supposed to. If the template is wrong, we should fix it.
