### ISSUE TITLE
Is release-trigger configured correctly?

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#8613]
Merging https://github.com/googleapis/google-cloud-java/pull/8610 didn't trigger the job. We manually triggered the job via fusion. This was the first release from this repository. Is release-trigger configured correctly in this repository?

**Comment by chingor13** [comment]
It's configured to not tag any releases: https://github.com/googleapis/google-cloud-java/blob/0db282cc0d781afd03c45604f35484d5bcd2aa29/release-please-config.json#L3

**Comment by meltsufin** [comment]
Is tagging releases the same as triggering the release job?

**Comment by suztomo** [comment]
It still doesn't trigger the job

 https://github.com/googleapis/google-cloud-java/pull/8623

<img width="783" alt="Screen Shot 2022-10-17 at 2 14 03 PM" src="https://user-images.githubusercontent.com/28604/196252411-60e1f11f-15b3-4356-a985-6bc873481277.png">
