### ISSUE TITLE
The URLs in published Maven Central is wrong

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-cloud-java#8630]
<img width="803" alt="Screen Shot 2022-10-18 at 11 15 36 AM" src="https://user-images.githubusercontent.com/28604/196471693-e07b242c-a55e-415b-a350-1e1491a168de.png">

https://search.maven.org/artifact/com.google.cloud/google-cloud-websecurityscanner/2.4.0/jar

https://github.com/googleapis/google-cloud-java/google-cloud-jar-parent/google-cloud-websecurityscanner-parent/google-cloud-websecurityscanner is invalid.

**Comment by meltsufin** [comment]
We still have the `<url>` elements in the individual modules. That's the reaosn.
