### ISSUE TITLE
CI issues with downloading Maven artifacts

### ISSUE THREAD

**Issue by meltsufin** [googleapis/google-cloud-java#8700]
There are failures trying to fetch artifacts from `https://maven-central.storage-download.googleapis.com/maven2/`. Should the CI be configured to fall back to `maven.org`?
Example: https://github.com/googleapis/google-cloud-java/actions/runs/3340021392/jobs/5529651647

**Comment by ddixit14** [comment]
The logs have expired, so closing it. In case the issue is still valid and we get notified of such failures, we will re-open this. 
![image](https://github.com/googleapis/google-cloud-java/assets/90280028/5189abc0-2236-4d47-948c-88dc254be112)
