### ISSUE TITLE
AnalyticsAdminServiceClient.create causes a popup window in MacOS Ventura

### ISSUE THREAD

**Issue by dannygonzalez** [googleapis/google-cloud-java#8892]
We are getting a popup shown below appear when we call AnalyticsAdminServiceClient.create(settings).

<img width="453" alt="Screenshot 2022-12-08 at 14 28 00" src="https://user-images.githubusercontent.com/6702882/206472287-8b684879-4495-4848-a95f-38d27603b119.png">

It seems that this call is triggering something that is making MacOS run the "install_name_tool"  which needs the command line tools to be installed.

I have set a breakpoint in and here is the stack trace leading up to this popup appearing:
```
ManagedChannelImplBuilder.build() line: 627	
NettyChannelBuilder(AbstractManagedChannelImplBuilder<T>).build() line: 297	
InstantiatingGrpcChannelProvider.createSingleChannel() line: 388	
0x0000000800bfa368.createSingleChannel() line: not available	
ChannelPool.<init>(ChannelPoolSettings, ChannelFactory, ScheduledExecutorService) line: 105	
ChannelPool.create(ChannelPoolSettings, ChannelFactory) line: 83	
InstantiatingGrpcChannelProvider.createChannel() line: 236	
InstantiatingGrpcChannelProvider.getTransportChannel() line: 230	
ClientContext.create(StubSettings) line: 201	
GrpcAnalyticsAdminServiceStub.create(AnalyticsAdminServiceStubSettings) line: 777	
AnalyticsAdminServiceStubSettings.createStub() line: 1271	
AnalyticsAdminServiceClient.<init>(AnalyticsAdminServiceSettings) line: 167	
AnalyticsAdminServiceClient.create(AnalyticsAdminServiceSettings) line: 149
```

The pop up appears after the call to  io.grpc.internal.ManagedChannelImplBuilder.build()

#### Environment details

  - Programming language: Java
  - OS: MacOS Ventura 13.0.1
  - Language runtime version: Java 17.0.2+8
  - Package version: google-analytics-admin 0.16.0

#### Steps to reproduce

  1. On a clean install of MacOS Ventura without any developer tools installed
  2. Call the method AnalyticsAdminServiceClient.create(settings)
  3. Observe the popup window that appears shown above

**Comment by suztomo** [comment]
I'm not familiar with Mac development. Stackoverflow search showed https://stackoverflow.com/questions/9263256/why-is-install-name-tool-and-otool-necessary-for-mach-o-libraries-in-mac-os-x

**Comment by dannygonzalez** [comment]
@suztomo I read that also, however this pop up shouldn't be appearing and enforcing users to install 'command line developer tools'.

If you look at the stack call flow above, there is something in the call to io.grpc.internal.ManagedChannelImplBuilder.build() that is triggering this.

**Comment by dannygonzalez** [comment]
Not sure why this was closed. 
I feel this is an issue that should be solved. Users shouldn't be mandated to install command line developer tools when calling AnalyticsAdminServiceClient.create on MacOS Ventura.
