### ISSUE TITLE
AnalyticsAdminServiceClient.create should not requires users to install Developer Tools

### ISSUE THREAD

**Issue by liamsharp** [googleapis/google-cloud-java#8948]
This is a re report of #8892 with a bit more context. 

Our product, [Screaming Frog SEO Spider](https://www.screamingfrog.co.uk/seo-spider/), integrates with Google Analytics 4. When users authorise they get the following pop up, shown here with our application for context:

<img width="894" alt="Screenshot 2023-01-05 at 11 41 46" src="https://user-images.githubusercontent.com/6429288/210774826-3d676b1d-5ebf-49ba-956e-ceabc5c7ee05.png">

This is confusing for users - they have no idea what "install_name_tool" is and why they would need it. If they accept this dialog Command Line Tools is installed. If they click cancel they can continue and everything works as expected.

However, we have had 3 users who have experienced a crash at this point. This is not a crash in Java application code, but in some native code causing a JVM exit, triggering a send to Apple dialog. We have logs for 2 of these cases:

- [103165.txt](https://github.com/googleapis/google-cloud-java/files/10352522/103165.txt)
- [104866.txt](https://github.com/googleapis/google-cloud-java/files/10352523/104866.txt)

Asking users to uninstall Command Line Tools resolved the issue in both cases, we are still waiting on feedback from the third.

For us it's unexpected behaviour for the `AnalyticsAdminServiceClient` to be triggering/requiring the installation of Command Line Tools, and a further issue that this sometimes crashes.

**Comment by meltsufin** [comment]
@ejona86 This appears to be connected to gRPC. Have you seen something like this before?

**Comment by meltsufin** [comment]
Thanks, @ejona86! @liamsharp I will close this, since there's nothing we can do on our side.

**Comment by liamsharp** [comment]
Thanks for looking into this @meltsufin and @ejona86, much appreciated.

This unfortunately leaves us in a difficult situation with customers, which is likely to get worse as more users move over from Universal Analytics (Due to be deprecated in July 2023) and move over to Google Analytics 4. The popping up of the dialog is annoying, but the crashing is a huge issue. Some customers will contacts us, others will just give up. Those that do contact us, it's likely to be time consuming on both sides to get Command Line Tools installed and working for them.

When we are faced with a similar situation with a dependency of our product causing issues for customers that can't be fixed, we look for an alternative. In this case we have no other option other than to use Googles official Java client. Is there an alternative that you can use to the netty library to solve this issue? If not, are we saying that Google can't really support GA4 for Java on macOS?

**Comment by meltsufin** [comment]
@liamsharp Would you be able to open a Google Cloud Support ticket so that your issue can go through the proper channels? Thanks!

**Comment by liamsharp** [comment]
@meltsufin thanks again for coming back to me, really appreciate it. I'm finding it hard to work out exactly where I should file this - I've landing on this page https://cloud.google.com/support/docs/issue-trackers which has lots of different issue trackers listed, could you point me at the correct one please?

**Comment by meltsufin** [comment]
You could start [here](https://cloud.google.com/support).

**Comment by liamsharp** [comment]
Thanks @meltsufin - that just leads us to the same list I mentioned before. I contacted Sales on that page, to see if they can advise and I'm now waiting on them to email and suggest next steps.

**Comment by liamsharp** [comment]
Setting `-Dio.grpc.netty.shaded.io.netty.native.tryPatchShadedId=false` stops the pop up happening, and thus hopefully stops any further crashes.

**Comment by meltsufin** [comment]
@liamsharp Thanks for the update! This will be useful for anyone coming across this issue in the future!
