### ISSUE TITLE
CHANGELOG.md and reference doc version history is outdated for individual libraries

### ISSUE THREAD

**Issue by burkedavison** [googleapis/google-cloud-java#8973]
The root [`CHANGELOG.md`](https://github.com/googleapis/google-cloud-java/blob/main/CHANGELOG.md) combines all updates from the individual client libraries under a version that does not have a meaning to customers. (It is neither the `libraries-bom` version they should use, nor the client library version the changes apply to.)

The library specific [`CHANGELOG.md`](https://github.com/googleapis/google-cloud-java/blob/main/java-asset/CHANGELOG.md) is no longer being updated; however, this is the file that is used to populate the [reference documentation's change log](https://cloud.google.com/java/docs/reference/google-cloud-asset/latest/history).

**Comment by suztomo** [comment]
To close after confirming the fix works on upcoming google-cloud-java release.

**Comment by lqiu96** [comment]
Checked the change log for a random library (aiplatform): https://cloud.google.com/java/docs/reference/google-cloud-aiplatform/latest/history and see the library specific CHANGELOG.md updates. 

@suztomo @burkedavison  I think we can mark this as closed unless you all see otherwise.

**Comment by suztomo** [comment]
Yes, it's done here.
