### ISSUE TITLE
Update .OwlBot.lock.yaml file to be updated via bot PRs instead of manually

### ISSUE THREAD

**Issue by alicejli** [googleapis/google-cloud-java#9030]
Currently the `github/.OwlBot.lock.yaml` file needs to be manually updated (see https://github.com/googleapis/google-cloud-java/pull/9016 for example). 
Ideally this is something that can get automatically updated via a bot PR (see https://github.com/googleapis/java-shared-dependencies/pull/932 for example) that can be regularly merged in, instead of needing to be done manually.

**Comment by JoeWang1127** [comment]
I think this issue is resolved by #9236 and #9238.

**Comment by suztomo** [comment]
Yes, thank you.
