### ISSUE TITLE
Nightly Failure: google-cloud-core contains no tests during -Pnative build

### ISSUE THREAD

**Issue by burkedavison** [googleapis/google-cloud-java#9075]
Nightly is failing due to `google-cloud-core` being built with `-Pnative` profile, but not containing any (activated) tests.

`Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.18:test (test-native) on project google-cloud-core: Execution test-native of goal org.graalvm.buildtools:native-maven-plugin:0.9.18:test failed: Test configuration file wasn't found.`

https://source.cloud.google.com/results/invocations/588e3ab9-7721-462f-95a8-10b8c5b537b6/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fgoogle-cloud-java%2Fnightly%2Fgraalvm-sub-jobs%2Fnative%2Fgraalvm-native-2/log

**Comment by suztomo** [comment]
I'm going to create some file.

**Comment by suztomo** [comment]
Memo: How to reproduce:

```
~/google-cloud-java $ mvn -pl java-core -amd -Dclirr.skip=true  -Denforcer.skip=true  -Dcheckstyle.skip=true -Dflatten.skip=true -Danimal.sniffer.skip=true -Pnative test
```
