### ISSUE TITLE
Future returned by AssetServiceClient.exportAssetsAsync often completes early and throws CancellationException, is there an alternative?

### ISSUE THREAD

**Issue by roy-t** [googleapis/google-cloud-java#9118]
#### Environment details

OS: `Custom Alpine image running on GKE`
Java Version: Eclipse `Adoptium\jre-17.0.3.7-hotspot`
Library Version: `google-cloud-asset-3.12.0`

#### Steps to reproduce

When exporting assets using 

`OperationFuture<ExportAssetResponse, ExportAssetRequest> future = AssetServiceClient.exportAssetsAsync(request)`  the future often completes before the export is actually done. Using `future.get` then throws a `CancellationException`.

This error is usually thrown roughly 5 minutes after the export started. The actual export does succeed and only takes 

Note that the actual export does succeed after around 20 minutes. 

Ideally I wouldn't need a future like this at all, but get an id that I can store and check later so that I can create a mechanism that polls and survives application restarts. Is that available?

#### Code example

```java
    void startExport(AssetServiceClient client, ExportAssetsRequest request, TaskExecutor executor) {
        var future = client.exportAssetsAsync(request);
        future.addListener(() -> {
            
            try {
                future.isCancelled(); //often returns true
                future.get(); // throws the cancellation exception, without further information
            } catch (Throwable t) {
            }
        }, executor);
    }
```

#### Stack trace
```
java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1543)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:586)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:66)
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:125)
	at com.bol.cloudexplorer.gcp.assets.GoogleAssetService.publishExport(GoogleAssetService.java:57)
	at com.bol.cloudexplorer.gcp.assets.GoogleAssetService.lambda$startExport$0(GoogleAssetService.java:50)
	at org.springframework.cloud.sleuth.instrument.async.TraceRunnable.run(TraceRunnable.java:64)
	at com.bol.cloudexplorer.app.actions.ActionsConfig.lambda$getActionsExecutor$0(ActionsConfig.java:34)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

#### Any additional information below

I'm looking to see if 'm using Google's future API wrong, or of there is any way for me to get an id of this task so that I can manually check if the task is done using a more error proof mechanism that also survives application restarts, for example.

**Comment by roy-t** [comment]
I found much better way to wait for long running exports. It took quite a bit of trial and error, because I could not find a holistic piece of documentation that explains how to resume futures or how `com.google.api.gax.longrunning` package is supposed to be used.

You can trigger an export and get a unique id to identify this export by using the `exportAssetsOperationCallable` method instead of the `exportAssetsAsync` method (both methods return different implementations of a Future).

```java
public int triggerExport(AssetServiceClient assetServiceClient, ExportAssetsRequest request) {
    try {
        var operation = client.exportAssetsOperationCallable(); // explain to the client what we want to do
        var future = operation.futureCall(request); // asynchronously start the operation

        return future.getName(); // returns a unique id identifying this long running task
    } catch (Throwable t) {
        // ...
    }
}
```
I then store the id in a database and use a Quartz schedule to check every 5 minutes to see if the export has completed

```java
public Optional<ExportAssetsResponse> checkIfExportFinished(AssetServiceClient assetServiceClient, String name) {
    try {
        var operation = client.exportAssetsOperationCallable();
        var future = operation.resumeFutureCall(name);

        // Resume the future, wait a short bit for it to complete, or give up and try again later
        var result = future.get(10L, TimeUnit.SECONDS); 
        return Optional.of(result);
    } catch (TimeoutException ex) {
        return Optional.Empty();
    }
}
```

**Comment by lqiu96** [comment]
Hi @roy-t, sorry I didn't see this issue earlier. I hope you ended up finding a solution to this problem months ago. I have a suspicion that what you are seeing is due to the default timeout values for our Long-Running Operations (LROs).

> Using future.get then throws a CancellationException ... This error is usually thrown roughly 5 minutes after the export started. The actual export does succeed and only takes. Note that the actual export does succeed after around 20 minutes.

The values for the async operation callable is defined here: https://github.com/googleapis/google-cloud-java/blob/f4d8639b48199526485326a112ab9426869c7c76/java-asset/google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java#L1423-L1433 with the total timeout value set to be 300000ms -> 5 minutes.

You can configure the default polling values via something like: https://github.com/googleapis/google-cloud-java#long-running-operations but with the code tailored to the service's client that you're using. 

> Ideally I wouldn't need a future like this at all, but get an id that I can store and check later so that I can create a mechanism that polls and survives application restarts. Is that available?

I think you found the option yourself on your second post (which I believe should work -- and hopefully you can confirm that it did work for your use case). The operation does return a unique id that you can poll again for the status. The underlying runtime library (gax) does the rechecking of the operation's status for you, so there *should* be no need for custom code if you update the default polling timeout values.

**Comment by lqiu96** [comment]
Marking this as closed. Feel free to ping me for any questions or re-open this issue if you have any bugs.

**Comment by roy-t** [comment]
Thanks for still taking the time to reply here. In the end the above solution worked and also made our application resilient to deploys/restarts so we stuck with that. Unfortunately that also means I can't easily verify if it was the timeout you mentioned. But it does make sense.

Just wanted to let you know, in my opinion the issue can stay closed :).

**Comment by lqiu96** [comment]
> Thanks for still taking the time to reply here. In the end the above solution worked and also made our application resilient to deploys/restarts so we stuck with that. Unfortunately that also means I can't easily verify if it was the timeout you mentioned. But it does make sense.
> 
> Just wanted to let you know, in my opinion the issue can stay closed :).

No worries about trying to verifying the timeout. Glad to hear your solution worked :)
