### ISSUE TITLE
resolutionStatus field is not available

### ISSUE THREAD

**Issue by kamilgregorczyk** [googleapis/google-cloud-java#9207]
Hello, the `ErrorGroup` java pojo doesn't contain `resolutionStatus` field which makes it impossible to transition given error from one status to another. That field is mentioned on the doc page but not available via `ErrorGroupServiceClient` 

https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.groups#ErrorGroup

https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.groups/get

**Comment by meltsufin** [comment]
`ErrorGroup.getResolutionStatusValues()` is there: https://github.com/googleapis/google-cloud-java/blob/main/java-errorreporting/proto-google-cloud-error-reporting-v1beta1/src/main/java/com/google/devtools/clouderrorreporting/v1beta1/ErrorGroup.java#L276
