### ISSUE TITLE
Update links in README to Maven Central (due to redirects)

### ISSUE THREAD

**Issue by meredithslota** [googleapis/google-cloud-java#9220]
The links in the main README to Maven Central are no longer working as intended due to a new redirect introduced by the site. 

For example, links like https://search.maven.org/search?q=g:com.google.cloud%20AND%20a:google-cloud-bigquery&core=gav used to go straight to the project page; now we see a landing page with a message from Maven that says: 

> On February 23, 2023, we started redirecting users from search.maven.org to central.sonatype.com. Launched in September of 2022, central.sonatype.com provides the main functionality of search.maven.org with enhanced search results, including security vulnerability and software quality information.

Can we update the Maven links to go directly to project pages, e.g. https://central.sonatype.com/artifact/com.google.cloud/google-cloud-bigquery/2.23.2, or to a new parameterized search with an updated root URL, instead of the above?

**Comment by suztomo** [comment]
Ack
