### ISSUE TITLE
Update java-maps-routing stability to "GA" in README

### ISSUE THREAD

**Issue by m-sandusky** [googleapis/google-cloud-java#9291]
The java-maps-routing library is now a 'GA' release, however the stability badge in the README indicates that it is still 'PREVIEW'

**Comment by suztomo** [comment]
I'll update template or version.

**Comment by suztomo** [comment]
![image](https://user-images.githubusercontent.com/28604/230164221-c686a57a-1592-4ca3-b07a-6d8e5432497a.png)

Next, we're bumping to the version to 1.0.0.

**Comment by suztomo** [comment]
We published https://central.sonatype.com/artifact/com.google.maps/google-maps-routing/1.0.0 last week
