### ISSUE TITLE
IT Failure: Nightly build failures due to 3hr timeout

### ISSUE THREAD

**Issue by burkedavison** [googleapis/google-cloud-java#9329]
[April 8 - Nightly GraalVM JDK 11](https://source.cloud.google.com/results/invocations/9608fb26-1cf9-466d-a921-24d8cbea7cfe/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fgoogle-cloud-java%2Fnightly%2Fgraalvm-native/log)
* Fails due to 3hr timeout in group 19
* Ends during `videointelligence.v1.it.ITSystemTest`

[April 9 - Nightly GraalVM JDK 11](https://source.cloud.google.com/results/invocations/639dcf14-14d1-42e2-a821-50ea7522e064/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fgoogle-cloud-java%2Fnightly%2Fgraalvm-native/log)
* Fails due to 3hr timeout in group 19
* Ends during `videointelligence.v1p2beta1.it.ITSystemTest`

[April 8 - Nightly GraalVM JDK 17](https://source.cloud.google.com/results/invocations/628f2aa0-79b6-44d4-ae05-057f3dd570f0/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fgoogle-cloud-java%2Fnightly%2Fgraalvm-native-17/log)
* Fails due to 3hr timeout in group 19
* Ends during `videointelligence.v1p1beta1.it.ITSystemTest`

[April 9 - Nightly GraalVM JDK 17](https://source.cloud.google.com/results/invocations/3ee4815d-a77b-4911-92ea-e3c3ceb78b66/targets/cloud-devrel%2Fclient-libraries%2Fjava%2Fgoogle-cloud-java%2Fnightly%2Fgraalvm-native-17/log)
* Fails due to 3hr timeout in group 19
* Ends during `videointelligence.v1p1beta1.it.ITSystemTest`

**Comment by suztomo** [comment]
The latest build passed "Run Date | Monday, April 10, 2023 at 3:01:06 AM EDT" for prod:cloud-devrel/client-libraries/java/google-cloud-java/nightly/graalvm-sub-jobs/native/graalvm-native-19

**Comment by suztomo** [comment]
We keep this issue open to track flakiness.

**Comment by lqiu96** [comment]
Keeping this issue open. Setting priority to P3.

**Comment by meltsufin** [comment]
@burkedavison @mpeddada1 These nightly builds are still failing pretty regularly. Do you know if it's for the same reason?

**Comment by burkedavison** [comment]
No - they're currently failing due to the standard vision ITs.
