### ISSUE TITLE
How to make insecure calls (disable SSL/TLS)

### ISSUE THREAD

**Issue by alex-rocha-hp** [googleapis/google-cloud-java#9368]
https://github.com/googleapis/google-cloud-java/blob/d4e9d09eb1314a732c98be74fc7f312d157e793e/java-apigee-registry/google-cloud-apigee-registry/src/main/java/com/google/cloud/apigeeregistry/v1/RegistryClient.java#L136

I have a local instance of the Registry API running with Docker, how to configure the RegistryClient class properly. I already configure the endpoint and CredentialsProvider using RegistrySettings. I've tried with both grpc and http transport.

**Comment by alex-rocha-hp** [comment]
Hi, @diegomarquezp,

I'm using an example Dockerfile with envoy and it's configurations which exists in the [apigee/registry](https://github.com/apigee/registry/blob/main/deployments/envoy/envoy.yaml.tmpl) repository.

**Comment by diegomarquezp** [comment]
Hi @alex-rocha-hp, thanks for sharing your setup. I'm wondering if the snippet I shared ended up allowing you make insecure calls to your local Registry API?

**Comment by alex-rocha-hp** [comment]
> Hi @alex-rocha-hp, thanks for sharing your setup. I'm wondering if the snippet I shared ended up allowing you make insecure calls to your local Registry API?

Sure, it helped, sorry for not giving feedback.
