### ISSUE TITLE
Can we retrieve Regions without doing request??

### ISSUE THREAD

**Issue by gokhandegerli** [googleapis/google-cloud-java#9380]
Same issue with #7574.

Hi,

I am trying to use the Regions enum in my code but I am not sure which dependency to implement for this Enum. Could you please assist me with this?

Thank you in advance!

**Comment by gokhanc4c** [comment]
same here

**Comment by lqiu96** [comment]
Hi @gokhandegerli, I'm not sure that enum file exists anymore. Can you use the [RegionsClient](https://cloud.google.com/java/docs/reference/google-cloud-compute/latest/com.google.cloud.compute.v1.RegionsClient) to pull a list of regions for your project?

**Comment by gokhandegerli** [comment]
Thanks a lot for your response. However I want to get the regionsList without making any request ( similar as I did for other providers( Aws and Azure), I would kindly ask if it is possible to add this Regions Enum again in the library with a new patch?

Moreover I am not sure how I can retrieve the lists of regions through RegionsClient?

**Comment by gokhandegerli** [comment]
@lqiu96 Moreover, when I check the RegionsClient a bit, I see it requires some information (such as projectId), however I do not want to return a list for an individual user, instead return an overall regions list.

**Comment by lqiu96** [comment]
Ah, understood. Let me get back to you about this.

**Comment by gokhandegerli** [comment]
Thanks @lqiu96! Could you also have a look regarding regions info for storage service or service independent regions such as the whole regions.

**Comment by lqiu96** [comment]
Yeah, this is a nice feature that I think would benefit the SDK. I'll need to have a discussion about this so it may take some time. For now, would you be able to use one of these possible workaround:
1. RegionsClient in Compute
2. gcloud list regions
3. Manually maintain a simple list of Regions and Zones from https://cloud.google.com/compute/docs/regions-zones#available

**Comment by gokhandegerli** [comment]
Nice to hear that we will have a solution for this. 
I am currently using the old version of Regions Enum for compute( yet the overall Regions or regions for each service would be better), after the updated one to be released, I will refactor my code with new dependency. 
Thanks again and waiting for the upcoming feature 😊

**Comment by gokhanc4c** [comment]
I would appreciate it if you could keep me informed of any news. Thanks @lqiu96.

**Comment by gokhandegerli** [comment]
I would appreciate it if you could keep me informed of any news. Thanks @lqiu96.

**Comment by lqiu96** [comment]
Hi @gokhandegerli, thanks for reaching out again. I've had some internal discussions about this. The original `Regions.java` was never an officially supported product and was added in way before compute was GA'd. When compute was GA'd, the "support" for it was dropped. 

Sorry this isn't the answer you were looking for. I recognize there was/ is a use case for this and will keep this in our backlog (standardizing this across multiple products is a large effort). I would recommend using a workaround.
