### ISSUE TITLE
Can we have an example of creating a distribution metric

### ISSUE THREAD

**Issue by anuprout** [googleapis/google-cloud-java#9425]
Hi, I am trying to create a distribution metric. However, I am getting java.lang.IndexOutOfBoundsException while setting bucket count.  Here is my code snippet.

```
TypedValue value = TypedValue.newBuilder().setDistributionValue(
    		  Distribution.getDefaultInstance().toBuilder()
    		  .setCount(10)
    		  .setMean(5)
    		  .setBucketCounts(0,10) // this is where I am getting the exception
    		  .setBucketOptions(
    				  BucketOptions.newBuilder().setExplicitBuckets(
    						  Explicit.newBuilder().addBounds(5).build()
    						  )
    				  )
    		 
    		  ).build();
```

An example will help on how to use this api.

**Comment by suztomo** [comment]
@anuprout Do you still have issue? Would you include import statements and maven dependency as well?

**Comment by JoeWang1127** [comment]
Close as no responds from customer, please reopen it if still needed.
