### ISSUE TITLE
Enable versions in titles of release PRs

### ISSUE THREAD

**Issue by alicejli** [googleapis/google-cloud-java#9475]
Currently the release PRs for this repo have the title `chore: release main` (e.g. https://github.com/googleapis/google-cloud-java/pull/9427). It would be great if we could have the version number as well as if it is a snapshot version in the title so it's easier to tell what version is getting released instead of having to click into the files. F

or example, java-bigquery has release PRs that look like this: `chore(main): release 2.26.1`  (https://github.com/googleapis/java-bigquery/pull/2703) and `chore(main): release 2.26.2-SNAPSHOT` https://github.com/googleapis/java-bigquery/pull/2704.

**Comment by suztomo** [comment]
@alicejli Do you see any difference in yaml files that has release-please in their names between this repository and java-bigquery?

**Comment by alicejli** [comment]
I suspect https://github.com/googleapis/google-cloud-java/blob/main/.github/release-please.yml#L3 is what is causing the discrepancy.

I see in the release-please documentation (https://github.com/googleapis/release-please/blob/main/docs/customizing.md#pull-request-title):

```
The default pull request title uses this pattern: chore${scope}: release${component} ${version} so a common release pull request title would be chore(main): release foo-bar v1.2.3.

Pattern | Description
-- | --
${scope} | This pattern is used for specifying the conventional commit scope (e.g. chore(scope): some message). We expect that the target branch name is used for the scope value
${component} | The name of the component being released
${version} | The version of the component being released
${branch?} | The target branch of the pull request. If you have multiple release branches, this helps identify which release branch we are working on

```

So it seems the issue is that release-please cannot find the `${scope}`, `${component}`, `${version}` within the PR, *or* by using the `.release-please-manifest.json` file, we should update `pullRequestTitlePattern` to the pattern we want.

I will test out the latter next week and respond back with findings.

**Comment by suztomo** [comment]
Chance to try: https://github.com/googleapis/google-cloud-java/pull/9516#issuecomment-1583897518

**Comment by suztomo** [comment]
It worked in the latest Release Please PR. Thank you.

<img width="625" alt="Screenshot 2023-06-16 at 6 10 10 PM" src="https://github.com/googleapis/google-cloud-java/assets/28604/4303a882-df91-4421-a102-c0af34f70fd7">
