### ISSUE TITLE
Get image by tag

### ISSUE THREAD

**Issue by SvetaAndriyanchik** [googleapis/google-cloud-java#9567]
Hi,

I am using your library for performing scanning in google Artifact Registry. Version I am using is:
` implementation("com.google.cloud:google-cloud-artifact-registry:1.18.0")`

With the following code I was able to get image metadata:
```
GetDockerImageRequest request = GetDockerImageRequest.newBuilder()
                    .setName(
                        DockerImageName.of("my-project",
                                "europe", "repository", "imageName@sha256:0a4994d8f9b0aba9e142e9bf09cf140798dde2f22a31ab41645aee41b8f24b16")
                            .toString())
                    .build();
                DockerImage dockerImage = artifactRegistryClient.getDockerImage(request);
```

Here I had to use digest of the image to be able to access it. 
I tried to get the same image by tag. Like this:
```
GetDockerImageRequest request = GetDockerImageRequest.newBuilder()
                    .setName(
                        DockerImageName.of("my-project",
                                "europe", "repository", "imageName:1.0.0")
                            .toString())
                    .build();
```

but then I got an error:
` io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.`

Is there a possibility to get image by tag using your library?

Thank you in advance

**Comment by suztomo** [comment]
Would you share the entire stacktrace of the error message?

**Comment by suztomo** [comment]
Thank you for stacktrace. Reassigning to Lawrence.

**Comment by lqiu96** [comment]
Hi @SvetaAndriyanchik, thanks for providing a snippet. I was able to reproduce this locally.

I took a look at the underlying proto and found that it seems to suggest that we're supposed to be providing a digest for docker image parameter: https://github.com/googleapis/googleapis/blob/974c49f05ed50ba22fa471a29eabb5959581e3ac/google/devtools/artifactregistry/v1/artifact.proto#L51

I uploaded a sample hello-world container to my local artifact registry and pulled it down to see what the server is responding with. I see that the `DockerImage`'s name is returned as `projects/{MY_PROJECT}/locations/us-east4/repositories/test-repository/dockerImages/hello-world@sha256:7e9b6e7ba2842c91cf49f3e214d04a7a496f8214356f41d81a6e6dcad11f11e3
`

Do you have a constraint with including the digest as part of the name in the request?

**Comment by SvetaAndriyanchik** [comment]
hi @lqiu96 thank you for the update. yes, I also noticed that name has a digest part in it.
so there is no way to pull image by tag?

**Comment by lqiu96** [comment]
Unfortunately, I don't think so (my local tests also haven't been able to find a way). It seems that the server is expecting a digest in the URL path.

**Comment by lqiu96** [comment]
Feel free to comment or re-open if you have further questions. Going to close this.
