### ISSUE TITLE
Cloud SDK Emulator startup time doubled since `v386`

### ISSUE THREAD

**Issue by sappenin** [googleapis/google-cloud-java#9569]
Version `v386` (and prior) of the Google Cloud SDK Emulator had a startup time of around 10s on my machine. However, all versions of the emulator after `v386` have a much longer startup time -- about double -- or around 20s on my machine, and sometimes beyond. 

Did something change after `v386`, possibly related to authentication to GCP? I'm running this in TestContainers, and specifying `NoCredentialsProvider` -- perhaps that has something to do with the slowdown?

#### Environment details
1. Docker v4.15
1. Java version: v17

#### Steps to reproduce

  1. Start the Google Cloud Emulator via Docker or TestContainers.
  2. Image version `gcr.io/google.com/cloudsdktool/cloud-sdk:386.0.0-emulators` and prior will startup in about `T` seconds (about 10s on my machine).
  3. All subsequent versions have a `2T` startup time (on my machine, ~20 seconds).
  4. This slowdown appears in all emulator versions after `v386`, including the most recent `gcr.io/google.com/cloudsdktool/cloud-sdk:435.0.1-emulators`.

**Comment by suztomo** [comment]
It seems that your question is not related to GCP Java client libraries. To get support for the gcloud CLI, please check https://cloud.google.com/sdk/docs/getting-support. (It doesn't have a GitHub repository)

**Comment by sappenin** [comment]
Sounds good - for anyone who comes across this issue in the future, I've opened https://issuetracker.google.com/issues/302775650
