### ISSUE TITLE
[translate]: Missing classes in the JAR

### ISSUE THREAD

**Issue by axel-op** [googleapis/google-cloud-java#9610]
I'm trying to use the Java API for Cloud Translate. I tried to reproduce the example in [this code snippet (Batch Translation/Batch Request)](https://cloud.google.com/translate/docs/advanced/batch-translation?hl=fr#batch-request). However, the following classes cannot be found in the downloaded JAR:

- com.google.cloud.translate.v3.BatchTranslateMetadata;
- com.google.cloud.translate.v3.BatchTranslateResponse;
- com.google.cloud.translate.v3.BatchTranslateTextRequest;
- com.google.cloud.translate.v3.GcsDestination;
- com.google.cloud.translate.v3.GcsSource;
- com.google.cloud.translate.v3.InputConfig;
- com.google.cloud.translate.v3.LocationName;
- com.google.cloud.translate.v3.OutputConfig.

They do not seem to be [in this repository](https://github.com/googleapis/google-cloud-java/tree/main/java-translate/google-cloud-translate/src/main/java/com/google/cloud/translate/v3) either.

I also cannot find them in the [JAR from Maven Central](https://mvnrepository.com/artifact/com.google.cloud/google-cloud-translate/2.20.0). 

#### Environment details

1. OS type and version: Linux Ubuntu 23.04
1. Java version: JDK 11.0.19
1. IDE: IntelliJ 2023.1.3
1. Apache Maven 3.8.7.
1. `pom.xml`:

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>libraries-bom</artifactId>
      <version>26.18.0</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependencies>
  <dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-translate</artifactId>
  </dependency>
</dependencies>
```

#### Steps to reproduce

  1. Add the BOM and the `google-cloud-translate` dependency to your `pom.xml`;
  3. Reproduce [this example from the documentation](https://cloud.google.com/translate/docs/advanced/batch-translation?hl=fr#batch-request).

#### Code example

```java
import com.google.cloud.translate.v3.BatchTranslateMetadata;
import com.google.cloud.translate.v3.BatchTranslateResponse;
import com.google.cloud.translate.v3.BatchTranslateTextRequest;
import com.google.cloud.translate.v3.GcsDestination;
import com.google.cloud.translate.v3.GcsSource;
import com.google.cloud.translate.v3.InputConfig;
import com.google.cloud.translate.v3.LocationName;
import com.google.cloud.translate.v3.OutputConfig;
```

#### Stack trace

```console
[ERROR] cannot find symbol
[ERROR]   symbol:   class BatchTranslateTextRequest
[ERROR]   location: package com.google.cloud.translate.v3
```

**Comment by diegomarquezp** [comment]
Hi @axel-op , thanks for raising the issue. 

The involved classes are found in the [v3 proto definitions](https://github.com/googleapis/google-cloud-java/tree/main/java-translate/proto-google-cloud-translate-v3/src/main/java/com/google/cloud/translate/v3)

I could compile the [example](https://cloud.google.com/translate/docs/advanced/batch-translation?hl=fr#translate_v3_batch_translate_text-java) with `Maven 3.8.6`, `google-cloud-bom:3.18.0` and `google-cloud-translate`. I assume the problem occurs at compilation - does it occur both when you manually run `mvn install` from the CLI and when you compile from Intellij? If not, then you can try [reloading the Maven project from Intellij](https://www.jetbrains.com/help/idea/delegate-build-and-run-actions-to-maven.html#maven_reimport).

It looks like a straightforward replication of the suggested example. Would you mind sharing a reproducer if the compilation error persists?

If you have a support plan, feel free to try our [support hub](https://cloud.google.com/support-hub) for faster response times

**Comment by axel-op** [comment]
Hi, thanks for your answer. Yes, the issue occurred at compile-time, using either the CLI or the IDE.

The root cause of the problem was that there was actually a statement missing in my `module-info.java`:

```java
requires google.cloud.translate;
// this directive was missing
requires proto.google.cloud.translate.v3;
```

Maybe this could be documented [here](https://cloud.google.com/translate/docs/setup?hl=fr#client_libraries) or [there](https://cloud.google.com/java/docs/bom)?
