### ISSUE TITLE
SECURITY.md file is not human-readable

### ISSUE THREAD

**Issue by meredithslota** [googleapis/google-cloud-java#9766]
https://github.com/googleapis/google-cloud-java/blob/main/SECURITY.md does not appear to be correct. For comparison, see the SECURITY.md file in split repos: https://github.com/googleapis/java-bigquery/blob/main/SECURITY.md and https://github.com/googleapis/python-bigquery/blob/main/SECURITY.md, as well as the Python mono-repo: https://github.com/googleapis/google-cloud-python/blob/main/SECURITY.md

**Comment by meltsufin** [comment]
@ddixit14 @suztomo PTAL

**Comment by suztomo** [comment]
Strange. Let me create a pull request.
