### ISSUE TITLE
[dataform]: com.google.auth.oauth2.GoogleAuthException: Error getting access token for service account

### ISSUE THREAD

**Issue by Siraachenbach** [googleapis/google-cloud-java#9831]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-cloud-java/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details

1. [google-cloud-java](https://github.com/googleapis/google-cloud-java/tree/main/java-dataform)
2. OS type and version: Google App Engine
3. Java version: Java 8
4. Version(s): https://mvnrepository.com/artifact/com.google.cloud/google-cloud-dataform-bom/0.22.0

#### Steps to reproduce

  1. Create a Google Cloud Task
  2. Within the Task a function is called that creates a DataformClient with the credentials by your service account of the AppEngine
  3. The IAM permissions of the AppEngine service account is Owner
  4. The dataform client requests a list of all repositories.

#### Code example

```java
ArrayList<String> scopes; // contains "https://www.googleapis.com/auth/cloud-platform"
GoogleCredentials credentials = ServiceAccountCredentials.fromStream(this.getClass().getResourceAsStream(fileCredentialName));
credentials = credentials.createScoped(scopes);
FixedCredentialsProvider fixedCredentialsProvider = FixedCredentialsProvider.create(credentials);

DataformSettings dataformSettings = DataformSettings.newBuilder().setCredentialsProvider(fixedCredentialsProvider).setQuotaProjectId(AppengineEnv.APP_ID).build();

try (DataformClient dataformClient = DataformClient.create(dataformSettings)) {
            ListWorkspacesPagedResponse listWorkspacesPagedResponse = dataformClient.listWorkspaces(repositoryName);
} catch (IOException e) {
      log.error("An exception is thrown!", e);
}
```

#### Stack trace

`Caused by: com.google.auth.oauth2.GoogleAuthException: Error getting access token for service account: com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager, iss: ###@appspot.gserviceaccount.com 	at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointIOException(GoogleAuthException.java:164) 	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:543) 	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:269) 	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:266)
`

#### External references such as API reference guides
https://github.com/googleapis/google-cloud-java/tree/main/java-dataform

#### Any additional information below
Scope in Google Credential Provider: "https://www.googleapis.com/auth/cloud-platform"

**Comment by Siraachenbach** [comment]
> Hi @Siraachenbach, thanks for reporting this. Is this the only code of your application? Would you mind sharing a reproducer project so we can work it out on our end? Thanks!

@diegomarquezp I think I have explained how to reproduce the issue. Unfortunately, I cannot share the code.

**Comment by suztomo** [comment]
> Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager

@Siraachenbach Does this error message makes sense? Would you write down threads that make "original request" and "urlfetch.Fetch"?
