### ISSUE TITLE
New client library generation needs to be updated with regard to api-shortname

### ISSUE THREAD

**Issue by alicejli** [googleapis/google-cloud-java#9902]
Currently, `new-client.py` uses `api-shortname` for directory creation. However, `api-shortname` is not always a unique value. We should determine a new methodology for creating the directory using a unique name.

For example: https://github.com/googleapis/google-cloud-java/pull/9896

**Comment by suztomo** [comment]
Avoid pursuing a perfect solution. Human understands "if" statement.

**Comment by meltsufin** [comment]
@suztomo What do you mean?

**Comment by suztomo** [comment]
"if there's conflict, use `--destination-name`" is good enough.
