### ISSUE TITLE
[google-cloud-batch]  How to set up InstanceTemplate and ProvisioningModel?

### ISSUE THREAD

**Issue by Jon-Gaara** [googleapis/google-cloud-java#9964]
I'm using google-cloud-batch and I have this requirement, I've created an instance template on gcp and its vm's type is spot, now there is a service that wants the vm's type to be other than spot, how can I set up both the InstanceTemplate and the ProvisioningModel, I I tried to set InstanceTemplate and InstancePolicy, but it prompts me that only InstanceTemplate or InstancePolicy is supported.

**Comment by suztomo** [comment]
> I I tried to set InstanceTemplate and InstancePolicy

Would you share the code?

> it prompts me that only InstanceTemplate or InstancePolicy is supported.

Would you share the exact message? Is it an program error or in UI?

**Comment by Jon-Gaara** [comment]
@suztomo 
![1697420955185](https://github.com/googleapis/google-cloud-java/assets/7116647/ee6f53e7-5e55-46a6-8fd8-b38a6117102c)
![1697420989429](https://github.com/googleapis/google-cloud-java/assets/7116647/d0101deb-1916-456c-baa0-6698e9445477)

**Comment by suztomo** [comment]
What are GoogleBatchTest.java line 59 and line 281 (they are in the stack teace)

**Comment by Jon-Gaara** [comment]
![1697446048057](https://github.com/googleapis/google-cloud-java/assets/7116647/683990ce-377b-43d0-87a5-973178ea8f98)
![1697446048068](https://github.com/googleapis/google-cloud-java/assets/7116647/9893f9fc-86b3-44ae-8d1e-f9c843f43448)

**Comment by Jon-Gaara** [comment]
The logic I thought should be that if I use InstanceTemplate and Policy, the value inside Policy can replace the value in InstanceTemplate, but that's not how it works, I can only set InstanceTemplate or Policy

**Comment by suztomo** [comment]
Thank you for information. 

My memo for the error: `INVALID_ARGUMENT: instances field is invalid. only one InstancePolicyOrTemplate specification of allocationPolicy.instances per job is supported.` and `InstancePolicyOrTemplate` might not be supposed to be instantiated.


> The logic I thought should be that if I use InstanceTemplate and Policy, the value inside Policy can replace the value in InstanceTemplate

Do you have a reference or documentation you used while writing the code?

**Comment by Jon-Gaara** [comment]
https://cloud.google.com/java/docs/reference/google-cloud-batch/latest/com.google.cloud.batch.v1.AllocationPolicy.AcceleratorOrBuilder

**Comment by suztomo** [comment]
Thank you.

**Comment by lqiu96** [comment]
Hi @Jon-Gaara, I took a look at this issue and I'm not able to find a way to set an InstanceTemplate and configure the ProvisioningModel together via code. This seems to be a limitation from the root Batch proto which defines the InstancePolicyOrTemplate message as a oneof field: https://github.com/googleapis/googleapis/blob/b6a7fba0dfe9a562e4bfc8b7f2b847ddb08d86a2/google/cloud/batch/v1/job.proto#L392-L400. Setting the policy will override the template and the template would override the policy. I will raise a question internally to the Batch team to see their response (might be a limitation of their service or I may be missing something obvious).

Note: I also see a note from the Batch team that only one instance is supported for now: https://github.com/googleapis/googleapis/blob/b6a7fba0dfe9a562e4bfc8b7f2b847ddb08d86a2/google/cloud/batch/v1/job.proto#L493-L495

One possible workaround (that may or may not work for your use case) is to configure a new InstanceTemplate in the console and set the ProvisioningModel: 
![image](https://github.com/googleapis/google-cloud-java/assets/6621793/959c5cae-ce21-4472-bdfe-0755ca491eb9). Not the ideal situation, but may help temporarily resolve this.

**Comment by lqiu96** [comment]
Actually, from looking at the docs about limitations of instance templates: https://cloud.google.com/compute/docs/instance-templates/create-instance-templates#limitations

`You can't update an existing instance template or change an instance template after it has been created. If an instance template goes out of date, or you need to make changes to the configuration, create a new instance template.`

It seems like the correct behavior. You'll need to create a new instance template if the one you're using has a SPOT provisioning model.

**Comment by Jon-Gaara** [comment]
Yes, we are currently supporting both standard and spot mode by adding new instance templates.

For ProvisioningMode,I can solve this by creating two instances of the template, which is acceptable for me.

But if I want to set the memory and CPU for the batch, it's a bit tricky because it prioritizes the "MachineType" field to generate the resources needed for the VM, so it's useless for me to set CpuMillis and MemoryMib. Since I'm configuring an instance template, I also can't modify the MachineType


If i have a lot of tasks, each requiring different reources, I have to create a template for each task.

I wish I could create a base instance template and the other configurations could be achieved by overriding the base instance template, but it seems to be unsupported at the moment.

**Comment by lqiu96** [comment]
> But if I want to set the memory and CPU for the batch, it's a bit tricky because it prioritizes the "MachineType" field to generate the resources needed for the VM, so it's useless for me to set CpuMillis and MemoryMib. Since I'm configuring an instance template, I also can't modify the MachineType. https://www.googlecloudcommunity.com/gc/Infrastructure-Compute-Storage/Batch-Setting-cpu-and-memory-does-not-take-effect/td-p/611832
> 
> If i have a lot of tasks, each requiring different reources, I have to create a template for each task.

I see. Obviously your use case might require instance templates (I don't know the full scope of everything you're doing), but using an InstancePolicy seems like it gives you options for the customizations you might be asking for (Provisioning model + Machine Type for vCPUs + Memory specifications).

> I wish I could create a base instance template and the other configurations could be achieved by overriding the base instance template, but it seems to be unsupported at the moment.

It does sound like something that may be useful and/or something that others might also find useful. I don't work with the Compute/ Batch folks so I wouldn't be able to give better recommendations. Would you mind creating a ticket here for a feature request? https://cloud.google.com/support/docs/issue-trackers

**Comment by Jon-Gaara** [comment]
Ok, thanks
